### PR TITLE
Make task validation errors more clear

### LINKED ISSUE #10987: creating an empty task fails with a 500 error
on the UI, we should handle this gracefully.

in the api, it should return an error message for invalid task.

### PR DESCRIPTION
**Pull request by lyondhill**
fixes #10987

_Briefly describe your proposed changes:_
When task validation returns an error it should be of the bas model errors type so that the api can determine what status codes to return. This allows us to return the proper 400 status code when its an invalid request.

### CODE REVIEW

File: task/validator.go [hunk 1]
```diff
@@ -254,11 +254,17 @@ func validateBucket(ctx context.Context, script string, preAuth query.PreAuthori
 
 	spec, err := flux.Compile(ctx, script, time.Now())
 	if err != nil {
-		return err
+		return platform.NewError(
+			platform.WithErrorErr(err),
+			platform.WithErrorMsg("Failed to parse flux script."),
```
Comment (mark-rushakoff) [inline task/validator.go]: Maybe this should be `compile` rather than `parse`?

Comment (lyondhill) [reply task/validator.go]: I like compile here!
