### PR TITLE
fix: improve delete speed when a measurement is part of the predicate

### LINKED ISSUE #23741: influxdb 2.x - very slow delete statement
__Steps to reproduce:__

run the following statement to delete a non existing metric in 1 hour timeframe (it happens also with actual metrics)

```
[root@influxdb ~]# time influx delete --http-debug --bucket prometheus --org myorg -p '_measurement="not_existing_metric"' --start '2022-09-19T15:00:00Z' --stop '2022-09-19T16:00:00Z'
2022/09/21 07:25:41
POST /api/v2/delete?bucket=prometheus&org=myorg HTTP/1.1
Host: localhost:8086
User-Agent: influx/2.2.1 (linux) Sha/31ac783 Date/2021-11-09T21:24:22Z
Transfer-Encoding: chunked
Accept: application/json
Authorization: Token xxxxx
Content-Type: application/json
Accept-Encoding: gzip

72
{"predicate":"_measurement=\"not_existing_metric\"","start":"2022-09-19T15:00:00Z","stop":"2022-09-19T16:00:00Z"}

0


2022/09/21 07:33:39
HTTP/1.1 204 No Content
Content-Length: 0
Date: Wed, 21 Sep 2022 07:33:39 GMT
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.4.0



real	7m57.226s
user	0m0.004s
sys	0m0.011s
```

__Expected behavior:__
delete statement being fast considering 1 hour timeframe and non existing metric

__Actual behavior:__
it takes 8 minutes

__Environment info:__

* System info: `Linux 4.18.0-372.26.1.el8_6.x86_64 x86_64`
* InfluxDB version:  `InfluxDB v2.4.0 (git: de247bab08) build_date: 2022-08-18T19:41:15Z`

VM: 16CPU, 64GB of Ram, disk usage

`/dev/mapper/influx_data 1618795736 1018890836 528798796  66% /influx_data
`
storage perfomance

```
/dev/mapper/influx_data:
 Timing buffered disk reads: 596 MB in  3.01 seconds = 198.10 MB/sec
```

__Logs:__
nothing useful in logs

__Performance:__

[iostat.txt](https://github.com/influxdata/influxdb/files/9624813/iostat.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/9624814/profiles.tar.gz)

### PR DESCRIPTION
**Pull request by jeffreyssmith2nd**
- Closes #23741

### Description
The current delete statement does not take into account the measurement predicate. It will blindly loop through all the measurements in each shard and run the delete. This can be very slow on instances with a lot of measurements. This change checks for measurement existence, and if found, only runs the delete on that measurement.

### Context
The value add is faster deletes that have a measurement predicate.

### Note for reviewers:
Check the semantic commit type:
 - Feat: a feature with user-visible changes
 - Fix: a bug fix that we might tell a user “upgrade to get this fix for your issue”
 - Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except dependency version changes)
 - Build: build script changes, CI config changes, build tool updates
 - Refactor: non-user-visible refactoring
 - Check the PR title: we should be able to put this as a one-liner in the release notes

### CODE REVIEW

File: http/delete_handler.go [hunk 1]
```diff
@@ -139,24 +142,71 @@ func (h *DeleteHandler) handleDelete(w http.ResponseWriter, r *http.Request) {
...
-func decodeDeleteRequest(ctx context.Context, r *http.Request, orgSvc influxdb.OrganizationService, bucketSvc influxdb.BucketService) (*deleteRequest, error) {
+func decodeDeleteRequest(ctx context.Context, r *http.Request, orgSvc influxdb.OrganizationService, bucketSvc influxdb.BucketService) (*deleteRequest, influxql.Expr, error) {
+	jsonErr := &errors.Error{
+		Code: errors.EInvalid,
+		Msg:  "invalid request; error parsing request json",
+	}
+
 	dr := new(deleteRequest)
-	err := json.NewDecoder(r.Body).Decode(dr)
+	buf, err := io.ReadAll(r.Body)
```
Comment (davidby-influx) [inline http/delete_handler.go:152]: Why the shift to a buffered read here?

Comment (davidby-influx) [reply http/delete_handler.go:152]: One rule of thumb I use is that every error cause should return a different error. This enormously helps narrow down debugging searches.  I would use `fmt.Errorf("$s : %w", "What I was doing", jsonErr)` for each return of `jsonErr` in this function. `errors.Is()` will still show it is a `jsonErr`, but you will know if it is an error from `io.ReadAll` or `Decode` or `Unmarshal`

Comment (davidby-influx) [reply http/delete_handler.go:152]: And that will help us when we see this from a misbehaving customer and have to figure it out.

File: http/delete_handler.go [hunk 2]
```diff
@@ -139,24 +142,71 @@ func (h *DeleteHandler) handleDelete(w http.ResponseWriter, r *http.Request) {
...
+		return nil, nil, jsonErr
+	}
+	buffer := bytes.NewBuffer(buf)
+	err = json.NewDecoder(buffer).Decode(dr)
+	if err != nil {
+		jsonErr.Err = err
+		return nil, nil, jsonErr
+	}
+
+	var drd deleteRequestDecode
```
Comment (davidby-influx) [inline http/delete_handler.go:164]: Do you need both `dr` and `drd`?  Isn't one a superset of the other?

File: http/delete_test.go [hunk 3]
```diff
@@ -335,7 +335,7 @@ func TestDelete(t *testing.T) {
 				body: []byte(`{
 					"start":"2009-01-01T23:00:00Z",
 					"stop":"2019-11-10T01:00:00Z",
-					"predicate": "tag1=\"v1\" and (tag2=\"v2\" and tag3=\"v3\")"
+					"predicate": "_measurement=\"testing\" and tag1=\"v1\" and (tag2=\"v2\" and tag3=\"v3\")"
```
Comment (davidby-influx) [inline http/delete_test.go:338]: Can you add a test with a malformed predicate?  Perhaps two measurements joined by `OR`?

File: tsdb/store.go [hunk 4]
```diff
@@ -1372,13 +1372,44 @@ func (s *Store) DeleteSeriesWithPredicate(ctx context.Context, database string,
...
+		}
+
 		// Find matching series keys for each measurement.
 		mitr, err := index.MeasurementIterator()
 		if err != nil {
 			return err
 		}
 		defer mitr.Close()
 
+		deleteSeries := func(mm []byte) error {
```
Comment (davidby-influx) [inline tsdb/store.go:1400]: Can we capture the error from `mitr.Close()` with Capture() call?  It is not new code, but a good thing to add while the hood is open.

File: tsdb/store.go [hunk 5]
```diff
@@ -1372,13 +1372,44 @@ func (s *Store) DeleteSeriesWithPredicate(ctx context.Context, database string,
...
+			sitr, err := index.MeasurementSeriesIDIterator(mm)
+			if err != nil {
+				return err
+			} else if sitr == nil {
+				return nil
+			}
+			defer sitr.Close()
```
Comment (davidby-influx) [inline tsdb/store.go:1407]: Does `sitr.Close()` return an error?  Can we use `Capture()` to handle it?

**Review by davidby-influx — CHANGES_REQUESTED** [review]
Some questions, which may lead to code changes, and some straight up code changes.

File: http/delete_handler.go (hunk 2 above)
Comment (jeffreyssmith2nd) [reply http/delete_handler.go:164]: So `dr` (a `deleteRequest`) when unmarshalled sets the predicate to a type that doesn't return the original string. We need that original string to do the expression parsing a few lines down. This is why I switched to the buffered read, it effectively decodes into a `deleteRequestDecode` twice, once here and once in the UnmarshalJson for the `deleteRequest` type. If we don't like that, I can remove the predicate stuff from the unmarshaling and do it elsewhere, my initial thought was to avoid that since I don't know everywhere that may be used.

File: tsdb/store.go [hunk 6]
```diff
@@ -6,6 +6,7 @@ import (
 	"context"
 	"errors"
 	"fmt"
+	errors3 "github.com/influxdata/influxdb/v2/pkg/errors"
```
Comment (davidby-influx) [inline tsdb/store.go:9]: `errors3` should be in a separate import block following the standard Go packages.

**Review by davidby-influx — CHANGES_REQUESTED** [review]
One import formatting change.

File: tsdb/store.go (hunk 6 above)
Comment (jeffreyssmith2nd) [reply tsdb/store.go]: Turns out GoLand was set to `gofmt` import style rather than `goimports`. Seems a violation of Go's whole ethos to have 2 different formatting styles.

Comment (davidby-influx) [reply tsdb/store.go]: Been bitten by that many times....

File: tsdb/store.go [hunk 7]
```diff
@@ -16,6 +15,8 @@ import (
 	"sync"
 	"time"
 
+	errors3 "github.com/influxdata/influxdb/v2/pkg/errors"
```
Comment (davidby-influx) [inline tsdb/store.go:18]: I thhink `errors3` should be in the block below, not a separate block.

**Review by davidby-influx — CHANGES_REQUESTED** [review]
More import formatting.

File: tsdb/store.go (hunk 7 above)
Comment (jeffreyssmith2nd) [reply tsdb/store.go:18]: It passed the lint stage (and my formatting once I set the right style), so I think this is right

Comment (davidby-influx) [reply tsdb/store.go:18]: Weird.

**Review by davidby-influx — APPROVED** [review]
I am surprised by the acceptance of the import ordering, but if the tools like it...
