### PR TITLE
Optimize SHOW TAG VALUES

### LINKED ISSUE #6233: Show tags, fields etc. much slower than they use to be.
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
influxdb-0.12.0-1.x86_64, Centos 7, 120G M, 16 CPUs

__Steps to reproduce:__

1. show tag keys 
2. show field keys

__Expected behavior:__ [What you expected to happen]
These queries should (used to) come back pretty quickly.

__Actual behavior:__ [What actually happened]
Since the change to the output of show tags etc., this has become very slow, which is most noticable waiting for templates to load in grafana.  I noticed this after the upgrade to 0.11, but it is still relevant in 0.12

### PR DESCRIPTION
**Pull request by benbjohnson**
## Overview

This commit optimizes `SHOW TAG VALUES` so that it avoids the `SELECT` query engine execution and iterator creation. There are also optimizations to reduce individual memory allocations and to reduce in-memory heap size by only operating on one measurement at a time.

Execution time has been reduce to approximately 900ms for 500,000 rows. This is about 2µs per row. Of this time, approximately 1µs is spent retrieving and sorting the row and 1µs is spent encoding into JSON and writing to the response body.

Fixes #6233

/cc @pauldix @jwilder 

### Notes

The previous implementation of `tagValuesIterator` still exists because it is used for the distributed `SHOW TAG VALUES`. This change only affects the single node implementation.

## TODO

- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by jsternberg** [comment]
👍 LGTM

File: tsdb/meta.go [hunk 1]
```diff
@@ -1121,9 +1132,9 @@ func expandExprWithValues(expr influxql.Expr, keys []string, tagExprs []tagExpr,
 	return exprs
 }
 
-// seriesIDsAllOrByExpr walks an expressions for matching series IDs
+// SeriesIDsAllOrByExpr walks an expressions for matching series IDs
 // or, if no expressions is given, returns all series IDs for the measurement.
-func (m *Measurement) seriesIDsAllOrByExpr(expr influxql.Expr) (SeriesIDs, error) {
+func (m *Measurement) SeriesIDsAllOrByExpr(expr influxql.Expr) (SeriesIDs, error) {
```
Comment (jwilder) [inline tsdb/meta.go]: This is not goroutine safe as well.  Needs a read-lock since `m.seriesIDs` accessed unprotected.  Not sure what `walkWhereForSeriesIds` accesses off-hand.

**Comment by jwilder** [comment]
I think those unexported funcs might need to stay unexported and unlocked and instead create a new exported version that takes a read-lock?

**Comment by jwilder** [comment]
👍

**Comment by beckettsean** [comment]
Thank you!!!

Add to CHANGELOG?
