### PR TITLE
fix(http): Return an empty array if organization has no secret keys

### LINKED ISSUE #15362: InfluxDB 2.0: The "/orgs/{orgID}/secrets" should return an empty array instead of "Internal Server Error" [area/api]
When I trying get a list of secret keys for an Organization without secrets  than the response should be an empty array as is common in rest of API not the `500 Internal Server Error`:

```bash
#
# Create Organization
# 
-> POST 
-> http://127.0.0.1:9999/api/v2/orgs
-> {"name":"Constant Pro-1570613904830-IT","status":"active"}

<- 201
<- Created
<- {"links":{"buckets":"/api/v2/buckets?org=Constant Pro1570613904830-IT","dashboards":"/api/v2/dashboards?org=Constant Pro1570613904830-IT","labels":"/api/v2/orgs/5b7a1faae6e6185a/labels","logs":"/api/v2/orgs/5b7a1faae6e6185a/logs","members":"/api/v2/orgs/5b7a1faae6e6185a/members","owners":"/api/v2/orgs/5b7a1faae6e6185a/owners","secrets":"/api/v2/orgs/5b7a1faae6e6185a/secrets","self":"/api/v2/orgs/5b7a1faae6e6185a","tasks":"/api/v2/tasks?org=Constant Pro1570613904830-IT"},"id":"5b7a1faae6e6185a","name":"Constant Pro1570613904830-IT","description":"","createdAt":"2019-10-09T09:38:24.9396056Z","updatedAt":"2019-10-09T09:38:24.9396214Z"}

#
# Get Secrets
# 
-> GET
-> http://127.0.0.1:9999/api/v2/orgs/5b7a1faae6e6185a/secrets

<- 500 
<- Internal Server Error
<- {"code":"internal error","message":"An internal error has occurred"}
```

### PR DESCRIPTION
**Pull request by bednar**
Closes #15362

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [x] Documentation updated or issue created (provide link to issue/pr)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: http/org_service.go [hunk 1]
```diff
@@ -440,10 +440,13 @@ func (h *OrgHandler) handleGetSecrets(w http.ResponseWriter, r *http.Request) {
 	}
 
 	ks, err := h.SecretService.GetSecretKeys(ctx, req.orgID)
-	if err != nil {
+	if err != nil && influxdb.ErrorCode(err) != influxdb.ENotFound {
 		h.HandleHTTPError(ctx, err, w)
 		return
 	}
+	if ks == nil {
+		ks = []string{}
```
Comment (kelwang) [inline http/org_service.go]: Instead of doing the markup here, why dunt we just simply return an empty string in the kv layer?

File: kv/secret.go [hunk 2]
```diff
@@ -120,7 +119,10 @@ func (s *Service) getSecretKeys(ctx context.Context, tx Tx, orgID influxdb.ID) (
 	}
 
 	if id != orgID {
-		return nil, fmt.Errorf("organization has no secret keys")
+		return nil, &influxdb.Error{
```
Comment (kelwang) [inline kv/secret.go]: I think we can simply return []string, nil here.

File: http/org_service.go (hunk 1 above)
Comment (bednar) [reply http/org_service.go]: Yeah, you are right

File: kv/secret.go (hunk 2 above)
Comment (bednar) [reply kv/secret.go]: Also fixed

**Comment by jademcgough** [comment]
@bednar seems like this is ready to merge if you'd like to
