### PR TITLE
fix: config environment override improvements

### LINKED ISSUE #6943: [v1.0.0-beta2] Setting [[graphite]] templates via ENV variable doesn't work
### Bug report

**Steps to reproduce:**

```
$ export INFLUXDB_GRAPHITE_0_ENABLED=true
$ export INFLUXDB_GRAPHITE_0_BIND_ADDRESS=":2010"
$ export INFLUXDB_GRAPHITE_0_DATABASE="graphiteTest"

$ export INFLUXDB_GRAPHITE_0_TEMPLATES='["jmeter.test.*.* app..measurement.field"]'
OR
$ export INFLUXDB_GRAPHITE_0_TEMPLATES_0="jmeter.test.*.* app..measurement.field"
OR
$ export INFLUXDB_GRAPHITE_0_TEMPLATES="jmeter.test.*.* app..measurement.field"
OR
$ export INFLUXDB_GRAPHITE_0_TEMPLATES_0='["jmeter.test.*.* app..measurement.field"]'

$ service influxdb start
$ echo "jmeter.test.a.max 23 `date +%s`" | nc -vvv localhost 2010
$ influx
> use graphiteTest
> show measurements
name: measurements
------------------
name
jmeter.test.a.max
```

**Expected behavior:** [What you expected to happen]

Measurement parses properly

**Actual behavior:** [What actually happened]

It failed to

### LINKED ISSUE #7726: Cannot configure multiple graphite listeners via env variables?
### Bug report

__System info:__ InfluxDB, version v1.0.2, branch master, commit ff307047057b7797418998a4ed709b0c0f346324. Mac OS X Sierra . Tested locally, also tested on dockerized version  of 1.1 

__Steps to reproduce:__

1. I need to configure two graphite listeners, one on UDP (port 2004) and other on TCP (port 2003)
2. I set some env variables (not all because lots of them are defaults):
```
INFLUXDB_GRAPHITE_1_ENABLED=true
INFLUXDB_GRAPHITE_1_PROTOCOL=udp
INFLUXDB_GRAPHITE_1_BIND_ADDRESS=:2004
INFLUXDB_GRAPHITE_1_DATABASE=test
INFLUXDB_GRAPHITE_0_PROTOCOL=tcp
INFLUXDB_GRAPHITE_ENABLED=true
```
3. I run `influxd` and in logs I can see
```
...
[httpd] 2016/12/15 11:34:36 Listening on HTTP: [::]:8086
[retention] 2016/12/15 11:34:36 Starting retention policy enforcement service with check interval of 30m0s
[monitor] 2016/12/15 11:34:36 Storing statistics in database '_internal' retention policy 'monitor', at interval 10s
[graphite] 2016/12/15 11:34:36 Starting graphite service, batch size 5000, batch timeout 1s
[monitor] 2016/12/15 11:34:36 'graphite:tcp::2003' registered for diagnostics monitoring
[graphite] 2016/12/15 11:34:36 Listening on TCP: [::]:2003
```
4. If I do it via config file it works

__Expected behavior:__ run two graphite listeners on two ports, which I can set via env variables

__Actual behavior:__ if I set configuration via env variable only one graphite listeners is started (from configuration `INFLUXDB_GRAPHITE_0`)

__Additional info:__ [vars](https://gist.github.com/kklocek/7e762201ef556a08514852cc15638b9f), [stats](https://gist.github.com/kklocek/bf4c953125e0fd60aa882da76e0e53f3), [diagnostics](https://gist.github.com/kklocek/59f1bf6dc5eae9ea9bb5e91a3cbcaa67)

I looked through the docs but I think there is an error there also - on [config](https://docs.influxdata.com/influxdb/v1.1/administration/config/#graphite) I see:
```
Note: To set or override settings in a config section that allows multiple configurations (any section with [[double_brackets]] in the header supports multiple configurations), the desired configuration must be specified by ordinal number. For example, for the first set of [[graphite]] environment variables, prefix the configuration setting name in the environment variable with the relevant position number (in this case: 0):

...
INFLUXDB_GRAPHITE_0_PROTOCOL
...

For the Nth Graphite configuration in the configuration file, the relevant environment variables would be of the form INFLUXDB_GRAPHITE_(N-1)_BATCH_PENDING. For each section of the configuration file the numbering restarts at zero.
```
but in a `graphite` section i see:
```
protocol = “tcp”

Set to tcp or udp.

Environment variable: INFLUXDB_GRAPHITE_PROTOCOL
```

### LINKED ISSUE #15360: INFLUXDB_HTTP_ACCESS_LOG_STATUS_FILTERS doesn't filter logs
__Steps to reproduce:__

1. start influxdb by docker image 1.7.7 with ENVs:
 - INFLUXDB_HTTP_ACCESS_LOG_STATUS_FILTERS_0: "4xx"
 - INFLUXDB_HTTP_ACCESS_LOG_STATUS_FILTERS_1: "5xx"
2. send there any data
3. logs contains `rappahw [httpd] 10.0.0.13 - mydb [09/Oct/2019:08:07:57 +0000] "POST /write?db=mydb&p=%5BREDACTED%5D&precision=n&rp=&u=test HTTP/1.1" 204 0 "-" "-" e792484f-eb6b-11e9-820b-03420aff0011 2260`

__Expected behavior:__
Logs should contains request with responses 4xx or 5xx.

__Actual behavior:__
Logs contains all https logs.

__Environment info:__

* System info: Influx is running in docker, Host OS: Linux 4.19.0-5-amd64 x86_64
* InfluxDB version: InfluxDB v1.7.7 (git: 1.7 f8fdf652f348fc9980997fe1c972e2b79ddd13b0)
* Other relevant environment details: Docker 19.03.1

### LINKED ISSUE #22974: max-index-log-file-size parsed differently between config and environment
In docs + the config file, you can set
`max-index-log-file-size = "128k"`
But... when they set
`INFLUXDB_DATA_MAX_INDEX_LOG_FILE_SIZE="128k"`
in their charts, Influx threw a paddy and refused to come up. We had to get them to change it to
`INFLUXDB_DATA_MAX_INDEX_LOG_FILE_SIZE=131072`
Are we doing some kind of type enforcement on the env var that we're not doing to the config file? They're running 1.8.10

### PR DESCRIPTION
**Pull request by gwossum**
Major overhaul and refactor of environment variable config overrides, providing many bug fixes and new features:
- The following environment variables now work as expected for overriding config settings:
  -  INFLUXDB_HTTP_UNIX_SOCKET_GROUP
    - Allows for setting group both by group names and numeric group IDs. 
  - INFLUXDB_HTTP_ACCESS_LOG_STATUS_FILTERS
  - INFLUXDB_GRAPHITE_#_TEMPLATES
  - INFLUXDB_GRAPHITE_#_TAGS
  - INFLUXDB_TLS_CIPHERS
- The following configuration options now support using size suffixes (e.g. "1k", "64M", "2G") in environment variable overrides:
  - [[collected] read-buffer](https://docs.influxdata.com/influxdb/v1/administration/config/#read-buffer) (INFLUXDB_COLLECTED_#_READ_BUFFER / INFLUXDB_COLLECTD_READ_BUFFER)
  - `[data] tar-stream-buffer-size` (INFLUXDB_DATA_TAR_STREAM_BUFFER_SIZE)
  - [[flux-controller] query-initial-memory-bytes](https://docs.influxdata.com/influxdb/v1/administration/config/#query-initial-memory-bytes) (INFLUXDB_FLUX_CONTROLLER_QUERY_MAX_MEMORY_BYTES)
  - [[flux-controller] query-max-memory-bytes](https://docs.influxdata.com/influxdb/v1/administration/config/#query-max-memory-bytes) (INFLUXDB_FLUX_CONTROLLER_QUERY_MAX_MEMORY_BYTES)
  - [[flux-controller] total-max-memory-bytes](https://docs.influxdata.com/influxdb/v1/administration/config/#total-max-memory-bytes) (INFLUXDB_FLUX_CONTROLLER_TOTAL_MAX_MEMORY_BYTES)
  - [[http] max-body-size](https://docs.influxdata.com/influxdb/v1/administration/config/#max-body-size) (INFLUXDB_HTTP_MAX_BODY_SIZE)
  - [[subscriber] total-buffer-bytes](https://docs.influxdata.com/influxdb/v1/administration/config/#total-buffer-bytes) (INFLUXDB_SUBSCRIBER_TOTAL_BUFFER_BYTES)
  - [[udp] read-buffer](https://docs.influxdata.com/influxdb/v1/administration/config/#read-buffer-1) (INFLUXDB_UDP_#_READ_BUFFER / INFLUXDB_UDP_READ_BUFFER)
- Support for growing configuration arrays with environment variables:
  - Configuration arrays can now be extended using environment variables. For instance, a new `[[graphite]]` section can be added with `INFLUXDB_GRAPHITE_1_*` environment variables.
  - Config slice elements created with environment variables now get their fields properly defaulted.
  - Slice growth through environment variables is limited to 64 elements. Attempts to extend beyond this limit result in errors.
- Leading and trailing whitespace is now trimmed from environment variable values before applying them. 
- Diagnostic logging for environment variables:
  - All environment variables used for config overrides are now logged on startup and on SIGHUB configuration reload.
  - Warn on startup and SIGHUP if any environment variables starting with `INFLUXDB_*` are set but not used for config overrides. This helps diagnose issues due to mispellings, removed configuration settings, unsupported configuration types, etc.
- Improved error handling and messages:
  - Some configuration settings could have a valid unsigned value set that would overflow when cast to a signed value for use. These now produce errors. Previously these issues were silently discarded. Impacted configuration settings are `compact-throughput`, `compact-throughput-burst`, `aggressive-points-per-block`, `max-index-log-file-size`, and `tar-stream-buffer-size`. Previously, invalid values for these could silently cause corrupt log file accounting or unintentionally disable rate limiting.
  - Mixing unindexed and indexed environment variables for configuration that are not struct fields is now an error. For example, setting both INFLUXDB_HTTP_ACCESS_LOG_STATUS_FILTERS and INFLUXDB_HTTP_ACCESS_LOG_STATUS_FILTERS_0 is now an error. The previous behavior was unexpected and surprising to the user.
  - Error messages now contain full configuration struct path and index for slices.
  - More informative error messages for some configuration types.
  - Better error messages when non-ASCII characters are found in environment variable values.

Closes: #22974, #15360, #7726, #6943

### CODE REVIEW

File: toml/toml.go [hunk 1]
```diff
@@ -151,79 +181,169 @@ func ApplyEnvOverrides(getenv func(string) string, prefix string, val interface{
...
+			indexedEnvName := fmt.Sprintf("%s_%d", prefix, idx)
+			if idx < element.Len() {
+				f := element.Index(idx)
+
+				// Apply the unindexed environment variable as a default value, if available.
+				if len(value) > 0 {
+					if err := applyEnvOverrides(getenv, prefix, f, structKey); err != nil {
+						return err
+					}
+				}
```
Comment (gwossum) [inline toml/toml.go]: This behavior of using the unindexed environment value as a default for existing slice values is very strange, but it is what OSS and plutonium have both been doing. It's not intuitive and confusing. Claude doesn't like it either.

Is this intentional or a used feature? Or could this be improved?

Comment (gwossum) [reply toml/toml.go]: There is a test that explicitly tests for this, so it does seem intentional. Whether it is useful or problematic is another issue.

File: toml/toml_test.go [hunk 2]
```diff
@@ -115,42 +136,111 @@ func TestGroup_UnmarshalTOML(t *testing.T) {
...
-		} else if got, want := u.Gid, strconv.Itoa(int(group)); got != want {
-			t.Fatalf("unexpected group id: %s != %s", got, want)
+	t.Run("by group name", func(t *testing.T) {
+		gr, err := user.LookupGroupId(u.Gid)
+		unkGID := user.UnknownGroupIdError(u.Gid)
+		if errors.Is(err, unkGID) {
+			t.Skipf("skipping because LookupGroupId failed for %q: %s", u.Gid, err)
 		}
-	}
+		require.NoError(t, err, "LookupGroupId failed with error other than uer.UnknownGroupIdErr")
```
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml_test.go]: Fixed

File: toml/toml.go [hunk 3]
```diff
@@ -148,137 +178,211 @@ func ApplyEnvOverrides(getenv func(string) string, prefix string, val interface{
...
+			indexedEnvName := fmt.Sprintf("%s_%d", prefix, idx)
+			if idx < element.Len() {
+				f := element.Index(idx)
+
+				// Apply the unindexed environment variable as a default value, if available.
+				// Finding a default environment value does not count when considering if we continue
+				// extending the slice, so we throw the found return value away.
+				if _, err := applyEnvOverrides(getenv, prefix, f, structKey); err != nil {
+					return false, err
+				}
```
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml.go]: This appears to be intentional because there is a test case specifically for this.

File: toml/toml_test.go [hunk 4]
```diff
@@ -42,64 +44,83 @@ func TestSize_UnmarshalText(t *testing.T) {
...
+		str    string
+		want   uint32
+		errStr string
 	}{
 		{str: ``, want: 0},
 		{str: `0777`, want: 0777},
 		{str: `777`, want: 0777},
 		{str: `1777`, want: 01777},
 		{str: `0755`, want: 0755},
+		{str: ``, want: 0},
```
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml_test.go]: Removed in next push

File: toml/toml_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml_test.go]: Fixed in next push

File: toml/toml_test.go [hunk 5]
```diff
@@ -162,28 +252,109 @@ func (s *stringUnmarshaler) UnmarshalText(data []byte) error {
...
+	if err == nil {
+		if groupName != "" {
+			groupOverride = groupName
+		} else {
+			t.Logf("could not get current user's group name, using GID instead")
+			groupOverride = fmt.Sprintf("%d", groupID)
+		}
+	} else {
+		t.Logf("could not get current user's group: %s", err)
+		groupID = 0
```
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml_test.go:935]: This will work properly. The next push contains test cases to explicitly test that this will work properly, along with comments explaining it.

File: toml/toml_test.go [hunk 6]
```diff
@@ -162,28 +252,110 @@ func (s *stringUnmarshaler) UnmarshalText(data []byte) error {
...
+		"X_STRSLICE2":        "eve,mallory",
+		"X_STRSLICE3":        "eve",     // default value
+		"X_STRSLICE3_1":      "mallory", // override for element 1
+		"X_STRSLICE3_3":      "trudy",   // appended
+		"X_STRSLICE3_5":      "oscar",   // ignored because it's out of bounds because there is no element 4
+		"X_INTSLICE_0":       "1",
+		"X_INTSLICE_1":       "2",
+		"X_INTSLICE_2":       "3",
+		"X_INTSLICE2":        "4,5, 6",
+		"X_SIZESLICE_0":      "128m",
```
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml_test.go]: A workaround has been implemented in the next push

File: toml/toml.go [hunk 7]
```diff
@@ -75,19 +86,19 @@ func (s *Size) UnmarshalText(text []byte) error {
...
+			return fmt.Errorf("%w: %c (expected k, m, or g)", ErrSizeBadSuffix, suffix)
 		}
 		sizeText = sizeText[:len(sizeText)-1]
 	}
 
 	// Parse numeric portion of value.
 	size, err := strconv.ParseUint(string(sizeText), 10, 64)
 	if err != nil {
-		return fmt.Errorf("invalid size: %s", string(text))
+		return fmt.Errorf("%w: %w", ErrSizeParse, err)
```
[the remark this answers is not in the document]
Comment (davidby-influx) [reply toml/toml.go]: I agree with this one

File: toml/toml.go [hunk 8]
```diff
@@ -148,137 +178,211 @@ func ApplyEnvOverrides(getenv func(string) string, prefix string, val interface{
...
+	if element.Type().Name() != "" && element.CanAddr() {
+		if u, ok := element.Addr().Interface().(encoding.TextUnmarshaler); ok {
 			// Skip any fields we don't have a value to set
 			if len(value) == 0 {
-				return nil
+				return false, nil
 			}
-			return u.UnmarshalText([]byte(value))
+			if err := u.UnmarshalText([]byte(value)); err != nil {
+				return false, fmt.Errorf("failed to apply %v to %v using TextUnmarshaler %v and value '%v': %s", prefix, structKey, element.Type().String(), value, err)
```
[the remark this answers is not in the document]
Comment (davidby-influx) [reply toml/toml.go]: I agree with this one.

File: toml/toml.go [hunk 9]
```diff
@@ -148,137 +178,211 @@ func ApplyEnvOverrides(getenv func(string) string, prefix string, val interface{
...
 		element.SetString(value)
+		return true, nil
 	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
+		if len(value) == 0 {
+			return false, nil
+		}
 		intValue, err := strconv.ParseInt(value, 0, element.Type().Bits())
 		if err != nil {
-			return fmt.Errorf("failed to apply %v to %v using type %v and value '%v': %s", prefix, structKey, element.Type().String(), value, err)
+			return false, fmt.Errorf("failed to apply %v to %v using type %v and value '%v': %s", prefix, structKey, element.Type().String(), value, err)
```
Comment (davidby-influx) [inline toml/toml.go]: Wrap error here too

File: toml/toml.go [hunk 10]
```diff
@@ -148,137 +178,211 @@ func ApplyEnvOverrides(getenv func(string) string, prefix string, val interface{
...
 		element.SetInt(intValue)
+		return true, nil
 	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
+		if len(value) == 0 {
+			return false, nil
+		}
 		intValue, err := strconv.ParseUint(value, 0, element.Type().Bits())
 		if err != nil {
-			return fmt.Errorf("failed to apply %v to %v using type %v and value '%v': %s", prefix, structKey, element.Type().String(), value, err)
+			return false, fmt.Errorf("failed to apply %v to %v using type %v and value '%v': %s", prefix, structKey, element.Type().String(), value, err)
```
Comment (davidby-influx) [inline toml/toml.go]: Wrap

**Review by davidby-influx — CHANGES_REQUESTED** [review]
I would wrap all errors returned as strings, but I'm open to dissent if I'm missing something.

I need to review the tests more.

File: toml/toml.go (hunk 10 above)
Comment (gwossum) [reply toml/toml.go]: Just commit and pushed wrapping the errors.

File: toml/toml.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml.go]: Updated and pushed up with improved error message tests.

File: toml/toml.go (hunk 1 above)
Comment (gwossum) [reply toml/toml.go]: One other _very_ odd thing this does: Let's say I have a have:
```go
type Config struct {
    values []string `toml:"values"`
}
```

If I start out with:
```go
Config{
    values: []string{"one", "two", "three"},
}
```
and I have an environment variable `INFLUXDB_VALUES="alice,bob,carol"`, then you end up with:
```go
Config{
    values: []string{"alice,bob,carol", "alice,bob,carol", "alice,bob,carol"
}
```

If, however, you start out with:
```go
Config{
    values: []string{},
}
```
and an environment variable `INFLUXDB_VALUES="alice,bob,carol"`, then you end up with:
```go
Config{
    values: []string{"alice", "bob", "carol"}
}
```

This is highly inconsistent behavior and very non-intuitive!

I think the reason the default is supported is for configuring common options across a slice of configurations, for instance UDP buffer sizes across all UDP inputs. It makes sense when you have a slice of structs, but behaves weirdly when you have a slice of simple types like strings. Maybe we handle the two cases differently?

File: toml/toml.go [hunk 11]
```diff
@@ -51,10 +55,17 @@ func (d Duration) MarshalText() (text []byte, err error) {
 // and "g" or "G" for gibibytes. If a size suffix isn't specified then bytes are assumed.
 type Size uint64
 
+var (
+	ErrSizeEmpty     = errors.New("size was empty")
+	ErrSizeBadSuffix = errors.New("unknown size suffix")
+	ErrSizeParse     = errors.New("invalid size")
+	ErrSizeOverflow  = fmt.Errorf("size would overflow the max size (%d) of a uint", uint64(math.MaxUint64))
```
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml.go]: This was fixed when `SSize` was added.

File: toml/toml.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml.go]: Fixed.

File: toml/toml.go (hunk 1 above)
Comment (davidby-influx) [reply toml/toml.go]: Does this work the same in Plutonium with a separate implementation, or does Plutonium rely on this implementation, or does it behave differently?

Comment (gwossum) [reply toml/toml.go]: So... Plutonium has the same behavior WRT to using the unindexed version of a variable to override a value for all elements in slice. For instance, `INFLUXDB_UDP_DATABASE` is a default for overriding each udp input, while `INFLUXDB_UDP_1_DATABASE` is a specific override for the second UDP input.

However, plutonium does not support a CSV list to set an array at all, so the behavior in https://github.com/influxdata/influxdb/pull/27312/changes#r3018901388 does not apply to plutonium. 

Since the CSV setting would only work with slices of primitive types (e.g. `[]string`, `[]int`), I thought maybe there was no way in the actual config to use it. I did find configurations in both OSS and plutonium where it could be used, but of course only OSS currently supports using CSV to set them. Previously, using a CSV list was probably the only _only_ way to override them, because growing a slice with indexed environment variables was not supported.

**Comment by gwossum** [comment]
I cranked Claude's effort up and told it to look for potential bugs, inconsistent behavior, and unintuitive behavior:

> 
> Potential Bugs
> 
>   1. Default applied to in-bounds elements of non-struct/non-pointer slices mutates existing values
> 
>   Lines 443-453: For in-bounds elements, the unindexed default is applied unconditionally to all element types:
> 
>   if idx < element.Len() {
>       f := element.Index(idx)
>       if defaultResult, err := applyEnvOverrides(getenv, prefix, f, ...); err != nil {
> 
>   But for growth elements (lines 467-469), the default is only applied to struct/pointer types:
> 
>   elemKind := element.Type().Elem().Kind()
>   if elemKind == reflect.Struct || elemKind == reflect.Pointer {
> 
>   This means if you have IntSlice: []int{10, 20, 30} and set INFLUXDB_INTSLICE=99, every existing element gets overwritten to 99 as a "default", then indexed overrides are applied on top. This is asymmetric: existing
>    []int elements get the default applied, but growth []int elements do not. In practice this means INFLUXDB_INTSLICE=99 overwrites all existing elements to 99 — which is probably unexpected when you thought you were
>    setting a default for new elements.
> 
>   2. Comma-separated path partial mutation on error
> 
>   Lines 508-519: If parsing fails mid-way through a comma-separated value (e.g., INFLUXDB_INTS="1,bad,3"), elements already appended to the slice (1) remain, but the function returns noResult, err. The slice is
>   partially mutated but the caller receives an error with no indication of the partial state. The caller (ApplyEnvOverrides) returns an error and a nil var list, but the config struct has been partially modified.
> 
>   This same issue exists in the indexed growth path — if element 0 is appended successfully but element 1's indexed override fails to parse, element 0 remains in the slice.
> 
>   3. getenv called for every struct field at every level regardless of relevance
> 
>   Line 361: value := strings.TrimSpace(getenv(prefix)) is called at the top of every recursive call — including for struct types where value is never used (structs don't have a direct value, only their fields do).
>   For the real config, this means getenv("INFLUXDB"), getenv("INFLUXDB_DATA"), getenv("INFLUXDB_META"), etc. are all called despite being useless for struct nodes. This is wasteful but not a bug per se. However, it
>   means a user who sets INFLUXDB_DATA="something" gets no error — it's silently ignored.
> 
>   4. Ambiguous env var names between slice index and struct field
> 
>   For GraphiteInputs []graphite.Config (toml tag: graphite), the slice creates env names like INFLUXDB_GRAPHITE_0_TEMPLATES. But if a struct had a field with toml tag 0, its env name would also be PREFIX_0. There's
>   no disambiguation between "index 0 of a slice" and "field named 0 of a struct." This isn't a realistic bug (no config field would be named 0), but it's an inherent ambiguity in the env var naming scheme.
> 
>   A more realistic collision: a struct with a field named templates alongside a []string field creates PREFIX_TEMPLATES for the scalar and PREFIX_TEMPLATES as the unindexed default for the slice — same env var name,
>   different semantics depending on which field is processed first.
> 
>   ---
>   Inconsistent Behavior
> 
>   5. Default application asymmetry between existing and growth elements
> 
>   As noted in #1, defaults for scalar slices ([]int, []string, etc.) are applied to existing elements but not to growth elements. The elemKind == reflect.Struct || elemKind == reflect.Pointer guard at line 467-469
>   means []string growth elements don't get defaults. This is intentional (defaulting a single string to a grown element doesn't make sense when the growth is driven by indexed vars), but it creates an inconsistency:
>   the same env var (X_FOO) both overwrites existing elements and is ignored for new ones.
> 
>   6. TrimSpace applied to all values including strings
> 
>   Line 361: strings.TrimSpace is applied before the type switch. For numeric types, bool, and durations this is helpful (allows " 42 "). But for strings, it silently strips meaningful whitespace. A value like
>   INFLUXDB_META_DIR=" /path " becomes "/path". This is a behavioral change from the original code that used raw getenv.
> 
>   7. Comma-separated path only triggers for initially-empty slices
> 
>   Line 500: if element.Len() == 0 && len(value) > 0. If the config file pre-populates a slice with one element, the comma-separated path is skipped entirely — even if both the unindexed and indexed env vars are
>   unset. The indexed loop runs, finds nothing, and the comma-separated check sees element.Len() != 0. So INFLUXDB_GRAPHITE_0_TEMPLATES="a,b,c" works only if templates was empty in the config file.
> 
>   This is the existing behavior and intentional (indexed vars processed first, CSV is a fallback for empty slices), but it's unintuitive — the same env var syntax works or doesn't depending on whether the config file
>    has a default value.
> 
>   8. No env var handling for map types
> 
>   Line 49 in config.go: HTTPHeaders map[string]string has toml tag headers. The function falls through to the default return noResult, nil at the bottom — maps are silently ignored. Setting
>   INFLUXDB_HTTP_HEADERS_X_CUSTOM="value" has no effect and no error.
> 
>   ---
>   Unintuitive Behavior
> 
>   9. Unindexed env var for struct slices acts as default for ALL fields
> 
>   For GraphiteInputs []graphite.Config (tag: graphite), setting INFLUXDB_GRAPHITE_DATABASE=mydb sets the database field on every graphite input (existing and grown), as a "default." Then
>   INFLUXDB_GRAPHITE_0_DATABASE=override overrides just element 0. The unindexed form silently applies to every element, which could surprise a user who expected it to only affect element 0 or a "global" setting.
> 
>   10. Growth stops at first gap — no sparse indexing
> 
>   If a user sets INFLUXDB_GRAPHITE_0_ENABLED=true and INFLUXDB_GRAPHITE_2_ENABLED=true (skipping 1), only element 0 is created. The loop hits index 1, finds nothing, sets envOutOfBounds = true, and stops. Element 2
>   is never reached. There's no error — it's silently ignored. A user might expect sparse indices to work.
> 
>   11. Whitespace-only values treated as "not set"
> 
>   Lines 390, 396, 406, 416, 426: if len(value) == 0 after TrimSpace means INFLUXDB_FOO=" " is treated as unset. A user explicitly setting an env var to spaces might expect it to be applied (especially for string
>   fields where " " could be meaningful). Combined with #6, there's no way to set a string field to whitespace via env vars.
> 
>   12. Pointer fields silently ignored when nil
> 
>   Lines 366-369: A nil pointer is silently skipped. If the config defines NestedPtr *Config and it's nil, setting INFLUXDB_NESTEDPTR_FOO=bar is silently ignored. The user gets no error or indication that their env
>   var had no effect. This is correct (you can't set fields on a nil struct), but it's a surprising silent failure.
> 
>

File: toml/toml.go [hunk 12]
```diff
@@ -51,21 +56,33 @@ func (d Duration) MarshalText() (text []byte, err error) {
...
-	mult := uint64(1)
-
-	// Preserve the original text for error messages
-	sizeText := text
+	mult = 1
+	numText = text
 
-	// Parse unit of measure
-	suffix := text[len(sizeText)-1]
+	suffix := text[len(text)-1]
```
Comment (davidby-influx) [inline toml/toml.go]: Is this safe if the last byte is part of a rune?  I think we need to use [DecodeLastRune](https://pkg.go.dev/unicode/utf8#DecodeLastRune)

File: toml/toml.go [hunk 13]
```diff
@@ -75,27 +92,131 @@ func (s *Size) UnmarshalText(text []byte) error {
 		case 'g', 'G':
 			mult = 1 << 30 // GiB
 		default:
-			return fmt.Errorf("unknown size suffix: %c (expected k, m, or g)", suffix)
+			return nil, 0, fmt.Errorf("%w: %c (expected k, m, or g)", ErrSizeBadSuffix, suffix)
+		}
+		numText = text[:len(text)-1]
```
Comment (davidby-influx) [inline toml/toml.go]: Probably should be rune-safe truncation here.

File: toml/toml.go [hunk 14]
```diff
@@ -75,27 +92,131 @@ func (s *Size) UnmarshalText(text []byte) error {
...
+}
+
+// unmarshalSize parses a byte size from text into a size type.
+// Unsigned types reject negative values; signed types accept them.
+func unmarshalSize[T sizeConstraint](dst *T, text []byte) error {
+	// Preserve original text for error messages before stripping the sign.
+	originalText := text
+
+	// Detect and strip leading negative sign.
+	negative := len(text) > 0 && text[0] == '-'
```
Comment (davidby-influx) [inline toml/toml.go]: Use [DecodeRune](https://pkg.go.dev/unicode/utf8#DecodeRune) here?

**Review by davidby-influx — CHANGES_REQUESTED** [review]
Some `[]byte` handling suggestionss

File: toml/toml_test.go [hunk 15]
```diff
@@ -197,70 +391,393 @@ func TestEnvOverride_Builtins(t *testing.T) {
...
+		default:
+			return ""
+		}
+	}
+
+	var c config
+	require.NoError(t, itoml.ApplyEnvOverrides(env, "X", &c))
+	// Indexed env var X_VALS_0 grows the slice to length 1.
+	// The comma-separated fallback is skipped because element.Len() != 0.
+	// X_VALS acts as a default applied to element 0 first, then X_VALS_0 overwrites it.
```
[the remark this answers is not in the document]
Comment (gwossum) [reply toml/toml_test.go]: Fixed in latest set of commits.

File: toml/toml.go (hunk 12 above)
Comment (gwossum) [reply toml/toml.go]: It is safe and the function would work as intended because all the valid suffixes are low ASCII, but the error message would be strange and report a character not present in the input.

Fixed so the error message comes out correct and added a test case.

File: toml/toml.go (hunk 13 above)
Comment (gwossum) [reply toml/toml.go]: Yes, updated in conjunction with previous comment.

File: toml/toml.go (hunk 14 above)
Comment (gwossum) [reply toml/toml.go]: This is correct, but it shouldn't require thinking about it to decide if it's correct. This will be made explicitly rune-safe in the next batch of commits.

File: cmd/influxd/run/command.go [hunk 16]
```diff
@@ -90,12 +99,37 @@ func (cmd *Command) LoadConfig(args ...string) (Options, *Config, error) {
...
+// Both lists are emitted unconditionally (even when empty) so operators can
+// confirm the diagnostic ran. The unmatched list is computed against
+// os.Environ() so it reflects the real process environment regardless of
+// what cmd.Getenv may have been overridden to during testing.
+func (cmd *Command) logEnvVarDiagnostics(log *zap.Logger, appliedEnvVars []string) {
+	unmatched := itoml.UnmatchedEnvVars(os.Environ(), EnvVarPrefix, appliedEnvVars)
+	log.Info("applied env var overrides",
+		zap.String("prefix", EnvVarPrefix),
+		zap.Strings("vars", appliedEnvVars))
+	log.Info("unmatched env vars in namespace; may be misspelled, unsupported by env var overrides, or removed in this version",
```
Comment (davidby-influx) [inline cmd/influxd/run/command.go]: `Info` or `Warn` or doesn't matter?  Very minor, not a blocker.

File: cmd/influxd/run/command.go [hunk 17]
```diff
@@ -90,12 +99,37 @@ func (cmd *Command) LoadConfig(args ...string) (Options, *Config, error) {
...
+//     a config field.
+//   - "unmatched env vars in namespace" lists env vars in the EnvVarPrefix
+//     namespace that were set but did not match any config field — typically
+//     the result of typos, fields that have been removed in this version, or
+//     fields whose types are not supported by env var overrides (such as map
+//     fields).
+//
+// Both lists are emitted unconditionally (even when empty) so operators can
+// confirm the diagnostic ran. The unmatched list is computed against
+// os.Environ() so it reflects the real process environment regardless of
```
Comment (davidby-influx) [inline cmd/influxd/run/command.go]: Is that what we want?  Why not respect the local `GetEnv` if there is one?  It would seem to make testing easier to do so.

File: services/collectd/service.go [hunk 18]
```diff
@@ -174,10 +174,10 @@ func (s *Service) Open() error {
 	}
 
 	if s.Config.ReadBuffer != 0 {
-		err = conn.SetReadBuffer(s.Config.ReadBuffer)
+		rbs := int(s.Config.ReadBuffer)
```
Comment (davidby-influx) [inline services/collectd/service.go]: Casting impedance

File: toml/toml.go [hunk 19]
```diff
@@ -94,7 +99,7 @@ func parseSizeSuffix(text []byte) (numText []byte, mult uint64, err error) {
 		default:
 			return nil, 0, fmt.Errorf("%w: %c (expected k, m, or g)", ErrSizeBadSuffix, suffix)
 		}
-		numText = text[:len(text)-1]
+		numText = text[:len(text)-suffixSize]
```
Comment (davidby-influx) [inline toml/toml.go:106]: Nice!

File: toml/toml.go [hunk 20]
```diff
@@ -284,6 +299,161 @@ func (g *Group) UnmarshalTOML(data interface{}) error {
...
+	appliedSet := make(map[string]struct{}, len(applied))
+	for _, name := range applied {
+		appliedSet[name] = struct{}{}
+	}
+
+	keyPrefix := prefix + "_"
+	seen := make(map[string]struct{})
+	var unmatched []string
+	for _, entry := range environ {
+		eq := strings.IndexByte(entry, '=')
```
Comment (davidby-influx) [inline toml/toml.go]: I feel like all the string handling should be runes, but I can't see how to do it efficiently with the runes package. So I guess this is just a lament, not a requested change.

File: toml/toml.go [hunk 21]
```diff
@@ -284,6 +299,161 @@ func (g *Group) UnmarshalTOML(data interface{}) error {
...
+		if reflect.PointerTo(target).Implements(textUnmarshalerType) {
+			return false
+		}
+		return true
+	}
+
+	var violations []string
+	seen := make(map[reflect.Type]bool)
+	var walk func(t reflect.Type, path string)
+	walk = func(t reflect.Type, path string) {
```
Comment (davidby-influx) [inline toml/toml.go]: Would this be cleaner as a separate function, not a lambda?  Not a blocker.

Comment (davidby-influx) [reply toml/toml.go]: taking in `violations` and returning it....

File: toml/toml_test.go [hunk 22]
```diff
@@ -70,22 +70,29 @@ func TestSize_UnmarshalText(t *testing.T) {
...
 		{"bad_suffix_f", "abcdef", itoml.ErrSizeBadSuffix, "unknown size suffix: f (expected k, m, or g)"},
 		{"bad_suffix_B", "1KB", itoml.ErrSizeBadSuffix, "unknown size suffix: B (expected k, m, or g)"},
 		{"bad_suffix_t", "1t", itoml.ErrSizeBadSuffix, "unknown size suffix: t (expected k, m, or g)"},
 		{"non_numeric", "√m", itoml.ErrSizeParse,
 			`invalid size: error parsing "√m": strconv.ParseUint: parsing "√": invalid syntax`},
+		// Trailing multi-byte rune: parseSizeSuffix must decode the last rune
+		// rather than the last byte, so the error message shows the actual
+		// character instead of a UTF-8 continuation byte.
+		{"bad_suffix_multibyte", "1√", itoml.ErrSizeBadSuffix,
+			"unknown size suffix: √ (expected k, m, or g)"},
```
Comment (davidby-influx) [inline toml/toml_test.go:85]: Thanks!

**Review by davidby-influx — CHANGES_REQUESTED** [review]
The AI suggestions on casting checks, and a few nits and questions from me.

Continued nice work!

File: cmd/influxd/run/command.go (hunk 17 above)
Comment (gwossum) [reply cmd/influxd/run/command.go]: We can't use `cmd.Getenv` because we need _all_ environment variables, but there could be symmetrical `cmd.Environ`. I'll make the change.

File: services/collectd/service.go (hunk 18 above)
Comment (gwossum) [reply services/collectd/service.go]: We have to make the conversion because `SetReadBuffer` takes an `int`, while the configuration is a `toml.SSize` (uint64). I've added range checking in an upcoming commit. The alternative is to either create a `toml.ISize` type, or not allow size suffixes for the configuration.

File: toml/toml.go (hunk 20 above)
Comment (gwossum) [reply toml/toml.go]: For low-ASCII characters, `strings.IndexByte` is safe. However, I've changed it to `strings.Cut` in an upcoming push.

File: toml/toml.go (hunk 21 above)
Comment (gwossum) [reply toml/toml.go]: Extracted and simplified. Also leveraged the cycle breaking code to be recursive type checking code, since recursive types (e.g. linked lists) can not be expressed in toml and therefore are not valid for config data types. Will be in next push.

File: toml/toml.go (hunk 1 above)
Comment (gwossum) [reply toml/toml.go:739]: The slice handling is greatly improved in the latest commit. Unindexed env vars with CSV data will now unconditionally overwrite slices of leaf types (not struct types). It is also now an error to use indexed and unindexed env vars with slices of leaf types, since that leads to surprising and unintuitive behavior.

File: services/subscriber/service.go [hunk 23]
```diff
@@ -370,7 +370,7 @@ func (s *Service) updateSubs() {
 	if createdNew || len(toClose) > 0 {
 		memoryLimit := int64(0)
 		if s.conf.TotalBufferBytes != 0 {
```
Comment (davidby-influx) [inline services/subscriber/service.go:372]: Perhaps `> 0` instead of `!= 0`

File: cmd/influxd/run/config_command.go [hunk 24]
```diff
@@ -43,7 +43,7 @@ func (cmd *PrintConfigCommand) Run(args ...string) error {
 	}
 
 	// Apply any environment variables on top of the parsed config
-	if err := config.ApplyEnvOverrides(os.Getenv); err != nil {
+	if _, err := config.ApplyEnvOverrides(os.Getenv); err != nil {
 		return fmt.Errorf("apply env config: %v", err)
```
Comment (davidby-influx) [inline cmd/influxd/run/config_command.go]: `w` for the Errorf format?

File: toml/toml.go [hunk 25]
```diff
@@ -124,161 +307,599 @@ func (m FileMode) MarshalText() (text []byte, err error) {
...
-		if err != nil {
-			return err
+	var gid int
+
+	group, lookupErr := user.LookupGroup(groupName)
+	if lookupErr != nil {
+		// Is groupName really a numeric group?
+		if _, err := strconv.Atoi(groupName); err != nil {
+			// No, not a number.
+			return lookupErr
```
Comment (davidby-influx) [inline toml/toml.go:303]: Check for negative or use `ParseUint` if GID must be positive

File: toml/toml.go [hunk 26]
```diff
@@ -124,161 +307,599 @@ func (m FileMode) MarshalText() (text []byte, err error) {
...
-		*g = Group(gid)
-		return nil
+		group, lookupErr = user.LookupGroupId(groupName)
+		if lookupErr != nil {
+			return lookupErr
+		}
+	}
+
+	gid, err := strconv.Atoi(group.Gid)
+	if err != nil {
```
Comment (davidby-influx) [inline toml/toml.go:312]: Same as above.  Negative GID permitted?

File: toml/toml.go [hunk 27]
```diff
@@ -124,161 +307,599 @@ func (m FileMode) MarshalText() (text []byte, err error) {
...
+			"%s: type %s forms a cycle (recursive types cannot be represented in TOML)",
+			path, t)}
+	}
+	stack[t] = true
+	// Simply deleting the type when returning up the struct key is OK since cycles are an error.
+	defer delete(stack, t)
+
+	switch t.Kind() {
+	case reflect.Pointer:
+		return walkForConfigType(t.Elem(), path, stack)
```
Comment (davidby-influx) [inline toml/toml.go:438]: Nothing added to `path` here?  No `*` ?

File: toml/toml.go [hunk 28]
```diff
@@ -124,161 +307,599 @@ func (m FileMode) MarshalText() (text []byte, err error) {
...
-		element = spec.Elem()
-	}
-
-	value := getenv(prefix)
 
 	switch element.Kind() {
 	case reflect.String:
 		if len(value) == 0 {
-			return nil
+			return noResult, nil
```
Comment (davidby-influx) [inline toml/toml.go]: So we can't clear a value with an ENV override?  Probably the right thing, and certainly the existing behavior.

File: toml/toml.go [hunk 29]
```diff
@@ -124,161 +307,599 @@ func (m FileMode) MarshalText() (text []byte, err error) {
...
 		}
 		element.SetString(value)
+		return appliedEnvVar(prefix), nil
 	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
+		if len(value) == 0 {
```
Comment (davidby-influx) [inline toml/toml.go]: Is this check in `ParseInt` or is it necessary here?  If it's in `ParseInt` do we get a better error message?

File: toml/toml.go [hunk 30]
```diff
@@ -124,161 +307,599 @@ func (m FileMode) MarshalText() (text []byte, err error) {
...
+		// This intentionally differs from TOML's stricter integer syntax.
 		intValue, err := strconv.ParseInt(value, 0, element.Type().Bits())
 		if err != nil {
-			return fmt.Errorf("failed to apply %v to %v using type %v and value '%v': %s", prefix, structKey, element.Type().String(), value, err)
+			return noResult, fmt.Errorf("failed to apply %v to %v using type %v and value %q: %w", prefix, structKey, element.Type().String(), value, err)
 		}
 		element.SetInt(intValue)
+		return appliedEnvVar(prefix), nil
 	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
+		if len(value) == 0 {
```
Comment (davidby-influx) [inline toml/toml.go]: As above for `ParseInt` call...

File: toml/toml.go [hunk 31]
```diff
@@ -124,161 +307,599 @@ func (m FileMode) MarshalText() (text []byte, err error) {
...
+
 		typeOfSpec := element.Type()
 		for i := 0; i < element.NumField(); i++ {
 			field := element.Field(i)
 
-			// Skip any fields that we cannot set
-			if !field.CanSet() && field.Kind() != reflect.Slice {
-				continue
-			}
+			fieldResult, err := func() (envOverrideResult, error) {
```
Comment (davidby-influx) [inline toml/toml.go]: Would this be better as a named function?  You would need `structkey`, `field`, and `getenv`? 

Lambdas with recursion (or alternating recursion) seem hard to reason about to me.  Your thoughts?  Cleaner as is or named?

**Review by davidby-influx — CHANGES_REQUESTED** [review]
A few changes, a few questions...

File: services/subscriber/service.go (hunk 23 above)
Comment (gwossum) [reply services/subscriber/service.go:372]: (NOTE: he semantics of this code are unchanged with the PR vs the previous code.)

I think your suggested change is correct and there has been a bug here. The enterprise docs for [total-buffer-bytes](https://docs.influxdata.com/enterprise_influxdb/v1/administration/configure/config-data-nodes/#total-buffer-bytes) say that 0 disables the memory limit. Since negative numbers are also accepted, a user might expect that -1 also disables the limit, but that probably actually sets a very low limit because `-1 / int64(len(s.subs))` is almost certainly 0, which then is pushed up to 1. 

Since this is _not_ directly related to the environment variable work, though, I'd rather put in a separate PR.

File: cmd/influxd/run/config_command.go (hunk 24 above)
Comment (gwossum) [reply cmd/influxd/run/config_command.go]: Will be in next set of commits pushed.

File: toml/toml.go (hunk 29 above)
Comment (gwossum) [reply toml/toml.go]: This is to ignore environment variables with no or an empty value. If we were to parse it, we would get an error and the entire `ApplyEnvOverrides` would error out. However, since we're using `os.Getenv`, an unset environment variable returns an empty string, and we don't want to error if the environment variable is not set.

This check has to happen here because slices and structs could have empty or no value for their field name. Otherwise it could happen higher up in the function before the switch. We could probably have `if isLeafType(element) && len(value) { return noResult, nil }`. That should be equivalent.

File: toml/toml.go (hunk 30 above)
Comment (gwossum) [reply toml/toml.go]: Same explanation.

File: toml/toml.go (hunk 25 above)
Comment (gwossum) [reply toml/toml.go:303]: No modern operating system that supports group IDs (e.g. macOS and Linux) allow negative group IDs. However, no explicit negative number check is necessary here because a negative group ID from the user would fail the `user.LookupGroupId` call, because negative group numbers are invalid. The error from `LookupGroupId` in that case is still informative and accurate.

File: toml/toml.go (hunk 26 above)
Comment (gwossum) [reply toml/toml.go:312]: At this point in the code, `group.Gid` came from an OS call. If the OS returns a negative number, that is correct.

File: toml/toml.go (hunk 27 above)
Comment (gwossum) [reply toml/toml.go:438]: This is dereferencing the pointer. The environment variable path and struct field do not change.

File: toml/toml.go (hunk 28 above)
Comment (gwossum) [reply toml/toml.go]: This is the current behavior and also doesn't keep you from doing anything you'd want to do. Most (all?) string fields in the configuration an empty string doesn't make sense. They're things like paths and hostnames, etc.

File: toml/toml.go (hunk 31 above)
Comment (gwossum) [reply toml/toml.go]: Each case of the switch has now be extracted into top-level functions. For structs, each field is now handled in a top-level function of its own.

File: toml/toml.go [hunk 32]
```diff
@@ -134,94 +131,72 @@ func unmarshalSize[T sizeConstraint](dst *T, text []byte) error {
...
-		} else {
-			maxVal = uint64(math.MaxInt64)
-		}
-		overflowErr = ErrSSizeOverflow
+		return fmt.Errorf("%w: parsing size suffix of %q got multiplier of 0", ErrSizeParse, text)
 	}
 
-	size, err := strconv.ParseUint(string(numText), 10, bitSize)
+	typ := reflect.TypeOf(*dst)
+	baseSize, err := parse(string(numText), 10, typ.Bits())
```
Comment (davidby-influx) [inline toml/toml.go:138]: Cool trick

**Review by davidby-influx — APPROVED** [review]
Very clean code for a messy problem!  Thanks for all the revisions; I think the code is eminently maintainable now.  Great work!
