### PR TITLE
fix: error instead of panic when enterprise tries to restore with OSS

### LINKED ISSUE #22018: updateMetaStore is only supported for OSS, panics in Enterprise
To reproduce: take a portable backup in OSS, then try to restore using OSS tooling (instead of Enterprise influxd-ctl) into an Enterprise cluster. The data node that the request hits panics and exits.

Desired behaviour: the data node should log an error and refuse the request.

### PR DESCRIPTION
**Pull request by lesam**
Closes #22018 

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

**Comment by lesam** [comment]
Note Enterprise users should use `influxd-ctl`, this bug applies to Enterprise users attempting to use the OSS `influxd restore` workflow.

File: services/snapshotter/service.go [hunk 1]
```diff
@@ -182,7 +188,15 @@ func (s *Service) updateMetaStore(conn net.Conn, bits []byte, backupDBName, rest
 		return fmt.Errorf("failed to decode meta: %s", err)
 	}
 
-	data := s.MetaClient.Data()
```
Comment (lesam) [inline services/snapshotter/service.go:185]: I testing this in 1.9.3 Enterprise - it `panic`s here because we in 1.9.3 we do an unchecked type assertion. A recent OSS PR fixed the unchecked type assertion, which broke the Enterprise build. This PR does the right thing and checks the type assertion.

**Review by gwossum — APPROVED** [review]
Looks good to me

**Comment by lesam** [comment]
New flaky test: fix at https://github.com/influxdata/influxdb/pull/22038 . Looks like a test problem, not a prod problem.
