### PR TITLE
fix(dbrp): improve DBRP API validation errors

### LINKED ISSUE #20134: Improve validation error messages for DBRP API
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Having an InfluxDB Cloud account (free tier)
2. Setup a bucket and write data into it
3. Try to do DBRP mapping with following command:

curl  --request POST 'https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/dbrps' \
--header 'Authorization:  Token {my token}' \
--header 'Content-type: application/json' \
--data '{
    "bucketID": "{my bucketID}",
    "database": "{some database name}",
    "default": true,
    "orgID": "{my orgID}",
    "retention_policy": "30days"
}'
__Expected behavior:__
A DBRP should be setup for the bucket I give

__Actual behavior:__
400 Bad request error happens with following message
{
    "code": "invalid",
    "message": "invalid ID"
}

__Environment info:__

* InfluxDB version: InfluxDB Cloud

__Config:__
Token I use an all permission token

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #20134

### CODE REVIEW

File: dbrp/error.go [hunk 1]
```diff
@@ -29,8 +25,51 @@ var (
...
+// to decode an organization ID.
+func ErrInvalidOrgID(id string, err error) error {
+	return &influxdb.Error{
+		Code: influxdb.EInvalid,
+		Msg:  fmt.Sprintf("invalid org ID %q", id),
+		Err:  err,
+	}
+}
+
+// ErrInvalidBucketID returns a more informative error about a failure
```
Comment (davidby-influx) [inline dbrp/error.go:54]: The functions below are nice - definitely helpful to provide more info.

**Review by davidby-influx — APPROVED** [review]
Looks helpful for debugging!
