### PR TITLE
Enforce minimum shard duration when creating retention policies

### LINKED ISSUE #7563: RP should not allow `INF` or `0` as a shard duration
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

InfluxDB 1.0.x

__Actual behavior:__ [What actually happened]

CREATE RP and ALTER RP queries will accept `INF` as a valid duration, which should not be accepted, as shards must have an explicit end time. What ends up happening is the shards have a `1s` duration, effectively meaning all data is dropped as soon as it is written.

__Desired behavior:__

Throw an error and reject the RP query.

### PR DESCRIPTION
**Pull request by corylanou**
Fixes #7563 

Here are examples of what the new results are when running `CREATE RETENTION POLICY` commands:

```sql
> create database foo
> CREATE RETENTION POLICY policy3 ON foo DURATION INF REPLICATION 1 SHARD DURATION 0m
> CREATE RETENTION POLICY policy4 ON foo DURATION INF REPLICATION 1 SHARD DURATION 1s
> show retention policies on foo
name    duration        shardGroupDuration      replicaN        default
----    --------        ------------------      --------        -------
autogen 0s              168h0m0s                1               true
policy3 0s              168h0m0s                1               false
policy4 0s              1h0m0s                  1               false

> CREATE RETENTION POLICY policy4 ON foo DURATION INF REPLICATION 1 SHARD DURATION INF
ERR: error parsing query: invalid duration INF for shard duration at line 1, char 82
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [x] Provide example syntax

### CODE REVIEW

File: services/meta/client_test.go [hunk 1]
```diff
@@ -239,8 +239,8 @@ func TestMetaClient_CreateRetentionPolicy(t *testing.T) {
 	rp0 := meta.RetentionPolicyInfo{
 		Name:               "rp0",
 		ReplicaN:           1,
-		Duration:           time.Hour,
-		ShardGroupDuration: time.Hour,
+		Duration:           2 * time.Hour,
```
Comment (corylanou) [inline services/meta/client_test.go]: This change was required as tests further down rely on changing the RP duration and it was dropping below the new min enforced floor.  This was the easiest way to fix that test other than rewriting the entire test.

File: influxql/parser_test.go [hunk 2]
```diff
@@ -2059,6 +2059,36 @@ func TestParser_ParseStatement(t *testing.T) {
 				ShardGroupDuration: 30 * time.Minute,
 			},
 		},
+		{
```
Comment (corylanou) [inline influxql/parser_test.go]: Added these tests just for coverage.  This is just validating the parser allows for these values, and parses the durations correctly.  The integration tests then make sure the minimums are being enforced.
