### PR TITLE
fix: bufio.Scanner: token too long

### LINKED ISSUE #19586: cli write: Error: Failed to write data: bufio.Scanner: token too long
I'm seeing the error:
`Error: Failed to write data: bufio.Scanner: token too long.`

when i try to write a csv data that is ~164MB to influxdb. Based on https://stackoverflow.com/questions/21124327/how-to-read-a-text-file-line-by-line-in-go-when-some-lines-are-long-enough-to-ca , it looks like we might need to evaluate if we should switch to bufio.Reader? https://github.com/influxdata/influxdb/blob/f09ee881fb33ca06474ca499deac0c5cd1bd9f91/write/batcher.go#L67

I can send the file offline. 

```
➜  influxdb git:(master) ✗ influx query -c tools 'from(bucket: "apps") |> range(start: -1m)' -r | influx write -c default --format csv -b apps
Error: Failed to write data: bufio.Scanner: token too long.
```

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #19586

This PR fixes two issues. 

* Fixes a panic that was introduced with a new `LineReader` type.
* Adds an option to override the maximum line length in `write.Batcher` to support line lengths greater than the default 64KiB for a new `bufio.Scanner`
* Adds a CLI argument, `max-line-length`, to configure the maximum line length. The default is 16MB, which should cover the majority of use cases.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: write/batcher.go [hunk 1]
```diff
@@ -59,13 +66,29 @@ func (b *Batcher) Write(ctx context.Context, org, bucket platform.ID, r io.Reade
...
 	scanner := bufio.NewScanner(r)
 	scanner.Split(ScanLines)
+
+	maxLineLength := bufio.MaxScanTokenSize
+	if b.MaxLineLength > 0 {
+		maxLineLength = b.MaxLineLength
+	}
+
+	// limit the initial size of the buffer to a maximum of bufio.MaxScanTokenSize bytes
+	scanner.Buffer(make([]byte, min(bufio.MaxScanTokenSize, maxLineLength)), maxLineLength)
```
Comment (rogpeppe) [inline write/batcher.go:90]: Or just `scanner.Buffer(nil, maxLineLength)` and let the buffer be grown as needed when lines are read. That way when all lines are short (presumably a common case) we'll use a lot less memory.

**Review by rogpeppe — COMMENTED** [review]
I'm afraid I didn't have time to finish looking through the code before eod, but here's one small comment in the meantime... (looks good otherwise as far as I saw so far!)

File: write/batcher.go (hunk 1 above)
Comment (stuartcarnie) [reply write/batcher.go:90]: Good feedback – consider it done!

**Review by brettbuddin — APPROVED** [review]
Nice find!

**Review by e-dard — APPROVED** [review]
LGTM 👍
