### PR TITLE
Fix Prometheus regex parsing

### LINKED ISSUE #9134: v1.4.2 - prometheus remote storage exception
### Bug report
Just wanted to report the following exception that I have encountered with the InfluxDB / Prometheus long storage integration, this exception is not continuously happening but it appears from time to time.

__System info:
InfluxDB v1.4.2
Prometheus 2.0
CentOS 7

__Additional info:

```
[I] 2017-11-17T15:40:03Z SELECT f64 FROM PROM.raw._ WHERE job = 'dev' AND u_metric_name !~ 'eventslast.*' AND u_metric_type = 'count' AND __name__ = 'events_metrics_seconds_count' AND time >= '2017-11-16T15:35:02Z' AND time <= '2017-11-16T18:00:00Z' GROUP BY * service=query
[E] 2017-11-17T15:40:03Z SELECT f64 FROM PROM.raw._ WHERE job = 'dev' AND u_metric_name !~ 'eventslast.*' AND u_metric_type = 'count' AND __name__ = 'events_metrics_seconds_count' AND time >= '2017-11-16T15:35:02Z' AND time <= '2017-11-16T18:00:00Z' GROUP BY * [panic:interface conversion: influxql.Expr is *influxql.StringLiteral, not *influxql.RegexLiteral] goroutine 28163241 [running]:
runtime/debug.Stack(0xc4936aeb60, 0xc43edead00, 0xf7)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/query.(*QueryExecutor).recover(0xc4201ea270, 0xc4936aeb60, 0xc4f593a900)
        /go/src/github.com/influxdata/influxdb/query/query_executor.go:443 +0xaf
panic(0xbca620, 0xc4c692a980)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/influxdata/influxql.(*SelectStatement).RewriteRegexConditions.func1(0x10d15c0, 0xc50f33e6f0, 0xcdff20, 0x10d1880)
        /go/src/github.com/influxdata/influxql/ast.go:1359 +0x1cb
github.com/influxdata/influxql.RewriteExpr(0x10d15c0, 0xc50f33e6f0, 0xcdff20, 0xc50f33e6c0, 0xc4e745e4d0)
        /go/src/github.com/influxdata/influxql/ast.go:3874 +0x189
github.com/influxdata/influxql.RewriteExpr(0x10d15c0, 0xc50f33e900, 0xcdff20, 0x10d15c0, 0xc50f33e6c0)
        /go/src/github.com/influxdata/influxql/ast.go:3852 +0x289
github.com/influxdata/influxql.RewriteExpr(0x10d15c0, 0xc50f33e930, 0xcdff20, 0xc4936aede0, 0xc4e745ea00)
        /go/src/github.com/influxdata/influxql/ast.go:3853 +0x2d5
github.com/influxdata/influxql.(*SelectStatement).RewriteRegexConditions(0xc51469f700)
        /go/src/github.com/influxdata/influxql/ast.go:1350 +0x44
github.com/influxdata/influxdb/query.Compile(0xc51469f600, 0x0, 0x0, 0x0, 0xd80, 0x90, 0xc47ae28b90, 0xc510932000)
        /go/src/github.com/influxdata/influxdb/query/compile.go:115 +0x163
github.com/influxdata/influxdb/query.Prepare(0xc51469f600, 0x10c2540, 0xc42022c040, 0x10d4d40, 0x1139eb0, 0x0, 0xc4f593a960, 0x0, 0x0, 0xc4ff437850, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:73 +0x4a
github.com/influxdata/influxdb/query.Select(0x10d31c0, 0xc420078060, 0xc51469f600, 0x10c2540, 0xc42022c040, 0x10d4d40, 0x1139eb0, 0x0, 0xc4f593a960, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:83 +0xcf
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc4201ec8c0, 0x10d31c0, 0xc420078060, 0xc51469f600, 0xc49ae5fcb0, 0x0, 0x0, 0xc4ff437980, 0xf, 0xc42007c0b8, ...)
        /go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:659 +0x106
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc4201ec8c0, 0x10d31c0, 0xc420078060, 0xc51469f600, 0xc49ae5fcb0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:555 +0x8f
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc4201ec8c0, 0x10d45c0, 0xc51469f600, 0x0, 0x22cd, 0xc507006bd0, 0xc4f593a900, 0x10d8460, 0xc42022e660, 0xc4f593a960, ...)
        /go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:62 +0x29a6
github.com/influxdata/influxdb/query.(*QueryExecutor).executeQuery(0xc4201ea270, 0xc4936aeb60, 0xc512f34129, 0x4, 0x10d4d40, 0x1139eb0, 0x2710, 0x1, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/query_executor.go:381 +0xb27
created by github.com/influxdata/influxdb/query.(*QueryExecutor).ExecuteQuery
        /go/src/github.com/influxdata/influxdb/query/query_executor.go:276 +0xc3
 service=query
[I] 2017-11-17T15:40:07Z executing continuous query grp_source_h5m (2017-11-17 15:35:00 +0000 UTC to 2017-11-17 15:40:00 +0000 UTC) service=continuous_querier
```

### PR DESCRIPTION
**Pull request by e-dard**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass

Fixes #9134.

InfluxDB expects regex condition values to be `influxql.RegexLiteral`s, which have literals beginning and ending in forward slashes.

Also adds further test coverage to `ReadRequestToInfluxQLQuery`.

Only thing that might be worth checking is whether the regex values originating from Prometheus format have already escaped forward slashes or not. For example, will the following condition arrive as:

`region  =~ foo/bar` which we would then convert into `region =~ /foo\/bar/` 

or, would the condition arrive as `region =~ foo\/bar`, which we would then _incorrectly_ convert to `region =~ /foo\\/bar/`?

No `CHANGELOG` update as this will probably be back-ported.

### CODE REVIEW

File: prometheus/converters.go [hunk 1]
```diff
@@ -93,6 +94,8 @@ func ReadRequestToInfluxQLQuery(req *remote.ReadRequest, db, rp string) (*influx
 // condFromMatcher converts a Prometheus LabelMatcher into an equivalent InfluxQL BinaryExpr
 func condFromMatcher(m *remote.LabelMatcher) (*influxql.BinaryExpr, error) {
 	var op influxql.Token
+	var RHS influxql.Expr
```
Comment (jsternberg) [inline prometheus/converters.go]: Can `RHS` be lowercase? Since it's a local variable, I think that's the standard for local variables.

File: prometheus/converters_test.go [hunk 2]
```diff
@@ -0,0 +1,98 @@
+package prometheus_test
+
+import (
+	"errors"
+	"reflect"
+	"testing"
+
+	"github.com/influxdata/influxql"
+
```
Comment (jsternberg) [inline prometheus/converters_test.go]: Can you remove the space between these?
