### PR TITLE
fix(storage): replace panic with error in influx_inspect verify

### LINKED ISSUE #9763: influx_inspect verify panics when data dir is missing
`influx_inspect verify` doesn't have a very nice UX with respect to the data dir. If it's missing, e.g., because you're on a system that uses a non-default data directory (not in `.influxdb`) then it panics.

It shouldn't panic, and the usage instructions should be better.

### PR DESCRIPTION
**Pull request by adamperlin**
Closes #9763 

Replaces panic with error handling in `influx_inspect verify` if the storage directory cannot be read from. 

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: cmd/influx_inspect/verify/tsm/verify.go [hunk 1]
```diff
@@ -66,9 +66,10 @@ func (cmd *Command) printUsage() {
 
 Usage: influx_inspect verify [flags]
 
-    -dir <path>
-            Root storage path
-            Defaults to "%[1]s/.influxdb".
+	-dir <path>
```
Comment (jacobmarble) [inline cmd/influx_inspect/verify/tsm/verify.go]: Replace tabs with spaces, as the surrounding text is
