### PR TITLE
fix: more variable dependancies

### LINKED ISSUE #17606: Variable Template Query Tag Values does not work for each bucket
Tools US 2.x Cluster
Dashboard Log File Studies V1.x - Shards

Variable shard defined as query:

import "influxdata/influxdb/v1"
v1.tagValues(bucket: v.bucket, tag: "shard_id")

The above sometimes works and sometimes does not based on the bucket.  For the following bucket, I actually created a cell to show that the value appears valid.

https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/0569ce471d8dd000?lower=2020-04-01T01%3A00%3A00.000Z&upper=2020-04-01T02%3A00%3A00.000Z

image

I have run through a few dozen buckets (log files from customers) and sometimes the drop down works for the variable, other times it fails.  The l-creditkarma-apr bucket does not enable the drop down but the tag value list should just have the 10 numbers as shown above.

image

Ping me if you cannot repro the problem or if the bucket shown above is gone.

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #17606

In this PR, i get dependent variables working again, move the concept of 'current context' deeper into the stack, isolate the "variable node graph" concepts from leaking outside of `hydrateVars`, remove some copy pasta, and update the tests to capture some of the changes made

### CODE REVIEW

File: ui/src/variables/actions/thunks.ts [hunk 1]
```diff
@@ -110,20 +131,24 @@ export const hydrateVariables = (skipCache?: boolean) => async (
...
 
-  vars
-    .filter(v => {
-      return vals[v.id] && v.arguments.type === 'query'
-    })
-    .forEach(v => {
-      v.arguments.values.results = vals[v.id].values
-      v.selected = vals[v.id].selected
-    })
+  const lookup = vals.reduce((prev, curr) => {
```
Comment (drdelambre) [inline ui/src/variables/actions/thunks.ts:134]: this change just reflects that hydratevars returns a list of variables now instead of the variablevalues[] thing

File: ui/src/variables/utils/hydrateVars.ts [hunk 2]
```diff
@@ -124,11 +119,13 @@ const findSubgraph = (
 ): VariableNode[] => {
   const subgraph: Set<VariableNode> = new Set()
 
+  // use an ID array to reduce the chance of reference errors
+  const varIDs = variables.map(v => v.id)
```
Comment (drdelambre) [inline ui/src/variables/utils/hydrateVars.ts:123]: this was the big fix
