### PR TITLE
Remove limit optimization when using an aggregate

### LINKED ISSUE #6661: Offset and limit combined with aggregation (group by time) gives incorrect results
### Bug report

__System info:__ InfluxDB 0.13.0, Amazon Linux AMI on EC2

__Steps to reproduce:__

1. Insert many data points with timestamps over multiple days
2. Query count of data points and group by time(1d)
3. Query count of data points and group by time(1d) and offset 1
4. Query count of data points and group by time(1d) and limit 1

__Expected behavior:__ 

- I expect the first entry in the result of step 3 to match the second entry in the result of step 2.
- I expect the result of step 4 to match the first entry in the result of step 2.

__Actual behavior:__ 

_Step 2:_
```
select count(field) from measure where userId = 'abc' and time >= '2016-05-01' group by time(1d)
```
time		|	count
------------- | -------------
1462060800000000000	|45884
1462147200000000000	|83958
1462233600000000000	|79540
... |...

_Step 3:_
```
select count(field) from measure where userId = 'abc' and time >= '2016-05-01' group by time(1d) offset 1
```
time		|	count
------------- | -------------
1462147200000000000	|2
1462233600000000000	|0
1462320000000000000	|0
... |...

_Step 4:_
```
select count(field) from measure where userId = 'abc' and time >= '2016-05-01' group by time(1d) limit 1
```
time		|	count
------------- | -------------
1462060800000000000	|2

As you can see, the timestamps are correctly returned according to the limit and offset, but for some reason the count is also affected.

__Additional info:__ 

We just migrated from InfluxDB 0.9.5 to 0.13.0.  All steps were followed and the migration was a success.  The queries were working on 0.9.5 this morning, but not on 0.13.0.  We don't know which version in between resulted in the changed behaviour.
Offset and limit gives the expected behaviour when querying the raw data without aggregation, but gives incorrect results when any aggregation function is applied.

### PR DESCRIPTION
**Pull request by jsternberg**
The limit optimization was put into the wrong place and caused only part
of the shard to be read when a limit was used. The optimization is
possible, but requires a bit of refactoring to the code here so the call
iterator is created per series before handed to the limit iterator.

Fixes #6661.

### CODE REVIEW

**Comment by e-dard** [comment]
LGTM :+1:

**Comment by jsternberg** [comment]
I'm going to leave this in a mergeable state, but I'm also going to try another version to keep the optimization and fix the underlying problem. If I can't do it in a timely manner before 1.0, this will be mergeable so at least the feature works correctly. We might just want to cherry-pick this to the 0.13.1 branch though if we want to fix the bug since this is a pretty bad regression from 0.12.

@jwilder thoughts?

File: tsdb/engine/tsm1/engine.go [hunk 1]
```diff
@@ -880,7 +880,9 @@ func (e *Engine) CreateIterator(opt influxql.IteratorOptions) (influxql.Iterator
 }
 
 // createVarRefIterator creates an iterator for a variable reference.
-func (e *Engine) createVarRefIterator(opt influxql.IteratorOptions) ([]influxql.Iterator, error) {
+// The limit argument determines if the limit optimization added for #6391 is used.
+// Limit optimization is disabled for aggregate queries temporarily. See #6661.
+func (e *Engine) createVarRefIterator(opt influxql.IteratorOptions, limit bool) ([]influxql.Iterator, error) {
```
Comment (benbjohnson) [inline tsdb/engine/tsm1/engine.go]: It seems like it'd be more useful in the future if this was named `aggregate` to signal that it's for an aggregate function.

Comment (jsternberg) [inline tsdb/engine/tsm1/engine.go]: Sure. This seems like a good change.

**Comment by benbjohnson** [comment]
:+1:
