### PR TITLE
fix(ui): wait for org to be available then fetch org settings just once

### LINKED ISSUE #18102: OrgSettings should wait until there is an org
Although the code for fetching org settings catches errors, ideally, we want to wait until an org with `id` is available before attempting to fetch org settings.

### PR DESCRIPTION
**Pull request by TCL735**
Closes #18102 

For Cloud only.

Wait for an org to be loaded before attempting to fetch org settings.

### CODE REVIEW

File: ui/src/cloud/components/OrgSettings.tsx [hunk 1]
```diff
@@ -1,34 +1,56 @@
...
+const OrgSettings: FunctionComponent<Props> = ({
+  org,
+  getOrgSettings,
+  children,
+}) => {
+  const [hasFetchedOrgSettings, setHasFetchedOrgSettings] = useState<boolean>(
+    false
+  )
+  useEffect(() => {
+    if (CLOUD && org && !hasFetchedOrgSettings) {
```
Comment (drdelambre) [inline ui/src/cloud/components/OrgSettings.tsx:36]: just flying through this, but shouldn't we be reading this off of the redux RemoteDataState?

Comment (TCL735) [reply ui/src/cloud/components/OrgSettings.tsx:36]: I tried that. RemoteDataState is `Done` before there is an org object. So that doesn't work for me.

Comment (TCL735) [reply ui/src/cloud/components/OrgSettings.tsx:36]: Specifically, `resources.orgs.status` is the RemoteDataState for all orgs. A specific org doesn't have a RemoteDataState. And because I need the `id` off of a specific org, I can't rely on `resources.orgs.status` as the signal.

Comment (drdelambre) [reply ui/src/cloud/components/OrgSettings.tsx:36]: lame
