### PR TITLE
fix(upgrade): check for existing 2.x CLI configs file

### LINKED ISSUE #19968: `influxd upgrade` raises confusing error when --influx-configs-path points to an existing file
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Write a 1.x config file to disk at /usr/local/etc/influxdb.conf (the Homebrew default)
2. Run `influxd upgrade` using the 2.x binary, pointing to the config file
```
./bin/darwin/influxd upgrade \
  --v1-dir /usr/local/var/influxdb \
  --influx-command-path $(which influx) \
  --influx-configs-path /usr/local/etc/influxdb.conf
```
3. Enter setup information when prompted.

__Expected behavior:__
`--influx-configs-path` is supposed to be an _output_ parameter. I got it confused with the `--config-file` arg. I'd expect a validation error of some kind.

__Actual behavior:__
I got this confusing error:
```
{"level":"error","ts":1605024356.9032362,"caller":"upgrade/setup.go:150","msg":"failed to save CLI config","path":"/usr/local/etc/influxdb.conf","error":"toml: type mismatch for config.Config: expected table but found []map[string]interface {}","stacktrace":"github.com/influxdata/influxdb/v2/cmd/influxd/upgrade.saveLocalConfig\n\t/Users/dan/influxdb/cmd/influxd/upgrade/setup.go:150\ngithub.com/influxdata/influxdb/v2/cmd/influxd/upgrade.runUpgradeE\n\t/Users/dan/influxdb/cmd/influxd/upgrade/upgrade.go:428\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/dan/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/dan/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/dan/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\nmain.main\n\t/Users/dan/influxdb/cmd/influxd/main.go:47\nruntime.main\n\t/Users/dan/.gvm/gos/go1.15/src/runtime/proc.go:204"}
```
The root of the error is coming from [this call](https://github.com/influxdata/influxdb/blob/master/cmd/influx/config/config.go#L186).

For some reason, I get a different error if the file is in a different location (i.e. ~/test/example.conf):
```
{"level":"error","ts":1605027180.906483,"caller":"upgrade/setup.go:150","msg":"failed to save CLI config","path":"/Users/danmoran/test/influxdb.conf","error":"mkdir /Users/danmoran: permission denied","stacktrace":"github.com/influxdata/influxdb/v2/cmd/influxd/upgrade.saveLocalConfig\n\t/Users/dan/influxdb/cmd/influxd/upgrade/setup.go:150\ngithub.com/influxdata/influxdb/v2/cmd/influxd/upgrade.runUpgradeE\n\t/Users/dan/influxdb/cmd/influxd/upgrade/upgrade.go:413\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/dan/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/dan/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/dan/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\nmain.main\n\t/Users/dan/influxdb/cmd/influxd/main.go:47\nruntime.main\n\t/Users/dan/.gvm/gos/go1.15/src/runtime/proc.go:204"}
```

I think both cases could be addressed by validating that the value of `--influx-configs-path` doesn't point to an existing file.

### PR DESCRIPTION
**Pull request by alespour**
Closes #19968

Adds check for existence of 2.x CLI configs file. If it exists, `upgrade` fails with error.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [X] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [X] Rebased/mergeable
- [X] Tests pass

### CODE REVIEW

**Review by danxmoran — COMMENTED** [review]
Can you add a line to the CHANGELOG?

**Comment by alespour** [comment]
Done.

File: cmd/influxd/upgrade/upgrade.go [hunk 1]
```diff
@@ -181,7 +181,7 @@ func NewCommand() *cobra.Command {
 			DestP:   &options.target.configsPath,
 			Flag:    "influx-configs-path",
 			Default: filepath.Join(v2dir, "configs"),
-			Desc:    "path for CLI configurations",
+			Desc:    "path to 2.x CLI configurations file",
```
Comment (danxmoran) [inline cmd/influxd/upgrade/upgrade.go:184]:
```suggestion
			Desc:    "path for 2.x CLI configurations file",
```
"to" makes it sounds like the file should already exist in my head

**Review by danxmoran — APPROVED** [review]
