### PR TITLE
Do not automatically reset the shard duration when using ALTER RETENTION POLICY

### LINKED ISSUE #7150: Alter Retention Policy resets shard group duration
### Bug report

__System info:__ InfluxDB 1.0.0-beta3

__Steps to reproduce:__

```
> create database mydb with shard duration 4w
> show retention policies on mydb
name    duration        shardGroupDuration      replicaN        default
autogen 0               672h0m0s                1               true

> alter retention policy autogen on mydb duration 4w
> show retention policies on mydb
name    duration        shardGroupDuration      replicaN        default
autogen 672h0m0s        24h0m0s                 1               true
```

__Expected behavior:__ The shard group duration should either not have reset the duration (beyond normalizing it for the new duration) or it should be documented that this will reset the shard group duration. It will also reset the shard group duration if you modify something unrelated to the duration.

__Actual behavior:__ The shard group duration is always reset unless you specify the current shard group duration.

### PR DESCRIPTION
**Pull request by jsternberg**
Fixes #7150.

### CODE REVIEW

File: services/meta/errors.go [hunk 1]
```diff
@@ -55,6 +55,10 @@ var (
 	// with an existing policy.
 	ErrRetentionPolicyConflict = errors.New("retention policy conflicts with an existing policy")
 
+	// ErrRetentionPolicyDurationBelowShardDuration is returned when updating a retention
+	// policy that has a duration lower than the current shard duration.
+	ErrRetentionPolicyDurationBelowShardDuration = errors.New("retention policy duration must be greater than the shard duration")
```
Comment (jsternberg) [inline services/meta/errors.go]: Hm, it is a really long name, but I think it matches with the naming convention of the other errors. I don't think `ErrShortDuration` says enough about the error since it can also applies to `ErrRetentionPolicyDurationTooLow`.

File: services/meta/client_test.go [hunk 2]
```diff
@@ -360,6 +360,77 @@ func TestMetaClient_SetDefaultRetentionPolicy(t *testing.T) {
...
+	duration = rpi.ShardGroupDuration / 2
+	if err := c.UpdateRetentionPolicy("db0", "rp0", &meta.RetentionPolicyUpdate{
+		Duration: &duration,
+	}); err == nil {
+		t.Fatal("expected error")
+	} else if err != meta.ErrRetentionPolicyDurationBelowShardDuration {
+		t.Fatalf("expected error '%s', got '%s'", meta.ErrRetentionPolicyDurationBelowShardDuration, err)
+	}
+
+	// Set the shard duration above the shard group duration. This should also return an error.
```
Comment (jsternberg) [inline services/meta/client_test.go]: Whoops. It seems I messed up changing the second half of this comment. Fixed.

File: services/meta/errors.go (hunk 1 above)
Comment (joelegasse) [inline services/meta/errors.go]: `ErrIncompatibleDurations`?

Comment (jsternberg) [inline services/meta/errors.go]: I can do that. But, I'm going to do `ErrRetentionPolicy` as the prefix since that's the naming standard. I know it's long, but I don't want to break that naming. So is `ErrRetentionPolicyIncompatibleDurations` fine?

Comment (joelegasse) [inline services/meta/errors.go]: I think that's excessive... `ErrReplicationFactorTooLow` isn't prefixed with `RetentionPolicy`...

I'll let other people weigh in on the excessively long names

Comment (e-dard) [inline services/meta/errors.go]: @jsternberg how about changing `ErrRetentionPolicyDurationTooLow` to `ErrRetentionPolicyDurationInvalid`, and then instead of `ErrRetentionPolicyDurationBelowShardDuration` have `ErrRetentionPolicyDurationTooLow` ?

Comment (jsternberg) [inline services/meta/errors.go]: I changed it to what @joelegasse suggested originally.

**Comment by jsternberg** [comment]
Updated. I also found that it didn't work when the duration was 0 (infinite time) and it didn't prevent creates so I added test cases for both of those and fixed it.
