### PR TITLE
fix: increase notification rule limit

### LINKED ISSUE #18684: only displaying 20 notification rules
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create 21 notification rules
2. ...
3. ...

__Expected behavior:__
be able to view / edit / delete all the notification rules

__Actual behavior:__
can view / edit only 20 notification rules, also filter only works o
NOTIFICATIONRULES2
n the displayed 20

### PR DESCRIPTION
**Pull request by 121watts**
Closes #18684 

### The Problem
User was only seeing 20 of their notification rules.

### The Temporary Solution
Increase the limit to max (100). This should unblock the user until...

### The Real Solution
Dedicate resources to pagination throughout the UI.  

Kapture 2020-08-13 at 10 22 05

### CODE REVIEW

File: ui/src/notifications/rules/actions/thunks.ts [hunk 1]
```diff
@@ -45,7 +46,9 @@ import {
   RuleEntities,
   ResourceType,
 } from 'src/types'
-import {incrementCloneName} from 'src/utils/naming'
+
+// Constants
+import {LIMIT} from 'src/resources/constants'
```
Comment (drdelambre) [inline ui/src/notifications/rules/actions/thunks.ts:51]: i know this is how we normally do this, but after watching russ bring down production, i dont think this limit is shared across all  api endpoints. some are 100, some are 200, which means we have no guarantee. Might be better to add a new const like RULE_LIMIT

Comment (russorat) [reply ui/src/notifications/rules/actions/thunks.ts:51]: yes i agree.

Comment (121watts) [reply ui/src/notifications/rules/actions/thunks.ts:51]: Took a look at resource maxes in the golang.  You're right.  Some resources are `500` some are `100`
