### PR TITLE
fix(cmd/influx): allow for creating users without initial passwords in `influx user create`

### LINKED ISSUE #20645: 'influx user create' cmd without -p flag misleading
When running the **`influx user create command -n user_name -o org`** the CLI shows this error message: **`Error: Passwords must be at least 8 characters long.`**

Which is misleading or it's a bug. Im not sure what was the intention here. 

The reason for reporting this is because user is still created even after not supplying the -p flag. 
It's also not mentioned in help or documentantion that -p flag is required, so I assume this error msg must have been overlooked and should not be displayed on `influx user create`

https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/user/create/ 
This documentation also mentions that -p flag and -o/--org flag are mutually exclusive, which is not the case. User can still be create with both flags.

Screenshot from 2021-01-29 09-51-01

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #20645 

I manually tested the case of setting a password without specifying an org, it's tough to unit-test because the org-flag helpers are coded to read a global config file as a fallback when no flags are passed in.

### CODE REVIEW

File: cmd/influx/user.go [hunk 1]
```diff
@@ -187,35 +204,46 @@ func (b *cmdUserBuilder) cmdCreateRunEFn(*cobra.Command, []string) error {
...
+	if b.password != "" {
+		setPassErr = dep.passSVC.SetPassword(ctx, user.ID, b.password)
+	} else {
+		log.Warn("No initial password set on user, use `influx user password`", zap.String("user", b.name))
 	}
 
-	pass := b.password
-	if orgID == 0 && pass == "" {
-		return b.printUser(userPrintOpts{user: user})
+	orgID, setOrgErr := b.org.getID(dep.orgSvc)
```
Comment (davidby-influx) [inline cmd/influx/user.go:214]: Do we want to bail earlier (i.e., here) if setPassErr != nil, and not try to set the Org?

File: cmd/influx/user.go [hunk 2]
```diff
@@ -187,35 +204,46 @@ func (b *cmdUserBuilder) cmdCreateRunEFn(*cobra.Command, []string) error {
...
+			UserID:       user.ID,
+			UserType:     influxdb.Member,
+			ResourceType: influxdb.OrgsResourceType,
+			ResourceID:   orgID,
+		})
 	}
 
-	if pass != "" && orgID == 0 {
-		return errors.New("an org id is required when providing a user password")
+	if setPassErr != nil {
```
Comment (davidby-influx) [inline cmd/influx/user.go:224]: Consider moving this above the attempt to set the organization.

**Review by davidby-influx — APPROVED** [review]
Wasn't sure if we should try to set the Org if we can't set the password, but maybe that's correct (saving the user another redo step when they set the password).

Minor point anyway.

File: cmd/influx/user.go (hunk 1 above)
Comment (danxmoran) [reply cmd/influx/user.go:214]: I'll restore the previous bail-out order (org first if ID is specified, then password). Better to not rock the boat too much on a patch release.

**Review by davidby-influx — APPROVED** [review]
Looks clean and clear.
