### PR TITLE
fix: Adjusting the width of dropdown

### LINKED ISSUE #18021: Dashboards: Variable values are truncated
the issue here is that the important part of this value is the very end, that is truncated.

- When the drop down is opened, we should expand the list horizontally to show the full value of the the variable.

image

### PR DESCRIPTION
**Pull request by zoesteinkamp**
This will make it so the width of the dropdown will adjust to the longest variable name

Closes #18021 

Describe your proposed changes here.
Ive done a simple math problem that determines the longest length in the values and makes that the width px
Screen Shot 2020-05-12 at 12 04 44 PM

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/variables/components/VariableDropdown.tsx [hunk 1]
```diff
@@ -43,6 +43,13 @@ class VariableDropdown extends PureComponent<Props> {
     const dropdownStatus =
       values.length === 0 ? ComponentStatus.Disabled : ComponentStatus.Default
 
+    const widthLength = Math.max(
+      140,
+      values.reduce(function(a, b) {
+        return a.length > b.length ? a : b
+      }, '').length * 8
```
Comment (drdelambre) [inline ui/src/variables/components/VariableDropdown.tsx:50]: how did you choose the number eight?

Comment (zoesteinkamp) [reply ui/src/variables/components/VariableDropdown.tsx:50]: Im not going to lie, it looked the best in the UI. I tried a few numbers, and 8 looked ideal for the px

Comment (drdelambre) [reply ui/src/variables/components/VariableDropdown.tsx:50]: is the intent to find out what the max width of the longest variable _could_ be?

**Comment by drdelambre** [comment]
@alexpaxton do you have any fancy tricks for measuring text up your sleeve? i have a fear that we're tightly coupling a font choice to system behavior here

File: ui/src/variables/components/VariableDropdown.tsx (hunk 1 above)
Comment (zoesteinkamp) [reply ui/src/variables/components/VariableDropdown.tsx:50]: So the intent is find the longest variable, then take its length and determine how much width in px would be needed to display it

**Comment by alexpaxton** [comment]
If we style the dropdown items to be in the monospace font then all characters will be the same width, and more predictable
