### PR TITLE
fix: prevent retention service creating orphaned shard files

### LINKED ISSUE #24529: Orphaned shard files can be left behind by retention service
Under certain circumstances, the retention can fail to delete shards from the store in a timely manner. When the shard groups are pruned based on age, this leaves orphaned shard files on the disk. The retention will then not attempt to remove the obsolete shard files because the meta store does not know about them. This can cause excessive disk space usage for some users.

### PR DESCRIPTION
**Pull request by gwossum**
Under certain circumstances, the retention service can fail to delete shards from the store in a timely manner. When the shard groups are pruned based on age, this leaves orphaned shard files on the disk. The retention service will then not attempt to remove the obsolete shard files because the meta store does not know about them. This can cause excessive disk space usage for some users.

This corrects that by requiring shards files be deleted before they can be removed from the meta store.

Closes #24529

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by davidby-influx — COMMENTED** [review]
This is complex enough I think I need a walk-through. Sorry that I am not fully grasping how this works.

**Comment by davidby-influx** [comment]
> This is complex enough I think I need a walk-through. Sorry that I am not fully grasping how this works.

What I am missing is how the scenario where the retention service leaves shards on disk but deletes them from the meta-data occurs, and how these changes fix that scenario.  You explained the scenario to me once, but I don't remember enough details to walk through it with the new code....

File: services/meta/data.go [hunk 1]
```diff
@@ -292,8 +292,11 @@ func (data *Data) DropShard(id uint64) {
 					data.Databases[dbidx].RetentionPolicies[rpidx].ShardGroups[sgidx].Shards = append(shards[:found], shards[found+1:]...)
 
 					if len(shards) == 1 {
-						// We just deleted the last shard in the shard group.
-						data.Databases[dbidx].RetentionPolicies[rpidx].ShardGroups[sgidx].DeletedAt = time.Now()
+						// We just deleted the last shard in the shard group, but make sure we don't overwrite the timestamp if it
+						// was already deleted.
+						if !data.Databases[dbidx].RetentionPolicies[rpidx].ShardGroups[sgidx].Deleted() {
```
Comment (davidby-influx) [inline services/meta/data.go:297]: Is this the key change?  Don't overwrite the `DeletedAt` time?

File: services/meta/data.go [hunk 2]
```diff
@@ -447,6 +450,26 @@ func (data *Data) DeleteShardGroup(database, policy string, id uint64) error {
...
 
+// PruneShardGroups removes any shards deleted before expiration and that have no remaining owners.
+// Returns true if data is modified.
+func (data *Data) PruneShardGroups(expiration time.Time) bool {
+	var changed bool
+	for i, d := range data.Databases {
+		for j, rp := range d.RetentionPolicies {
+			var remainingShardGroups []ShardGroupInfo
+			for _, sgi := range rp.ShardGroups {
+				if sgi.DeletedAt.IsZero() || !expiration.After(sgi.DeletedAt) || len(sgi.Shards) > 0 {
```
Comment (davidby-influx) [inline services/meta/data.go:461]: And here we check if any shards are left in a shard group, and retain it if so.

Comment (davidby-influx) [reply services/meta/data.go:461]: This keeps the shards we failed to remove from disk in the meta-data for a later attempt at deletion.

File: services/retention/service.go [hunk 3]
```diff
@@ -80,83 +103,124 @@ func (s *Service) run() {
...
-			if err := s.MetaClient.PruneShardGroups(); err != nil {
-				log.Info("Problem pruning shard groups", zap.Error(err))
+			log.Info("Deleted shard",
+				logger.Database(info.db),
+				logger.Shard(id),
+				logger.RetentionPolicy(info.rp))
+			if err := dropShardMetaRef(id, info); err != nil {
+				// removeShardMetaReference already logged the error.
 				retryNeeded = true
+				continue
```
Comment (davidby-influx) [inline services/retention/service.go:200]: Does this `continue` do anything?

File: services/retention/service.go [hunk 4]
```diff
@@ -80,83 +103,124 @@ func (s *Service) run() {
...
 			}
-
-			if err := s.MetaClient.PruneShardGroups(); err != nil {
-				log.Info("Problem pruning shard groups", zap.Error(err))
+			log.Info("Deleted shard",
+				logger.Database(info.db),
+				logger.Shard(id),
+				logger.RetentionPolicy(info.rp))
+			if err := dropShardMetaRef(id, info); err != nil {
+				// removeShardMetaReference already logged the error.
```
Comment (davidby-influx) [inline services/retention/service.go:198]: `dropShardMetaRef`

File: services/retention/service.go [hunk 5]
```diff
@@ -80,83 +103,124 @@ func (s *Service) run() {
...
-
-			logEnd()
+	// Check for expired phantom shards that exist in the metadata but not in the store.
+	for id, info := range deletedShardIDs {
+		log.Error("Expired phantom shard detected during retention check, removing from metadata",
+			logger.Database(info.db),
+			logger.Shard(id),
+			logger.RetentionPolicy(info.rp))
+		if err := dropShardMetaRef(id, info); err != nil {
+			// removeShardMetaReference already logged the error.
```
Comment (davidby-influx) [inline services/retention/service.go:212]: `dropShardMetaRef`

File: services/meta/data.go (hunk 1 above)
Comment (davidby-influx) [reply services/meta/data.go:297]: This is not the key change, but seems reasonable.

File: services/meta/data.go (hunk 2 above)
Comment (davidby-influx) [reply services/meta/data.go:461]: This is the actual fix for the problem. Do not prune shard groups which have shards that could not be deleted.

File: cmd/influxd/run/server.go [hunk 6]
```diff
@@ -290,6 +290,7 @@ func (s *Server) appendRetentionPolicyService(c retention.Config) {
 	srv := retention.NewService(c)
 	srv.MetaClient = s.MetaClient
 	srv.TSDBStore = s.TSDBStore
+	srv.DropShardMetaRef = retention.OSSDropShardMetaRef(s.MetaClient)
```
Comment (davidby-influx) [inline cmd/influxd/run/server.go:293]: Can this assignment just be `s.MetaClient.DropShard` and we eliminate the wrapper function?

File: services/retention/service.go [hunk 7]
```diff
@@ -37,12 +49,23 @@ func NewService(c Config) *Service {
 	}
 }
 
+// OSSDropShardMetaRef creates a closure appropriate for OSS to use as DropShardMetaRef.
```
Comment (davidby-influx) [inline services/retention/service.go:52]: Do we need this function, or could we simply use `mc.DropShard` as `DropShardMetaRef`?

Comment (davidby-influx) [reply services/retention/service.go:52]: See example here: https://play.golang.com/p/IQo6LwLkpIR

**Review by davidby-influx — CHANGES_REQUESTED** [review]
A few comment typos, and a suggestion to simplify a little code.

File: services/meta/data.go (hunk 1 above)
Comment (gwossum) [reply services/meta/data.go:297]: This is necessary to prevent a new bug from appearing in enterprise. Without this change, the enterprise code for nodes to drop references to the shard will cause the shard files to last double the RP duration.

File: services/meta/data.go (hunk 2 above)
Comment (gwossum) [reply services/meta/data.go:461]: Yes, this is the heart of the fix that prevents orphaned TSM files that InfluxDB will not attempt to delete.

File: services/retention/service.go (hunk 3 above)
Comment (gwossum) [reply services/retention/service.go:200]: No, it is for symmetry with the code that was already here. If someone comes and adds some code after this `if`, though, the `continue` is important.

I'd probably remove the use of `continue` completely if I was making more drastic changes.

File: services/retention/service.go (hunk 5 above)
Comment (gwossum) [reply services/retention/service.go:212]: `dropShardMetaRef` is passed in during service creation. It is parameterized because single-node OSS and clustered enterprise require different methods to drop the meta store reference.

The Enterprise PR uses `RemoveShardOwner` for `dropShardMetaRef`. This allows each node to drop it's reference to the shard when it deletes the TSM files from disk. Already existing code will implicitly drop the shard from the meta store once the shard owner count reaches 0. However, OSS does not make use of the shard owners field in the meta store. It's way of dropping the shard reference is to simply call `DropShard` after the TSM files have been removed from disk. Once all the shards in the shard group have been dropped the modified code in `PruneShardGroups` will then be able to remove the shard group.

File: cmd/influxd/run/server.go (hunk 6 above)
Comment (gwossum) [reply cmd/influxd/run/server.go:293]: Enterprise has to use a different method for `DropShardMetaRef` (`MetaClient.RemoveShardOwner` to be precise)

File: services/retention/service.go (hunk 7 above)
Comment (davidby-influx) [reply services/retention/service.go:57]: With the extra argument, this simplification becomes impossible, so disregard comment above.

File: services/retention/service.go [hunk 8]
```diff
@@ -80,83 +108,135 @@ func (s *Service) run() {
...
-							zap.Error(err))
-						retryNeeded = true
-						continue
-					}
-					log.Info("Deleted shard",
+	// Remove shards if we store them locally
+	for _, id := range s.TSDBStore.ShardIDs() {
+		if info, ok := deletedShardIDs[id]; ok {
+			delete(deletedShardIDs, id)
+			if err := s.TSDBStore.DeleteShard(id); err != nil {
```
Comment (davidby-influx) [inline services/retention/service.go:190]: One more change - what do you think about printing one more message before calling `DeleteShard`: 
- `attempting deletion of shard X, database Y, retention policy Z`

We have no visibility into why the retention service hangs for so long, and this might give us more clues; we can look at the size and cardinality of a shard that prints the message and then never prints a success or failure message.

**Review by davidby-influx — CHANGES_REQUESTED** [review]
One more change requested, an additional log message.

**Review by davidby-influx — APPROVED** [review]
Yay!
