### PR TITLE
Prevent full compactions from conflicting with other compactions

### LINKED ISSUE #6595: Influxd: Compaction-related panic on HEAD-2016/04/26
During a compaction run (with the compaction intervals in the config file set to `5s`), `influxd` panic'ed. cc @toddboom @jwilder 

```
$ ./influxd run --config=influxdb.conf

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

[run] 2016/05/10 16:13:04 InfluxDB starting, version 0.10.0, branch master, commit 662ead753b56dacee72f67d093d920729f73a3da
[run] 2016/05/10 16:13:04 Go version go1.6.2, GOMAXPROCS set to 8
[run] 2016/05/10 16:13:04 Using configuration at: influxdb.conf
[store]2016/05/10 16:13:04 Using data dir: /mnt/nvme/influxdb_data/db/data
[tsm1wal] 2016/05/10 16:13:04 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/05/10 16:13:04 tsm1 WAL writing to /mnt/nvme/influxdb_data/db/wal/_internal/monitor/1
[tsm1wal] 2016/05/10 16:13:04 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/05/10 16:13:04 tsm1 WAL writing to /mnt/nvme/influxdb_data/db/wal/benchmark_db/default/2
[cacheloader] 2016/05/10 16:13:04 reading file /mnt/nvme/influxdb_data/db/wal/_internal/monitor/1/_00001.wal, size 55128
[filestore] 2016/05/10 16:13:04 /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000073-000000001.tsm (#4) opened in 5.758746ms
[filestore] 2016/05/10 16:13:04 /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000072-000000003.tsm (#3) opened in 5.034206ms
[filestore] 2016/05/10 16:13:04 /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000068-000000003.tsm (#2) opened in 5.738256ms
[filestore] 2016/05/10 16:13:04 /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000064-000000004.tsm (#1) opened in 5.708621ms
[filestore] 2016/05/10 16:13:04 /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000048-000000005.tsm (#0) opened in 7.144912ms
[cacheloader] 2016/05/10 16:13:04 reading file /mnt/nvme/influxdb_data/db/wal/benchmark_db/default/2/_00343.wal, size 10871632
[cacheloader] 2016/05/10 16:13:04 reading file /mnt/nvme/influxdb_data/db/wal/_internal/monitor/1/_00002.wal, size 0
[tsm1] 2016/05/10 16:13:04 /mnt/nvme/influxdb_data/db/data/_internal/monitor/1 database index loaded in 2.680021ms
[store]2016/05/10 16:13:04 /mnt/nvme/influxdb_data/db/data/_internal/monitor/1 opened in 20.046772ms
[cacheloader] 2016/05/10 16:13:04 reading file /mnt/nvme/influxdb_data/db/wal/benchmark_db/default/2/_00344.wal, size 722946
[cacheloader] 2016/05/10 16:13:04 reading file /mnt/nvme/influxdb_data/db/wal/benchmark_db/default/2/_00345.wal, size 0
[tsm1] 2016/05/10 16:13:05 /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2 database index loaded in 527.878343ms
[store]2016/05/10 16:13:05 /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2 opened in 959.814821ms
[subscriber] 2016/05/10 16:13:05 opened service
[monitor] 2016/05/10 16:13:05 Starting monitor system
[monitor] 2016/05/10 16:13:05 'build' registered for diagnostics monitoring
[monitor] 2016/05/10 16:13:05 'runtime' registered for diagnostics monitoring
[monitor] 2016/05/10 16:13:05 'network' registered for diagnostics monitoring
[monitor] 2016/05/10 16:13:05 'system' registered for diagnostics monitoring
[cluster] 2016/05/10 16:13:05 Starting cluster service
[shard-precreation] 2016/05/10 16:13:05 Starting precreation service with check interval of 10m0s, advance period of 30m0s
[snapshot] 2016/05/10 16:13:05 Starting snapshot service
[copier] 2016/05/10 16:13:05 Starting copier service
[admin] 2016/05/10 16:13:05 Starting admin service
[monitor] 2016/05/10 16:13:05 Storing statistics in database '_internal' retention policy 'monitor', at interval 10s
[admin] 2016/05/10 16:13:05 Listening on HTTP: [::]:8083
[continuous_querier] 2016/05/10 16:13:05 Starting continuous query service
[httpd]2016/05/10 16:13:05 Starting HTTP service
[httpd]2016/05/10 16:13:05 Authentication enabled: false
[httpd]2016/05/10 16:13:05 Listening on HTTP: [::]:8086
[retention] 2016/05/10 16:13:05 Starting retention policy enforcement service with check interval of 30m0s
[run] 2016/05/10 16:13:05 Listening for signals
2016/05/10 16:13:05 Sending anonymous usage statistics to m.influxdb.com
[tsm1] 2016/05/10 16:13:09 beginning full compaction of group 0, 5 TSM files
[tsm1] 2016/05/10 16:13:09 compacting full group (0) /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000048-000000005.tsm (#0)
[tsm1] 2016/05/10 16:13:09 compacting full group (0) /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000064-000000004.tsm (#1)
[tsm1] 2016/05/10 16:13:09 compacting full group (0) /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000068-000000003.tsm (#2)
[tsm1] 2016/05/10 16:13:09 compacting full group (0) /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000072-000000003.tsm (#3)
[tsm1] 2016/05/10 16:13:09 compacting full group (0) /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000073-000000001.tsm (#4)
[tsm1] 2016/05/10 16:13:10 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/05/10 16:13:10 compacting level 1 group (0) /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000073-000000001.tsm (#0)
[tsm1] 2016/05/10 16:13:10 compacting level 1 group (0) /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000075-000000001.tsm (#1)
[tsm1] 2016/05/10 16:13:11 compacted level 1 group (0) into /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000075-000000002.tsm.tmp (#0)
[tsm1] 2016/05/10 16:13:11 compacted level 1 group 0 of 2 files into 1 files in 61.043111ms
[tsm1] 2016/05/10 16:13:21 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/05/10 16:13:21 compacting level 1 group (0) /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000001-000000001.tsm (#0)
[tsm1] 2016/05/10 16:13:21 compacting level 1 group (0) /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000002-000000001.tsm (#1)
[tsm1] 2016/05/10 16:13:21 beginning full compaction of group 0, 2 TSM files
[tsm1] 2016/05/10 16:13:21 compacting full group (0) /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000001-000000001.tsm (#0)
[tsm1] 2016/05/10 16:13:21 compacting full group (0) /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000002-000000001.tsm (#1)
[tsm1] 2016/05/10 16:13:21 compacted level 1 group (0) into /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000002-000000002.tsm.tmp (#0)
[tsm1] 2016/05/10 16:13:21 compacted level 1 group 0 of 2 files into 1 files in 2.402858ms
[tsm1] 2016/05/10 16:13:21 error replacing new TSM files: rename /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000002-000000002.tsm.tmp /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000002-000000002.tsm: no such file or directory
[tsm1] 2016/05/10 16:13:32 compacted full group (0) into /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000073-000000002.tsm.tmp (#0)
[tsm1] 2016/05/10 16:13:32 compacted full 5 files into 1 files in 22.734636333s
[tsm1] 2016/05/10 16:13:32 beginning level 2 compaction of group 0, 2 TSM files
[tsm1] 2016/05/10 16:13:32 compacting level 2 group (0) /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000073-000000002.tsm (#0)
[tsm1] 2016/05/10 16:13:32 compacting level 2 group (0) /mnt/nvme/influxdb_data/db/data/benchmark_db/default/2/000000075-000000002.tsm (#1)
[tsm1] 2016/05/10 16:13:41 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/05/10 16:13:41 compacting level 1 group (0) /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000003-000000001.tsm (#0)
[tsm1] 2016/05/10 16:13:41 compacting level 1 group (0) /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000004-000000001.tsm (#1)
[tsm1] 2016/05/10 16:13:41 compacted level 1 group (0) into /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000004-000000002.tsm.tmp (#0)
[tsm1] 2016/05/10 16:13:41 compacted level 1 group 0 of 2 files into 1 files in 5.079504ms
[tsm1] 2016/05/10 16:13:42 beginning level 2 compaction of group 0, 2 TSM files
[tsm1] 2016/05/10 16:13:42 compacting level 2 group (0) /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000002-000000002.tsm (#0)
[tsm1] 2016/05/10 16:13:42 compacting level 2 group (0) /mnt/nvme/influxdb_data/db/data/_internal/monitor/1/000000004-000000002.tsm (#1)
panic: runtime error: slice bounds out of range

goroutine 98 [running]:
panic(0xb4a800, 0xc82000e090)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*indirectIndex).UnmarshalBinary(0xc823764080, 0x7fb7df834a15, 0x2b90, 0x2b98, 0x0, 0x0)
        /Users/todd/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:671 +0x515
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*mmapAccessor).init(0xc824c3c140, 0x0, 0x0, 0x0, 0x0)
        /Users/todd/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:981 +0x569
github.com/influxdata/influxdb/tsdb/engine/tsm1.NewTSMReaderWithOptions(0x0, 0x0, 0xc820960010, 0x0, 0x0, 0x0)
        /Users/todd/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:157 +0x2df
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).compact(0xc8201cc090, 0xc820080701, 0xc824b40220, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/todd/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:459 +0x306
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).CompactFast(0xc8201cc090, 0xc824b40220, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/todd/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:486 +0x71
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel.func1(0xc820074400, 0xc82011b600, 0x2, 0x1, 0x0, 0xc824b40220, 0x2, 0x2)
        /Users/todd/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:577 +0x5fd
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel
        /Users/todd/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:603 +0x265

```

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

Normally, compactions do not conflict on the files they are compacting.
If the full cold threshold is set very low, it can cause conflicts where
two compactions compact the same files.  The full compaction was the
only place this could happen as it's planning is greedy and normally does
not run until the shard is cold for a long period of time.

To make this safer for concurrent execution, the compactor tracks which
files are currently being compacted and prevents any new compactions from
starting if the file set overlaps.

Fixes #6595

### CODE REVIEW

File: tsdb/engine/tsm1/compact.go [hunk 1]
```diff
@@ -762,6 +759,36 @@ func (c *Compactor) write(path string, iter KeyIterator) (err error) {
...
 }
 
+func (c *Compactor) add(files []string) bool {
+	c.mu.Lock()
+	defer c.mu.Unlock()
+
+	var inuse bool
+	for _, f := range files {
+		if _, ok := c.files[f]; ok {
+			inuse = true
```
Comment (corylanou) [inline tsdb/engine/tsm1/compact.go]: Could you just return false from here instead of breaking and then checking and returning?

Comment (corylanou) [inline tsdb/engine/tsm1/compact.go]: You also wouldn't need the `inuse` variable either.

**Comment by corylanou** [comment]
Looks good.  Minor nit.  Also, could there be tests added to verify this functionality?  👍

File: tsdb/engine/tsm1/compact.go (hunk 1 above)
Comment (toddboom) [inline tsdb/engine/tsm1/compact.go]: I was going to say the same, but I wasn't sure if this was more idiomatic.

Comment (jwilder) [inline tsdb/engine/tsm1/compact.go]: Yeah.  I'll rework.  I had a different approach initially and this is leftover from that.
