### PR TITLE
fix #8677: check for snapshot size == 0

### LINKED ISSUE #8677: [BUG] Backup stopped working after upgrade to 1.3.2
After yesterday's upgrade to version 1.3.2 (from 1.3.1 via Debian repo), backup fails with this error message:

`influxd backup -database telegraf /tmp/influxbackup`

```
2017/08/09 10:05:21 backing up db=telegraf since 0001-01-01 00:00:00 +0000 UTC
2017/08/09 10:05:21 backing up metastore to /tmp/influxbackup/meta.01
2017/08/09 10:05:21 backing up db=telegraf rp=autogen shard=169 to /tmp/influxbackup/telegraf.autogen.00169.00 since 0001-01-01 00:00:00 +0000 UTC
2017/08/09 10:05:21 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (0)...
2017/08/09 10:05:22 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (1)...
2017/08/09 10:05:23 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (2)...
2017/08/09 10:05:24 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (3)...
2017/08/09 10:05:25 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (4)...
2017/08/09 10:05:26 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (5)...
2017/08/09 10:05:27 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (6)...
2017/08/09 10:05:28 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (7)...
2017/08/09 10:05:29 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (8)...
2017/08/09 10:05:30 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (9)...
2017/08/09 10:05:31 backup failed: copy backup to file: err=<nil>, n=0
backup: copy backup to file: err=<nil>, n=0
```
Version: 1.3.2
OS: Debian jessie on x86_64

### PR DESCRIPTION
**Pull request by dgnorton**
- [x] Rebased/mergable
- [ ] Tests pass
- [x] CHANGELOG.md updated

### CODE REVIEW

File: tsdb/engine/tsm1/engine.go [hunk 1]
```diff
@@ -1117,6 +1117,10 @@ func (e *Engine) WriteSnapshot() error {
 		return err
 	}
 
+	if snapshot.Size() == 0 {
+		return nil
```
Comment (jwilder) [inline tsdb/engine/tsm1/engine.go]: I think you will also need to run `e.Cache.ClearSnapshot(true)` in this case.  That is currently done in `e.writeSnapshotAndCommit`.

Comment (dgnorton) [inline tsdb/engine/tsm1/engine.go]: fixed
