### PR TITLE
fix: eliminate race condition on Monitor.globalTags

### LINKED ISSUE #23466: Race condition on Monitor.globalTags
Race condition detected in test on `Monitor.globalTags` for 1.x branch:

```
==================
WARNING: DATA RACE
Write at 0x00c00341def0 by goroutine 348:
  runtime.mapassign_faststr()
      /go/src/runtime/map_faststr.go:203 +0x0
  github.com/influxdata/influxdb/monitor.(*Monitor).SetGlobalTag()
      /go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20220607180904-c44ec5974d81/monitor/service.go:189 +0xd1
  github.com/influxdata/plutonium/cmd/influxd/run.(*Server).init()
      /root/project/cmd/influxd/run/server.go:871 +0xbc
  github.com/influxdata/plutonium/cmd/influxd/run.(*Server).appendClusterService.func1()
      /root/project/cmd/influxd/run/server.go:311 +0x34
  github.com/influxdata/plutonium/cluster.(*Service).processJoinClusterRequest()
      /root/project/cluster/service.go:1178 +0x338
  github.com/influxdata/plutonium/cluster.(*Service).handleConn()
      /root/project/cluster/service.go:489 +0xd90
  github.com/influxdata/plutonium/cluster.(*Service).handleMuxConn.func3()
      /root/project/cluster/service.go:312 +0x9e

Previous read at 0x00c00341def0 by goroutine 179:
  runtime.mapiterinit()
      /go/src/runtime/map.go:815 +0x0
  github.com/influxdata/influxdb/monitor.(*Monitor).Statistics()
      /go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20220607180904-c44ec5974d81/monitor/service.go:320 +0x1ae
  github.com/influxdata/influxdb/monitor.(*Monitor).storeStatistics()
      /go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20220607180904-c44ec5974d81/monitor/service.go:443 +0x72e
  github.com/influxdata/influxdb/monitor.(*Monitor).Open.func1()
      /go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20220607180904-c44ec5974d81/monitor/service.go:126 +0x39

Goroutine 348 (running) created at:
  github.com/influxdata/plutonium/cluster.(*Service).handleMuxConn()
      /root/project/cluster/service.go:310 +0x2e9
  github.com/influxdata/plutonium/cluster.(*Service).serveMux.func1()
      /root/project/cluster/service.go:264 +0x9e

Goroutine 179 (running) created at:
  github.com/influxdata/influxdb/monitor.(*Monitor).Open()
      /go/pkg/mod/github.com/influxdata/influxdb@v1.5.1-0.20220607180904-c44ec5974d81/monitor/service.go:126 +0x43d
  github.com/influxdata/plutonium/cmd/influxd/run.(*Server).Open()
      /root/project/cmd/influxd/run/server.go:683 +0x92a5
  github.com/influxdata/plutonium/cmd/influxd/run.(*Command).Run()
      /root/project/cmd/influxd/run/command.go:184 +0x173c
  github.com/influxdata/plutonium/cmd/testhelper.(*TestDataRunCommand).MustRun.func1()
      /root/project/cmd/testhelper/integration.go:488 +0xde
==================
```

### PR DESCRIPTION
**Pull request by gwossum**
Closes #23466

### CODE REVIEW

**Review by davidby-influx — APPROVED** [review]
LGTM

File: monitor/service.go [hunk 1]
```diff
@@ -32,6 +32,39 @@ const (
...
+
+	t.tags[key] = fmt.Sprintf("%v", value)
+}
+
+// Tags safely returns a copy of the current tag mapping
+func (t *tags) Tags() map[string]string {
+	t.mu.RLock()
+	defer t.mu.RUnlock()
+
+	r := make(map[string]string)
```
Comment (jeffreyssmith2nd) [inline monitor/service.go:61]: Just a note of interest, 1.18 gave us a nice map copy function.

https://pkg.go.dev/golang.org/x/exp/maps#Copy
