### PR TITLE
fix(notification/rule): convert time, trigger, severity

### LINKED ISSUE #15032: Generated Flux code for Pagerduty notifications
TODO:
- [x]  get severity/action fix deployed and integrated
- [x] parse time format
- [x] what to pass for clientURL

```
 |> monitor.notify(data: notification, endpoint: pagerduty_endpoint(mapFn: (r) =>
        ({
            routingKey: pagerduty_secret,
            client: r._check_name,
            clientURL: "http://localhost:7777",
            class: r._check_name,
            group: r._check_name,
            severity: pagerduty.severityFromLevel(r._level),
                        eventAction: pagerduty.actionFromLevel(r._level),
            source: r._source_measurement,
            summary: r._message,
            timestamp: time(v: r._source_timestamp),
        })))
```

### PR DESCRIPTION
**Pull request by goller**
Semantically, we've done the following:

// name of the client sending the alert.
client: "influxdata"

// url of the client sending the alert.
client_url: the endpoint URL for now (needs to change to rule) tracked in https://github.com/influxdata/influxdb/issues/15042

// The class/type of the event, for example ping failure or cpu load
class: check's name

// Logical grouping of components of a service, for example app-stack
group: source measurement

Co-authored-by: Alirie Gray <alirie.gray@gmail.com>

Closes #15032

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [x] http/swagger.yml updated (if modified Go structs or API)
- [x] Documentation updated or issue created (provide link to issue/pr)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: notification/rule/pagerduty.go [hunk 1]
```diff
@@ -132,20 +132,25 @@ func (s *PagerDuty) generateFluxASTNotifyPipe(url string) ast.Statement {
 	// optional
 	// string
 	// Logical grouping of components of a service, for example app-stack
-	endpointProps = append(endpointProps, flux.Property("group", flux.Identifier("r._check_name")))
+	endpointProps = append(endpointProps, flux.Property("group", flux.Identifier("r._source_measurement")))
```
Comment (desa) [inline notification/rule/pagerduty.go]: *nit* this should probably be `flux.Member`, but it doesn't matter

File: notification/rule/pagerduty.go [hunk 2]
```diff
@@ -132,20 +132,25 @@ func (s *PagerDuty) generateFluxASTNotifyPipe(url string) ast.Statement {
...
+	// string trigger
+	// The type of event. Can be trigger, acknowledge or resolve. See Event Action.
+	endpointProps = append(endpointProps, flux.Property("eventAction", actionFromLevel()))
 
 	// source:
 	// required
 	// string
 	// The unique location of the affected system, preferably a hostname or FQDN
-	endpointProps = append(endpointProps, flux.Property("source", flux.Identifier("r._source_measurement")))
+	endpointProps = append(endpointProps, flux.Property("source", flux.Identifier("r._notification_rule_name")))
```
Comment (desa) [inline notification/rule/pagerduty.go]: nit this should probably be `flux.Member`, but it doesn't matter
