### PR TITLE
fix(alertHistory): stop linking to dead resources

### LINKED ISSUE #14930: Clicking a check that has been deleted should be handled gracefully
For now, let's just show a notification in the UI that the Check has been deleted.

image

### PR DESCRIPTION
**Pull request by 121watts**
Closes #14930

### What
From the AlertingIndex we stopped linking to resources that don't exist.

Kapture 2019-09-06 at 14 02 46

Co-Author: Michael Desa <mjdesa@gmail.com>

### CODE REVIEW

File: ui/src/alerting/reducers/checks.ts [hunk 1]
```diff
@@ -66,3 +66,7 @@ export default (
         return
     }
   })
+
+export const getCheckIDs = (state: ChecksState): {[x: string]: boolean} => {
```
Comment (chnn) [inline ui/src/alerting/reducers/checks.ts]: This would be more similar to most of the other selectors in the app if it lived in a `selectors` directory and accepted an `AppState` rather than `ChecksState` as an argument.

File: ui/src/alerting/utils/history.ts [hunk 2]
```diff
@@ -110,7 +110,7 @@ from(bucket: "${MONITORING_BUCKET}")
   - "notification_rule"
   - "_notification_rule"
 
-  The rewrite rules for the "noficationEndpoint" work similarly.
+  The rewrite rules for the "notificationEndpoint" work similarly.
```
Comment (chnn) [inline ui/src/alerting/utils/history.ts]: 😛

File: ui/src/alerting/components/AlertHistoryIndex.tsx [hunk 3]
```diff
@@ -44,39 +45,45 @@ const AlertHistoryIndex: FC<Props> = ({params: {orgID}}) => {
...
-            <div className="alert-history">
-              <EventTable {...props} fields={fields} />
-            </div>
-          </Page.Contents>
-        </Page>
-      )}
-    </EventViewer>
+    <GetResources resource={ResourceTypes.Checks}>
+      <GetResources resource={ResourceTypes.NotificationEndpoints}>
+        <GetResources resource={ResourceTypes.NotificationRules}>
```
Comment (chnn) [inline ui/src/alerting/components/AlertHistoryIndex.tsx]: Sooner or later I think we will really want to be able to pass multiple resource types to a single `GetResources` component. It will load faster (parallel rather than serial) and make the spinners look way less janky.

File: ui/src/alerting/reducers/checks.ts (hunk 1 above)
Comment (121watts) [reply ui/src/alerting/reducers/checks.ts]: Ah, yes they should take all of AppState

File: ui/src/alerting/components/AlertHistoryIndex.tsx (hunk 3 above)
Comment (121watts) [reply ui/src/alerting/components/AlertHistoryIndex.tsx]: Agreed.
