### PR TITLE
Alertchecksdefinequeryerror

### LINKED ISSUE #18196: Alert Checks - 1. Define Query step unusable after importing manifest
After importing a manifest, an Alert check can not be modified.  
The 1. Define Query step is not functioning properly.

The following has been verified using influxdb 2.0 beta 10, using various community-templates based manifests, on multiple instances and workstations.

__Steps to reproduce:__

1. Import a community template.  
`./influx pkg -f ~/community-templates/docker/docker.yml`
2. Using browser, click on any of the newly created "Checks" in the "Alerts" configurations, such as "Container Mem Usage Pct"
3. Click to "1. Define Query" 
config-check

__Expected behavior:__
The ability to modify the query.  Able to browse the schema.

__Actual behavior:__
Query not editable.  (image above)
The UI is complaining about missing field and aggregate functions.  
config-check-alert

### PR DESCRIPTION
**Pull request by zoesteinkamp**
Closes #18196

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/checks/actions/thunks.ts [hunk 1]
```diff
@@ -115,9 +115,15 @@ export const getCheckForTimeMachine = (checkID: string) => async (
...
+    const normCheck = normalize<Check, CheckEntities, string>(
+      resp.data,
+      checkSchema
+    )
+    const builderCheck = normCheck.entities.checks[normCheck.result]
+
+    const view = createView<CheckViewProperties>(builderCheck.type)
 
-    view.properties.queries = [check.query]
+    view.properties.queries = [builderCheck.query]
```
Comment (drdelambre) [inline ui/src/checks/actions/thunks.ts:126]: iirc, this is the crux of the issue. we normalized the check, but didn't use the normalized result.

File: ui/src/timeMachine/actions/queries.ts [hunk 2]
```diff
@@ -103,6 +105,58 @@ export const getOrgIDFromBuckets = (
   return get(bucketMatch, 'orgID', null)
 }
 
+//We only need a minimum of one bucket, function, and tag,
+export const getQueryFromFlux = (text: string) => {
```
Comment (drdelambre) [inline ui/src/timeMachine/actions/queries.ts:109]: NOTE: flux team is working on fleshing this ability out for us a bit in the near future
