### PR TITLE
fix: systemd unit should block on startup until http endpoint is ready

### LINKED ISSUE #6068: systemd service should "wait" until influxdb has finished starting up
Currently, using a configuration management tool, whenever the InfluxDB configuration file gets modified, InfluxDB gets restarted. The `systemctl restart` seems to complete immediately, but InfluxDB doesn't seem to be fully restarted - because some subsequent commands that check if an InfluxDB user exists and creates it if it doesn't, fails with a "Connection refused" message. If I run the configuration manager again right afterwards (<5 sec delay), it works just fine.

I know systemd has a concept of notifications to help solve this problem: https://www.freedesktop.org/software/systemd/man/systemd-notify.html

Alternatively, the script that launches the daemon shouldn't exit until the forked process is done starting up InfluxDB.

I'm not sure if this is an issue in other init systems, I've only tested in Debian 8.

### PR DESCRIPTION
**Pull request by codyshepherd**
Closes #6068 

Implements a wrapper around influxd when called by systemd to wait until the server is ready before exiting startup.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: scripts/influxd_wrapper.sh [hunk 1]
```diff
@@ -0,0 +1,15 @@
+#!/bin/bash -e
+/usr/bin/influxd
```
Comment (danxmoran) [inline scripts/influxd_wrapper.sh:2]: Should this be:
```suggestion
/usr/bin/influxd &
```
?

File: scripts/influxd_wrapper.sh [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+HOST=${INFLUXDB_HOSTNAME:-"localhost"}
+PORT=${INFLUXDB_HTTP_BIND_ADDRESS:-"8086"}
```
Comment (danxmoran) [inline scripts/influxd_wrapper.sh:5]: This won't pick up any changes in `config.toml` that modify the port.

You could use `influxd print-config --key-name http-bind-address` to print the value that the server will use given the current environment. It will be a pseudo-full address, i.e. `:8086` as shorthand for `localhost:8086`

File: scripts/influxd_wrapper.sh (hunk 1 above)
Comment (danxmoran) [reply scripts/influxd_wrapper.sh:2]: And if so, do we need to track the pid so we can somehow tell systemd about it? Or is it tracked automatically since it's a child of the wrapper script?

File: scripts/influxd_wrapper.sh (hunk 2 above)
Comment (codyshepherd) [reply scripts/influxd_wrapper.sh:5]: Ah ok, I had wondered if `influxd` would populate those variables. the docs seemed a bit unclear. i'll fix

File: scripts/influxd_wrapper.sh (hunk 1 above)
Comment (codyshepherd) [reply scripts/influxd_wrapper.sh:2]: Probably

File: scripts/influxd_wrapper.sh (hunk 2 above)
Comment (codyshepherd) [reply scripts/influxd_wrapper.sh:5]: So actually, in the context of this being run by systemd, I think any variables in the "environment file" will be present

Comment (danxmoran) [reply scripts/influxd_wrapper.sh:5]: I would still recommend using `influxd print-config` here. It performs the same config & env resolution/merging as the top-level `influxd` command, so you won't need to worry about as many mismatches between what the script expects vs. what `influxd` actually does.

File: scripts/notify.sh [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+BIND_ADDRESS=$(influxd print-config --key-name http-bind-address)
+HOST=${BIND_ADDRESS%%:*}
+HOST=${HOST:-"localhost"}
+PORT=${BIND_ADDRESS##*:}
+
+set +e
+result=$(curl -s -o /dev/null http://$HOST:$PORT/ready -w %{http_code})
+while [ "$result" != "200" ]; do
+  sleep 1
+  result=$(curl -s -o /dev/null http://$HOST:$PORT/ready -w %{http_code})
```
Comment (danxmoran) [inline scripts/notify.sh:12]: Do we want to have some sort of escape-hatch here? Like a max number of retries

Comment (codyshepherd) [reply scripts/notify.sh:12]: I was wondering about that, but I feel like hitting the sweet spot for that could be a moving target. Also, I believe that `Restart=on-failure` in the service file means that systemd will attempt to restart it anyway. Thoughts?

Comment (danxmoran) [reply scripts/notify.sh:12]: Let's keep it simple for now, we can change it later if people hit problems

**Review by danxmoran — APPROVED** [review]
LGTM as far as I know!

File: scripts/influxdb.service [hunk 4]
```diff
@@ -10,9 +10,10 @@ User=influxdb
 Group=influxdb
 LimitNOFILE=65536
 EnvironmentFile=-/etc/default/influxdb2
-ExecStart=/usr/bin/influxd
+ExecStart=/usr/lib/influxdb/scripts/influxd-systemd-start.sh
 KillMode=control-group
 Restart=on-failure
+Type=forking
```
Comment (danxmoran) [inline scripts/influxdb.service:16]: The [docs](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=) on this say it's recommended to also set [`PIDFile=`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile=) when using `forking`. Could we do that?

Comment (codyshepherd) [reply scripts/influxdb.service:16]: I tried this, passing it `/run/influxdb/influxd.pid`, but that file did not always show up, so I'm not super sure what's going on there. Do you have insight on how/when/by what component that file is created?

Comment (codyshepherd) [reply scripts/influxdb.service:16]: To clarify, we could add a section in the wrapper script that acts like `init.sh` which touches a pidfile and then passes that path to the systemd config, but I elected not to do that, as a) I couldn't see what difference it made functionally, and 2) I wanted to alter the startup behavior of influxd via systemd as little as possible from the original.

**Comment by codyshepherd** [comment]
I've confirmed that changes to the /etc/influxdb/config.toml are visible to influxd when started by systemd

File: scripts/influxdb.service (hunk 4 above)
Comment (danxmoran) [reply scripts/influxdb.service:16]: I'd expect something like this to work:
1. We put `PIDFile=/run/influxd.pid` (or something else under `/run/`)
2. We update `influxd-systemd-start.sh` to `echo $! > /run/influxd.pid` on the line after `/usr/bin/influxd &`

Comment (codyshepherd) [reply scripts/influxdb.service:16]: ok, can do

**Review by danxmoran — APPROVED** [review]
🎉

File: scripts/influxdb.service [hunk 5]
```diff
@@ -10,9 +10,11 @@ User=influxdb
...
+PIDFile=/var/lib/influxdb/influxd.pid
```
Comment (twm) [inline scripts/influxdb.service:17]: PID files should go in `/run/`, see [systemd.service(5)](https://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile=):

> `PIDFile=`
>
>    Takes a path referring to the PID file of the service. Usage of this option is recommended for services where Type= is set to forking. The path specified typically points to a file below /run/. If a relative path is specified it is hence prefixed with /run/. The service manager will read the PID of the main process of the service from this file after start-up of the service. The service manager will not write to the file configured here, although it will remove the file after the service has shut down if it still exists. The PID file does not need to be owned by a privileged user, but if it is owned by an unprivileged user additional safety restrictions are enforced: the file may not be a symlink to a file owned by a different user (neither directly nor indirectly), and the PID file must refer to a process already belonging to the service.
>
>    Note that PID files should be avoided in modern projects. Use Type=notify or Type=simple where possible, which does not require use of PID files to determine the main process of a service and avoids needless forking.

File: scripts/influxd-systemd-start.sh [hunk 6]
```diff
@@ -0,0 +1,17 @@
+#!/bin/bash -e
+
+/usr/bin/influxd &
```
Comment (twm) [inline scripts/influxd-systemd-start.sh:3]: Rather than doing this background-process dance with the PID file, you could use [`ExecStartPost=`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=) in the unit file to call this script separately. This would also have the advantage of allowing the system administrator to override it with a dropin file if the script causes a problem like in https://github.com/influxdata/influxdb/issues/21967
