### PR TITLE
fix: response writer simplification

### LINKED ISSUE #23845: Extra work in allocations for empty series returned from flux read response
When flux returns a read response, it does extra work to create data and series frames, and then throws away those frames when the series turns out not to have data.

This is a backport of a similar change in InfluxDB Cloud. InfluxDB OSS2 is unaffected.

### PR DESCRIPTION
**Pull request by lesam**
Also a performance improvement for when we don't need to write series keys that have no data.

- Closes #23845

### Required checklist
- [ ] Sample config files updated (both `/etc` folder and `NewDemoConfig` methods) (influxdb and plutonium)
- [ ] openapi swagger.yml updated (if modified API) - link openapi PR
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### Description
#23845

### Context
This simplifies the code and reduces allocation work when a large number of series are queried without any data.

### Affected areas (delete section if not relevant):
None - refactor and performance enhancement

### Note for reviewers:
Check the semantic commit type:
 - Feat: a feature with user-visible changes
 - Fix: a bug fix that we might tell a user “upgrade to get this fix for your issue”
 - Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except dependency version changes)
 - Build: build script changes, CI config changes, build tool updates
 - Refactor: non-user-visible refactoring
 - Check the PR title: we should be able to put this as a one-liner in the release notes

### CODE REVIEW

File: storage/reads/response_writer.go [hunk 1]
```diff
@@ -91,38 +88,42 @@ func (w *ResponseWriter) WriteResultSet(rs ResultSet) error {
...
-			w.startSeries(gc.Tags())
-			w.streamCursor(cur)
+			w.streamCursor(gc.Tags(), cur)
 			if w.err != nil {
 				gc.Close()
 				return w.err
 			}
 			stats.Add(gc.Stats())
 		}
 		gc.Close()
```
Comment (davidby-influx) [inline storage/reads/response_writer.go:115]: Check that `gc.Close()` error is reflected in `gc.Err()`

**Review by davidby-influx — APPROVED** [review]
One question on error handling

File: storage/reads/response_writer.go (hunk 1 above)
Comment (lesam) [reply storage/reads/response_writer.go:115]: From the interface definition:

```
	// Close releases any resources allocated by the GroupCursor.
	Close()

	// Err returns the first error encountered by the GroupCursor.
	Err() error
```

So `Close()` doesn't return an error at all.
