### PR TITLE
fix(task): inactive task runs when updated

### LINKED ISSUE #21874: [bug]: Saving an inactive task activates it without toggling it to active state
**OS info**: macOS Catalina 10.15.7, Darwin Kernel Version 19.6.0/RELEASE_X86_64
**InfluxDB version**: 2.0.7, installed with homebrew

**Steps to reproduce**:
1. Click on inactive task to edit it
2. Save the task
3. Return to task menu where task is toggled inactive
4. Check task runs for logs of new task execution

**Expected behaviour**:

- By saving the inactive task, no changes will take effect until the task is toggled active

**Actual behaviour**:

- By saving the inactive task, changes take effect while it is toggled as inactive & Task runs show it being treated as active
- In order to deactivate it, the task needs to be toggled active, then inactive

**Screen recording of the bug replication**:

https://user-images.githubusercontent.com/56439717/126171988-22ab0470-a0cc-4d88-a038-73f6843a149d.mov

### PR DESCRIPTION
**Pull request by raffs**
Closes #21874

When a tasks is being updated, ensure is scheduled only when the tasks status is active. Otherwise, an already-inactivated tasks might be scheduled if the task status is not being changed. 

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by wbaker85** [comment]
Great job tracking this down @raffs!

One other thing you'll need to do is add a test case to show that the bug is fixed. I think you could create a new case in the existing `Test_Coordinator_Scheduler_Methods` test that shows the expected scheduler calls for updating an inactive task without changing it's status.

File: task/backend/coordinator/coordinator.go [hunk 1]
```diff
@@ -135,7 +135,7 @@ func (c *Coordinator) TaskUpdated(ctx context.Context, from, to *taskmodel.Task)
 		if err := c.sch.Release(sid); err != nil && err != taskmodel.ErrTaskNotClaimed {
 			return err
 		}
-	} else {
+	} else if to.Status == string(taskmodel.TaskActive) {
```
Comment (wbaker85) [inline task/backend/coordinator/coordinator.go:138]: What would you think about adding a guard clause like:

```
	if to.Status == from.Status && to.Status == string(taskmodel.TaskInactive) {
		return nil
	}
```

At the top of this method & then simplifying the `if ... else if` logic?

Comment (raffs) [reply task/backend/coordinator/coordinator.go:138]: Yes, this seems like a nicer approach. I'll update that together with the test case.

Comment (raffs) [reply task/backend/coordinator/coordinator.go]: I have update the PR with your proposed changes. I'm resolving this case - please let me know in case the Reviewer is the one that should resolve the PR's case.

**Comment by raffs** [comment]
> Great job tracking this down @raffs!
> 
> One other thing you'll need to do is add a test case to show that the bug is fixed. I think you could create a new case in the existing `Test_Coordinator_Scheduler_Methods` test that shows the expected scheduler calls for updating an inactive task without changing it's status.

Thanks @wbaker85. 

I have added the test case as requested. Previously, I wasn't entire sure how to create the test case for a tasks that shouldn't be scheduled. But now, I can see that we `diff` the config on every test and having a empty schedule for updating an already inactive tasks seems to do trick for testing this case.

**Review by danxmoran — APPROVED** [review]
LGTM! The CI failure is unrelated to this PR, we added a new job that apparently doesn't work on PRs from forked repos. We'll patch it up and then a rebase/merge from `master` should get this passing.

**Comment by wbaker85** [comment]
@raffs - I merged https://github.com/influxdata/influxdb/pull/22232 just now, so if you can rebase onto the latest master it should get rid of the test failure and we can get this merged!

**Review by wbaker85 — APPROVED** [review]

**Comment by raffs** [comment]
>LGTM! The CI failure is unrelated to this PR, we added a new job that apparently doesn't work on PRs from forked repos. We'll patch it up and then a rebase/merge from master should get this passing.

Thank you for the info danxmoran 

>@raffs - I merged #22232 just now, so if you can rebase onto the latest master & resolve the conflict in the changelog we should be able to get this merged!

Great! thanks for the info.
