### PR TITLE
fix: filter variables to only those you are using

### LINKED ISSUE #17513: Variables on dashboards messed up in Safari
I'm able to reproduce on cloud2.
image

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #17513

i let all the variables in. @russorat only wants some of the variables in. the good ones. the kind you can change, and the page works more gooderer.

### CODE REVIEW

File: ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx [hunk 1]
```diff
@@ -163,7 +164,12 @@ const mstp = (state: AppState): StateProps => {
   } = state
 
   return {
-    variables,
+    variables: filterUnusedVars(
+      variables,
+      Object.values(state.resources.views.byID).filter(
+        v => v.dashboardID === dashboardID
```
Comment (hoorayimhelping) [inline ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx:170]:
```suggestion
        variable => variable.dashboardID === dashboardID
```
just to improve searchability

Comment (drdelambre) [reply ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx:170]: 👍
