### PR TITLE
Check for NaNs from Holt-Winters and do not return them

### LINKED ISSUE #6758: [0.14 nightly] holt-winters function returns odd error message
### Bug report

__System info:__
InfluxDB nightly
Ubuntu

__Steps to reproduce:__

1. Using data from the [trig](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/trig) Telegraf plugin.

2. Holt-Winters with the seasonal parameter `2` returns expected results:
```
curl -GET 'http://45.55.15.48:8086/query' --data-urlencode "q=SELECT holt_winters(first(sine), 20, 2) FROM telegraf.\"default\".trig WHERE time > '2016-05-27T22:32:00Z' and time <= '2016-05-27T22:44:10Z'  group by time(10s)"

{"results":[{"series":[{"name":"trig","columns":["time","holt_winters"],"values":[["2016-05-27T22:44:20Z",2.2990323761599405],["2016-05-27T22:44:30Z",4.140002852877649],["2016-05-27T22:44:40Z",4.65915976747487],["2016-05-27T22:44:50Z",7.884261143813246],["2016-05-27T22:45:00Z",8.857053779980657],["2016-05-27T22:45:10Z",14.261270897728767],["2016-05-27T22:45:20Z",15.984517580826934],["2016-05-27T22:45:30Z",24.73091072427377],["2016-05-27T22:45:40Z",27.6500778392273],["2016-05-27T22:45:50Z",41.42268190701654],["2016-05-27T22:46:00Z",46.19461775183526],["2016-05-27T22:46:10Z",67.41278651518552],["2016-05-27T22:46:20Z",74.99394447812716],["2016-05-27T22:46:30Z",107.11191505259298],["2016-05-27T22:46:40Z",118.8821256887086],["2016-05-27T22:46:50Z",166.80676380225592],["2016-05-27T22:47:00Z",184.74242067948907],["2016-05-27T22:47:10Z",255.414792446075],["2016-05-27T22:47:20Z",282.33062430439304],["2016-05-27T22:47:30Z",385.5345455556818]]}]}]}
```

3. Holt-Winters with the seasonal parameter `6` returns and unexpected error message:
```
curl -GET 'http://45.55.15.48:8086/query' --data-urlencode "q=SELECT holt_winters(first(sine), 20, 6) FROM telegraf.\"default\".trig WHERE time > '2016-05-27T22:32:00Z' and time <= '2016-05-27T22:44:10Z'  group by time(10s)"

json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: NaNRegans-MacBook-Pro-2:Documents regankuchan$
```

### PR DESCRIPTION
**Pull request by nathanielc**
The Holt-Winters forecast method can become unstable given either bad data or bad parameters and it can produce NaNs. This prevents the NaNs from being returned to the client and causing errors.

Also multiple initial guesses are tried instead of only a single guess.

Fixes #6758 

- [x] Rebased/mergable
- [x] Tests pass

### CODE REVIEW

**Comment by nathanielc** [comment]
@jsternberg Care to take a look?

File: influxql/functions.go [hunk 1]
```diff
@@ -464,7 +442,7 @@ func (r *FloatHoltWintersReducer) Emit() []FloatPoint {
 			}
 		}
 	} else {
-		l_0 += alpha * r.y[0]
+		l_0 += 0.5 * r.y[0]
```
Comment (jsternberg) [inline influxql/functions.go]: I think you should keep the constants for the defaults and use them here instead of a magic variable.

File: influxql/functions.go [hunk 2]
```diff
@@ -505,28 +479,53 @@ func (r *FloatHoltWintersReducer) Emit() []FloatPoint {
 	}
 
 	// Determine best fit for the various parameters
-	_, params := r.optim.Optimize(r.sse, parameters, r.epsilon, 1, r.constrain)
+	minSSE := math.Inf(1)
+	var bestParams []float64
+	lower := 0.3
+	step := 0.4
```
Comment (jsternberg) [inline influxql/functions.go]: These two variables should also be constants if you can.

**Comment by jsternberg** [comment]
Just some comments about magic numbers. Otherwise, it looks good.

**Comment by nathanielc** [comment]
@jsternberg Thanks, updated.

File: influxql/functions.go [hunk 3]
```diff
@@ -355,11 +347,19 @@ type FloatHoltWintersReducer struct {
 }
 
 const (
-	defaultAlpha   = 0.5
-	defaultBeta    = 0.5
-	defaultGamma   = 0.5
-	defaultPhi     = 0.5
+	// Arbitrary weight for initializing some intial guesses.
+	// This should be in the  range [0,1]
+	weight = 0.5
```
Comment (jsternberg) [inline influxql/functions.go]: Is there a way these variables can be prefixed for with something like `hw` to namespace the holt winters variables from other variables?

Comment (nathanielc) [inline influxql/functions.go]: I'd rather not start prefixing a bunch of vars. Should we move this code into its own package? Its just implementing an interface so its should be easy to move.

Comment (jsternberg) [inline influxql/functions.go]: There are enough constants here that I think that would be a good idea. The number of constants is starting to pollute the `influxql` namespace.

**Comment by jsternberg** [comment]
👍 on green.
