### PR TITLE
Fix panic when checking fieldsets

### LINKED ISSUE #9548: nil pointer dereference with certain SHOW TAG VALUES qeuries
Certain types of `SHOW TAG VALUES` queries, against certain types of schema, appear to be allowing either measurements without fields, or an empty set of indexes in an `IndexSet`. If a `WHERE` is present in the query, then `seriesByBinaryExprIterator` is called, and attempting to lookup the fields associated with a `nil` `MeasurementFields` results in a panic.

See comment here: https://github.com/influxdata/influxdb/issues/8786#issuecomment-371916894

```
SHOW TAG VALUES WITH KEY = room WHERE area =~ /^OG$/ [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 133184 [running]:
runtime/debug.Stack(0xc43da1fda0, 0xc423bb0000, 0x34)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/query.(*QueryExecutor).recover(0xc4201510b0, 0xc43da1fda0, 0xc42b42d860)
	/go/src/github.com/influxdata/influxdb/query/query_executor.go:451 +0xaf
panic(0xce4120, 0x1302970)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/influxdata/influxdb/tsdb.(*MeasurementFields).HasField(0x0, 0xc43da2774c, 0x4, 0xc4202f2910)
	/go/src/github.com/influxdata/influxdb/tsdb/shard.go:1408 +0x26
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByBinaryExprIterator(0xc4200a9500, 0x1, 0x99, 0xc4202f2910, 0xc421ac5ec8, 0x7, 0x8, 0xc42e1b44b0, 0x0, 0xd3ac00, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:1833 +0xdd2
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc4200a9500, 0x1, 0x99, 0xc4202f2910, 0xc421ac5ec8, 0x7, 0x8, 0x12cae00, 0xc42e1b44b0, 0x0, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:1786 +0x476
github.com/influxdata/influxdb/tsdb.IndexSet.tagValuesByKeyAndExpr(0xc4200a9500, 0x1, 0x99, 0xc4202f2910, 0x7fc5cdfc93a8, 0xc420184120, 0xc421ac5ec8, 0x7, 0x8, 0xc43150e310, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:2144 +0x1a0
github.com/influxdata/influxdb/tsdb.IndexSet.MeasurementTagKeyValuesByExpr(0xc4200a9500, 0x1, 0x99, 0xc4202f2910, 0x7fc5cdfc93a8, 0xc420184120, 0xc421ac5ec8, 0x7, 0x8, 0xc43150e310, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/index.go:2293 +0xca1
github.com/influxdata/influxdb/tsdb.(*Store).TagValues(0xc420001980, 0x7fc5cdfc93a8, 0xc420184120, 0xc420b6b800, 0x99, 0x100, 0x12cae00, 0xc42e1b4360, 0x100, 0x400, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/store.go:1517 +0x946
github.com/influxdata/influxdb/coordinator.LocalTSDBStore.TagValues(0xc420001980, 0x7fc5cdfc93a8, 0xc420184120, 0xc420b6b800, 0x99, 0x100, 0x12cae00, 0xc42e1b4360, 0x32f2d7fe, 0x109d537404, ...)
	<autogenerated>:1 +0x97
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeShowTagValues(0xc4201953b0, 0xc4300bca80, 0xc42153dc48, 0xdf7588, 0xf)
	/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:1066 +0x840
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc4201953b0, 0x12ce780, 0xc4300bca80, 0x0, 0x14e, 0xc42e8cdf80, 0xc42b42d860, 0xc42b42d8c0, 0xc43da23e3e, 0x6, ...)
	/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:194 +0x2937
github.com/influxdata/influxdb/query.(*QueryExecutor).executeQuery(0xc4201510b0, 0xc43da1fda0, 0xc43da23e3e, 0x6, 0x7fc5cdfc93a8, 0xc420184120, 0x2710, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/influxdata/influxdb/query/query_executor.go:389 +0xae8
created by github.com/influxdata/influxdb/query.(*QueryExecutor).ExecuteQuery
	/go/src/github.com/influxdata/influxdb/query/query_executor.go:285 +0xc3

```

Also seen in #9539.

### PR DESCRIPTION
**Pull request by e-dard**
This fixes #9548.

Within the `Store`, there is the concept of an `IndexSet`, which is an arbitrary collection of shard indexes. When dealing with iterators over an `IndexSet` a lot of the merging and filtering is handled automatically. The introduction of the `IndexSet` was a side-effect of the moving of index-query-planning up from the shard level to the database level.

One optimisation introduce during the `1.5.` cycle was to reduce the size of the `IndexSet` down to `1`, for `inmem` indexes. This was possible because each shard index in the `inmem` index is identical.

However, each `Shard` also stores a `MeasurementFieldSet`, which tracks the fields associated with measurements within that shard only. For the case of the `inmem` index, all`MeasurementFieldSet`s except for one belonging to the first shard in the set were being discarded. Unlike the index themselves, they're not duplicated.

The side-effect of this was that it was possible with some queries (`SHOW TAG VALUES WITH KEY = "x" WHERE "a" = 'b'` being the main example) to end up asking to see the fields that belonged to a measurement that was not present in the first shard's `MeasurementFieldSet`. This resulted in a panic.

As the `IndexSet` methods only needs to use one of the methods on the `MeasurementFieldSet`, this PR adds that method on the `IndexSet` itself, and the `IndexSet` will then call through on to each shard's field set.

### CODE REVIEW

File: tsdb/index.go [hunk 1]
```diff
@@ -1104,20 +1105,40 @@ func (is IndexSet) Database() string {
...
+// IndexSet have the provided field for the provided measurement.
+func (is IndexSet) HasField(measurement []byte, field string) bool {
 	if len(is.Indexes) == 0 {
-		return nil
+		return false
+	}
+
+	if len(is.fieldSets) == 0 {
+		// field sets may not have been initialised yet.
+		is.fieldSets = make([]*MeasurementFieldSet, 0, len(is.Indexes))
```
Comment (jwilder) [inline tsdb/index.go]: This looks racy.  Couldn't two concurrent queries end up assigning to `is.fieldSets` at the same time?

Comment (e-dard) [reply tsdb/index.go]: An `IndexSet` is not  (shouldn't be anyway) shared across goroutines. It should be one per query.

**Comment by jwilder** [comment]
Looks like a flaky test failed
```
--- FAIL: TestService_ModeANY (0.02s)
	service_test.go:254: expected points request
```

File: tsdb/index.go (hunk 1 above)
Comment (joelegasse) [reply tsdb/index.go]: Also, this is on a value receiver, so assignments to the field won't leak anyway... :-)

Comment (joelegasse) [reply tsdb/index.go]: It also means nothing is being cached.
