### PR TITLE
fix(kit/cli): fix loading of .yml config files

### LINKED ISSUE #20521: INFLUXD_CONFIG_PATH ignored if pointing to a file with extension ".yml"
__Steps to reproduce:__

1. echo 'log-level: warn' >> ${HOME}/config.yml
2. INFLUXD_CONFIG_PATH=${HOME}/config.yml influxd

__Expected behavior:__
Custom config is used, and log level is set to warn.

__Actual behavior:__
Custom config is ignored, log level stays at default of info.

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #20521

The actual fix is 1 character, but I took the chance to beef up our tests in this area.

### CODE REVIEW

File: kit/cli/viper.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ func NewCommand(v *viper.Viper, p *Program) *cobra.Command {
 
 	if configPath := v.GetString("CONFIG_PATH"); configPath != "" {
 		switch path.Ext(configPath) {
-		case ".json", ".toml", ".yaml", "yml":
+		case ".json", ".toml", ".yaml", ".yml":
```
Comment (davidby-influx) [inline kit/cli/viper.go:65]: Is there any chance of running on Windows where we would need case-insensitive comparison?

**Review by davidby-influx — APPROVED** [review]

File: kit/cli/viper.go (hunk 1 above)
Comment (danxmoran) [reply kit/cli/viper.go:65]: Case-insensitivity seems like a good idea either way, will update.
