### PR TITLE
fix(http): filter buckets by FindOptions

### LINKED ISSUE #10946: Open platform PR#2168
https://github.com/influxdata/platform/pull/2168

@zhulongcheng 

As we migrated the platform repository to the influxdb repo, would you mind reopening your PR against the `next` branch of this repo

### PR DESCRIPTION
**Pull request by zhulongcheng**
Closes #10946

_Briefly describe your proposed changes:_

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] http/swagger.yml updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: bolt/bucket.go [hunk 1]
```diff
@@ -284,11 +284,27 @@ func (c *Client) findBuckets(ctx context.Context, tx *bolt.Tx, filter platform.B
...
+
 	filterFn := filterBucketsFn(filter)
-	err := c.forEachBucket(ctx, tx, func(b *platform.Bucket) bool {
+	err := c.forEachBucket(ctx, tx, descending, func(b *platform.Bucket) bool {
 		if filterFn(b) {
-			bs = append(bs, b)
+			if count >= offset {
+				bs = append(bs, b)
+			}
+			count += 1
```
Comment (leodido) [inline bolt/bucket.go]: Replace with count++ pls :)

File: testing/bucket_service.go [hunk 2]
```diff
@@ -744,7 +838,18 @@ func FindBuckets(
 				filter.Name = &tt.args.name
 			}
 
-			buckets, _, err := s.FindBuckets(ctx, filter)
+			opt := platform.FindOptions{}
```
Comment (leodido) [inline testing/bucket_service.go]: If using the argument `findOptions` as suggested above we could get rid of this IFs.

File: testing/bucket_service.go [hunk 3]
```diff
@@ -744,7 +838,18 @@ func FindBuckets(
...
+				opt.Offset = tt.args.offset
+			}
+			if tt.args.limit > 0 {
+				opt.Limit = tt.args.limit
+			}
+			if tt.args.descending {
+				opt.Descending = tt.args.descending
+			}
+
+			buckets, _, err := s.FindBuckets(ctx, filter, opt)
```
Comment (leodido) [inline testing/bucket_service.go]: And use `tt.args.findOptions` here rather than `opt`.

File: testing/bucket_service.go [hunk 4]
```diff
@@ -512,6 +512,10 @@ func FindBuckets(
 		name           string
 		organization   string
 		organizationID platform.ID
+
```
Comment (leodido) [inline testing/bucket_service.go]: Just a comment.
Could you please use a `findOptions platform.FindOptions` field here?

**Comment by leodido** [comment]
Going to add my suggestions in another PR. Merging this.
