### PR TITLE
fix: improve error message when onboarding requests are missing data

### LINKED ISSUE #21566: `influxd upgrade` with `-f` and missing options prints unhelpful error message
See [this example](https://github.com/influxdata/influxdb/issues/21534#issuecomment-848503180). When running `influxd upgrade` with the `-f` option, users must provide:
* `--username`
* `--password`
* `--bucket`
* `--org`

If they don't, the onboarding request to the server will fail with the very unhelpful message:
```
Error: onboarding error: onboard failed, missing value
```

We should beef up validation for force-mode to print something more useful.

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #21566

### CODE REVIEW

File: testing/onboarding.go [hunk 1]
```diff
@@ -123,26 +123,7 @@ func OnboardInitialUser(
 				},
 			},
 			wants: wants{
-				errCode: errors.EEmptyValue,
-			},
-		},
-		{
-			name: "missing password should fail",
```
Comment (danxmoran) [inline testing/onboarding.go:130]: Other than the `name` here, this case was identical to the case above (missing bucket). The code doesn't actually enforce that a password is included in the request body, so I deleted the case instead of fixing it up.

**Review by lesam — APPROVED** [review]
