### PR TITLE
fix(py-api): hide internal helpers from PyPluginCallApi Python interface 

### LINKED ISSUE #26972: PyPluginCallApi exposes internal helper methods to Python
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. run the following plugin

```
def process_writes(influxdb3_local, table_batches, args=None):
    allowed = {"info", "warn", "error", "query", "write", "cache"}
    attrs = {name for name in dir(influxdb3_local) if not name.startswith("__")}
    extras = attrs - allowed
    missing = allowed - attrs
    if extras or missing:
        raise RuntimeError(f"unexpected attributes: extras={sorted(extras)}, missing={sorted(missing)}")
```

__Expected behaviour:__
PyPluginCallApi should only expose Python methods info, warn, error, query, write, and cache, so the regression test should pass.

__Actual behaviour:__
The test fails with RuntimeError: unexpected attributes: extras=['log_args_to_string', 'write_to_db'], missing=[], showing that internal helpers were exported to Python.

### PR DESCRIPTION
**Pull request by caterryan**
PyPluginCallApi exposed internal helper method `log_args_to_string` to plugin code. It shouldn't have been part of the plugin call api `PyPluginCallApi`. 

This PR removes the helper from the api and adds a test.

* fixes #26972

### CODE REVIEW

File: influxdb3_py_api/src/lib.rs [hunk 1]
```diff
@@ -21,3 +21,72 @@ pub enum ExecutePluginError {
...
+def process_writes(influxdb3_local, table_batches, args=None):
+    allowed = {"info", "warn", "error", "query", "write", "cache", "write_to_db"}
+    attrs = {name for name in dir(influxdb3_local) if not name.startswith("__")}
+    extras = attrs - allowed
+    missing = allowed - attrs
+    if extras or missing:
+        raise RuntimeError(f"unexpected attributes: extras={sorted(extras)}, missing={sorted(missing)}")
+"#;
+
+        let result = system_py::execute_python_with_batch(
```
Comment (philjb) [inline influxdb3_py_api/src/lib.rs]: if you switch to `execute_schedule_trigger`, you'll get the same effect but won't need to construct the empty write_batch.

File: influxdb3_py_api/src/lib.rs [hunk 2]
```diff
@@ -21,3 +21,72 @@ pub enum ExecutePluginError {
...
+
+        let time_provider: Arc<dyn TimeProvider> =
+            Arc::new(MockProvider::new(Time::from_timestamp_nanos(0)));
+        let cache_store = Arc::new(Mutex::new(CacheStore::new(
+            Arc::clone(&time_provider),
+            Duration::from_secs(60),
+        )));
+        let py_cache = PyCache::new_test_cache(cache_store, "method_visibility".to_string());
+
+        let query_executor: Arc<dyn QueryExecutor> = Arc::new(UnimplementedQueryExecutor);
```
Comment (philjb) [inline influxdb3_py_api/src/lib.rs]: i'd prolly just inline query_executor and py_cache into the call to execute_python_... a matter of taste perhaps, but in a test we can be more concise, especially with setup that is just needed to call the method under test. 

probably do the same for db_name (once write_batch is gone) and schema.

File: influxdb3_py_api/src/lib.rs [hunk 3]
```diff
@@ -21,3 +21,72 @@ pub enum ExecutePluginError {
...
+    use influxdb3_internal_api::query_executor::{QueryExecutor, UnimplementedQueryExecutor};
+    use influxdb3_wal::{TableChunks, WriteBatch};
+    use iox_time::{MockProvider, Time, TimeProvider};
+    use parking_lot::Mutex;
+    use pyo3::prepare_freethreaded_python;
+    use std::sync::Arc;
+    use std::time::Duration;
+
+    #[tokio::test]
+    async fn py_plugin_call_api_exposes_only_allowed_methods() {
```
Comment (philjb) [inline influxdb3_py_api/src/lib.rs]: the test method name should start with `test_`. We don't always follow this pattern but it makes way easier to recognize when a method is a unit test since in rust tests and prod code are in the same files. 

speaking of files. it's unusual to have put this test into lib.rs. It would fit better in system_py.rs. Would you move it there unless there is a reason you can't?

**Comment by philjb** [comment]
The test failure in ci is real:

```
────────────
     Summary [  39.412s] 789 tests run: 788 passed, 1 failed, 10 skipped
        FAIL [   0.025s] (436/789) influxdb3_py_api tests::py_plugin_call_api_exposes_only_allowed_methods
  stdout ───

    running 1 test
  stderr ───
    Could not find platform independent libraries <prefix>
    Could not find platform dependent libraries <exec_prefix>
    Fatal Python error: Failed to import encodings module
    Python runtime state: core initialized
    ModuleNotFoundError: No module named 'encodings'

    Current thread 0x00007f9874fff6c0 (most recent call first):
      <no Python frame>

    (test failed with exit code 1)

error: test run failed
```

**Review by philjb — CHANGES_REQUESTED** [review]
nice find about the exposed helper method; pr needs some changes

* see if you can move the test to system_py.rs
* need to fix the test failure ci found
* switch to `execute_schedule_trigger`
* prefix the test name with `test_`

**Comment by philjb** [comment]
Your PR description needs to be more accurate too. The only exposed helper is `log_args_to_string` but the description mentions two methods. 

The added test is not an end to end regression test; imo. Again a matter of taste, but i view the pr description as overly verbose (touch grandiose too) as AI generated text often is. At least for the next few months (🤣 😭 ), humans are reading the text still. It pays to be concise (or at least reduce AI verbosity) to save the human time. AI is actually good at reducing its own text, but you have to ask it. "Write my pr description in a concise and technical prose". 

How I would edit this: I'm being extra pedantic in your first pr. 

```
PyPluginCallApi exposed internal helper method `log_args_to_string` to plugin code. It shouldn't have been part of the plugin call api `PyPluginCallApi`. 

This PR removes the helper from the api and adds a test.
```

**Comment by philjb** [comment]
The commit messages should get the same treatment as the pr description. Again, a matter of taste, but I've found commit messages generated and committed by AI to be too verbose and to me doesn't wrap at 80 (or 100) chars so calling git log is poorly formatted and hard to read. 

`git commit --amend` will let you rewrite the last commit but to write several commits i usually do `git rebase -i  d9e44a234a9c8fdaa1d3ddecc64c13d5111ea402` and choose the "reword" option.

Screenshot 2025-11-13 at 9 59 05 AM

**Comment by caterryan** [comment]
Requested changes are complete.

To fix the CI failure, the test was moved to processing_engine because of a dependency on its virtualenv mod.

**Review by philjb — APPROVED** [review]
LGTM -- sorry for the delay and thanks for addressing the items in my feedback.
