### PR TITLE
Simplify cache snapshotting

### LINKED ISSUE #5686: tsm: snapshots leak and data may disappear on restart if a compaction fails due transient write errors
This issue is based on a code review, rather than something I have seen in the wild. If my analysis is incorrect, then feel free to close the issue.

It seems to me that if the periodic snapshotting and compaction fails (perhaps because of a temporary shortage of disk space on the database's file system) a snapshot will be retained in memory and never be released. If such transient disk space shortages were to occur regularly, "abandoned" snapshots could accumulate in memory, eventually resulting in an OOM condition.

A fix might be to handle this case by registering the snapshot associated with a failed compaction in the cache and then when Cache.ClearSnapshot runs after the next successful compaction, clearing these snapshots as well.

### PR DESCRIPTION
**Pull request by jwilder**
The Cache had support for taking multiple snapshots to support writing
multiple snapshots to TSM files concurrently.  This was in place in case snapshotting the cache happened to be a bottleneck.  In practice, this is never a bottleneck and we only
run one snappshoting goroutine continously per shard which has worked
well for all workloads.

The multiple snapshot support introduces some unhandled failure scenarios
where wal segments could be removed without writing them to TSM files.  If
a snapshot compaction fails to write due to transient disk errors, subsequent
snapshots will continue, but the failed one will not be retried.  When the
subsequent ones succeeded, all closed wal segments are removed causing data
loss.

This change simplifies the snapshotting capability to ensure that there is only
ever one snapshot.  If one fails, the next snapshot will update the existing
snapshot and retry all of old and new data.

Fixes #5686

### CODE REVIEW

**Comment by jonseymour** [comment]
G'day Jason,

I have rebased #5701 against your change and submitted two pull requests against this branch.

#5794 demonstrates the issue.
#5795 fixes the issue in the same way it was fixed in #5701.

If you accept the fix, you only need to merge #5795. Otherwise, you can take the test without the fix (#5794). 

#5795 also fixes a statistics accounting issue with #5789 regarding the accounting for current disk size.

**Comment by jonseymour** [comment]
I have some additional comments about this solution w.r.t to the alternative I proposed (#5689). I'll summarise the comments now, but prepare a more detailed explanation, with tests offline. The comments below assume #5795 (or an alternative fix to #5794) has been accepted. 

- #5789 lacks a locking solution equivalent to c1476773 of #5689, meaning that periodic compacts and aperiodic maintenance activity that also compacts (like a backup) could interact in unpredictable ways. I will prepare a test case that shows how this might happen and propose a fix (e.g. re-introducing a variant of c146673).

The following comments only apply to recovery scenarios where there is an existing snapshot.

- #5789 is now doing much more work during the preparation of a snapshot than #5689, particularly when a snapshot already exists. I suspect that this means that #5789 will perform less well than #5689 in write intensive performance tests, particularly in the presence of write failures.

- #5689 only has to deduplicate an entry in a given snapshot once. 

- #5789 must commit the entries from all previously failed snapshots once. If there is a repeated write error, all progress is lost and #5789 must start from the beginning. (deduplication + writing TSM files)

So my view is that the simplification in #5789 achieves most of the benefits of #5689 on the good path, however, in failure scenarios #5789 will perform less well than #5689 primarily because it will increase the duration of write locks (while the snapshot is being taken) and the repetition of de-duplication and writing work that would have otherwise succeeded.

I would have thought that #5689 addressed the issues in #5686 quite well without introducing any additional performance issues. However, I understand that you would like to place an emphasis on simplicity of the good path over performance of the bad path and that is, of course, your choice to make.

File: tsdb/engine/tsm1/cache.go [hunk 1]
```diff
@@ -289,13 +294,15 @@ func (c *Cache) merged(key string) Values {
...
 	var entries []*entry
 	sz := 0
-	for _, s := range c.snapshots {
-		e := s.store[key]
-		if e != nil {
-			entries = append(entries, e)
-			sz += len(e.values)
+
+	if c.snapshot != nil {
+		snapShotEntries := c.snapshot.store[key]
```
Comment (e-dard) [inline tsdb/engine/tsm1/cache.go]: nit: this can be `snapshotEntries`

File: tsdb/engine/tsm1/cache.go [hunk 2]
```diff
@@ -457,10 +464,10 @@ func (c *Cache) updateMemSize(b int64) {
 func (c *Cache) updateSnapshots() {
```
Comment (e-dard) [inline tsdb/engine/tsm1/cache.go]: Should this now be `updateSnapshot`?

**Comment by e-dard** [comment]
Just a couple of nits, otherwise as far as I can tell LGTM.

**Comment by jwilder** [comment]
@jonseymour This is not intended to solve the race you logged for #5794.  It only fixes #5686.  I still need to look at the race issue to understand it more fully.  

I ran performance tests on this change and found no regressions.  We'll be running more performance and stress tests before `0.11` is released.  If there is a performance issue introduced by this change, a new issues can be created.
