### PR TITLE
fix: replications remote write failure can deadlock remote writer

### LINKED ISSUE #23397: Replications not replicating after remote node failure
Multiple community issues have been raised about this: https://community.influxdata.com/t/influxdb-2-2-replication/24841

Reproduce:
1) Start two OSS nodes with access to another
2) Shut down remote note (one being replicated to) or disconnect them in another way for a few minutes
*queue should build up*
3) Start remote note or re-establish connection
4) Data written during queue build-up not replicated to remote node

### PR DESCRIPTION
**Pull request by DStrand1**
Closes #23397

Fixes an issue where we could get stuck on a `time.Timer#C` channel listen. If we had multiple remote write failures in a row, we would end up in a situation where the `retry.C` channel was just drained, then we call `retry.Stop()`, followed by `<-retry.C`, which would deadlock the goroutine responsible for sending remote writes.

Additionally, this PR adds several new test cases, and refactors the `remoteWriter` interface to no longer return `shouldRetry`, since it was unnecessary and unused.

- [X] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] Rebased/mergeable
- [X] Tests pass

### CODE REVIEW

File: cmd/influxd/launcher/replication_test.go [hunk 1]
```diff
@@ -298,6 +303,121 @@ csv.from(csv: csvData) |> to(bucket: %q)
...
+
+	l := launcher.RunAndSetupNewLauncherOrFail(ctx, t)
+	defer l.ShutdownOrFail(t, ctx)
+	client := l.APIClient(t)
+
+	localBucketName := l.Bucket.Name
+	remoteBucketName := "remote1"
+
+	random := rand.New(rand.NewSource(1000))
+	pointsIndex := 1
```
Comment (lesam) [inline cmd/influxd/launcher/replication_test.go:333]: Nitpick: I'd prefer if this started at zero and our points were `v0,v1,v2,v3`.

File: cmd/influxd/launcher/replication_test.go [hunk 2]
```diff
@@ -298,6 +303,121 @@ csv.from(csv: csvData) |> to(bucket: %q)
...
+
+	// Create separate buckets to act as the target for remote writes
+	svc := l.BucketService(t)
+	remoteBucket := &influxdb.Bucket{
+		OrgID: l.Org.ID,
+		Name:  remoteBucketName,
+	}
+	require.NoError(t, svc.CreateBucket(ctx, remoteBucket))
+
+	// Create a replication for the first remote bucket.
```
Comment (lesam) [inline cmd/influxd/launcher/replication_test.go:394]:
```suggestion
	// Create a replication for the remote bucket.
```

File: replications/internal/queue_management_test.go [hunk 3]
```diff
@@ -437,6 +437,82 @@ func TestEnqueueData(t *testing.T) {
 	require.Equal(t, data, string(written))
 }
 
+// this test ensures that data does not get incorrectly dropped from the Queue on remote write failures
+func TestSendWrite(t *testing.T) {
```
Comment (lesam) [inline replications/internal/queue_management_test.go:441]: Did this test fail for the old code?

Comment (DStrand1) [reply replications/internal/queue_management_test.go:441]: No, but was a test I wanted to make sure passed since I wasn't sure of the scale of the original issue this PR fixes

File: replications/remotewrite/writer_test.go [hunk 4]
```diff
@@ -244,9 +236,67 @@ func TestWrite(t *testing.T) {
 
 		configStore.EXPECT().GetFullHTTPConfig(gomock.Any(), testID).Return(testConfig, nil)
 		configStore.EXPECT().UpdateResponseInfo(gomock.Any(), testID, http.StatusInternalServerError, invalidResponseCode(http.StatusInternalServerError).Error()).Return(nil)
-		_, _, actualErr := w.Write(testData, 1)
+		_, actualErr := w.Write(testData, 1)
 		require.Equal(t, invalidResponseCode(http.StatusInternalServerError), actualErr)
 	})
+
+	t.Run("writes resume after temporary remote disconnect", func(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (DStrand1) [reply replications/remotewrite/writer_test.go:243]: Same as above, this test passed when written

**Review by lesam — APPROVED** [review]
