### PR TITLE
fix(http): improve error handling and response to api consumer for org service

### LINKED ISSUE #16498: Malformed JSON produces unhelpful error message
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

`curl --data '{"MYSQL_USER", "davidgs"}' --request PATCH --url https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/orgs/f978dfb87de31ea3/secrets --header 'Authorization: Token token>'`

__Expected behavior:__
Describe what you expected to happen.
Some sort of detailed error message
__Actual behavior:__
Describe What actually happened.
"An internal error has occured"

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

### PR DESCRIPTION
**Pull request by jsteenb2**
Closes #16498

add a reusable api type for decoding and responding to http requests. Improves error handling.

Work is broken up into 2 commits, first one for creating the API decoder/responder, and the 2nd for using it within the org service. The new API type normalizes handling of decoding issues and failed write issues amongst. It is also very extensible, more we can do with it than what meets the eye.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: http/org_service.go [hunk 1]
```diff
@@ -203,399 +201,232 @@ func newOrgResponse(o *influxdb.Organization) *orgResponse {
...
 	}
-}
+	h.log.Debug("Org created", zap.String("org", fmt.Sprint(org)))
 
-type postOrgRequest struct {
-	Org *influxdb.Organization
-}
+	h.API.Respond(w, http.StatusCreated, newOrgResponse(org))
 
-func decodePostOrgRequest(ctx context.Context, r *http.Request) (*postOrgRequest, error) {
```
Comment (jsteenb2) [inline http/org_service.go]: this PR axes a bunch of unneccsary indirection, reduce the jumping around and make it easier to follow within the handler itself.
