### PR TITLE
fix: Show Replication Queue size and Replication TCP Errors

### LINKED ISSUE #23942: list replication API does not show the correct latestErrorMessage
The List Replication API does not show the correct latestErrorMessage.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Configure edge to edge Replication Influxdb v 2.5.1
2. If the remote device is not reachable, then the log will show: 2022-11-23T02:47:54.375113Z     error   Error in replication stream     {"log_id": "0eKYjXjW000", "service": "replications", "replication_id": "0a5367c619216000", "error": "Post \"http://192.168.6.61:8086/api/v2/write?bucket=c7ae00d9c6bda8e8&org=5d238a6ee32d9ef5\": dial tcp 192.168.6.61:8086: connect: no route to host", "retries": 290}
3. If you list the replication using http://precision-5820-ubuntu:8086/api/v2/replications?orgID=83735307485b794f command, it shows the following response: (Please note the latestErrorMessage is empty)
replications": [
        {
            "id": "0a5367c619216000",
            "orgID": "83735307485b794f",
            "name": "Edge2Center",
            "remoteID": "0a53673b824d7000",
            "localBucketID": "39a2fc7ae5a5d7bc",
            "remoteBucketID": "c7ae00d9c6bda8e8",
            "RemoteBucketName": "",
            "maxQueueSizeBytes": 67108860,
            "currentQueueSizeBytes": 3397765,
            "latestResponseCode": 204,
            "latestErrorMessage": "",
            "dropNonRetryableData": false,
            "maxAgeSeconds": 0
        }
    ]
}

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

### PR DESCRIPTION
**Pull request by suitableZebraCaller**
- Closes #23942
### Required checklist
- [ ] Sample config files updated (both `/etc` folder and `NewDemoConfig` methods) (influxdb and plutonium)
- [ ] openapi swagger.yml updated (if modified API) - link openapi PR
- [*] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### Description
1-3 sentences describing the PR (or link to well written issue)
Contains two commits: 
1. Show non-http error messages in the latest error message when requested by API. (e.g. issue https://github.com/influxdata/influxdb/issues/23942)

2.Show remaining queue size when requested by the API.

### Context
Why was this added? What value does it add? What are risks/best practices?
1. TCP Errors would be hidden when List or Retrieve calls are made for the replication queue. For example errors such as "no route to host" or "connection refused". Adding this would make sure such errors aren't hidden from the user/other programs, and allow for easier identification of issues during deployment. 

2. Currently there is no way to know the number of bytes remaining in the queue via the API.  Users and other programs do not know if the queue has been consumed. "CurrentQueueSizeBytes" only shows the queue file size in replicationq folder and not the actual queue size. 

### Affected areas (delete section if not relevant):
List of user-visible changes. As a user, what would I need to see in do
Changes to the returned request body: JSON objects fields.

### Note for reviewers:
Check the semantic commit type:
 - Feat: a feature with user-visible changes
 - Fix: a bug fix that we might tell a user “upgrade to get this fix for your issue”
 - Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except dependency version changes)
 - Build: build script changes, CI config changes, build tool updates
 - Refactor: non-user-visible refactoring
 - Check the PR title: we should be able to put this as a one-liner in the release notes

### CODE REVIEW

File: replications/remotewrite/writer.go [hunk 1]
```diff
@@ -111,11 +111,7 @@ func (w *writer) Write(data []byte, attempts int) (backoff time.Duration, err er
 	}
 
 	res, postWriteErr := PostWrite(ctx, conf, data, w.clientTimeout)
-	res, msg, ok := normalizeResponse(res, postWriteErr)
-	if !ok {
-		// bail out
-		return w.backoff(attempts), postWriteErr
```
Comment (jeffreyssmith2nd) [inline replications/remotewrite/writer.go:117]: I don't think we can't to lose this backoff calculation here. However, I do agree that we want to record the last return code/message. You can copy lines 121-128 into this if block so that we do update the response info, but also still attempt the backoff correctly.

File: replications/service.go [hunk 2]
```diff
@@ -76,6 +76,7 @@ type DurableQueueManager interface {
 	DeleteQueue(replicationID platform.ID) error
 	UpdateMaxQueueSize(replicationID platform.ID, maxQueueSizeBytes int64) error
 	CurrentQueueSizes(ids []platform.ID) (map[platform.ID]int64, error)
+	RemainingQueueSizes(ids []platform.ID) (map[platform.ID]int64, error)
```
Comment (jeffreyssmith2nd) [inline replications/service.go:79]: This change needs some updates to the tests as well so that they start building successfully again.

**Review by jeffreyssmith2nd — COMMENTED** [review]
Thanks for the contribution! A few minor comments, but overall you're on the right track here.

**Comment by jeffreyssmith2nd** [comment]
Hey @suitableZebraCaller, I think this is pretty much ready to go. To meet our standard of conventional commits, you'll need to rebase the three commits that start with `FIX` to start with `fix` instead. The casing does matter unfortunately.

**Review by jeffreyssmith2nd — APPROVED** [review]

**Comment by jeffreyssmith2nd** [comment]
Thanks again @suitableZebraCaller!
