### PR TITLE
fix: advance replications queue after successful remote writes

### LINKED ISSUE #22964: Replication queues should consistently advance following successful remote writes
For scenarios where local writes happen at about the same rate or slightly faster than remote writes, we need to make sure that the queue on-disk position is consistently advanced. This is to allow the on-disk queue to free up space from old segments to allow new data to be queued, and to prevent re-sending large amounts of data if the scanner errors out before the call to advance is made.

### PR DESCRIPTION
**Pull request by wbaker85**
Closes #22964

Advances the queue after successful remote writes. This prevents a condition where after a sequence of successful remote writes, an error returned from the remote write function [perhaps due to a server shutdown](https://github.com/influxdata/influxdb/pull/22958) puts the queue into a state where remote writes will be duplicated when `SendWrite` is called again.

### CODE REVIEW

File: replications/internal/queue_management.go [hunk 1]
```diff
@@ -136,62 +136,51 @@ func (rq *replicationQueue) run() {
 			// that rq.SendWrite will be called again in this situation and not leave data in the queue. Outside of this
 			// specific scenario, the buffer might result in an extra call to rq.SendWrite that will immediately return on
 			// EOF.
-			for rq.SendWrite() {
-			}
+			rq.SendWrite()
```
Comment (wbaker85) [inline replications/internal/queue_management.go:139]: After some refactoring associated with the scanner advancement, it came to the point where this function would only ever return `false`, so looping over it is no longer needed.

File: replications/internal/queue_management.go [hunk 2]
```diff
@@ -136,62 +136,51 @@ func (rq *replicationQueue) run() {
...
-		if scan.Err() != nil {
+		if err := scan.Err(); err != nil {
+			if errors.Is(err, io.EOF) {
+				// An io.EOF error here indicates that there is no more data left to process, and is an expected error.
+				return
+			}
+			// Any other error here indicates a problem reading the data from the queue, so we log the error and drop the data
+			// with a call to scan.Advance() later.
 			rq.logger.Info("Segment read error.", zap.Error(scan.Err()))
-			// TODO: Add metrics collection for dropped data here.
```
Comment (wbaker85) [inline replications/internal/queue_management.go:171]: I am not 100% sure if it is possible to have `scan.Next()` return true and `scan.Err()` not be nil. I could not find a way to generate that scenario for testing. So at this point, I am leaving the error checking and logging in, but dropping the metrics collection. Adding a metrics collector here that is not able to be tested makes me nervous since they like to panic if the labels aren't set up correctly, and that eludes static analysis.

File: replications/internal/queue_management.go [hunk 3]
```diff
@@ -136,62 +136,51 @@ func (rq *replicationQueue) run() {
...
-		if err != io.EOF {
-			rq.logger.Error("Error in replication queue scanner", zap.Error(err))
+		if _, err = scan.Advance(); err != nil {
+			if err != io.EOF {
+				rq.logger.Error("Error in replication queue scanner", zap.Error(err))
+			}
+			return
 		}
-		return false
+		rq.metrics.Dequeue(rq.id, rq.queue.TotalBytes())
```
Comment (wbaker85) [inline replications/internal/queue_management.go:182]: We should only need to update these metrics if the scanner advances (and is not EOF or some other error), so moved this out of a defer for simplicity.

File: replications/internal/queue_management.go (hunk 1 above)
Comment (wbaker85) [reply replications/internal/queue_management.go]: Turns out that there is a reason to continue to loop over this - when testing with small segment sizes so that multiple segments would be written through, there are situations where `Next()` returns falls even if there is more data in the queue. So to take care of that I modified the test and restored the looping / bool returning behavior.

**Review by DStrand1 — APPROVED** [review]
LGTM
