### PR TITLE
Force subqueries to match the parent queries ordering

### LINKED ISSUE #8699: subquery doesn't support order by
InfluxDB version: 1.3.1  

When I run the subquery with `order by`, it doesn't work:

```
> select * from cpu order by time desc
name: cpu
time                host    region  value
----                ----    ------  -----
1502764231978282504 serverA us_west 0.6
1502763228833832379 serverA us_west 0.61
1502763224144379689 serverA us_west 0.64
> 
> select * from (select * from cpu) order by time desc
name: cpu
time                host    region  value
----                ----    ------  -----
1502763224144379689 serverA us_west 0.64
1502763228833832379 serverA us_west 0.61
1502764231978282504 serverA us_west 0.6
```

### PR DESCRIPTION
**Pull request by jsternberg**
Previously, subqueries would honor their own ordering. We never really
supported that and I have no idea if it would work since most parts in
the query engine assume that points are being delivered in only one
ordering.

Subqueries have now been modified so if a person tries to do different
ordering, they get an error when running the query. If they specify an
ordering in the top most query, that ordering gets propagated to all
subqueries.

Fixes #8699.

- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] CHANGELOG.md updated

### CODE REVIEW

File: query/compile.go [hunk 1]
```diff
@@ -764,6 +768,19 @@ func (c *compiledStatement) subquery(stmt *influxql.SelectStatement) error {
...
+	if subquery.Ascending != c.Ascending {
+		// If the ordering is different, but the subquery has no sort fields
+		// (so the user never specified they wanted it to be ascending), inherit
+		// the ordering from the parent query.
+		if len(stmt.SortFields) == 0 {
+			subquery.Ascending = c.Ascending
+		} else {
+			return errors.New("subqueries must be ordered in the same direction as the query itself")
+		}
+	}
```
Comment (benbjohnson) [inline query/compile.go]: Do the sort fields need to be the same if `Ascending` is the same?

Comment (jsternberg) [reply query/compile.go]: Well, the sort fields have to be the same if `Ascending` is the same. Although I think we could largely change this logic to `if len(stmt.SortFields) != 0 && subquery.Ascending != c.Ascending`. I'll change it to that so there's less nesting.
