### PR TITLE
fix(system-vars-mapping): updated variable mapping for system variabes to register changes in system variables

### LINKED ISSUE #19346: Changing System Variables queries cached results
The crux of this issue is that the query cache is incorrectly mapping selected system values when they're being toggled. The issue here then becomes that toggling between relative tumeRanges does not issue a new query even though it should.

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #19346

### Problem

Changing the timeRange in the dashboard page does not issue a new query for the newly selected timerange

### Solution

The issue here is that the system variables stored selected values differently than other variables so we are writing a condition to map system variables differently. This PR also clears the cache whenever the timerange selection is updated 

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)

### CODE REVIEW

File: ui/src/dashboards/components/DashboardHeader.tsx [hunk 1]
```diff
@@ -106,6 +106,9 @@ const DashboardHeader: FC<Props> = ({
   }
 
   const handleChooseTimeRange = (timeRange: TimeRange) => {
+    if (isFlagEnabled('queryCacheForDashboards')) {
+      resetQueryCache()
```
Comment (Asalem1) [inline ui/src/dashboards/components/DashboardHeader.tsx:110]: @drdelambre do you think this is necessary?
