### PR TITLE
Influx CLI: Make cli case insensitive

### LINKED ISSUE #8590: [bug] influx cli case sensitivity
### Bug report

__System info:__ InfluxDB 1.2.4 on Centos7

__Steps to reproduce:__

1. Start `influx` cli client
2. Enter `format column`
3. Enter `FORMAT column` (fails; same as above, just keyword capitalized)
4. Enter `format json` (works)
5. Enter `FORMAT json` (fails)
6. Enter `format JSON`  (works)

__Expected behavior:__
- All should work; all keywords shall be handled case-insensitive (most are: SHOW, USE, SELECT, CREATE...)

__Actual behavior:__
```
> format json
> FORMAT json
Unknown format "format json". Please use json, csv, or column.
> FORMAT JSON
Unknown format "format json". Please use json, csv, or column.
> format JSON
> 
```

__Additional info:__
- I generally capitalize keywords in SQL-like syntaxes
- Seems to be specific to the `FORMAT` keyword.

### PR DESCRIPTION
**Pull request by liketic**
I'm trying to fix #8590 . It's my first PR, happy to hear any comments. 
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by liketic** [comment]
Can anyone help to review this. I'm OK to close it if it's not issue.

**Comment by rbetts** [comment]
@mark-rushakoff Can you review this?

File: cmd/influx/cli/cli.go [hunk 1]
```diff
@@ -294,6 +294,9 @@ func (c *CommandLine) ParseCommand(cmd string) error {
 
 // Connect connects to a server.
 func (c *CommandLine) Connect(cmd string) error {
+	// normalize cmd
+	cmd = strings.ToLower(cmd)
```
Comment (mark-rushakoff) [inline cmd/influx/cli/cli.go]: I was a little concerned about lowercasing the hostname in the rest of the string, but as far as I can research, host names are expected to be case insensitive in any context here.
