### PR TITLE
fix(ui): fetch queries when opening veo

### LINKED ISSUE #12797: after opening the veo from clicking the edit cell, the graph should be here
Currently, it just says create a query, even though there is a query selected in the builder.

open_veo

### PR DESCRIPTION
**Pull request by ischolten**
Closes #12797

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] http/swagger.yml updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/dashboards/components/VEO.tsx [hunk 1]
```diff
@@ -58,6 +60,15 @@ interface OwnProps extends WithRouterProps {
 type Props = OwnProps & StateProps & DispatchProps
 
 class VEO extends PureComponent<Props, {}> {
+  public componentDidMount() {
+    const {existingView} = this.props
+    const view = existingView || createView<XYView>(ViewType.XY)
+
+    this.props.setActiveTimeMachine(VEO_TIME_MACHINE_ID, {view})
```
Comment (AlirieGray) [inline ui/src/dashboards/components/VEO.tsx]: is it possible to destructure these on line 64?

Comment (ischolten) [reply ui/src/dashboards/components/VEO.tsx]: because the name of the action creator is the same as the name that the prop function was named, destructuring would create a shadowed name.
