### PR TITLE
(fix)(ui) Sort by description broken

### LINKED ISSUE #13950: [UI] - Settings > Labels - sort by description has no effect
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open Settings > Labels
2. Create 5 or more labels including various descriptions
3. Sort by name ascending - OK
4. Sort by name descending - OK
5. Sort by description ascending - looks like the result is sort by name
6. Sort by description descending - no change

__Expected behavior:__

Expected that sorting by description should work by alpha, whether ascending or descending, based on values in the description field. 

__Actual behavior:__

First description sort followed order of strings in name field.  Attempt to sort in opposite direction resulted in no change to the sort order.

__Environment info:__

* System info: Run `uname -srm` and copy the output here `Linux x86_64`
* InfluxDB version: Run `influxd version` and copy the output here - local build for creating cypress tests.  Last commit from master d31be2a6f540bd64e38ea0ab6341a268a5e09a40
* Other relevant environment details: Container runtime, disk info, etc
Browser: Chrome 73
__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Boot command

```
./bin/linux/influxd --store=memory --e2e-testing=true --log-level debug 2>&1 > ~/var/log/influxd.log &
```

__Screenshots__
LabelsSortByName01
LabelsSortByName02
LabelsSortByDesc01
LabelsSortByDesc02

### PR DESCRIPTION
**Pull request by zoesteinkamp**
Also the test have been added that correlate to this issue

Closes #13950 

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/labels/components/LabelList.tsx [hunk 1]
```diff
@@ -87,10 +86,6 @@ export default class LabelList extends PureComponent<Props, State> {
     )
   }
 
-  private get headerKeys(): SortKey[] {
```
Comment (121watts) [inline ui/src/labels/components/LabelList.tsx]: We lose the type safety here but its okay :)
