### PR TITLE
fix: add a timestamp to the telegraf label creation to insure uniqueness

### LINKED ISSUE #15730: [UI - Telegrafs]  Create telegraf transaction fails to create special label
__Steps to reproduce:__
From the Load Data > Telegrafs page
1.  Click Create Configuration
2. Choose a bucket and a plugin (Have been using Docker but issue also appears with others)
3. Click continue
4. Configure the plugin
5. Add a name and description
6. Click Create and Verify 

__Expected behavior:__
If all values are correct expect to see a notification that the Configuration was Successfully saved 

__Actual behavior:__
An error notification appears. "Failed to save configurations"
The console log shows 
```
 POST http://localhost:9999/api/v2/labels 422 (Unprocessable Entity)
```
Which is also shown in the network log 
```
Request URL: http://localhost:9999/api/v2/labels
Request Method: POST
Status Code: 422 Unprocessable Entity
Remote Address: [::1]:9999
Referrer Policy: no-referrer-when-downgrade
```
Payload sent looked like

```
{"orgID":"72548c12d87a9727","name":"@influxdata.token","properties":{"color":"#FFFFFF","description":"token for telegraf config: asdf","tokenID":"04b9730246697000"}}
```
Note that when creating labels directly there is no tokenID in the properties. 

Also can click to another area of the UI and then return to Load Data > Telegrafs and the configuration is present. 

__Screencast__

TelegrafLabel01

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.4.0-166-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Working with nightly build docker image.  From docker log: 
```
ts=2019-11-04T08:41:47.008799Z lvl=info msg="Welcome to InfluxDB" log_id=0IuP4e00000 version=nightly commit=2d6d38179 build_date=2019-11-04T07:21:10Z
```
* Other relevant environment details: Container runtime, disk info, etc
browser: __Chrome 77__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
Started with e2e-testing enabled
```
--e2e-testing=true
```

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Closes #15730

Labels require unique names. The buggy behavior when we create a telegraf config is to create a label for the config and to name every label `@influxdata.name`. This fix appends a timestamp to `@influxdata.name` (that string is being filtered on, so we want keep `@influxdata.name`)

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: ui/src/dataLoaders/actions/dataLoaders.ts [hunk 1]
```diff
@@ -454,10 +454,11 @@ const createTelegraf = async (dispatch, getState, plugins) => {
 
     const createdLabel = await client.labels.create({
       orgID: org.id,
-      name: '@influxdata.token',
+      name: `@influxdata.token-${new Date().getTime()}`,
       properties,
     })
 
+    console.log('label', createdLabel)
```
Comment (Asalem1) [inline ui/src/dataLoaders/actions/dataLoaders.ts]: :(

File: ui/cypress/e2e/collectors.test.ts [hunk 2]
```diff
@@ -356,6 +356,30 @@ describe('Collectors', () => {
           })
       })
     })
+
+    // fix for https://github.com/influxdata/influxdb/issues/15730
+    it('creates a cofiguration with a unique label', () => {
```
Comment (121watts) [inline ui/cypress/e2e/collectors.test.ts]:
```suggestion
    it('creates a configuration with a unique label', () => {
```

File: ui/src/dataLoaders/actions/dataLoaders.ts [hunk 3]
```diff
@@ -454,7 +454,7 @@ const createTelegraf = async (dispatch, getState, plugins) => {
 
     const createdLabel = await client.labels.create({
       orgID: org.id,
-      name: '@influxdata.token',
+      name: `@influxdata.token-${new Date().getTime()}`,
```
Comment (121watts) [inline ui/src/dataLoaders/actions/dataLoaders.ts]: perhaps the same comment in the cypress test here?
