### PR TITLE
fix(task): Improve Executor#Execute error consistency

### LINKED ISSUE #15161: Improve task query Executor#Execute to return more consistent errors for multiple implementations
`asyncQueryServiceExecutor` and `queryServiceExecutor` both implement the `backend.Executor` interface. The `Execute` method does not return consistent errors between these APIs. This issue is intended to unify the behavior as much as possible.

In summary this means moving most of the logic out of `asyncQueryServiceExecutor#Execute` and into the `asyncRunPromise` type.

### PR DESCRIPTION
**Pull request by stuartcarnie**
Implementations of the backend.Executor produce errors limited to querying the KV store. The remainder of the errors will be processed in the implementation of a `RunPromise`.

Closes #15161

### CODE REVIEW

File: task/backend/executor/executor.go [hunk 1]
```diff
@@ -312,10 +298,31 @@ func (p *asyncRunPromise) Cancel() {
 // followQuery waits for the query to become ready and sets p's results.
```
Comment (GeorgeMac) [inline task/backend/executor/executor.go]: take it or leave it: update doc here

Comment (stuartcarnie) [reply task/backend/executor/executor.go]: good catch; I'll fix that
