### PR TITLE
fix(api/orgs): (API-design-issue) FindOptions for orgs

### LINKED ISSUE #19319: V2.0: Listing all organizations only returns first 20 results
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create more than 20 organizations
2. Use either `/api/v2/orgs` or `influx org list` to retrieve list of organisations

__Expected behavior:__
I'd expect more than 20 entries or some pagination mechanism.

__Actual behavior:__
List is limited to 20 entries. Missing organizations can be access if id/name is known.

__Environment info:__

* InfluxDB version: InfluxDB 2.0.0-beta.15 (git: f54848f443) build_date: 2020-07-23T18:27:19Z

### PR DESCRIPTION
**Pull request by KevinSmile**
Closes #19319

Describe your proposed changes here.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [x] http/swagger.yml updated (if modified Go structs or API)
- [x] Signed CLA (if not already signed)

fix for https://github.com/influxdata/influxdb/issues/19319#issuecomment-673512362

### CODE REVIEW

**Comment by KevinSmile** [comment]
also need to update client-libs for this API.

File: http/org_service.go [hunk 1]
```diff
@@ -241,8 +241,14 @@ func (h *OrgHandler) handleGetOrg(w http.ResponseWriter, r *http.Request) {
 
 // handleGetOrgs is the HTTP handler for the GET /api/v2/orgs route.
 func (h *OrgHandler) handleGetOrgs(w http.ResponseWriter, r *http.Request) {
-	var filter influxdb.OrganizationFilter
 	qp := r.URL.Query()
+
+	var filter influxdb.OrganizationFilter
```
[the remark this answers is not in the document]
Comment (KevinSmile) [reply http/org_service.go]: done

File: kv/org.go [hunk 2]
```diff
@@ -398,13 +412,18 @@ func organizationIndexKey(n string) []byte {
...
 		return err
 	}
 
-	cur, err := b.ForwardCursor(nil)
+	direction := CursorAscending
+	if descending {
+		direction = CursorDescending
+	}
+
+	cur, err := b.ForwardCursor(nil, WithCursorDirection(direction))
```
[the remark this answers is not in the document]
Comment (KevinSmile) [reply kv/org.go:426]: I'm following: 
https://github.com/influxdata/influxdb/blob/5d63ebb4fc6ed10f869fc9bfab2d9f19078d2210/kv/bucket.go#L602-L605

https://github.com/influxdata/influxdb/blob/5d63ebb4fc6ed10f869fc9bfab2d9f19078d2210/kv/dashboard.go#L745-L748
and so on...

many duplicate snippets about this, maybe we could do some refactor in another issue?

File: http/org_service.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (KevinSmile) [reply http/org_service.go]: As for `FindUserResourceMappings`,  I would prefer to implement it in https://github.com/influxdata/influxdb/blob/5d63ebb4fc6ed10f869fc9bfab2d9f19078d2210/kv/urm.go#L94

because `opt` do have usages in https://github.com/influxdata/influxdb/blob/5d63ebb4fc6ed10f869fc9bfab2d9f19078d2210/tenant/service_user.go#L148 
and some other places.

**Comment by KevinSmile** [comment]
As for some general design about paging, maybe could do some refactor in another issue?

e.g. general args(REST)/flags(CLI) remove or add, duplicate snippets...

File: kv/org.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (glinton) [reply kv/org.go:426]: You implemented it just fine, I misunderstood the intention at first as I mentioned.

File: kv/org.go [hunk 3]
```diff
@@ -246,11 +246,25 @@ func (s *Service) FindOrganizations(ctx context.Context, filter influxdb.Organiz
 		return os, len(os), nil
 	}
 
+	var offset, limit, count int
```
Comment (glinton) [inline kv/org.go:249]: I still think you should implement the new options for the above organization slice, maybe something like:
```diff
@@ -1,12 +1,28 @@
+  var offset, limit, count int
+  var descending bool
+  if len(opt) > 0 {
+    // these checks should be part of DecodeFindOffset
+    if opt[0].Offset > 0 {
+      offset = opt[0].Offset
+    }
+
+    if opt[0].Limit > 0 {
+      limit = opt[0].Limit
+    }
+
+    descending = opt[0].Descending
+  }
+
   if filter.UserID != nil {
     // find urms for orgs with this user
     urms, _, err := s.FindUserResourceMappings(ctx, influxdb.UserResourceMappingFilter{
       UserID:       *filter.UserID,
       ResourceType: influxdb.OrgsResourceType,
-    }, opt...)
+    })
     if err != nil {
       return nil, 0, err
     }
+
     // find orgs by the urm's resource ids.
     for _, urm := range urms {
       o, err := s.FindOrganizationByID(ctx, urm.ResourceID)
@@ -15,5 +31,18 @@
         os = append(os, o)
       }
     }
+
+    if offset > 0 && offset < len(os) {
+      os = os[offset:]
+    }
+
+    if limit > 0 && limit < len(os) {
+      os = os[:limit]
+    }
+
+    if descending {
+      os = // reverse `os` how you wish
+    }
+
     return os, len(os), nil
   }
```

Comment (KevinSmile) [reply kv/org.go:249]: Yes, you are right, it makes code clean. 
However, (again) I'm following similar duplicate snippets in some other places, so I guess it would be better to start a new refactor-issue to solve all these duplicate snippets?

https://github.com/influxdata/influxdb/blob/ce443f832e87484582eb3d5c78c812c683299a06/kv/notification_rule.go#L370-L391

https://github.com/influxdata/influxdb/blob/ce443f832e87484582eb3d5c78c812c683299a06/kv/dashboard.go#L231-L237

https://github.com/influxdata/influxdb/blob/ce443f832e87484582eb3d5c78c812c683299a06/kv/bucket.go#L406-L412

Comment (glinton) [reply kv/org.go:249]: You're doing great. For now I think go ahead and implement the `offset` and `limit` options for the user resource mappings wherever you prefer and this pr should be good to go. Without some implementation for the urm's i don't think the different behavior of using options with/without filters makes for a good user experience.

Comment (KevinSmile) [reply kv/org.go]: Thanks for your advice! Done.

Comment (KevinSmile) [reply kv/org.go]: BTW, similar issue in https://github.com/influxdata/influxdb/pull/19330.
(and maybe some other places about `FindOptions`)

Comment (KevinSmile) [reply kv/org.go]: What do you think? @glinton

File: http/swagger.yml [hunk 4]
```diff
@@ -3940,6 +3940,8 @@ paths:
       summary: List all organizations
       parameters:
         - $ref: "#/components/parameters/TraceSpan"
+        - $ref: "#/components/parameters/Offset"
+        - $ref: "#/components/parameters/Limit"
```
Comment (glinton) [inline http/swagger.yml:3944]: Seems like an entry for `descending` should go in here as well.

Comment (KevinSmile) [reply http/swagger.yml:3944]: Done.

**Comment by glinton** [comment]
Looks like you just need to sign the [CLA](https://www.influxdata.com/legal/cla/) and I think we can merge this

**Comment by KevinSmile** [comment]
Just signed the CLA. Thanks! @glinton
