### PR TITLE
fix: UX improvements and bug fixes to dbrp commands

### LINKED ISSUE #20085: Improvements to dbrp CLI commands
## What

* Expand _DBRP_ to _database and retention policy_, as DBRP won't make sense to a new user
* Drop the `-d` and `-r` short options
    * they are only two characters different from `--db` and `--rp` respectively; and
    * in some cases conflict or may be non-obvious with other long-form parameters
* Fix a number of bugs with the CLI arguments not mapped to the correct commands.

The `list` command bound to the `create` command arguments:

https://github.com/influxdata/influxdb/blob/d93560fdc85f21d8a4720a7882698f38c5be28b2/cmd/influx/v1_dbrp.go#L54-L56

however, the `list` command is using a mixture of create and find flags:

https://github.com/influxdata/influxdb/blob/d93560fdc85f21d8a4720a7882698f38c5be28b2/cmd/influx/v1_dbrp.go#L64

https://github.com/influxdata/influxdb/blob/d93560fdc85f21d8a4720a7882698f38c5be28b2/cmd/influx/v1_dbrp.go#L80

* Fix incorrect logic in how flags are read and used. Note the following is incorrect:

    Checks `BucketID` but binds to the `ID` flag:

    https://github.com/influxdata/influxdb/blob/d93560fdc85f21d8a4720a7882698f38c5be28b2/cmd/influx/v1_dbrp.go#L99-L105

    Checks `DB` flag, but binds the `BucketID` filter:

    https://github.com/influxdata/influxdb/blob/d93560fdc85f21d8a4720a7882698f38c5be28b2/cmd/influx/v1_dbrp.go#L107-L113

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #20085

As described in #20085, this PR includes the following changes:

* Expand _DBRP_ to _database and retention policy_ in the help text, as DBRP won't make sense to a new user
    * At the same time, we're teaching them that the `dbrp` command is an abbreviated form
* Fix a number of identified bugs

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass

### CODE REVIEW

File: cmd/influx/v1_dbrp.go [hunk 1]
```diff
@@ -33,34 +33,34 @@ var v1DBRPCRUDFlags struct {
...
 	Org      organization // required  // Specifies the organization ID to filter on
 	RP       string       // Specifies the retention policy to filter on
 }
 
 func v1DBRPFindCmd(f *globalFlags, opt genericCLIOpts) *cobra.Command {
 	cmd := &cobra.Command{
 		Use:   "list",
-		Short: "List DBRP",
+		Short: "List database and retention policy mappings",
 		RunE:  checkSetupRunEMiddleware(&flags)(v1DBRPFindF),
```
Comment (danxmoran) [inline cmd/influx/v1_dbrp.go:48]: Reminded about `Args: cobra.NoArgs` below, this one also needs it.

File: cmd/influx/v1_dbrp.go [hunk 2]
```diff
@@ -88,28 +88,16 @@ func v1DBRPFindF(cmd *cobra.Command, args []string) error {
 	}
 	filter := influxdb.DBRPMappingFilterV2{OrgID: &orgID}
 
-	if v1DBRPFindFlags.ID != "" {
-		fID, err := influxdb.IDFromString(v1DBRPFindFlags.ID)
-		if err != nil {
-			return err
-		}
-		filter.ID = fID
+	if v1DBRPFindFlags.ID.Valid() {
```
Comment (danxmoran) [inline cmd/influx/v1_dbrp.go:91]: Should we return an `err` as an `else` case for these checks?

File: cmd/influx/v1_dbrp.go [hunk 3]
```diff
@@ -142,24 +130,25 @@ var v1DBRPCreateFlags struct {
...
 	v1DBRPCreateFlags.Org.register(opt.viper, cmd, false)
-	cmd.Flags().StringVarP(&v1DBRPCreateFlags.BucketID, "bucket-id", "b", "", "the bucket ID to filter on")
+	cli.IDVar(cmd.Flags(), &v1DBRPCreateFlags.BucketID, "bucket-id", 0, "The ID of the bucket to be mapped")
 	_ = cmd.MarkFlagRequired("bucket-id")
-	cmd.Flags().StringVarP(&v1DBRPCreateFlags.DB, "db", "d", "", "the v1 database to map from")
+	cmd.Flags().StringVar(&v1DBRPCreateFlags.DB, "db", "", "The name of the database")
 	_ = cmd.MarkFlagRequired("db")
-	cmd.Flags().BoolVar(&v1DBRPCreateFlags.Default, "default", false, "Specify if this mapping represents the default retention policy for the database specificed")
-	cmd.Flags().StringVarP(&v1DBRPCreateFlags.RP, "rp", "r", "", "InfluxDB v1 retention policy")
+	cmd.Flags().BoolVar(&v1DBRPCreateFlags.Default, "default", false, "Identify this mapping as the default retention policy")
```
Comment (danxmoran) [inline cmd/influx/v1_dbrp.go:145]:
```suggestion
	cmd.Flags().BoolVar(&v1DBRPCreateFlags.Default, "default", false, "Identify this retention policy as the default for the database")
```

File: cmd/influx/v1_dbrp.go [hunk 4]
```diff
@@ -142,24 +130,25 @@ var v1DBRPCreateFlags struct {
...
+	cmd.Flags().StringVar(&v1DBRPCreateFlags.RP, "rp", "", "Name of the retention policy")
```
Comment (danxmoran) [inline cmd/influx/v1_dbrp.go:146]:
```suggestion
	cmd.Flags().StringVar(&v1DBRPCreateFlags.RP, "rp", "", "The name of the retention policy")
```

File: cmd/influx/v1_dbrp.go [hunk 5]
```diff
@@ -308,30 +291,30 @@ func v1DBRPDeleteF(cmd *cobra.Command, args []string) error {
...
 	registerPrintOptions(opt.viper, cmd, &v1DBRPCRUDFlags.hideHeaders, &v1DBRPCRUDFlags.json)
-	v1DBRPCreateFlags.Org.register(opt.viper, cmd, false)
-	cmd.Flags().StringVarP(&v1DBRPUpdateFlags.ID, "id", "i", "", "The dbrp ID (required)")
+	v1DBRPUpdateFlags.Org.register(opt.viper, cmd, false)
+	cli.IDVar(cmd.Flags(), &v1DBRPUpdateFlags.ID, "id", 0, "The ID of the mapping to be updated")
 	_ = cmd.MarkFlagRequired("id")
-	cmd.Flags().StringVarP(&v1DBRPUpdateFlags.RP, "rp", "r", "", "The dbrp InfluxDB v1 retention policy")
-	cmd.Flags().Bool("default", false, "If dbrp InfluxDB v1 retention policy is default, (only changes when explicitly set)") // note for update we only care about update flags that the user set
+	cmd.Flags().StringVar(&v1DBRPUpdateFlags.RP, "rp", "", "The updated name of the retention policy")
+	cmd.Flags().Bool("default", false, "Set this as the default mapping for the associated database name") // note for update we only care about update flags that the user set
```
Comment (danxmoran) [inline cmd/influx/v1_dbrp.go:312]:
```suggestion
	cmd.Flags().Bool("default", false, "Set this mapping's retention policy as the default for the mapping's database") // note for update we only care about update flags that the user set
```

File: cmd/influx/v1_dbrp.go [hunk 6]
```diff
@@ -308,30 +291,30 @@ func v1DBRPDeleteF(cmd *cobra.Command, args []string) error {
...
+	Default *bool        // A nil value means that Default is unset in the Flags
+	RP      string       // Updated name of the retention policy
 }
 
 func v1DBRPUpdateCmd(f *globalFlags, opt genericCLIOpts) *cobra.Command {
 	cmd := &cobra.Command{
 		Use:   "update",
-		Short: "Update DBRP",
+		Short: "Update a database and retention policy mapping",
 		RunE:  checkSetupRunEMiddleware(&flags)(v1DBRPUpdateF),
```
Comment (danxmoran) [inline cmd/influx/v1_dbrp.go:304]: `Args: cobra.NoArgs` needed here as well

**Review by danxmoran — COMMENTED** [review]
Thanks Stuart!

**Comment by danxmoran** [comment]
@docmerlin I'll probably end up pushing my own suggestions to get the release out this morning, could you also review my ideas for how things could be reworded?

**Comment by docmerlin** [comment]
> @docmerlin I'll probably end up pushing my own suggestions to get the release out this morning, could you also review my ideas for how things could be reworded?

Yes, @danxmoran .

**Review by docmerlin — APPROVED** [review]
LGTM

File: cmd/influx/v1_dbrp.go (hunk 2 above)
Comment (stuartcarnie) [reply cmd/influx/v1_dbrp.go:92]: Not needed, because I added them as IDVar parameters, they will be validated at argument parsing time.
