### PR TITLE
Fix memory leak of retained HTTP write payloads

### LINKED ISSUE #7827: Performance deterioration after upgrading to 1.1
### Bug report

InfluxDB 1.1, Centos7, hosted on EC2, c4.xlarge.
Write is done using HTTP.
Our current model includes about 30 databases with ~120 ops points written and 60 ops queries.
This is after limiting the number of connections to 300 because we had memory issues (We are reporting from about 450 servers once a minute).
Also we are using kapacitor that adds to the querying and writes and have Grafana querying the db.
Until a couple of days ago we were using 1.0 and decided to upgrade to 1.1 because of performance improvements.
Unfortunately, our performance seriously deteriorated:
image

I don't have the performance dumps, I'm afraid, because I had to downgrade as this was a production issue, but I do have the data in the _internal db so if you want me to query something let me know.

### PR DESCRIPTION
**Pull request by mark-rushakoff**
This leak seems to have been introduced in 8aa224b22dc007e,
present in 1.1.0 and 1.1.1.

When points were parsed from HTTP payloads, their tags and fields
referred to subslices of the request body; if any tag set introduced a
new series, then those tags then were stored in the in-memory series
index objects, preventing the HTTP body from being garbage collected. If
there were no new series in the payload, then the request body would be
garbage collected as usual.

Now, we clone the tags before we store them in the index. This is an
imperfect fix because the Point still holds references to the original
tags, and the Point's field iterator also refers to the payload buffer.
However, the current write code path does not retain references to the
Point or its fields; and this change will likely be obsoleted when TSI
is introduced.

This change likely fixes #7827, #7810, #7778, and perhaps others.

- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by mark-rushakoff** [comment]
If anyone is running into this issue now and needs a workaround until this is merged or released, the best option is to keep the HTTP payload as small as possible for writes that introduce a new series. Writes that only affect existing series should not contribute to the leak. Once new series have been written, I believe the only way to release the memory of the associated HTTP payloads is to restart the server.

**Comment by joelegasse** [comment]
If we're concerned about total allocations, this will create a lot of smaller allocations. We could instead just perform one large allocations for cloning `Tags`, rather than cloning each tag Key/Value separately. It would be a two-pass `Clone()`, and there wouldn't be any `Clone()` defined for a single `Tag`, but I think given the usage and goal, that would be OK

**Comment by mark-rushakoff** [comment]
@joelegasse I see what you mean. We have a couple options for a more efficient `Tags.Clone`:

* One backing slice containing all deduplicated keys and values
  * Advantage: one allocation
  * Disadvantage: that one allocation stays in memory until all referring series are deleted
* One backing slice for deduplicated keys, one backing slice for deduplicated values
  * Unlikely to be any better than the previous option
* One backing slice for deduplicated keys, one backing slice per deduplicated value:
  * Advantage: any individual value slice can be freed if all series containing that value are dropped
  * Disadvantage: potentially many small allocations (but potentially not that many, and likely still less than the implementation in cdbdd15)

Ultimately it probably would be best if `tsdb.NewSeries` was instead a method on `tsdb.DatabaseIndex` so that backing slices for tags' keys and values could all be shared. I'll look into this approach tomorrow, and if it seems too complex to get into 1.2, we can fall back to probably the third option above.

File: tsdb/shard.go [hunk 1]
```diff
@@ -580,6 +580,10 @@ func (s *Shard) validateSeriesAndFields(points []models.Point) ([]models.Point,
 				continue
 			}
 
+			// If the tags were created by models.ParsePointsWithPrecision,
+			// they refer to subslices of the buffer containing line protocol.
+			// To ensure we don't refer to that buffer, preventing that buffer from being garbage collected, clone the tags.
+			tags = tags.Clone()
```
Comment (e-dard) [inline tsdb/shard.go]: This is going to cause unnecessary  allocations a lot of the time because `CreateSeriesIndexIfNotExists` only holds onto the subsliced tags if a new series needs to be created.

I think it would be better to push `tags` through to `NewSeries` as-is, and then clone the tags inside `CreateSeriesIndexIfNotExists` only when `AddSeries` is called. Maybe you could just do something like:

```go
series.Tags = series.Tags.Clone()
m.AddSeries(series)
```

File: models/points.go [hunk 2]
```diff
@@ -1633,6 +1655,19 @@ func NewTags(m map[string]string) Tags {
 	return a
 }
 
+// Clone returns a shallow copy of Tags.
+//
+// Tags associated with a Point created by ParsePointsWithPrecision will hold references to the byte slice that was parsed.
+// Use Clone to create Tags with new byte slices that do not refer to the argument to ParsePointsWithPrecision.
+func (a Tags) Clone() Tags {
```
Comment (e-dard) [inline models/points.go]: Just a suggestion: `a` is not at risk of holding onto anything, if we remove all the references it contains. Therefore I don't think we need to allocate a new `Tags` value here. We can just do `a[i] = a[i].Clone()` and it will probably make this method significantly faster. 

Whether or not it's still appropriate to call this `Clone` with that implementation I'm not sure about. 😄
