### PR TITLE
fix(onboarding): don't ignore failures to set initial password

### LINKED ISSUE #20088: Onboarding API ignores errors when trying to set user password
Hello,

I'm using influxdb 2.0 but i coud not sign in. i get this error in logs :
error   api error encountered   {"log_id": "0QYiUwu0000", "handler": "session", "error": "unauthorized access"}

Could you please help.

Best Regards.

### PR DESCRIPTION
**Pull request by danxmoran**
Fixes #20088 

This was the most obvious problem with the onboarding path's handling of passwords. There's also a lot of duplication in the CLI with slight differences between the onboarding paths for interactive vs. noninteractive runs and the `influx setup` vs. `influxd upgrade` runs, but I'm leaving that refactor for a follow-up PR.

### CODE REVIEW

File: tenant/service_onboarding.go [hunk 1]
```diff
@@ -6,12 +6,14 @@ import (
...
 	icontext "github.com/influxdata/influxdb/v2/context"
 	"github.com/influxdata/influxdb/v2/kv"
+	"go.uber.org/zap"
 )
 
 type OnboardService struct {
 	service     *Service
 	authSvc     influxdb.AuthorizationService
 	alwaysAllow bool
+	log         *zap.Logger
```
Comment (danxmoran) [inline tenant/service_onboarding.go:16]: It's a little odd to have a `log` parameter here when there's a whole middleware layer for logging. IMO the middlewares are more confusing than they're worth and could be replaced by option-setters like `WithOnboardingLogger` below. Holding off on the refactor for now 🙂

File: tenant/service_onboarding.go [hunk 2]
```diff
@@ -98,7 +107,18 @@ func (s *OnboardService) onboardUser(ctx context.Context, req *influxdb.Onboardi
 
 	// create users password
 	if req.Password != "" {
-		s.service.SetPassword(ctx, user.ID, req.Password)
+		if err := s.service.SetPassword(ctx, user.ID, req.Password); err != nil {
```
Comment (davidby-influx) [inline tenant/service_onboarding.go:110]: This looks like the best you can do in cascading errors.  Nice that you return the original error here, not the cleanup error. +1

**Review by davidby-influx — APPROVED** [review]
I really like to see this level of error handling. Nice work!

**Review by docmerlin — APPROVED** [review]
