### PR TITLE
Meta node only fixes

### LINKED ISSUE #5754: Adding a node as meta only results in a data node also being registered
To replicate:

Three `influxd` processes. The first two (`n1` and `n2`) should be registered as data and meta nodes, the third (`n3`) should have `enabled = false` set under the `[data]` section in its configuration.

Launch as follows:

```
influxd -config /path/to/n1/config.toml -join localhost:8191,localhost:8291,localhost:8391
influxd -config /path/to/n2/config.toml -join localhost:8191,localhost:8291,localhost:8391
influxd -config /path/to/n3/config.toml -join localhost:8191,localhost:8291,localhost:8391
```

Then on `n1`:

```
> show servers
name: data_nodes
----------------
id	http_addr	tcp_addr
1	localhost:8186	localhost:8188
2	localhost:8286	localhost:8288
3	localhost:8386	localhost:8388


name: meta_nodes
----------------
id	http_addr	tcp_addr
1	localhost:8191	localhost:8188
2	localhost:8291	localhost:8288
3	localhost:8391	localhost:8388

>
```

Checking that there really isn't a data node setup on `n3`:

```
> show servers
ERR: Get http://localhost:8386/query?db=db&epoch=ns&q=show+servers: dial tcp [::1]:8386: getsockopt: connection refused
>
```

Logs for the nodes are attached:

[n1.txt](https://github.com/influxdata/influxdb/files/138482/n1.txt)
[n2.txt](https://github.com/influxdata/influxdb/files/138483/n2.txt)
[n3.txt](https://github.com/influxdata/influxdb/files/138484/n3.txt)

### PR DESCRIPTION
**Pull request by jwilder**
This fixes some issues that come up with creating meta-only nodes.

1. Monitor service defaults to storing statistics in the `_internal` database.  A meta-only node can't store anything itself so for now that config option has to be disabled.  The server will report that as a configuration error for now.
2. A data node was always getting created in the meta store regardless of whether the role of the node was actually a data node.  We now create the appropriate nodes based on the services that are enabled.
3. The `join` config file option was incorrectly exposed under the `[meta]` section as a string slice.  This has been revert and it's now a top-level string that matches the env var and `-join` flag (e.g.  `join = 'host1:8091,host2:9091"`).

Fixes #5754

### CODE REVIEW

File: cmd/influxd/run/config_test.go [hunk 1]
```diff
@@ -79,6 +81,8 @@ enabled = true
 		t.Fatalf("unexpected subscriber enabled: %v", c.Subscriber.Enabled)
 	} else if c.ContinuousQuery.Enabled != true {
 		t.Fatalf("unexpected continuous query enabled: %v", c.ContinuousQuery.Enabled)
+	} else if exp, got := "foo:123,bar:456", c.Join; exp != got {
+		t.Fatalf("unexpected join value: exp %v, got %v", exp, got)
```
Comment (e-dard) [inline cmd/influxd/run/config_test.go]: nit: `got` then `expected`.

File: cmd/influxd/run/config_test.go [hunk 2]
```diff
@@ -162,3 +166,23 @@ enabled = false
...
+dir = "foo"
+
+[data]
+enabled = false
+`, &c); err != nil {
+		t.Fatal(err)
+	}
+
+	if err := c.Validate(); err == nil {
+		t.Fatalf("expected error, got nil")
```
Comment (e-dard) [inline cmd/influxd/run/config_test.go]: `got`, `expected`.

File: services/meta/client.go [hunk 3]
```diff
@@ -834,12 +834,17 @@ func (c *Client) JoinMetaServer(httpAddr, tcpAddr string) error {
 			currentServer++
 			continue
 		}
-		resp.Body.Close()
 
 		// Successfully joined
 		if resp.StatusCode == http.StatusOK {
```
Comment (e-dard) [inline services/meta/client.go]: Maybe tidy this up to:

```go
if resp.StatusCode == http.StatusOK {
    if err := json.NewDecoder(resp.Body).Decode(&node); err != nil {
	    resp.Body.Close()
        return nil, err
    }
    break
}
```

File: services/meta/client.go [hunk 4]
```diff
@@ -834,12 +834,17 @@ func (c *Client) JoinMetaServer(httpAddr, tcpAddr string) error {
...
-			return nil
+			defer resp.Body.Close()
```
Comment (e-dard) [inline services/meta/client.go]: Maybe tidy this up to:

```go
if resp.StatusCode == http.StatusOK {
    if err := json.NewDecoder(resp.Body).Decode(&node); err != nil {
	    resp.Body.Close()
        return nil, err
    }
    break
}
```

File: services/meta/handler.go [hunk 5]
```diff
@@ -164,6 +164,13 @@ func (h *handler) serveExec(w http.ResponseWriter, r *http.Request) {
 			return
 		}
 
+		// Return the node with newly assigned ID as json
+		w.Header().Add("Content-Type", "application/json")
+		enc := json.NewEncoder(w)
+		if err := enc.Encode(node); err != nil {
```
Comment (e-dard) [inline services/meta/handler.go]: Could put the encoding on one line here, too.

**Comment by e-dard** [comment]
LGTM :+1:

File: services/meta/client.go (hunk 4 above)
Comment (jwilder) [inline services/meta/client.go]: That won't close the body in the case there is no error.  I'll convert encoder to one line though.

Comment (e-dard) [inline services/meta/client.go]: Missed the loop!
