### PR TITLE
fix: adding labels to resources is no longer broken

### LINKED ISSUE #15547: [UI - Templates ] Add new label to template triggers Failed to add Label to Template Error Message
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. In Settings > Templates - import a user template
2. In the newly created card, click the '+' add label control (with a fresh install no labels are shown)
3. Type a string into the search field - a dropdown item "Create new label" appears
4. Click "Create new label".  The create label popup loads
5. Accept default color and save the new label. 

N.B. preparing to write a test covering this use case 

__Expected behavior:__
Expected the label to be created and added to the template card.  This is the behavior of a similar process for adding labels to telegrafs.  

__Actual behavior:__
An error message appeared "Failed to add Label to Template".  The console log threw a TypeError.  See below. 

__Screencast__
TemplateAddLabelFail

__Workaround__

Click the add label control '+' again. The label is now visible.  Click it and it is added to the card. 

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.4.0-166-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
This was detected in a nightly build docker image. 
```
ts=2019-10-23T07:57:45.148794Z lvl=info msg="Welcome to InfluxDB" log_id=0Ieun9F0000 version=nightly commit=0fc47bc69 build_date=2019-10-23T07:26:48Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 77__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
Started with e2e testing enabled. 

```
--e2e-testing=true
```

__Logs:__
Include snippet of errors in log.

Console log:

```
TypeError: Cannot read property 'id' of undefined
    at index.ts:291
    at Array.map (<anonymous>)
    at index.ts:291
    at index.js:9
    at redux.js:449
    at handleAddLabel (TemplateCard.tsx:209)
    at handleCreateLabel (InlineLabelsEditor.tsx:243)
(anonymous) @ index.ts:296
(anonymous) @ index.js:9
(anonymous) @ redux.js:449
handleAddLabel @ TemplateCard.tsx:209
handleCreateLabel @ InlineLabelsEditor.tsx:243
async function (async)
handleCreateLabel @ InlineLabelsEditor.tsx:241
handleSubmit @ CreateLabelOverlay.tsx:98
onSubmit @ Form.tsx:67
(anonymous) @ react-dom.production.min.js:14
f @ react-dom.production.min.js:15
(anonymous) @ react-dom.production.min.js:15
S @ react-dom.production.min.js:17
C @ react-dom.production.min.js:18
T @ react-dom.production.min.js:18
L @ react-dom.production.min.js:21
xn @ react-dom.production.min.js:84
Es @ react-dom.production.min.js:250
je @ react-dom.production.min.js:39
Cn @ react-dom.production.min.js:86
(anonymous) @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ps @ react-dom.production.min.js:251
Mn @ react-dom.production.min.js:85
S.Object.isExtensible.Object.isExtensible.e.___hb.e.___hb @ honeybadger.js:466
```

### LINKED ISSUE #16643: Can't add a new label to a variable (cloud 2)
__Steps to reproduce:__
1. Go into the variables screen.
2. Select a variable, and click on + to create a new label.  
3. Create the label. 
4. The label will be created, but you'll get an error message "Failed to add label to variables".
5. Select the variable again, and select the label you just created, and now you will be able to add the label to the variable.

__Expected behavior:__
Should be able to create a new label and add it to the variable in one step.

__Actual behavior:__
Got an error message.

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #16643
Closes #15547

also a few more tickets we haven't even written yet. seems like all of the top level views in the files change list that didn't have an `await` before the `this.props.onCreateLabel` calls should be broken. ie:

- `ui/src/alerting/components/endpoints/EndpointCard.tsx`
- `ui/src/alerting/components/notifications/RuleCard.tsx`
- `ui/src/tasks/components/TaskCard.tsx`
- `ui/src/templates/components/TemplateCard.tsx`
- `ui/src/variables/components/VariableCard.tsx`

these roughly map to the interaction of putting a label on the resource

### CODE REVIEW

File: ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx [hunk 1]
```diff
@@ -1,5 +1,6 @@
 // Libraries
 import React, {Component, ChangeEvent, createRef} from 'react'
+import {connect} from 'react-redux'
```
Comment (121watts) [inline ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx]: yay!

File: ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx [hunk 2]
```diff
@@ -232,12 +241,11 @@ class InlineLabelsEditor extends Component<Props, State> {
...
+    const {name, properties} = label
 
-    try {
-      await onCreateLabel(label)
-      const newLabel = this.props.labels.find(l => l.name === label.name)
-      await onAddLabel(newLabel)
-    } catch (error) {}
+    await onCreateLabel(name, properties)
+    const newLabel = this.props.labels.find(l => l.name === label.name)
+    onAddLabel(newLabel)
```
Comment (121watts) [inline ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx]: more yay!

File: ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx [hunk 3]
```diff
@@ -27,13 +29,20 @@ export const ADD_NEW_LABEL_LABEL: Label = {
 
 import {ErrorHandling} from 'src/shared/decorators/errors'
 
-interface Props {
+interface DispatchProps {
+  onCreateLabel: typeof createLabel
+}
+
+interface StateProps {}
```
Comment (121watts) [inline ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx]: No need for empty state props

File: ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx [hunk 4]
```diff
@@ -256,4 +264,15 @@ class InlineLabelsEditor extends Component<Props, State> {
   }
 }
 
-export default InlineLabelsEditor
+const mstp = (): StateProps => {
+  return {}
+}
```
Comment (121watts) [inline ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx]: You can delete this

File: ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx [hunk 5]
```diff
@@ -256,4 +264,15 @@ class InlineLabelsEditor extends Component<Props, State> {
...
+
+const mdtp: DispatchProps = {
+  onCreateLabel: createLabel,
+}
+
+export default connect<StateProps, DispatchProps, OwnProps>(
+  mstp,
```
Comment (121watts) [inline ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx]: This can just be `null`
