### PR TITLE
Avoid a panic when using show diagnostics with text/csv

### LINKED ISSUE #9504: Panic when running SHOW DIAGNOSTICS with text/csv
### Bug report

__System info:__ InfluxDB 1.5 and likely older

__Steps to reproduce:__

```
$ curl -G 'http://localhost:8086/query' -H 'Accept: text/csv' --data-urlencode 'q=SHOW DIAGNOSTICS'
```

__Expected behavior:__ It likely shouldn't panic.

__Actual behavior:__ It does panic.

__Additional info:__ This is likely because `SHOW DIAGNOSTICS` is weird. It is the only command that changes which columns exist in the row within the same statement, which is pretty weird. Most queries use the same columns for the entire statement, but this command doesn't.

### PR DESCRIPTION
**Pull request by jsternberg**
If the columns change between series, it will now act as if it was a new
statement id and reprint the headers. This only happens with show
diagnostics at the moment and we shouldn't add this functionality
anywhere else anyway.

Fixes #9504.

### CODE REVIEW

File: services/httpd/response_writer.go [hunk 1]
```diff
@@ -147,7 +148,29 @@ func (w *csvFormatter) WriteResponse(resp Response) (n int, err error) {
 			}
 		}
 
-		for _, row := range result.Series {
+		for i, row := range result.Series {
+			if i > 0 && !reflect.DeepEqual(result.Series[i-1].Columns, row.Columns) {
```
Comment (mark-rushakoff) [inline services/httpd/response_writer.go]: Since these are both string slices, can you make a helper method to compare them instead of using reflect?

File: services/httpd/response_writer.go [hunk 2]
```diff
@@ -147,7 +148,29 @@ func (w *csvFormatter) WriteResponse(resp Response) (n int, err error) {
...
+					return n, err
+				}
+				n += out
+
+				w.columns = make([]string, 2+len(row.Columns))
+				w.columns[0] = "name"
+				w.columns[1] = "tags"
+				copy(w.columns[2:], row.Columns)
+				if err := csv.Write(w.columns); err != nil {
+					return n, err
```
Comment (mark-rushakoff) [inline services/httpd/response_writer.go]: The `n` tracking is missing most of the csv calls - it's unfortunate that the csv.Writer doesn't expose the bytes written.

Assuming we do want to track `n` (for the QueryRequestBytesTransmitted stat), what do you think about using io.MultiWriter with the underlying `w` and some fake writer like

```go
type countWriter struct { n int64 }
func (w *countWriter) Write(p []byte) (int, err) {
  w.n += len(p)
  return len(p), nil
}
```

so that we can properly track `n`?

Comment (jsternberg) [reply services/httpd/response_writer.go]: That would be good. Can we open up another PR for that though? The behavior is already broken and I'm not breaking it anymore than it previously was.

File: services/httpd/response_writer.go (hunk 1 above)
Comment (jsternberg) [reply services/httpd/response_writer.go]: Sure.

File: services/httpd/response_writer.go (hunk 2 above)
Comment (mark-rushakoff) [reply services/httpd/response_writer.go]: Sure thing - opened https://github.com/influxdata/influxdb/issues/9690 to track it.
