### PR TITLE
fix(ui/variables): filter vars with prefix names

### LINKED ISSUE #12939: Exported variable template should contain all variables that are in the dependency tree
Variable queries can contain other variables. So an exported variable template must include all other variables in the dependency tree. 

https://github.com/influxdata/influxdb/blob/df8a0d0ddd70a2ec3b3ec46ab1303a113998d4d0/ui/src/variables/utils/hydrateVars.ts#L57-L60 
^^ searches all variables to find those that are in variable query.

### PR DESCRIPTION
**Pull request by OfTheDelmer**
Closes #12939 
Closes https://github.com/influxdata/influxdb/issues/13090

_Briefly describe your proposed changes:_
Match exported and dashboard var names up to a word boundary so var names like `v.be` don't display as dependent vars of `v.before` 

Also updates the variable exports util to use this word boundary filter to find all dependent vars in the variable graph resolving #13090 

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [ ] Rebased/mergeable
  - [ ] Tests pass
  - [ ] http/swagger.yml updated (if modified Go structs or API)
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/variables/utils/hydrateVars.ts [hunk 1]
```diff
@@ -212,16 +227,24 @@ const constVariableValues = (
...
+
+  // reduce children
   for (const child of node.children) {
-    acc.push(child)
-    collectDescendants(child)
+    if (visited.has(child)) {
+      continue
+    }
+    visited.add(child)
+    descendants = descendants.concat(child, collectDescendants(child, visited))
```
Comment (chnn) [inline ui/src/variables/utils/hydrateVars.ts]: I feel like keeping track of two accumulators (`children`, `visited`) is pretty confusing... could this work like the `collectAncestors` method instead?

```
const collectDescendents = (
  node: VariableNode,
  acc = new Set()
): VariableNode[] => {
  for (const child of node.children) {
    if (!acc.has(child)) {
      acc.add(child)
      collectAncestors(child, acc)
    }
  }

  return [...acc]
}
```

File: ui/src/variables/constants/index.ts [hunk 2]
```diff
@@ -2,3 +2,70 @@ export const OPTION_NAME = 'v'
 export const TIME_RANGE_START = 'timeRangeStart'
 export const TIME_RANGE_STOP = 'timeRangeStop'
 export const WINDOW_PERIOD = 'windowPeriod'
+
+enum FluxBoundaries {
```
Comment (chnn) [inline ui/src/variables/constants/index.ts]: Does this need to be a enum?

File: ui/src/variables/utils/hydrateVars.test.ts [hunk 3]
```diff
@@ -41,16 +41,64 @@ class FakeFetcher implements ValueFetcher {
...
+      const vars = [a, b, c, d, e, f, g, h]
 
       const actual = exportVariables([a], vars)
+      const expected = new Set([a, b, c, e, f, g])
 
-      expect(actual).toEqual([a, b, c])
+      expect(new Set(actual)).toEqual(expected)
+    })
+
+    const examples = [
```
Comment (chnn) [inline ui/src/variables/utils/hydrateVars.test.ts]: beautiful

File: ui/src/variables/utils/hydrateVars.ts [hunk 4]
```diff
@@ -35,25 +35,26 @@ interface HydrateVarsOptions {
...
-  allVariables: Variable[]
+  varGraph: VariableNode[]
 ): Variable[] => {
-  const query: string = variable.arguments.values.query
-  const dependencies = allVariables.filter(maybeChild =>
-    query.includes(`${OPTION_NAME}.${maybeChild.name}`)
-  )
-
-  return dependencies
+  const node = varGraph.find(n => n.variable.id === variable.id)
```
Comment (chnn) [inline ui/src/variables/utils/hydrateVars.ts]: Do you think you could move the export specific stuff to a separate utility module? `findDependentVariables` and `exportVariables`

Just because the `hydrateVars` module is so gnarly as is, I want to keep it as focused as possible

File: ui/src/variables/constants/index.ts (hunk 2 above)
Comment (OfTheDelmer) [reply ui/src/variables/constants/index.ts]: ahh true it could just be be vars

File: ui/src/variables/utils/hydrateVars.ts (hunk 4 above)
Comment (OfTheDelmer) [reply ui/src/variables/utils/hydrateVars.ts]: was thinking that before that last commit. Will do.

File: ui/src/variables/utils/hydrateVars.ts (hunk 1 above)
Comment (OfTheDelmer) [reply ui/src/variables/utils/hydrateVars.ts]: works for me.

File: ui/src/variables/utils/exportVariables.test.ts [hunk 5]
```diff
@@ -0,0 +1,65 @@
+import {exportVariables} from 'src/variables/utils/exportVariables'
+// Mocks
+import {createVariable} from 'src/variables/mocks'
+
+describe('exportVariables', () => {
+  test('should find dependent variables', () => {
```
Comment (121watts) [inline ui/src/variables/utils/exportVariables.test.ts]: `it`

File: ui/src/variables/utils/exportVariables.test.ts [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+  examples.forEach(example => {
+    test(`should filter vars with shared prefix: ${example.name}`, () => {
+      const target = createVariable('target', 'match me!')
+      const partial = createVariable('tar', 'broke!')
+      const vars = [example, target, partial]
+
+      const actual = exportVariables([example], vars)
+
+      expect(actual).toEqual([example, target])
+    })
```
Comment (121watts) [inline ui/src/variables/utils/exportVariables.test.ts]: nice!
