### PR TITLE
fix: enforce bounds on query-related CLI/config parameters to avoid startup panics

### LINKED ISSUE #20144: Panic when setting --query-concurrency to large value
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run `influxd --query-concurrency 9223372036854775807`

__Expected behavior:__
Either the program runs successfully, or the CLI errors out telling me the number is too big.

__Actual behavior:__
```
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc0018362d0, 0x7fffffffffffffff)
        /Users/dan/.gvm/gos/go1.15/src/sync/waitgroup.go:74 +0x147
github.com/influxdata/influxdb/v2/query/control.New(0x7fffffffffffffff, 0x0, 0x7fffffffffffffff, 0x0, 0xa, 0xc00169a480, 0x0, 0x0, 0x0, 0xc001562f90, ...)
        /Users/dan/influxdb/query/control/controller.go:189 +0x7f5
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).run(0xc0005b0e00, 0x760eb80, 0xc00055d480, 0x0, 0x0)
        /Users/dan/influxdb/cmd/influxd/launcher/launcher.go:901 +0x3a38
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.cmdRunE.func1(0x0, 0x0)
        /Users/dan/influxdb/cmd/influxd/launcher/launcher.go:149 +0x14c
github.com/influxdata/influxdb/v2/kit/cli.NewCommand.func1(0xc000130b00, 0xc000ce90e0, 0x0, 0x2, 0x0, 0x0)
        /Users/dan/influxdb/kit/cli/viper.go:62 +0x29
github.com/spf13/cobra.(*Command).execute(0xc000130b00, 0xc000184190, 0x2, 0x2, 0xc000130b00, 0xc000184190)
        /Users/dan/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000130b00, 0xc000d9ff48, 0x1, 0x1)
        /Users/dan/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/dan/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /Users/dan/influxdb/cmd/influxd/main.go:41 +0x31c
```
This is apparently a known problem in Go's `WaitGroup` impl: https://github.com/golang/go/issues/20687

__Environment info:__
InfluxDB OSS 2.0.2

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #20144 

`math.MaxInt32` is the biggest value that the `WaitGroup` wrapped in the query controller will accept without panicking. When I try running `influxd` with that parameter it takes a loooooong time to boot up, but I assume it'd be faster on a beefed-up VM.

### CODE REVIEW

File: query/control/controller.go [hunk 1]
```diff
@@ -121,6 +128,9 @@ func (c *Config) validate(isComplete bool) error {
 	if c.ConcurrencyQuota <= 0 {
 		return errors.New("ConcurrencyQuota must be positive")
 	}
+	if c.ConcurrencyQuota > MaxQueryConcurrency {
```
Comment (davidby-influx) [inline query/control/controller.go:131]: Should we define ConcurrencyQuota as an int64 in the struct? I realize that `int` is 64 bits on our target architectures, but the additional clarity couldn't hurt.

File: query/control/controller_test.go [hunk 2]
```diff
@@ -122,6 +122,15 @@ func validateUnusedMemory(t testing.TB, reg *prometheus.Registry, c control.Conf
 	}
 }
 
+func TestConfig_ValidateMaxConcurrencyQuota(t *testing.T) {
+	config.ConcurrencyQuota = control.MaxQueryConcurrency + 1
```
Comment (davidby-influx) [inline query/control/controller_test.go:127]: My Golang ignorance - does this correctly cast MazQueryConcurrency to an int64 before the addition, and void a wrap-around?

**Review by davidby-influx — APPROVED** [review]
You can proceed without my issues if you think they are not useful.  Won't block the commit for these minor nits.

File: query/control/controller.go (hunk 1 above)
Comment (danxmoran) [reply query/control/controller.go:131]: `int32` is what we'd want/need to use, but I'm a fan of the general idea... it might get us some extra validation "for free" too, if the CLI parser is smart about detecting overflows. I'll give it a try in the morning.

File: query/control/controller_test.go (hunk 2 above)
Comment (danxmoran) [reply query/control/controller_test.go:127]: Once I changed the type of `ConcurrencyQuota` to `int32`:
1. This still compiled fine
2. Running the test resulted in immediate failure, with an overflow error

File: query/control/controller.go (hunk 1 above)
Comment (danxmoran) [reply query/control/controller.go:131]: Using `int32` does give us some validation at the CLI layer. I'll keep heading down this path.

File: CHANGELOG.md [hunk 3]
```diff
@@ -34,7 +36,6 @@ want to use the default.
 1. [20053](https://github.com/influxdata/influxdb/pull/20053): Upgrade Flux to v0.95.0.
 1. [20058](https://github.com/influxdata/influxdb/pull/20058): UI: Upgrade flux-lsp-browser to v0.5.23.
 1. [20067](https://github.com/influxdata/influxdb/pull/20067): Add DBRP cli commands as `influxd v1 dbrp`.
-1. [20097](https://github.com/influxdata/influxdb/pull/20097): Ensure Index.Walk fetches matching foreign keys only.
```
Comment (danxmoran) [inline CHANGELOG.md:37]: Accidentally filed under the wrong release

**Review by davidby-influx — APPROVED** [review]
Looks much safer. Comments are outstanding!
