### PR TITLE
fix: regenerate protos using gogo 1.3.2

### LINKED ISSUE #21504: Intermittent failure in `cross_build` CI job
Our `cross_build` CI job intermittently fails with an error like:
```
exec /tmp/go-build791299071/b001/exe/tmpl: no such file or directory
```

An example job is [here](https://app.circleci.com/pipelines/github/influxdata/influxdb/20625/workflows/86279b1b-9bb4-4186-96a6-94f78009747a/jobs/190833). The error (so far) always resolves itself on a re-run.

### PR DESCRIPTION
**Pull request by danxmoran**
`protoc-gen-gogo` was already at `v1.3.2` in the `go.mod`, but we hadn't re-generated after upgrading it. To upgrade I did:
```
go install github.com/gogo/protobuf/protoc-gen-gogo
go install github.com/gogo/protobuf/protoc-gen-gogofaster
go generate ./...
```

Closes #21504

Closes the above because it removes the use of `tmpl` from the `build` and `cross_build` jobs, so we shouldn't see those intermittent failures any more.

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -112,7 +112,19 @@ checktidy:
...
-generate: $(SUBDIRS)
+generate: gogo $(SUBDIRS)
+	$(GO_GENERATE) \
+		./v1/services/meta \
+		./v1/services/storage \
+		./tsdb \
+		./chronograf/bolt/internal \
+		./storage/reads/datatypes \
+		./influxql/query \
+		./pkg/tracing/wire
```
Comment (danxmoran) [inline Makefile:123]: A blanket `go generate ./...` hits errors because of something in `chronograf/dist`... instead of enumerating these here & having to remember to update / add to them, is there a way to say "all modules except for `X`" when passing to `go generate`?

Comment (danxmoran) [reply Makefile:123]: Nevermind, found it! Edit incoming...

File: Makefile [hunk 2]
```diff
@@ -112,7 +112,13 @@ checktidy:
 checkgenerate:
 	./etc/checkgenerate.sh
 
-generate: $(SUBDIRS)
+generate: gogo $(SUBDIRS)
+	# FIXME: chronograf/dist fails `go generate` because of something to do with the UI.
+	$(GO_GENERATE) $(shell go list ./... | grep -v chronograf/dist)
```
Comment (danxmoran) [inline Makefile:117]: Opened #21881 to delete the broken code, it's unused

File: Makefile [hunk 3]
```diff
@@ -112,7 +112,21 @@ checktidy:
 checkgenerate:
 	./etc/checkgenerate.sh
 
-generate: $(SUBDIRS)
+generate: gogo tmpl stringer goimports $(SUBDIRS)
+	$(GO_GENERATE) ./...
+
+gogo:
+	go build -o $(GOPATH)/bin/ github.com/gogo/protobuf/protoc-gen-gogo
```
Comment (lesam) [inline Makefile:119]: Is this better than `go install` ?

Comment (danxmoran) [reply Makefile:119]: Nope, can switch it

File: scripts/fetch-ui-assets.sh [hunk 4]
```diff
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
```
Comment (lesam) [inline scripts/fetch-ui-assets.sh:1]: nitpick: If we know where bash lives (i.e. if this is only for CI) I'd prefer to enforce it rather than using `/usr/bin/env`

**Comment by lesam** [comment]
Looks good other than asking for some comments to clarify the special handling for the UI embedding codegen

File: scripts/fetch-ui-assets.sh (hunk 4 above)
Comment (danxmoran) [reply scripts/fetch-ui-assets.sh:1]: It's also used for local development, to build the server w/ a bundled UI

**Review by lesam — APPROVED** [review]
