### PR TITLE
fix: pass variables into a function

### LINKED ISSUE #16290: Cloud 2.0 GCP: InfluxDB Output plugin download does not match what is in UI
Environment: Cloud 2.0 GCP staging environment
Issue: The information that is displayed on the screen when you hit `InfluxDB Output Plugin` button on `Telegraf Configuration` page is correctly populated with `Organization` and `Bucket`, but when you hit `Download Config` button, it does not seem to download what is shown on screen and therefore the `Organization` and `Bucket` are not the correct entries in the downloaded configuration file. (See attached screenshot)
image

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #16290

just looks like the template function wasn't being passed variables. also took time to normalize some internal state while rummaging around in there.

### CODE REVIEW

File: ui/src/telegrafs/components/TelegrafOutputOverlay.tsx [hunk 1]
```diff
@@ -144,9 +158,15 @@ class TelegrafOutputOverlay extends PureComponent<Props> {
   }
 
   private handleDownloadConfig = () => {
+    const {server, org} = this.props
+    const bucket = this.currentBucket
     const config = transform(
       TELEGRAF_OUTPUT,
-      Object.assign({}, OUTPUT_DEFAULTS, {})
+      Object.assign({}, OUTPUT_DEFAULTS, {
+          server,
```
Comment (drdelambre) [inline ui/src/telegrafs/components/TelegrafOutputOverlay.tsx]: this is the actual magic

File: ui/src/telegrafs/components/TelegrafOutputOverlay.tsx [hunk 2]
```diff
@@ -144,9 +158,15 @@ class TelegrafOutputOverlay extends PureComponent<Props> {
   }
 
   private handleDownloadConfig = () => {
+    const {server, org} = this.props
+    const bucket = this.currentBucket
     const config = transform(
       TELEGRAF_OUTPUT,
-      Object.assign({}, OUTPUT_DEFAULTS, {})
+      Object.assign({}, OUTPUT_DEFAULTS, {
```
Comment (hoorayimhelping) [inline ui/src/telegrafs/components/TelegrafOutputOverlay.tsx]: interesting that this isn't being destructured, might be worth considering when thinking about patterns @ebb-tide.

also, it looks like there's an extra space in indentation below, i think you'll need to run `prettier:fix`

Comment (drdelambre) [reply ui/src/telegrafs/components/TelegrafOutputOverlay.tsx]: i dont understand
