### PR TITLE
Fix write path lock contention

### LINKED ISSUE #6131: Performance degradation on influx 0.11 and memory saturation on high volume.
We are conducting stress test with influxdb 0.10 and 0.11 based TSM engine.
When we start to test on influx db 0.10, we can write 200,000 points per sec. But when we change to influxdb 0.11 on same machine, the result is too different, writing 50,000 points per sec. It looks like to similar influx db 0.8 performance.

To find the number of points per sec, we used _internal database.
https://docs.influxdata.com/influxdb/v0.10/troubleshooting/statistics/.

Is there any write performance issue on influx 0.11 ?

H/W spec is 1 CPU (ES 2620 v3, hex core), 32M/M, 4 x SSD(500M). Our goal is to write 10,000,000 ~ 15,000,000 points every 5 minutes based on 100,000 measurements (no tag, 5 values).

Our test scripts is like this. It is to generate many points on multiple clients 
for (i = 0; i < 20; i++)
 ./wrk -t1 -c1 -d30 -s influx_test.lua &

wrk is HTTP benchmarking tool. https://github.com/wg/wrk

influx_test.lua is to write batch job(1000 point per 1 batch) into influx db.

Another issue is memory saturation during stress test. To mitigate memory saturation, we've changed cache-max-memory-size (2.5G) and awl-flush-cold-interval(1m) on influx 0.10. But the issue is still remained.
Could you give more tips to solve memory issue ?

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

This fixes two performance regressions in the write path.
* #5816 introduced a locking issue when creating a new statistics for a measurement.  #6131 had a script that creates 100k measurements that reproduces the issue.  This PR reverts the measurement statistics added in #5816.  If we need to track them, we'll need to find a different way to do it.  A side-effect of removing this is that shards load much faster now.
* #5372 introduced an index write lock issue when adding a shard to a series in the in-memory index.   Running the script from #6131 showed this lock contention.  This PR moves the lock to the series to avoid locking the whole index.

cc @mark-rushakoff 

Fixes #6131

### CODE REVIEW

**Comment by mark-rushakoff** [comment]
Good profiling work here. We'll be fine for now without those stats. Choosing those speedups over the stats is a no-brainer.

File: tsdb/meta.go [hunk 1]
```diff
@@ -1311,6 +1291,7 @@ func (a Measurements) union(other Measurements) Measurements {
 
 // Series belong to a Measurement and represent unique time series in a database
 type Series struct {
+	mu   sync.RWMutex
```
Comment (e-dard) [inline tsdb/meta.go]: Can you move `shardIDs` to under `mu` since it's now being protected by `mu`?

**Comment by e-dard** [comment]
Aside from moving location of `shardIDs` in struct LGTM :+1:

File: tsdb/meta.go (hunk 1 above)
Comment (jwilder) [inline tsdb/meta.go]: `mu` is protecting everything right now.

Comment (e-dard) [inline tsdb/meta.go]: Ah the space between `Tags` and `id` threw me. Can you close that up if `mu` is protecting everything?

File: tsdb/meta.go [hunk 2]
```diff
@@ -1360,11 +1349,16 @@ func (s *Series) UnmarshalBinary(buf []byte) error {
 
 // InitializeShards initializes the list of shards.
 func (s *Series) InitializeShards() {
+	s.mu.Lock()
+	defer s.mu.Unlock()
```
Comment (joelegasse) [inline tsdb/meta.go]: This doesn't need to be deferred, and can just be called directly after `s.shardIDs` is assigned.

File: tsdb/meta.go (hunk 1 above)
Comment (jwilder) [inline tsdb/meta.go]: Done

File: tsdb/meta.go [hunk 3]
```diff
@@ -1360,11 +1349,16 @@ func (s *Series) UnmarshalBinary(buf []byte) error {
...
 	s.shardIDs = make(map[uint64]bool)
 }
 
 // match returns true if all tags match the series' tags.
 func (s *Series) match(tags map[string]string) bool {
```
Comment (joelegasse) [inline tsdb/meta.go]: I can't find where this function is called, and since it's non-exported, we should just remove it.

Comment (jwilder) [inline tsdb/meta.go]: Done

File: tsdb/meta.go (hunk 2 above)
Comment (jwilder) [inline tsdb/meta.go]: Good point. Fixed.

**Comment by joelegasse** [comment]
Needs a rebase (changelog, I'm guessing), but otherwise looks good to me :+1:

File: tsdb/meta.go [hunk 4]
```diff
@@ -1329,11 +1309,16 @@ func NewSeries(key string, tags map[string]string) *Series {
 }
```
Comment (benbjohnson) [inline tsdb/meta.go]: Is there a lot of read contention on `Series.shardIDs`? If there's not then it would be more efficient to use a `sync.Mutex`.

Comment (jwilder) [inline tsdb/meta.go]: I'm going to leave this as a `sync.RWMutex` because I've had to change almost all of our uses of `sync.Mutex` to `sync.RWMutex` due to lock contention issues that appear under different workloads.
