### PR TITLE
fix: load dashboard before accessing

### LINKED ISSUE #17505: Save as Cell Reports Success but Fails
save-as-fail

Errors in console
```
2cellGetters.ts:88 Uncaught (in promise) TypeError: Cannot read property 'w' of undefined
    at cellGetters.ts:88
    at Array.map (<anonymous>)
    at cellGetters.ts:88
    at thunks.ts:104
    at Object.dispatch (index.js:8)
    at dispatch (<anonymous>:1:28545)
    at redux.js:449
    at SaveAsCellForm.tsx:197
    at Array.forEach (<anonymous>)
    at handleSubmit (SaveAsCellForm.tsx:188)
(anonymous) @ cellGetters.ts:88
(anonymous) @ cellGetters.ts:88
(anonymous) @ thunks.ts:104
(anonymous) @ index.js:8
dispatch @ VM1915:1
(anonymous) @ redux.js:449
(anonymous) @ SaveAsCellForm.tsx:197
handleSubmit @ SaveAsCellForm.tsx:188
s @ react-dom.production.min.js:14
f @ react-dom.production.min.js:15
(anonymous) @ react-dom.production.min.js:15
D @ react-dom.production.min.js:17
M @ react-dom.production.min.js:18
O @ react-dom.production.min.js:18
I @ react-dom.production.min.js:21
xn @ react-dom.production.min.js:84
As @ react-dom.production.min.js:250
je @ react-dom.production.min.js:39
Mn @ react-dom.production.min.js:86
(anonymous) @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Fs @ react-dom.production.min.js:251
Tn @ react-dom.production.min.js:85
Object.isExtensible.Object.isExtensible.e.___hb.e.___hb @ honeybadger.js:466
react_devtools_backend.js:6 TypeError: Cannot destructure property 'maxBuckets' of 'a.bucket' as it is null.
    at Proxy.<anonymous> (limits.ts:69)
    at e.value (immer.module.js:661)
    at xt (limits.ts:58)
    at redux.js:435
    at redux.js:435
    at p (<anonymous>:1:36402)
    at v (<anonymous>:1:36684)
    at <anonymous>:1:40069
    at Object.v [as dispatch] (redux.js:213)
    at e (<anonymous>:1:40553)
r @ react_devtools_backend.js:6
(anonymous) @ limits.ts:259
async function (async)
(anonymous) @ limits.ts:255
(anonymous) @ index.js:8
dispatch @ VM1915:1
(anonymous) @ redux.js:449
componentDidMount @ GetAssetLimits.tsx:34
Ya @ react-dom.production.min.js:216
Va @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ps @ react-dom.production.min.js:250
Ns @ react-dom.production.min.js:249
Es @ react-dom.production.min.js:248
Fs @ react-dom.production.min.js:251
Tn @ react-dom.production.min.js:85
Object.isExtensible.Object.isExtensible.e.___hb.e.___hb @ honeybadger.js:466
react-dom.production.min.js:13 Uncaught (in promise) Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://influxdb.aws.influxdata.io/static/2.68196a9332.js:2:3903266
    at a (https://influxdb.aws.influxdata.io/static/2.68196a9332.js:2:3903371)
    at es (https://influxdb.aws.influxdata.io/static/2.68196a9332.js:2:3998026)
    at Object.enqueueSetState (https://influxdb.aws.influxdata.io/static/2.68196a9332.js:2:3947600)
    at Te._.setState (https://influxdb.aws.influxdata.io/static/2.68196a9332.js:2:3897958)
    at https://influxdb.aws.influxdata.io/static/2.68196a9332.js:2:393371
    at new Promise (<anonymous>)
    at Te.next (https://influxdb.aws.influxdata.io/static/2.68196a9332.js:2:393342)
    at Te.componentDidUpdate (https://influxdb.aws.influxdata.io/static/2.68196a9332.js:2:394105)
    at Te.componentDidMount (https://influxdb.aws.influxdata.io/static/2.68196a9332.js:2:393482)
```

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #17505

while the dashboard was getting created, it wasn't being added to the local resources. the cell would then error when it tried to access the dashboard, as it didn't exist until a hard refresh

### CODE REVIEW

File: ui/src/authorizations/apis/index.ts [hunk 1]
```diff
@@ -20,7 +21,7 @@ export const createAuthorization = async (
 
 export const getAuth0Config = async (): Promise<Auth0Config> => {
   try {
-    const response = await fetch('/api/v2private/oauth/clientConfig')
+    const response = await fetch(`${getAPIBasepath()}/api/v2private/oauth/clientConfig`)
```
Comment (drdelambre) [inline ui/src/authorizations/apis/index.ts]: AJAX injects this by default, fetch does not, shouldn't have a v2private in the first place, needed to add this to get my dev env to work

File: ui/src/cells/actions/thunks.ts [hunk 2]
```diff
@@ -143,6 +143,17 @@ export const createDashboardWithView = (
       throw new Error(resp.data.message)
     }
 
+    const normDash = normalize<Dashboard, DashboardEntities, string>(
+      resp.data,
+      dashboardSchema
+    )
+
+    await dispatch(setDashboard(
```
Comment (drdelambre) [inline ui/src/cells/actions/thunks.ts]: here's the actual change.. everything else is just rampaging

File: ui/src/authorizations/apis/index.ts (hunk 1 above)
Comment (drdelambre) [reply ui/src/authorizations/apis/index.ts]: i think the longer term solution to this is being addressed as part of the larger "restructure the ui in 3 places problem" task coming this quarter, this was just a weird anomaly.

Comment (Asalem1) [reply ui/src/authorizations/apis/index.ts]: that's really strange since this was actually returning the correct data when toggled on acceptance. Would you mind elaborating about the defaults a bit?

Comment (drdelambre) [reply ui/src/authorizations/apis/index.ts]: sure! all of our cloud environments run with a default api prefix of `/`, but for oss, people need the ability to run the frontend under an arbitrary prefix. i run it under `/influx` or `/metrics` for my personal projects, as my introspection tooling isn't the application itself, but rides shotgun.

here's where it happens for ajax requests:
https://github.com/influxdata/influxdb/blob/master/ui/src/utils/ajax.ts#L6

and here's where it happens for the swagger defined endpoints:
https://github.com/influxdata/influxdb/blob/master/ui/src/client/index.ts#L10

i think it's an edgecase to add api requests outside of those two avenues, so we dont have to auto fill fetch or anything, and we dont do it perfectly everywhere (im looking at you webpack-dev-server), i'm just stoked to share the concept of prefixing your app so that you can embed frontends into larger url hierarchies without forcing their code to be linked.
