### PR TITLE
Fixes #5077

### LINKED ISSUE #5077: [0.9.6] CREATE DATABASE [...] new-rp-name  should throw error if NAME missing
As expected, when I create a new database, specify a new retention policy, and don't include a name for the new retention policy, the rp is called `default`:
```sh
> CREATE DATABASE santa WITH DURATION 3d REPLICATION 1
> SHOW RETENTION POLICIES ON santa
name	 duration	 replicaN	default
default	 72h0m0s     1		    true
```

Unexpectedly, when I do the same thing and include a name for the rp, the rp is still called `default`:
```sh
> DROP DATABASE santa
> CREATE DATABASE santa WITH DURATION 3d REPLICATION 1 presents
> SHOW RETENTION POLICIES ON santa
name	duration	replicaN	default
default	72h0m0s		1		    true
```

### PR DESCRIPTION
**Pull request by pires**
Throw an error if NAME is not provided when creating a database with retention, but something else is.

- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign CLA (if not already signed)

Fixes #5077

### CODE REVIEW

File: influxql/parser_test.go [hunk 1]
```diff
@@ -1717,10 +1717,13 @@ func TestParser_ParseStatement(t *testing.T) {
 		{s: `DROP FOO`, err: `found FOO, expected SERIES, CONTINUOUS, MEASUREMENT, SERVER, SUBSCRIPTION at line 1, char 6`},
 		{s: `CREATE FOO`, err: `found FOO, expected CONTINUOUS, DATABASE, USER, RETENTION, SUBSCRIPTION at line 1, char 8`},
 		{s: `CREATE DATABASE`, err: `found EOF, expected identifier at line 1, char 17`},
+		{s: `CREATE DATABASE "testdb" "db2"`, err: `found db2, expected EOF at line 1, char 26`},
 		{s: `CREATE DATABASE "testdb" WITH`, err: `found EOF, expected DURATION, REPLICATION, NAME at line 1, char 31`},
 		{s: `CREATE DATABASE "testdb" WITH DURATION`, err: `found EOF, expected duration at line 1, char 40`},
 		{s: `CREATE DATABASE "testdb" WITH REPLICATION`, err: `found EOF, expected number at line 1, char 43`},
 		{s: `CREATE DATABASE "testdb" WITH NAME`, err: `found EOF, expected identifier at line 1, char 36`},
+		{s: `CREATE DATABASE "testdb" WITH DURATION 24h REPLICATION 1 "db2"`, err: `found db2, expected NAME at line 1, char 58`},
+		{s: `CREATE DATABASE "testdb" WITH DURATION 24h REPLICATION 1 NAME "testrpi" "db2"`, err: `found db2, expected EOF at line 1, char 73`},
```
Comment (otoolep) [inline influxql/parser_test.go]: Can we have some tests that don't quote the names?

Comment (pires) [inline influxql/parser_test.go]: Sure!

Comment (otoolep) [inline influxql/parser_test.go]: Thanks @pires -- quoting handles some edge cases in our code, and I want to make sure it doesn't confuse anything.

Comment (pires) [inline influxql/parser_test.go]: @otoolep done.

**Comment by otoolep** [comment]
+1, thanks @pires 

@corylanou @dgnorton ?

**Comment by dgnorton** [comment]
@pires it's a little confusing but the way this is handled is that each statement parsing method only parses the tokens it needs and leaves everything after it.  In the example you gave with `REPLICATION 1 presents`, The bug is that `parseCreateDatabase` checks for the `NAME` token and doesn't `p.unscan()` when the token is anything other than `NAME`.  It should put the token back in the stream and let the outer parsing loop handle it.  Should look like...
```
// Look for "NAME"
var rpName string = "default" // default is default
if err := p.parseTokens([]Token{NAME}); err == nil {
   rpName, err = p.parseIdent()
   if err != nil {
      return nil, err
   }
} else {
   p.unscan()
}
```

**Comment by pires** [comment]
@dgnorton @jsternberg you are right regarding `p.unscan()`. I will fix this over the next couple days. Thank you!

**Comment by pires** [comment]
@dgnorton @jsternberg so I push-forced a single commit. This is enough, right?

**Comment by dgnorton** [comment]
@pires  that should fix it.  Thanks!

+1 once the tests pass

**Comment by jsternberg** [comment]
Perfect @pires!

Can you update the changelog with your contribution and the issue it fixes?

**Comment by pires** [comment]
Thank you all for helping with this!

@jsternberg done.

**Comment by jsternberg** [comment]
@pires you should give yourself credit in the changelog.

Can you also squash them into a single commit? Thanks.

**Comment by pires** [comment]
@jsternberg done! :joy:

**Comment by jsternberg** [comment]
+1 I'll merge when the tests finish running.
