### PR TITLE
fix(kit/cli): don't ignore failures to mark CLI options as required

### LINKED ISSUE #20394: CLI helpers silently fail to mark options as required
We set the required marker before we register the corresponding flag, and don't check for an error.

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #20394 

We can only mark a flag as required after it's been registered in the `cobra.Command`.

### CODE REVIEW

File: kit/cli/viper.go [hunk 1]
```diff
@@ -272,9 +299,13 @@ func BindOptions(v *viper.Viper, cmd *cobra.Command, opts []Opt) {
 			} else {
 				IDVar(flagset, destP, o.Flag, d, o.Desc)
 			}
-			if s := v.GetString(envVar); s != "" {
-				_ = (*destP).DecodeFromString(v.GetString(envVar))
+			mustBindPFlag(v, o.Flag, flagset)
```
Comment (lesam) [inline kit/cli/viper.go:302]: Why are we adding mustBindPFlag here (what does this change?)

Comment (danxmoran) [reply kit/cli/viper.go:302]: This makes flags of these types get bound to viper, same as all the others. Right now flags of type `influxdb.ID` and `zapcore.Level` are being left out for no good reason.

I can revert this addition though, because one of the follow-up PRs is going to change the logic across the board for when flags are bound to viper.

**Review by lesam — APPROVED** [review]
lgtm
