### PR TITLE
fix(alerting): disable save button if query is invalid

### LINKED ISSUE #14894: Disable saving on checks when the query for a check is invalid

### PR DESCRIPTION
**Pull request by 121watts**
Closes #14894 
Kapture 2019-09-09 at 12 16 24

### Note
I will update the e2e tests to only run once for each test.

### CODE REVIEW

File: ui/cypress/support/commands.ts [hunk 1]
```diff
@@ -305,25 +305,14 @@ export const flush = () => {
...
 
 export const writeData = (
-  lines: string[],
-  chunkSize: number = 100
+  lines: string[]
 ): Cypress.Chainable<Cypress.Response> => {
   return cy.fixture('user').then(({org, bucket}) => {
-    let chunk: string[]
-    let chunkCt: number = 0
-    while (chunkCt < lines.length) {
```
Comment (chnn) [inline ui/cypress/support/commands.ts]: what in tarnation...

File: ui/src/alerting/components/CheckEOHeader.tsx [hunk 2]
```diff
@@ -47,10 +79,17 @@ const CheckEOHeader: FC<Props> = ({name, onSetName, onCancel, onSave}) => {
     }
   }
 
-  const saveButtonStatus =
-    saveStatus === RemoteDataState.Loading
-      ? ComponentStatus.Loading
-      : ComponentStatus.Default
+  const saveButtonStatus = () => {
```
Comment (chnn) [inline ui/src/alerting/components/CheckEOHeader.tsx]: how come this is a function?

File: ui/src/timeMachine/utils/queryBuilder.ts [hunk 3]
```diff
@@ -46,6 +46,18 @@ export const isDraftQueryAlertable = (
   }
 }
 
+export const isCheckSaveable = (
```
Comment (alexpaxton) [inline ui/src/timeMachine/utils/queryBuilder.ts]: =D

File: ui/src/alerting/components/CheckEOHeader.tsx [hunk 4]
```diff
@@ -64,7 +103,11 @@ const CheckEOHeader: FC<Props> = ({name, onSetName, onCancel, onSave}) => {
         />
       </Page.Header.Left>
       <Page.Header.Center widthPixels={300}>
-        <CheckAlertingButton />
+        <CheckAlertingButton
```
Comment (chnn) [inline ui/src/alerting/components/CheckEOHeader.tsx]: What was your motivation for disconnecting it from Redux? We've moved this button around a bunch and it was nice to not worry about reconnecting the right props every time. I bet we'll end up moving it again since I think it makes more sense to be closer to the query/alert builder, which is the part of the UI that changes when you click it.

File: ui/src/alerting/components/CheckEOHeader.tsx (hunk 2 above)
Comment (121watts) [reply ui/src/alerting/components/CheckEOHeader.tsx]: I think it reads much nicer as a function.

File: ui/src/alerting/components/CheckEOHeader.tsx (hunk 4 above)
Comment (121watts) [reply ui/src/alerting/components/CheckEOHeader.tsx]: Two sibling both required `draftQueries` to make independent display decisions.  Rather than connect two  children to redux, I decided to pull the state up to their shared parent and pass props down one level.  Mayhaps I'll regret this decision.
