### PR TITLE
Fix Issue#6042, #6030 CreateDatabase failure on Windows

### LINKED ISSUE #6042: InfluxDB 0.11.0 RC breaks windows completely
Up until last week master branch was compatible with windows (e.g. PR #5999), but now 0.11.0RC breaks basic `create database` itself, and is not compatible with Windows. Going by #5359 you are still [committed to providing windows support by 0.11 ](https://github.com/influxdata/influxdb/issues/5359#issuecomment-183142936)), and this is back pedaling.

```go
[monitor] 2016/03/17 08:11:04 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:04 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:14 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:14 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:24 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:24 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:34 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:34 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:44 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:44 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:54 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:54 failed to store statistics: database not found: _internal
```

image

### PR DESCRIPTION
**Pull request by mvadu**
- [x] CHANGELOG.md updated
- [X] Rebased/mergable
- [X] Tests pass
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Commit [27cfaa4](https://github.com/influxdata/influxdb/commit/27cfaa4b7a517364556cdd1a7225cab513784bc6#diff-1ab852c12e0bcdadffcaabf579a32345)  introduced a regression in `meta/client.go`, which made `CreateDatabase` calls to fail on windows. Root cause is the `[os.Rename](https://github.com/influxdata/influxdb/blob/27cfaa4b7a517364556cdd1a7225cab513784bc6/services/meta/client.go#L898)` in `func (c *Client) Snapshot()`. In Windows this fails when the file already exists. Fix is to remove the old file, and store the new file.

Fixes #6042, #6030

### CODE REVIEW

**Comment by mvadu** [comment]
@jsternberg @jwilder attempt#2. I closed previous PR#6043 and resubmitted this one with proper author info. I also moved the snapshot function to a separate file, and provided a OS specific override. Since we now have ARM release, I am not sure if it needs another file. It compiled and ran on my raspberry pi2 without any issues.

File: services/meta/client.go [hunk 1]
```diff
@@ -957,35 +957,6 @@ func (c *Client) updateAuthCache() {
...
-
-	if _, err := f.Write(d); err != nil {
-		return err
-	}
-
-	if err = f.Close(); nil != err {
-		return err
-	}
-
-	return os.Rename(tmpFile, file)
```
Comment (jsternberg) [inline services/meta/client.go]: Instead of copying the entire function, can you just make a private function `renameFile` so only that part of the code has to be in a separate file? I think this change will not work on Mac OS X because the function will only exist on Linux or Windows. I think renaming that file to something like `file_unix.go` works correctly.

Comment (mvadu) [inline services/meta/client.go]: @jsternberg I tried that, `_unix.go` is not standard GOOS constant. (refer to https://github.com/golang/go/tree/master/src/runtime/internal/sys, look at the zgoos family of files). With `_unix.go` it does compile on Linux, but fails on windows
```go
# github.com/influxdata/influxdb/services/meta
services\meta\sysrename_windows.go:8: sysrename redeclared in this block
        previous declaration at services\meta\sysrename_unix.go:8
```

Comment (jsternberg) [inline services/meta/client.go]: Include the conditional compilation flags like as it was done here: https://github.com/influxdata/influxdb/blob/master/tsdb/engine/tsm1/file_unix.go

This is also where I'm getting the naming standard from. So there's consistency between these files (as this file is also used for a similar reason to your issue), please use the basename `file` so there will be a `file_windows.go` and a `file_unix.go` and include the conditional compilation headers at the beginning. That should work.

Comment (mvadu) [inline services/meta/client.go]: Yup, I arrived at the same thing from a [different source](http://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool). I have it named as `_windows.go` and `_others.go`. will that do?

Comment (jsternberg) [inline services/meta/client.go]: I think using `_unix.go` is better since another part of the codebase uses that. More consistency in the codebase is always a good thing.

Comment (mvadu) [inline services/meta/client.go]: sure, pushing it now..

**Comment by mvadu** [comment]
as per @jsternberg suggestion, moved only rename part to be platform specific, and covered windows vs non windows, all platforms should be good.

File: services/meta/renameFile_unix.go [hunk 2]
```diff
@@ -0,0 +1,12 @@
+// +build !windows
+
+package meta
+
+import (
+	"os"
+)
+
+// rename the source to target using os function
```
Comment (jsternberg) [inline services/meta/renameFile_unix.go]: The first string of the docstring comment should match the name of the function.

File: services/meta/renameFile_unix.go [hunk 3]
```diff
@@ -0,0 +1,12 @@
+// +build !windows
+
+package meta
+
+import (
```
Comment (jsternberg) [inline services/meta/renameFile_unix.go]: Please use [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) for formatting files. `goimports` produces this output for only a single import statement.

```
import "os"
```

**Comment by jsternberg** [comment]
Can you rename `renameFile_unix.go` to `file_unix.go`? The same with `renameFile_windows.go` to `file_windows.go`.

**Comment by mvadu** [comment]
You want me to just rename the files or the function as well?

**Comment by jsternberg** [comment]
Just the file and please squash your commits so it's only one commit.

**Comment by mvadu** [comment]
@jsternberg Done!! because of you I learnt a lot of new git commands.. Thank you! Hope everything is good now.

**Comment by jsternberg** [comment]
@mvadu did you find this bug from master or when running against the 0.11 release candidate? I'm unable to cherry pick it to the 0.11 branch due to a conflict.

I need to know so I can make sure this bugfix gets into 0.11 if the problem happens in 0.11.

**Comment by mvadu** [comment]
The bug (renaming in snapshot method, and whole snapshot method were part of Commit 27cfaa4). I have given the link to that commit in my PR comment.

**Comment by jsternberg** [comment]
Ah, it looks like that commit was made after we branched off for 0.11, so it shouldn't exist in the 0.11 release candidate or 0.11. I'll make sure to modify the changelog appropriately.

**Comment by mvadu** [comment]
Oh!! so for 0.11 RC branch, #5999 should be merged, so that on Windows we can run without any modifications to config. Let me know if you want to consider it, and I will resubmit.

**Comment by mvadu** [comment]
I submitted #6056 against 0.11 branch for one open issue in Windows. Merging that will allow 0.11 version to run fresh out of build.

**Comment by jsternberg** [comment]
@mvadu since we're about to release 0.11 and Windows isn't officially supported in that release, I think it would be best to just try running off of master if you want to use InfluxDB on Windows. If you find any other issues with compiling and using InfluxDB on Windows, please open an issue and we appreciate pull requests that help us get to Windows support.

Thanks for your help. We will also have 0.12 out by sometime in April if you would prefer to wait until then.

**Comment by mvadu** [comment]
@jsternberg Sure,I understand. Just to let you know, I released a version of InfluxDB (off of 011 branch with #6056 at https://github.com/mvadu/influxdb/releases/tag/v0.11.0-rc1 so people like me who are interested in Windows and Influx can give it a try earlier than you guys can officially offer it.
