### PR TITLE
Don't return empty response bodies when gzip encoding requested

### LINKED ISSUE #6624: Content-Encoding: gzip sent in 204 responses, breaks some clients
```
curl -vvv -XPOST -H 'Accept-Encoding: gzip' 'localhost:8086/write?db=junk&precision=us' --data-binary 'x n=1i'
*   Trying ::1...
* Connected to localhost (::1) port 8086 (#0)
> POST /write?db=junk&precision=us HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.43.0
> Accept: */*
> Accept-Encoding: gzip
> Content-Length: 6
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 6 out of 6 bytes
< HTTP/1.1 204 No Content
< Content-Encoding: gzip
< Request-Id: 988f51ba-1939-11e6-806b-000000000000
< X-Influxdb-Version: unknown
< Date: Fri, 13 May 2016 18:36:24 GMT
<
* Connection #0 to host localhost left intact
```

I'm using a client library that crashes when it sees `Content-Encoding: gzip` and tries to read the 0-length body (and I am going to file a separate issue on that client library). I can work around this by sending my writes with `Accept-Encoding: identity`.

I tried to see whether `Content-Encoding: gzip` on a 204 response was standards-compliant, but I wasn't able to find a clear answer on Google. I didn't want to spend the time to comb through any RFCs for an answer.

There is precedent in https://github.com/labstack/echo/issues/489 for not sending `Content-Encoding: gzip` on 204 responses, and I think InfluxDB should follow suit. That issue also points out that "nginx warns about empty responses (HTTP 204) with a Content-Encoding header set".

(FWIW someone else [ran into this same issue last September against 0.9.3](https://groups.google.com/forum/#!topic/racket-users/lsZhFjUaQwE) but seemingly didn't open an upstream bug with us.)

### PR DESCRIPTION
**Pull request by e-dard**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

Fixes #6624 

If a client requests a gzip encoded response body and we return `http.StatusNoContent` with an empty response body some clients will be unhappy.

Instead, we'll check if the client wants a `gzip` encoded body, and when they do (and we have nothing to return), we'll instead return a minimally gzipped response body, and a `200` since the body is no longer empty.

/cc @mark-rushakoff

### CODE REVIEW

File: services/httpd/handler.go [hunk 1]
```diff
@@ -319,8 +320,8 @@ func (h *Handler) serveQuery(w http.ResponseWriter, r *http.Request, user *meta.
 
 	// Execute query.
 	w.Header().Add("Connection", "close")
-	w.Header().Add("content-type", "application/json")
-	readonly := r.Method == "GET" || r.Method == "HEAD"
+	w.Header().Add("Content-Type", "application/json")
+	readonly := r.Method == "GET"
```
Comment (jsternberg) [inline services/httpd/handler.go]: What's wrong with checking for `HEAD`? I know that we don't currently support that for queries, but it really shouldn't harm anything to ensure that, if we do add it, that the query is done in a read-only context.

File: services/httpd/handler.go [hunk 2]
```diff
@@ -464,15 +465,15 @@ func (h *Handler) serveWrite(w http.ResponseWriter, r *http.Request, user *meta.
 	_, err := buf.ReadFrom(body)
 	if err != nil {
 		if h.Config.WriteTracing {
-			h.Logger.Print("write handler unable to read bytes from request body")
+			h.Logger.Print("Write handler unable to read bytes from request body.")
```
Comment (jsternberg) [inline services/httpd/handler.go]: Why the change in capitalization and the addition of periods? We don't generally include those in log messages to my knowledge.

File: services/httpd/handler.go (hunk 1 above)
Comment (e-dard) [inline services/httpd/handler.go]: Just seems redundant to me, and gives the impression it's possible. I don't mind putting it back though.

File: services/httpd/handler.go (hunk 2 above)
Comment (e-dard) [inline services/httpd/handler.go]: I don't know why I added punctuation, I'll remove it. Logged messages though, unlike error messages, should be capitalised.

File: services/httpd/handler.go [hunk 3]
```diff
@@ -517,25 +518,36 @@ func (h *Handler) serveWrite(w http.ResponseWriter, r *http.Request, user *meta.
...
 }
 
 // serveStatus has been depricated
 func (h *Handler) serveStatus(w http.ResponseWriter, r *http.Request) {
 	h.Logger.Printf("WARNING: /status has been depricated.  Use /ping instead.")
 	h.statMap.Add(statStatusRequest, 1)
-	w.WriteHeader(http.StatusNoContent)
+	if r.Header.Get("Accept-Encoding") != "gzip" {
+		w.WriteHeader(http.StatusNoContent)
+	}
```
Comment (mark-rushakoff) [inline services/httpd/handler.go]: These three lines are repeated a few times, but they are incorrect: 204 should still be the status code sent back regardless, but the response should not contain the header `Content-Encoding: gzip`. Also, `Accept-Encoding` can be comma-delimited, e.g. in Chrome I see `gzip, deflate, sdch`.

Comment (mark-rushakoff) [inline services/httpd/handler.go]: After thinking a little more, I'm pretty sure it should be the other way around – if the status is going to be a 204 and the response body is empty, then we should delete (or preferably never set) the `Content-Encoding` header.

Comment (e-dard) [inline services/httpd/handler.go]: @mark-rushakoff it was my understanding from your original issue that clients are requesting gzipped responses and then processing the responses as gzipped regardless of `Content-Encoding` header. 

If the clients are checking the `Content-Type` header then yes we could never set it for the `write` endpoint, which would be a simpler solution. 👍

**Comment by joelegasse** [comment]
The "real" answer is that the client is misbehaving, as `204`, according to the [RFC](http://tools.ietf.org/html/rfc2616#section-10.2.5), "MUST NOT include a message-body". It's probably just checking the `Content-Encoding` header, ignoring the length or 204 (implied length zero), and reading the body.

I also think we should just make sure that if we're returning a `204`, that we remove the `Content-Encoding` header. Or find a way to not add the header until we actually write data to the connection.

**Comment by jsternberg** [comment]
I'll add my +1 to removing the `Content-Encoding: gzip` from a `204`. It felt dirty to me to return a blank body when we really do want to send `204`. I'm not sure if there's an easy way to remove setting that header though. You can probably do it more easily by overwriting the `WriteHeader` method for the `gzipResponseWriter` and have it set the header if the status is not `204`.

**Comment by e-dard** [comment]
@jsternberg @joelegasse updated.

File: services/httpd/handler.go [hunk 4]
```diff
@@ -517,6 +518,10 @@ func (h *Handler) serveWrite(w http.ResponseWriter, r *http.Request, user *meta.
 	}
 
 	h.statMap.Add(statPointsWrittenOK, int64(len(points)))
+
+	if w.Header().Get("Content-Encoding") == "gzip" {
```
Comment (jsternberg) [inline services/httpd/handler.go]: I think it would be better to remove the header management from here completely and do it in the `gzipResponseWriter`. Something like this:

```
func (w *gzipResponseWriter) WriteHeader(code int) {
    if code != http.StatusNoContent {
        w.Header().Set("Content-Encoding", "gzip")
    }
    w.ResponseWriter.WriteHeader(code)
}
```

Then you can remove all of the locations where `Content-Encoding` is set or removed.

Comment (e-dard) [inline services/httpd/handler.go]: I was about to say this won't work because the response may already of started streaming, but in this special case (`204`) it won't have, so yeah, good idea!

**Comment by jsternberg** [comment]
👍 please squash and merge on green.
