### PR TITLE
fix: avoid rewriting fields.idx unnecessarily

### LINKED ISSUE #21597: Rewriting fields.idx is a bottleneck with many new fields and measurements [port to 1.9 branch]
https://github.com/influxdata/influxdb/issues/21577 port to 1.9 branch for 1.9.2

### PR DESCRIPTION
**Pull request by lesam**
Closes #21597

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: tsdb/shard.go [hunk 1]
```diff
@@ -1736,83 +1738,153 @@ func (fs *MeasurementFieldSet) IsEmpty() bool {
...
 
-	fd, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR|os.O_EXCL|os.O_SYNC, 0666)
-	if err != nil {
-		return err
+func (w *MeasurementFieldSetWriter) Close() {
+	if w != nil {
+		close(w.writeRequests)
 	}
-	defer os.RemoveAll(path)
+	w.wg.Wait()
```
Comment (davidby-influx) [inline tsdb/shard.go:1766]: We should move the Wait() call inside the if statement....  My mistake.

**Review by davidby-influx — APPROVED** [review]
One small error in my code I noted, but non-blocking.
