### PR TITLE
fix(ui): updated table threshold to set background colors for thresholds correctly

### LINKED ISSUE #15904: Table thresholds are not functional
1. Threshold colors are not applied to table

no-threshold-coloring

2. Threshold settings do not persist

threshold-settings-dont-persist

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #15904 

### Problem

Setting table thresholds would not reflect changes to styling in the table ui

### Solution

Added in check to colorization of the table thresholds to set the background colors correctly. Also updated a table method to correctly determine whether a value is a number or not

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)

### CODE REVIEW

File: ui/src/shared/components/tables/TableCell.tsx [hunk 1]
```diff
@@ -137,8 +137,12 @@ class TableCell extends PureComponent<Props> {
...
   }
 
-  private get isNumerical(): boolean {
-    return !isNaN(Number.parseFloat(this.props.data))
+  private get isTimestamp(): boolean {
+    return this.props.dataType === 'dateTime:RFC3339'
+  }
+
+  private get isNaN(): boolean {
+    return isNaN(Number(this.props.data))
```
Comment (TCL735) [inline ui/src/shared/components/tables/TableCell.tsx]: Passing in `null` has now changed. Previously, using Number.parseFloat(null) would return `NaN` and ultimately the expression is NaN

Number(null) returns 0, and ultimately the expression is **not** NaN

This looks like an improvement, because we _do_ want to handle null values. Just wanted to make sure it was intentional.

Comment (Asalem1) [reply ui/src/shared/components/tables/TableCell.tsx]: @TCL735 it was intentional in terms of my understanding of how the UI should handle UI values, but it was not explicit in terms of what the criteria should have been. @sjwang90 what're your thoughts on the way we should handle `null` values?
