### PR TITLE
fix: hierarchy of variables is back

### LINKED ISSUE #17606: Variable Template Query Tag Values does not work for each bucket
Tools US 2.x Cluster
Dashboard Log File Studies V1.x - Shards

Variable shard defined as query:

import "influxdata/influxdb/v1"
v1.tagValues(bucket: v.bucket, tag: "shard_id")

The above sometimes works and sometimes does not based on the bucket.  For the following bucket, I actually created a cell to show that the value appears valid.

https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/0569ce471d8dd000?lower=2020-04-01T01%3A00%3A00.000Z&upper=2020-04-01T02%3A00%3A00.000Z

image

I have run through a few dozen buckets (log files from customers) and sometimes the drop down works for the variable, other times it fails.  The l-creditkarma-apr bucket does not enable the drop down but the tag value list should just have the 10 numbers as shown above.

image

Ping me if you cannot repro the problem or if the bucket shown above is gone.

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #17606

variables now hold their own values, and we gotta respect that, you know?

### CODE REVIEW

File: ui/src/timeMachine/actions/queries.ts [hunk 1]
```diff
@@ -115,6 +116,8 @@ export const executeQueries = () => async (dispatch, getState: GetState) => {
   try {
     dispatch(setQueryResults(RemoteDataState.Loading, [], null))
 
+    await dispatch(hydrateVariables())
```
Comment (drdelambre) [inline ui/src/timeMachine/actions/queries.ts:119]: this refreshes variables that haven't been fetched by another means before sending off the query, just in case. found this while deep linking w/ dependent variables and no application state.

File: ui/src/variables/selectors/index.tsx [hunk 2]
```diff
@@ -175,6 +175,11 @@ export const getVariable = (
   if (!vari.selected) {
     if (vari.arguments.type === 'map') {
       vari.selected = [Object.keys(vari.arguments.values)[0]]
+    } else if (
```
Comment (drdelambre) [inline ui/src/variables/selectors/index.tsx:178]: unrelated change, just an oversight I caught while debugging

File: ui/src/variables/selectors/index.tsx [hunk 3]
```diff
@@ -252,6 +257,9 @@ export const asAssignment = (variable: Variable): VariableAssignment => {
   }
 
   if (variable.arguments.type === 'query') {
+    if (!variable.selected[0]) {
```
Comment (drdelambre) [inline ui/src/variables/selectors/index.tsx:260]: the ensures that the AST doesn't return variables if they don't have a value set, because that causes all sorts of issues in the LSP and on the api

File: ui/src/variables/utils/buildVarsOption.ts [hunk 4]
```diff
@@ -20,7 +20,7 @@ export const buildVarsOption = (variables: VariableAssignment[]): File => ({
         },
         init: {
           type: 'ObjectExpression',
-          properties: variables.map(assignmentToProperty),
+          properties: variables.filter(v => !!v).map(assignmentToProperty),
```
Comment (drdelambre) [inline ui/src/variables/utils/buildVarsOption.ts:23]: and this makes sure those variables we removed are filtered from the list before further processing

File: ui/src/variables/utils/hydrateVars.ts [hunk 5]
```diff
@@ -372,7 +372,10 @@ export const hydrateVars = (
     node.status === RemoteDataState.Loading
 
     try {
+      // TODO: remove the concept of node.values, just use node.variable
       node.values = await hydrateVarsHelper(node, options)
+      node.variable.arguments.values.results = node.values.values
```
Comment (drdelambre) [inline ui/src/variables/utils/hydrateVars.ts:377]: here is the actual fix for this PR

File: ui/src/dashboards/actions/thunks.ts [hunk 6]
```diff
@@ -286,7 +286,7 @@ export const getDashboard = (dashboardID: string) => async (
       throw new Error(resp.data.message)
     }
 
-    dispatch(hydrateVariables())
+    dispatch(hydrateVariables(true))
```
Comment (ebb-tide) [inline ui/src/dashboards/actions/thunks.ts:289]:
```suggestion
    const skipCache = true
    dispatch(hydrateVariables(skipCache))
```

Comment (drdelambre) [reply ui/src/dashboards/actions/thunks.ts:289]: is the request to be more explicit about what it's doing through the var name?

Comment (ebb-tide) [reply ui/src/dashboards/actions/thunks.ts:289]: yup :)

Comment (drdelambre) [reply ui/src/dashboards/actions/thunks.ts:289]: 💯
