### PR TITLE
fix: nav double highlight

### LINKED ISSUE #12308: Fix double nav highlighting
screen shot 2019-03-01 at 2 20 48 pm
screen shot 2019-03-01 at 2 20 51 pm

Should only highlight the `Orgs` nav tab when viewing dashboards or tasks from within an org

### PR DESCRIPTION
**Pull request by 121watts**
Closes #12308 
### After

kapture 2019-03-05 at 16 04 43

### CODE REVIEW

File: ui/src/pageLayout/components/NavMenuItem.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ interface Props {
   link: string
   children?: JSX.Element | JSX.Element[]
   location: string
-  highlightWhen: string[]
+  highlightPaths: string[]
```
Comment (ischolten) [inline ui/src/pageLayout/components/NavMenuItem.tsx]: nice!

File: ui/src/pageLayout/containers/Nav.test.tsx [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+  const props = {
+    pathname: '/',
+    ...override,
+  }
+
+  return render(<Nav {...props} />)
+}
+
+describe('Nav', () => {
+  it('only highlights one nav item', () => {
```
Comment (ischolten) [inline ui/src/pageLayout/containers/Nav.test.tsx]: woo!

File: ui/src/pageLayout/containers/Nav.tsx [hunk 3]
```diff
@@ -40,67 +40,67 @@ class SideNav extends PureComponent<Props> {
...
           location={location.pathname}
-          highlightWhen={['configuration']}
+          highlightPaths={['configuration']}
         >
           <NavMenu.SubItem
             title="Labels"
             link="/configuration/labels_tab"
             location={location.pathname}
-            highlightWhen={['labels']}
+            highlightPaths={['labels_tab']}
```
Comment (ischolten) [inline ui/src/pageLayout/containers/Nav.tsx]: good catch!
