### PR TITLE
Fix queries against compacted files

### LINKED ISSUE #5501: Queries against files that have just been compacted need to point to new files
If a query is run and is executing against a TSM file that is compacted and replaced while the query is executing, we need to use the new file.

Original issue from #4977

### LINKED ISSUE #6925: BUG: Serious Data Consistency error [v1.0.0beta2, v.1.0.0beta1 - perhaps older?]
### Bug report

System Info:
 v1.0.0beta2
 v1.0.0beta1
 (potentially earlier)
 ubuntu 14.04.2 LTS

I have been testing with a collection of large time-series files, being importing via 'influx -import' or via my own python utility using influxdb-python. The problem is present with both methods.

Series: 128, 2Hz (500ms sample period); each series with a sinusoidal signal, various amplitudes - either clean or additive random white noise (20% of max amplitude). The time values are *all* in the past.
Import Size: Tested with range of files size: 24 hrs - 14 days (336 hrs); 24 hrs = 187K lines
(BTW, I have also tested with "production data" with similar data-size/frequency characteristics, and problem also exists).

Method:
* Import file1 (covering period1); no fault observed
* Import file2 (covering period2): fault may/not not observed (perhaps depending on the period crossing a shard boundary)
* Keep repeating
* Import fileN (covering periodN):fault will *always occur* eventually; exact time-point seems to be related the number/size of the import files used. (Perhaps following a compaction event triggering?) 

The are *no* unusual (e.g. ERRORS/WARNINGS) entries in the influxdb.log; just the write and compaction events. 

Issue: Some data queries across the data series responsd with "missing" or "out of sequence" data. This can be visualised externally (for example, Grafana), but it present using the influxdb-CLI. Where there is a data fault, it will occur at the same time point in all series. This is observed in both raw (full) queries; and in query aggregated with GROUP BY time(<period>). 

(simplified example)
Query: SELECT mean('A') FROM 'X' WHERE time>t1 and time < t7 GROUP BY time(x)
(NOTE: this could be a raw query as well, such as: SELECT 'A' FROM 'X' WHERE time>t1 and time<t7)

> t1: good-data
> t2: good-data
> t3: (no data)
> t4: (no data)
> t5: (no data)
> t6: good-data
> t3: good-data (note the jump back in time)
> t4: good-data (still in past)
> t5: good-data (still in past)
> t6: good-data (repeat of the above data point)
> t7: good-data

Examples are attached. 

Anecdotally, I suspect the fault to occur once shard compaction begins. I have repeated the test nearly dozen times now on different host systems, using different memory configurations, at different import speeds. The problem *always* occurs at some point, but the exact number of import files or where the data faults occurs seems to vary - though the "jump" always seems to *end* close to the start of the latest import - and then pushing backwards in time to the previous "file").

Also, it does not seem to matter if the query (resulting in gap/jump-back) is issued during import, immediately after; or significantly >1hr.  

I realise this a complicated description, so I attach some influx CLI and grafana examples to try and illustrate.

(I have the database snapshot and import files available, but too large to casually upload) 

Jonathan

[dataFault.txt](https://github.com/influxdata/influxdb/files/337304/dataFault.txt)

datafault01
datafault02
datafault03
datafault04

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

This fixes #5501 and #6925 so that running queries against files that are also being compacted does not cause the query to end abruptly.  This usually looks like large chunks of data just disappearing and then re-appearing the next time the query runs.  In grafana, a graph could look like the third image in #6925.  Queries should now be consistent as of the time they are executed with respect data on disk regardless if files are compacted.

To fix this, this PR uses a reference counting approach where queries register their usage of a TSM file and remove that reference when finished.  In the `FileStore`, if a TSM file is replaced, but is still in use, it is moved aside to allow the query to complete and then periodically the file is checked to see if it can be removed.  The new files being installed will be use by any future queries after `Replace` returns.

In order to not complicate or block compactions, the existing file is renamed to a temp file and the live file is removed.  The `TSMReader` then re-MMAPs this new file, using it's existing index and tombstone state.  This approach performs well in local testing and should also work on windows.  In the event of a crash, the moved aside files are cleaned up as part of startup like other temp files managed by the engine.

Fixes #5501 
Fixes #6925 

cc @benbjohnson

### CODE REVIEW

File: tsdb/engine/tsm1/file_store.go [hunk 1]
```diff
@@ -84,9 +84,22 @@ type TSMFile interface {
...
 	Size() uint32
 
+	// Rename renames the existing TSM file to a new name and replaces the mmap backing slice using the new
+	// file name.  Index and Reader state are not re-initialized.
+	Rename(path string) error
+
 	// Remove deletes the file from the filesystem
 	Remove() error
 
+	// Returns true if the file is current in use by queries
```
Comment (jsternberg) [inline tsdb/engine/tsm1/file_store.go]: current -> currently

File: tsdb/engine/tsm1/file_store.go [hunk 2]
```diff
@@ -485,12 +505,43 @@ func (f *FileStore) Replace(oldFiles, newFiles []string) error {
...
 	// We need to prune our set of active files now
-	var active []TSMFile
+	var active, inuse []TSMFile
 	for _, file := range updated {
 		keep := true
 		for _, remove := range oldFiles {
 			if remove == file.Path() {
 				keep = false
+
+				// If queries running against this file, then we need to move it out of the
```
Comment (jsternberg) [inline tsdb/engine/tsm1/file_store.go]: "If queries running against this file" -> "If there are queries running against this file"

File: tsdb/engine/tsm1/file_store.go [hunk 3]
```diff
@@ -782,12 +840,25 @@ func newKeyCursor(fs *FileStore, key string, t int64, ascending bool) *KeyCursor
 		sort.Sort(descLocations(c.seeks))
 	}
 
+	// Determine the distinct set of TSM files in use and mark then as in-use
+	for _, f := range c.seeks {
+		if _, ok := c.refs[f.r.Path()]; !ok {
+			f.r.Ref()
```
Comment (jsternberg) [inline tsdb/engine/tsm1/file_store.go]: I think this is ok, but I want to highlight it just to make sure I'm reading the code correctly. I think that both the `Replace` and `newKeyCursor` use the same lock so they can't be run simultaneously. Without the lock, there's a possibility of a race condition here where `fs.location()` retrieves a `TSMFile` and then that file gets deleted before the reference can be taken. I think because of the lock, this is fine, but I just want to confirm that's correct because this would be a very hard race condition to find otherwise.

**Comment by jsternberg** [comment]
I think this is OK. I have one question since the code is complicated and I found two grammatical errors in the comments, but I think it's good otherwise.

File: tsdb/engine/tsm1/file_store.go (hunk 3 above)
Comment (jwilder) [inline tsdb/engine/tsm1/file_store.go]: There isn't a race.  There is a read-lock taken on the file store by the caller of `newKeyCursor`.  The cursor then uses the TSM files at that point in time until they complete.  The file store is free to remove the references to the `TSMFile`s it's managing when it's able to acquire the write lock.

Comment (jsternberg) [inline tsdb/engine/tsm1/file_store.go]: 👍
