### PR TITLE
Fix parsing keys when loading database index

### LINKED ISSUE #6496: space in measure name makes first query after restart fail
### Bug report

__System info:__  Recent .13 Nightly on Windows 10

__Steps to reproduce:__

1. Start a server in one console.
2. Run the influx.exe client in another, use a database.
3. Run this: insert a\ b value=1
4. Run this and observe a single record: select * from "a b" 
5. Go back to the server and kill it. Restart it.
6. Run the select again and observe no records when there should be one
7. Run the insert and then the select again and observe the two records

__Expected behavior:__ I should not have to insert data before I can query it.

The problem does not exist without whitespace in the measure name. This is a showstopper for me as my server is restarted daily (for other reasons) and reports are ran shortly after the server is up.

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

The code for parsing a key our of the WAL or TSM files in the engine
was naive and didn't account for measurements with escape chars. This
uses the correct parsing code to parse and load them correctly.

Fixes #6496

### CODE REVIEW

**Comment by jwilder** [comment]
@e-dard

File: tsdb/meta.go [hunk 1]
```diff
@@ -1772,9 +1772,7 @@ func (s stringSet) intersect(o stringSet) stringSet {
...
 // contains a measurement name.
 func MeasurementFromSeriesKey(key string) string {
-	idx := strings.Index(key, ",")
-	if idx == -1 {
-		return key
-	}
-	return key[:idx]
+	// Ignoring the error because the func returns "missing fields"
+	k, _, _ := models.ParseKey(key)
+	return escape.UnescapeString(k)
```
Comment (e-dard) [inline tsdb/meta.go]: Is this a breaking change? Looks like the keys were not previously unescaped.

**Comment by e-dard** [comment]
Aside from my question about storing the keys, LGTM 👍

File: tsdb/meta.go (hunk 1 above)
Comment (jwilder) [inline tsdb/meta.go]: No, it has always been broken, but never discovered.  This is called to parse a key already on disk.
