### PR TITLE
fix: legacy fromFlux translation

### LINKED ISSUE #16474: Data with column error should not result in UI error screen
error-column

This happens as we use the simply check for a column called `error` on the csv returned.

We should check for the exact schema returned when there is a runtime error and only display the error screen on that condition. See https://github.com/influxdata/flux/blob/master/docs/SPEC.md#errors

### LINKED ISSUE #17262: [2.x] Cell shows ⚠️False in graph area for specific queries
__Steps to reproduce:__
Example source data. This is brought in by a Scraper.
```
# HELP users_active_hour_total Total number of active users in the past hour.
# TYPE users_active_hour_total gauge
users_active_hour_total 48 1584100800000
# HELP users_active_day_total Total number of active users in the past day.
# TYPE users_active_day_total gauge
users_active_day_total 482 1584057600000
# HELP users_active_month_total Total number of active users in the past month.
# TYPE users_active_month_total gauge
users_active_month_total 3201 1583020800000
# HELP api_calls_total Number of API calls made in the past hour.
# TYPE api_calls_total gauge
api_calls_total{source="app",error="false"} 2403 1584100800000
api_calls_total{source="app",error="true"} 0 1584100800000
api_calls_total{source="cron",error="false"} 1198 1584100800000
api_calls_total{source="cron",error="true"} 10 1584100800000
api_calls_total{source="external",error="false"} 12 1584100800000
api_calls_total{source="external",error="true"} 0 1584100800000
```

Example of a query on the active user data. This one works without issue.
```
from(bucket: "app")
  |> range(start:-30d)
  |> filter(fn: (r) => r._measurement == "users_active_hour_total")
  |> keep(columns: ["_time", "_value"])
```

Next I was trying to query the api_calls_total data. I expect this query would work:
```
from(bucket: "app")
  |> range(start:-6h)
  |> filter(fn: (r) => r._measurement == "api_calls_total")
  |> filter(fn: (r) => r.source == "app")
  |> filter(fn: (r) => r.error == "false")
```
However, the dashboard shows ":warning: false" in the chart area.

Here's the response from the HTTP request:
```
#group,false,false,true,true,false,false,true,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string
#default,_result,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,error,source
,,0,2020-03-13T11:42:50.483343323Z,2020-03-13T17:42:50.483343323Z,2020-03-13T12:00:00Z,2403,gauge,api_calls_total,false,app
,,0,2020-03-13T11:42:50.483343323Z,2020-03-13T17:42:50.483343323Z,2020-03-13T13:00:00Z,3411,gauge,api_calls_total,false,app
,,0,2020-03-13T11:42:50.483343323Z,2020-03-13T17:42:50.483343323Z,2020-03-13T14:00:00Z,5065,gauge,api_calls_total,false,app
,,0,2020-03-13T11:42:50.483343323Z,2020-03-13T17:42:50.483343323Z,2020-03-13T15:00:00Z,5182,gauge,api_calls_total,false,app
,,0,2020-03-13T11:42:50.483343323Z,2020-03-13T17:42:50.483343323Z,2020-03-13T16:00:00Z,5399,gauge,api_calls_total,false,app
,,0,2020-03-13T11:42:50.483343323Z,2020-03-13T17:42:50.483343323Z,2020-03-13T17:00:00Z,5871,gauge,api_calls_total,false,app


```

influx

 If I try to run that same query in the `influx repl` tool, it works:
```
> from(bucket: "app")
  |> range(start:-6h)
  |> filter(fn: (r) => r._measurement == "api_calls_total")
  |> filter(fn: (r) => r.source == "app")
  |> filter(fn: (r) => r.error == "false")
Result: _result
Table: keys: [_start, _stop, _field, _measurement, error, source]
                   _start:time                      _stop:time           _field:string     _measurement:string            error:string           source:string                      _time:time                  _value:float
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ----------------------------
2020-03-13T07:31:41.482175926Z  2020-03-13T13:31:41.482175926Z                   gauge         api_calls_total                   false                     app  2020-03-13T08:00:00.000000000Z                          2599
2020-03-13T07:31:41.482175926Z  2020-03-13T13:31:41.482175926Z                   gauge         api_calls_total                   false                     app  2020-03-13T09:00:00.000000000Z                          2019
2020-03-13T07:31:41.482175926Z  2020-03-13T13:31:41.482175926Z                   gauge         api_calls_total                   false                     app  2020-03-13T10:00:00.000000000Z                          1980
2020-03-13T07:31:41.482175926Z  2020-03-13T13:31:41.482175926Z                   gauge         api_calls_total                   false                     app  2020-03-13T11:00:00.000000000Z                          2067
2020-03-13T07:31:41.482175926Z  2020-03-13T13:31:41.482175926Z                   gauge         api_calls_total                   false                     app  2020-03-13T12:00:00.000000000Z                          2403
```

I started fiddling, and found that the following query works on the dashboard (added the last onEmpty):
```
from(bucket: "app")
  |> range(start:-6h)
  |> filter(fn: (r) => r._measurement == "api_calls_total")
  |> filter(fn: (r) => r.source == "app")
  |> filter(fn: (r) => r.error == "false", onEmpty: "keep")
```

Here's the response from the HTTP request:
```
#group,false,false,true,true,false,false,true,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string
#default,_result,0,2020-03-13T11:42:29.087771059Z,2020-03-13T17:42:29.087771059Z,,,gauge,api_calls_total,true,app
,result,table,_start,_stop,_time,_value,_field,_measurement,error,source

#group,false,false,true,true,false,false,true,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string
#default,_result,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,error,source
,,1,2020-03-13T11:42:29.087771059Z,2020-03-13T17:42:29.087771059Z,2020-03-13T12:00:00Z,2403,gauge,api_calls_total,false,app
,,1,2020-03-13T11:42:29.087771059Z,2020-03-13T17:42:29.087771059Z,2020-03-13T13:00:00Z,3411,gauge,api_calls_total,false,app
,,1,2020-03-13T11:42:29.087771059Z,2020-03-13T17:42:29.087771059Z,2020-03-13T14:00:00Z,5065,gauge,api_calls_total,false,app
,,1,2020-03-13T11:42:29.087771059Z,2020-03-13T17:42:29.087771059Z,2020-03-13T15:00:00Z,5182,gauge,api_calls_total,false,app
,,1,2020-03-13T11:42:29.087771059Z,2020-03-13T17:42:29.087771059Z,2020-03-13T16:00:00Z,5399,gauge,api_calls_total,false,app
,,1,2020-03-13T11:42:29.087771059Z,2020-03-13T17:42:29.087771059Z,2020-03-13T17:00:00Z,5871,gauge,api_calls_total,false,app


```

__Environment info:__

* System info: Linux 4.15.0-66-generic x86_64
* InfluxDB version: InfluxDB 2.0.0-beta.5 (git: 2295247a5) build_date: 2020-03-13T11:22:29Z

__Config:__
It's a fresh installation; haven't changed anything.

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #16474
Closes #17262
Closes influxdata/idpe#6772

replaces the flux parser that lives in giraffe with one that lives in influxdb. it closes the issue because it more closely follows the spec (throws an error during parsing). This PR is a weird side effect of a migration strategy and is wasteful of resources, but i wanted to merge it in while taking care of the todos, as i have no idea what the ramifications of changing that stuff is and this has a nice little bow on it.

### CODE REVIEW

File: ui/src/onboarding/components/CompletionStep.tsx [hunk 1]
```diff
@@ -41,15 +40,6 @@ interface Props extends OnboardingStepProps {
   bucketID: string
 }
 
-const getOrganizations = async () => {
```
Comment (drdelambre) [inline ui/src/onboarding/components/CompletionStep.tsx:44]: this was breaking tests

**Comment by drdelambre** [comment]
@Asalem1 i can't break this locally, but that doesn't mean it's good
@TCL735 this is the kicking off of a talk about the interface between giraffe and influxdb
