### PR TITLE
fix: enable cloning and exporting of dashboards

### LINKED ISSUE #16613: Fix dashboard exporting and cloning
Can not currently export or clone dashboards

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #16613

### CODE REVIEW

File: ui/src/dashboards/actions/thunks.ts [hunk 1]
```diff
@@ -96,19 +96,19 @@ export const createDashboard = () => async (
   }
 }
 
-export const cloneDashboard = (dashboard: Dashboard) => async (
-  dispatch,
-  getState: GetState
-): Promise<void> => {
+export const cloneDashboard = (
+  dashboardID: string,
+  dashboardName: string
```
Comment (121watts) [inline ui/src/dashboards/actions/thunks.ts]: yaaas
