### PR TITLE
Fix panic: interface conversion: tsm1.Value is *tsm1.FloatValue, not *tsm1.StringValue

### LINKED ISSUE #7498: panic: interface conversion: tsm1.Value is *tsm1.FloatValue, not *tsm1.StringValue
Hi,

I use InfluxDB 1.0.2 on armhf Ubuntu Xenial.

Since yesterday I get a restart each hour with the following:

```
Oct 21 07:40:52 cubietruck3 influxd[18586]: [tsm1] 2016/10/21 07:40:52 Snapshot for path /var/lib/influxdb/data/iobroker/global/59 written in 5.377168818s
Oct 21 07:40:52 cubietruck3 influxd[18586]: panic: interface conversion: tsm1.Value is *tsm1.FloatValue, not *tsm1.StringValue
Oct 21 07:40:52 cubietruck3 influxd[18586]: goroutine 161 [running]:
Oct 21 07:40:52 cubietruck3 influxd[18586]: panic(0x6686f0, 0x1f1fc760)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/usr/local/go/src/runtime/panic.go:481 +0x330
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.encodeStringBlock(0x0, 0x0, 0x0, 0x17c685f0, 0xa, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:517 +0x200
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.Values.Encode(0x17c685f0, 0xa, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:82 +0x148
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*cacheKeyIterator).Read(0x1498d980, 0x0, 0x0, 0x7c6da700, 0x14605c03, 0xabe3e080, 0x146234eb, 0x0, 0x0, 0x0, ...)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1266 +0x28c
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0x11ec71c0, 0x181e60a0, 0x45, 0x7a5bc4a8, 0x1498d980, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:731 +0x498
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0x11ec71c0, 0x1, 0x1, 0x7a5bc4a8, 0x1498d980, 0x0, 0x0, 0x0, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:672 +0x2b4
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).WriteSnapshot(0x11ec71c0, 0x1b6776e0, 0x0, 0x0, 0x0, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:533 +0x138
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).writeSnapshotAndCommit(0x11075320, 0x15f6af88, 0x1, 0x1, 0x1b6776e0, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:776 +0x84
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).WriteSnapshot(0x11075320, 0x0, 0x0)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:751 +0x278
Oct 21 07:40:52 cubietruck3 influxd[18586]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0x11075320)
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:814 +0x208
Oct 21 07:40:52 cubietruck3 influxd[18586]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).SetCompactionsEnabled
Oct 21 07:40:52 cubietruck3 influxd[18586]: #011/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:166 +0x11c
Oct 21 07:40:52 cubietruck3 systemd[1]: influxdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 21 07:40:52 cubietruck3 systemd[1]: influxdb.service: Unit entered failed state.
Oct 21 07:40:52 cubietruck3 systemd[1]: influxdb.service: Failed with result 'exit-code'.
Oct 21 07:40:53 cubietruck3 systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.
Oct 21 07:40:53 cubietruck3 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Oct 21 07:40:53 cubietruck3 systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
```

On Restart the line from "filestore" of open the tsm file is also missing for "59". The directory /var/lib/influxdb/data/iobroker/global/59 is empty
What can I do?

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [ ] Tests pass

This fixes a panic when snapshotting the cache.  If concurrent writes to the same shard occur, it's possible for different types to be added to the cache for the same series.  The way the measurementFields map on the shard is updated is racy in this scenario which would normally prevent this from occurring. When this occurs, the snapshot compaction panics because it can't encode different types in the same series.

To prevent this, we have the cache return an error a different type is added to existing values in the cache.

This also fixes a race that was introduced in #7480 where the `FileStore.Stats` slice is read by the compactor without a lock when the `FileStore` is updating it.

Fixes #7498 

cc @e-dard

### CODE REVIEW

File: tsdb/engine/tsm1/cache.go [hunk 1]
```diff
@@ -219,7 +240,10 @@ func (c *Cache) Write(key string, values []Value) error {
 		return ErrCacheMemoryExceeded
 	}
 
-	c.write(key, values)
+	if err := c.write(key, values); err != nil {
+		c.mu.Unlock()
```
Comment (e-dard) [inline tsdb/engine/tsm1/cache.go]: Should we update `c.stats.WriteErr` or maybe add a new stat for this unusual condition?

File: tsdb/engine/tsm1/file_store.go [hunk 2]
```diff
@@ -261,7 +261,7 @@ func (f *FileStore) Add(files ...TSMFile) {
 	for _, file := range files {
 		atomic.AddInt64(&f.stats.DiskBytes, int64(file.Size()))
 	}
-	f.lastFileStats = f.lastFileStats[:0] // Will need to be recalculated on next call to Stats.
+	f.lastFileStats = nil
```
Comment (e-dard) [inline tsdb/engine/tsm1/file_store.go]: Heh, I guess we were trying to be too clever for our own good making that change 😄

File: tsdb/engine/tsm1/cache.go (hunk 1 above)
Comment (jwilder) [inline tsdb/engine/tsm1/cache.go]: Done.  Just discovered that the existing `OK` and `Err` stats are tracked, but not actually recorded.
