### PR TITLE
fix: throw error when adding fields to non-existent table in WAL

### LINKED ISSUE #25524: `CatalogOp::AddFields` should throw an error if applied to non-existent table
In the logic to apply catalog batches, the `AddFields` operation is handled here: https://github.com/influxdata/influxdb/blob/391b67f9ab144651af73b8cfae0da569e83502ba/influxdb3_catalog/src/catalog.rs#L474-L498

This will create a new table for the case where an `AddFields` is encountered for a table that does not already exist. This should instead throw an error, as there should always be either a `CreateTable` operation preceding it. That is, the table would have either been encountered in a preceding WAL operation, or that table is present in the catalog, i.e., the WAL ops are gone due to the snapshot process, but their state is captured in the persisted catalog.

### PR DESCRIPTION
**Pull request by hiltontj**
Closes #25524

In addition to throwing an error when an `AddFields` operation is applied for a table that does not exist, this PR adds some helper methods to the `influxdb3_wal` crate for creating WAL operations that were previously added in pro.

A test was added to check for the failure condition.

### CODE REVIEW

File: influxdb3_wal/src/create.rs [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+
+use crate::*;
+
+pub fn wal_contents(
+    (min_timestamp_ns, max_timestamp_ns, wal_file_number): (i64, i64, u64),
+    ops: impl IntoIterator<Item = WalOp>,
+) -> WalContents {
+    WalContents {
+        min_timestamp_ns,
+        max_timestamp_ns,
```
Comment (praveen-influx) [inline influxdb3_wal/src/create.rs:15]: Thanks for embedding the unit `ns`, really helps when reading the code without full context.

**Review by praveen-influx — APPROVED** [review]
Looks good.

File: influxdb3_wal/src/create.rs (hunk 1 above)
Comment (pauldix) [reply influxdb3_wal/src/create.rs:15]: Yeah, we should do that everywhere in the code where we don't have a typed time.

**Review by pauldix — APPROVED** [review]
