### PR TITLE
Speed up delete/drop statements

### LINKED ISSUE #6819: Database unresponsive after DROP MEASUREMENT
### Bug report

__System info:__ Fedora release 22, InfluxDB version 0.13.0

__Steps to reproduce:__

1. Drop a measurement via HTTP
2. Try to write to the database before the DROP MEASUREMENT call returns

__Expected behavior:__ The measurement gets deleted. Everything continues working.

__Actual behavior:__ The HTTP request to delete the measurement often times out after **300** seconds. The entire database is unresponsive while deleting measurements.

We have a use case where measurements need to be periodically deleted. I understand this is not what InfluxDB is optimized for, but cleaning up data and updating measurements is both a legitimate use case and one that is listed in the public API (so presumably supported). How can I delete a measurement completely without rendering the database inoperable for several minutes? We can insert upwards of 100k points/second so not being able to insert for prolonged periods of time can cause significant, contiguous chunks of data to be lost.
The timing of the deletion here isn't super important, we're happy to do it over many hours if need be as long as the database doesn't stop responding to writes for several minutes at a time.

Thanks.

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

This PR speeds up drop and delete statements by converting the locks held from write locks to shorter read locks as well as processing shards in parallel.  

The write locks where problematic on the `tsdb.Store` as that essentially locks up the database to all queries and writes.  If the deletes take a long time, many things backup (writes, compactions, etc..) which can cause memory problems, lockups, and unresponsiveness.

Processing shards in parallel reduces the execution time of the operation when there are many shards on disk.

Fixes #6819 #6796

### CODE REVIEW

File: tsdb/store.go [hunk 1]
```diff
@@ -458,16 +443,24 @@ func (s *Store) DeleteRetentionPolicy(database, name string) error {
 	}
 
 	// Remove the retention policy folder from the the WAL.
-	return os.RemoveAll(filepath.Join(s.EngineOptions.Config.WALDir, database, name))
+	if err := os.RemoveAll(filepath.Join(s.EngineOptions.Config.WALDir, database, name)); err != nil {
```
Comment (pauldix) [inline tsdb/store.go]: does the RP get removed from the metadata before this is called? Would this maybe cause a problem if it isn't?

File: tsdb/store.go [hunk 2]
```diff
@@ -478,21 +471,78 @@ func (s *Store) DeleteMeasurement(database, name string) error {
...
 	db.DropMeasurement(m.Name)
 
-	// Remove underlying data.
+	return nil
+}
+
+// filterShards returns a slice of shards where fn returns true
+// for the shard.
+func (s *Store) filterShards(fn func(sh *Shard) bool) []*Shard {
+	shards := make([]*Shard, 0, len(s.shards))
```
Comment (pauldix) [inline tsdb/store.go]: should this filter function dup `s.shards` while it has a read lock and then walk? Might this cause a problem if a shard is deleted (either through retention or user) while this runs?

File: tsdb/store.go (hunk 1 above)
Comment (jwilder) [inline tsdb/store.go]: No.  The statement executor drops the data from the `tsdb.Store` and only removes it from the meta store after that succeeds.  We previously deleted it from the meta store and then drop the shard data, but that causes problems if the data deleting fails (orphan data, data re-appearing after startup, etc..).

File: tsdb/store.go [hunk 3]
```diff
@@ -680,9 +730,13 @@ func (s *Store) deleteSeries(database string, seriesKeys []string, min, max int6
...
 
-	for _, sh := range s.shards {
+	shards := s.filterShards(func(sh *Shard) bool {
+		return sh.database == database
+	})
+
+	return s.walkShards(shards, func(sh *Shard) error {
 		if sh.database != database {
-			continue
+			return nil
```
Comment (joelegasse) [inline tsdb/store.go]: If this ever executes, it either means that `filterShards` doesn't work, or `sh.database` changed since `filterShards` ran, making this check a race...

File: tsdb/store.go (hunk 2 above)
Comment (jwilder) [inline tsdb/store.go]: The caller is required to acquire a read lock on the `tsdb.Store`.  Looks like I missed two spots.  Generally, the exported functions acquire locks and the unexported ones assume the caller has acquired them which makes reusing the unexported functions easier to re-use.

File: tsdb/store.go (hunk 3 above)
Comment (jwilder) [inline tsdb/store.go]: Yes, I left it in to be little more paranoid since it's deleting data.

File: tsdb/store.go [hunk 4]
```diff
@@ -478,21 +471,80 @@ func (s *Store) DeleteMeasurement(database, name string) error {
...
+		go func(sh *Shard) {
+			throttle.take()
+			defer throttle.release()
+
+			if err := fn(sh); err != nil {
+				resC <- &res{err: fmt.Errorf("shard %d: %s", sh.id, err)}
+				return
+			}
+
+			resC <- &res{s: sh}
```
Comment (joelegasse) [inline tsdb/store.go]: The shard field is never used, so this send doesn't really do anything other than signal the work is done. What do you think about using a WaitGroup for the synchronization aspect, rather than counting? `resC` can just be `errC := make(chan error)`, and `go func() { wg.Wait(); close(errC) }` will handle closing the channel so that `for err := range errC` can be used to read the errors.

Comment (joelegasse) [inline tsdb/store.go]: Not directly related to this change, but `throttle` isn't needed. We can just use an empty buffered channel as a semaphore: https://golang.org/ref/mem#tmp_7

File: tsdb/store.go [hunk 5]
```diff
@@ -478,21 +471,80 @@ func (s *Store) DeleteMeasurement(database, name string) error {
...
+// functions return an error, the first error is returned.
+func (s *Store) walkShards(shards []*Shard, fn func(sh *Shard) error) error {
+	// struct to hold the result of opening each reader in a goroutine
+	type res struct {
+		s   *Shard
+		err error
 	}
 
-	return nil
+	throttle := newthrottle(runtime.GOMAXPROCS(0))
```
Comment (joelegasse) [inline tsdb/store.go]: Not directly related to this change, but `throttle` isn't needed. We can just use an empty buffered channel as a semaphore: https://golang.org/ref/mem#tmp_7

Comment (jwilder) [inline tsdb/store.go]: Yes.  The `throttle` type just wraps an empty buffered channel to make it easier to reuse in other places without having to know that trick and embed it everywhere.  I think it's also a little more clear that it's trying limit things when reading the code.

File: tsdb/store.go (hunk 4 above)
Comment (jwilder) [inline tsdb/store.go]: Ah right, the shard is not used here.  It was adapted from the `Open` code which does use it. I'll remove it.

I tend to prefer using channels over `WaitGroup`.

File: tsdb/store.go (hunk 5 above)
Comment (joelegasse) [inline tsdb/store.go]: `throttle` actually fills the channel and uses receive as the "acquire": https://github.com/influxdata/influxdb/blob/master/tsdb/store.go#L869

It's also a struct containing a channel, which you then get a pointer to, rather than just being an aliased type with some methods. It works, but it's just a little messy

Comment (jwilder) [inline tsdb/store.go]: Got it.  Updated with a revised throttle type.

**Comment by joelegasse** [comment]
LGTM 👍

File: tsdb/store.go [hunk 6]
```diff
@@ -388,68 +382,59 @@ func (s *Store) ShardIteratorCreator(id uint64) influxql.IteratorCreator {
...
 	// database.
-	for shardID, sh := range s.shards {
-		if sh.database == database && sh.retentionPolicy == name {
-			// Delete the shard from disk.
-			if err := s.deleteShard(shardID); err != nil {
-				return err
-			}
+	if err := s.walkShards(shards, func(sh *Shard) error {
+		if sh.database != database || sh.retentionPolicy != name {
+			return nil
```
Comment (corylanou) [inline tsdb/store.go]: This should be impossible right?  Is this just being extra defensive?

Comment (jwilder) [inline tsdb/store.go]: Yes

File: tsdb/store.go (hunk 5 above)
Comment (corylanou) [inline tsdb/store.go]: could use `runtime.NumCPU` here instead as well.

Comment (joelegasse) [inline tsdb/store.go]: There's a small chance, but someone could manually override `GOMAXPROCS` to a smaller value than `NumCPU`, in which case we would have increased contention for resources. Reading the current value of `GOMAXPROCS` is probably the better solution, especially since Go 1.5, where it defaults to the number of available CPU cores.
