### PR TITLE
fix(ui): sort by modified now integrated

### LINKED ISSUE #15610: Sort by "Modified" in Dashboards does not sort by modified date
__Steps to reproduce:__
1. Go to Dashboards page
2. Default page is sorted by Name, Click "Modified"
3. Sorting by Modified does not sort by last modified date, continues to sort by name

__Expected behavior:__
When select "Modified", expect dashboards to sort by modified in asc/desc order

__Actual behavior:__
Sorts by Name

dashboards_sortbymodified

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #15610

### Problem

Sorting dashboards by modified dates defaulted to sorting by name

### Solution

Pass in the correct property to sort by so that the orderby function can sort the elements by their appropriate props

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)

### CODE REVIEW

File: ui/src/shared/utils/useVisDomainSettings.ts [hunk 1]
```diff
@@ -22,7 +23,7 @@ export const getValidRange = (
   timeRange: TimeRange | null
 ) => {
   const range = extent((data as number[]) || [])
-  if (!timeRange) {
+  if (isNull(timeRange)) {
```
Comment (Asalem1) [inline ui/src/shared/utils/useVisDomainSettings.ts]: this never sent up with my last PR so I'm including here as per the PR suggestions
