### PR TITLE
fix: avoid rewriting fields.idx unnecessarily

### LINKED ISSUE #21577: Rewriting fields.idx is a bottleneck with many new fields and measurements
When using schema designs that involve many (hundreds of thousands) of 
measurements and fields, the non-incremental rewrites of fields.idx can
become a serious bottleneck. While the IOx storage engine will solve this
in the long run, as a temporary improvement, influxdb should abandon 
rewrites that will be immediately overwritten by subsequent fields and
measurement creation, whenever possible.

### PR DESCRIPTION
**Pull request by davidby-influx**
Under heavy write load creating new fields and measurements
the rewrite of the fields.idx file is a bottleneck. This
enhancement combines multiple writes into a single one and
shares any error return value with all of the combined
invocations.

Closes #21577

- [X] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [X] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [X] Rebased/mergeable
- [X] Tests pass

### CODE REVIEW

File: tsdb/shard.go [hunk 1]
```diff
@@ -1736,73 +1732,127 @@ func (fs *MeasurementFieldSet) IsEmpty() bool {
...
+}
 
-	fd, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR|os.O_EXCL|os.O_SYNC, 0666)
-	if err != nil {
-		return err
-	}
-	defer os.RemoveAll(path)
+func (w *MeasurementFieldSetWriter) RequestSave() error {
+	done := make(chan error)
+	w.writeErrChannels <- done
```
Comment (lesam) [inline tsdb/shard.go:1754]: Read from a newly created channel not used elsewhere should be blocking forever?

File: tsdb/shard.go [hunk 2]
```diff
@@ -1736,73 +1732,127 @@ func (fs *MeasurementFieldSet) IsEmpty() bool {
...
+}
 
-	if _, err := fd.Write(b); err != nil {
-		return err
-	}
+// writeToFile: Write the new index to a temp file and rename when it's sync'd
+func (fs *MeasurementFieldSet) writeToFile(first errorChannel) (errorChannels []errorChannel, err error) {
+	// Put the errorChannel on which we blocked into a slice to allow more invocations
+	// to share the return code from the file write
+	errorChannels = append(errorChannels, first)
```
Comment (lesam) [inline tsdb/shard.go:1774]: nitpick: I would write the error handling as:

defer func() {
  for _, c := range errorChannels {
    c <- err
  }
}()

I don't think the close() should be necessary, hopefully there are not multiple waiters on the channel.

File: tsdb/shard.go [hunk 3]
```diff
@@ -1736,73 +1732,127 @@ func (fs *MeasurementFieldSet) IsEmpty() bool {
...
+			select {
+			case ec := <-fs.writer.writeErrChannels:
+				errorChannels = append(errorChannels, ec)
+				continue
+			default:
+			}
+			break
+		}
+		// Lock, copy, and marshal the in-memory index
+		b, err := fs.marshalMeasurementFieldSet()
```
Comment (lesam) [inline tsdb/shard.go:1815]: Why not re-check for pending writes here? If there's a new write, we could throw away the marshalled data and re-marshal.

Do we have any perf test setup that we could check which way would be better?

**Review by lesam — COMMENTED** [review]
Overall this seems much more straightforward, thanks!

File: tsdb/shard.go (hunk 3 above)
Comment (davidby-influx) [reply tsdb/shard.go:1815]: I didn't recheck because the copying and marshaling locks the structure, preventing new changes to it, so the window for new updates to capture is small, at the cost of significant code complexity. My assumption was that the file open and initial write was a nice blocking IO operation that would let other threads run and possibly modify the MeasurementFieldSet for subsequent capture by the marshalMeasurementFieldSet

File: tsdb/shard.go (hunk 1 above)
Comment (davidby-influx) [reply tsdb/shard.go:1754]: The channel is the one used to signal the completion of the write to file, and should be used exactly once.

File: tsdb/shard.go (hunk 2 above)
Comment (davidby-influx) [reply tsdb/shard.go:1774]: That's a nice style point.

Comment (davidby-influx) [reply tsdb/shard.go:1774]: But you don't even need to return the error, in that case.  The `writeToFile` need not return anything.

Comment (davidby-influx) [reply tsdb/shard.go:1774]: I like the `close` in case there is some magic clean-up, or GC preparation or whatever.  I don't see it as hurting anything, and being a good defensive practice.

File: tsdb/shard.go (hunk 1 above)
Comment (lesam) [reply tsdb/shard.go:1754]: Ah sorry, I misinterpreted a a read from done rather than a send to writeErrChannels.

Can we wrap this in a `request` struct? Sending a channel in a channel is too confusing.

Comment (davidby-influx) [reply tsdb/shard.go:1754]: Sure.  You had had that in your prototype, and I didn't like the proliferation of single-field structures. But, if you think it's clearer, happy to oblige.

File: tsdb/shard.go [hunk 4]
```diff
@@ -1736,73 +1738,138 @@ func (fs *MeasurementFieldSet) IsEmpty() bool {
...
 
-	fd, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR|os.O_EXCL|os.O_SYNC, 0666)
-	if err != nil {
-		return err
+func (w *MeasurementFieldSetWriter) Close() {
+	if w != nil {
+		close(w.writeRequests)
 	}
-	defer os.RemoveAll(path)
+}
```
Comment (lesam) [inline tsdb/shard.go:1762]: `Close` should block until the writer goroutine exits.

**Review by lesam — DISMISSED** [review]

**Review by lesam — APPROVED** [review]

**Review by danxmoran — APPROVED** [review]
Is there already a ticket for forward-porting to 2.x?
