### PR TITLE
fix(ui): add label from resource labels editor

### LINKED ISSUE #11624: Add ability to create a new label while adding labels to a resource.
Add ability to create a new label while adding labels to a resource. Labels should be able to be created on the fly instead of only on the config page.

### PR DESCRIPTION
**Pull request by OfTheDelmer**
Closes #11624

_Briefly describe your proposed changes:_
Add resource label creation form when label is not present. Tune label filtering to not aggressively match labels not in the list to more easily enable user to create a new label. Add a random color button instead of a color dropdown which does not work well in the label list dropdown.

  - [ ] Rebased/mergeable
  - [ ] Tests pass
  - [ ] http/swagger.yml updated (if modified Go structs or API)
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
kapture 2019-02-21 at 7 29 57

### CODE REVIEW

File: ui/src/configuration/components/RandomLabelColor.tsx [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+import 'src/configuration/components/RandomLabelColor.scss'
+
+interface Props {
+  colorHex: string
+  onClick: (newRandomHex: string) => void
+}
+
+export default class RandomLabelColorButton extends Component<Props> {
+  public componentDidMount() {
+    this.handleClick()
```
Comment (chnn) [inline ui/src/configuration/components/RandomLabelColor.tsx]: Using the mount of the component to eventually provide data from higher up in the render tree feels a bit funky. Can the color be generated for the first time outside of this component and then passed in?

**Comment by mavarius** [comment]
Closes #11978
