### PR TITLE
fix(catalog): consistent ordering of catalog operations

### LINKED ISSUE #25667: v3 Race condition on schema creation
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.
1. Trigger the write_lp() pathway for a table that doesn't exist yet twice. In normal usage this will be an _extremely_ tight race, as if the first row creates that table and parsing it finishes, this bug won't occur. The Cow<DatabaseSchema> created [here](https://github.com/influxdata/influxdb/blob/7d92b75731eba6c973a61ec3967864c093d262c3/influxdb3_write/src/write_buffer/validator.rs#L174) has to be missing the table in both calls
2. Both will detect the table is missing and go to create it, inserting it atomically. The second one will then panic [here](https://github.com/influxdata/influxdb/blob/7d92b75731eba6c973a61ec3967864c093d262c3/influxdb3_write/src/write_buffer/validator.rs#L478). 

__Expected behaviour:__
One of them will be create the table, the other will detect that and use the schema. Functionally, the behavior should be identical to the two inputs being interleaved in some manner.

__Actual behaviour:__
The second call panics. Since the view of the database schema didn't originally have a table, it expects to be able to create it.

__Environment info:__
I'm running on an M3 OS X machine locally, using the --quick-release target and filesystem. This was discovered when implementing processing engine plugins that read data off a shared queue and write back to a table. It probably takes something like that to reproduce in the wild, and even then doesn't happen reliably.

__Logs:__
```
2024-12-17T00:22:32.480694Z ERROR panic_logging: Thread panic panic_type="unknown" panic_message="attempted to overwrite existing table" panic_file="influxdb3_write/src/write_buffer/validator.rs" panic_line=696 panic_column=9
thread 'InfluxDB 3.0 Tokio IO 8' panicked at influxdb3_write/src/write_buffer/validator.rs:696:9:
attempted to overwrite existing table
```

### PR DESCRIPTION
**Pull request by jacksonrnewhouse**
Closes #25667 

In looking at addressing #25667 I found a class of race conditions related to inconsistencies between the ordering of catalog operations against the in-memory Catalog versus how they were written to the WAL. For example, if write calls A and B are both writing to table `foo`, one might create the table while the other adds some field. If the order of the WAL calls is different than the order of the original invocations the system will fail on restoration, as it'll receive a field addition for a table it hasn't yet created.

The new approach is for the WalOps to be take an `OrderedCatalogBatch`, which will have been produced by calling `apply_catalog_batch`. We then sort the WalOps by a newly defined order, putting the catalog ops first, sorted by catalog_sequence_number.

Following on the work in #25642, I've removed the dedicated methods `add_meta_cache()`, `remove_meta_cache()`, `add_last_cache()`, `delete_last_cache()`, instead relying on the apply_catalog_batch() method.  @hiltontj, can you take a look to make sure this was done safely?

### CODE REVIEW

**Comment by pauldix** [comment]
PR and commit subject should be `fix: consistent ordering of catalog operations` with the space after the `:`

**Review by pauldix — APPROVED** [review]
I think this looks good, but I'd like @hiltontj to have a look too.

File: influxdb3_write/src/persister.rs [hunk 1]
```diff
@@ -754,11 +757,11 @@ mod tests {
         }
         let snapshots = persister.load_snapshots(9500).await.unwrap();
         // We asked for the most recent 9500 so there should be 9001 of them
```
Comment (hiltontj) [inline influxdb3_write/src/persister.rs:759]: This comment is stale now.

File: influxdb3_write/src/write_buffer/mod.rs [hunk 2]
```diff
@@ -1748,6 +1766,9 @@ mod tests {
         assert_eq!(ParquetFileId::next_id().as_u64(), 6);
     }
 
+    #[tokio::test]
+    async fn catalog_ops_correctly_ordered() {}
+
```
Comment (hiltontj) [inline influxdb3_write/src/write_buffer/mod.rs:1771]: Still planning to write this one? 😃

**Review by hiltontj — APPROVED** [review]
This looks good to me @jacksonrnewhouse - removing the create/delete methods on the catalog for the last/meta caches looks a lot cleaner and also looks sound to me.

👍 on having all changes go through a single point (`apply_catalog_batches`).

I left a couple comments on things I noticed but they are not blockers for this PR.

File: influxdb3_write/src/persister.rs (hunk 1 above)
Comment (jacksonrnewhouse) [reply influxdb3_write/src/persister.rs:759]: Right, I bumped this down because I was running out of file descriptors on my machine.

File: influxdb3_write/src/write_buffer/mod.rs (hunk 2 above)
Comment (jacksonrnewhouse) [reply influxdb3_write/src/write_buffer/mod.rs:1771]: No, wrote it somewhere else.

File: influxdb3_write/src/persister.rs (hunk 1 above)
Comment (hiltontj) [reply influxdb3_write/src/persister.rs]: Ah yes, that kept getting me too, good call.
