### PR TITLE
fix(restore): fix race condition which could cause restore command to fail

### LINKED ISSUE #22957: Restore command fails on some shards [port 2.x]
Port #15323 to master (2.x)

### PR DESCRIPTION
**Pull request by gwossum**
Fixes a race condition in the restore code path that could cause shard data restores to fail. When the race condition occurs, `Error while freeing cold shard resources` appears in the log files.

This is port of PR 22796 from master-1.x to master. Attempts at creating a test case for master failed, so the fix has ported without a corresponding unit test.

fixes #22957

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: tsdb/shard.go [hunk 1]
```diff
@@ -356,10 +361,24 @@ func (s *Shard) Path() string { return s.path }
...
+			err = werr
+		}
+	}
+	return err
+}
 
+// openNoLock performs work of Open. Must hold s.mu before calling. The first return
+// value is true if the caller should call closeWait after unlocking s.mu in order
+// to clean up a failed open operation.
+func (s *Shard) openNoLock(ctx context.Context) (bool, error) {
```
Comment (davidby-influx) [inline tsdb/shard.go:380]: Is the bool return necessary? I only spot two `return` statements, with error and true and without error and false.

**Review by davidby-influx — APPROVED** [review]
One non-blocking nitpick.  Feel free to merge without any changes if you prefer.

File: tsdb/shard.go (hunk 1 above)
Comment (gwossum) [reply tsdb/shard.go:380]: I agree it's kind of clunky, but it's a future safety thing. We want to make it clear to callers of `openNoLock` that they will need to handle calling `closeWait`, but we also want to make sure that callers don't call `closeWait` unless `closeNoLock` was closed first. Currently all error return cases indicate that the caller should call `openNoLock`, but that may not be true in the future.

As the code stands right now, `openNoLock` could be eliminated, as the only place it is called from is `Open`. This made more sense when I originally implemented it, but the changes I had to make to handle the closing the `metricsUpdater` cause everything to call `Open` again.
