### PR TITLE
fix: query bugs with buffer

### LINKED ISSUE #25206: Create integration test for WriteBufferImpl to validate wal flushing and snapshotting
We should have some higher level integration tests to validate WAL flushes and replay bring data back into the buffer. Further, we should validate that snapshots persist parquet data, persist the catalog, and persist snapshot info files. Finally, validate that reloading a write buffer will contain all of that snapshotted data.

Follow on work for #25196

### PR DESCRIPTION
**Pull request by pauldix**
This fixes three different bugs with the buffer. First was that aggregations would fail because projection was pushed down to the in-buffer data that de-duplication needs to be called on. The test in influxdb3/tests/server/query.rs catches that.

I also added a test in write_buffer/mod.rs to ensure that data is correctly queryable when combining with different states: only data in buffer, only data in parquet files, and data across both. This showed two bugs, one where the parquet data was being doubled up (parquet chunks were being created in write buffer mod and in queryable buffer. The second was that the timestamp min max on table buffer would panic if the buffer was empty.

Closes #25206, #25215

### CODE REVIEW

**Review by mgattozzi — CHANGES_REQUESTED** [review]
The changes are fine, but I had a suggestion/question around projection

File: influxdb3_write/src/write_buffer/queryable_buffer.rs [hunk 1]
```diff
@@ -68,39 +66,19 @@ impl QueryableBuffer {
         db_schema: Arc<DatabaseSchema>,
         table_name: &str,
         filters: &[Expr],
-        projection: Option<&Vec<usize>>,
+        _projection: Option<&Vec<usize>>,
```
[the remark this answers is not in the document]
Comment (pauldix) [reply influxdb3_write/src/write_buffer/queryable_buffer.rs:69]: We will want to at some point. That is part of the signature for the `ChunkContainer` that the write buffer implements. Ideally, we'd use the passed in projection and have all record batches include all tags/keys, time and any fields in the projection. All other fields can be bypassed. I've logged #25220 to track that work.

File: influxdb3_write/src/write_buffer/mod.rs [hunk 2]
```diff
@@ -793,6 +793,139 @@ mod tests {
...
+                max_write_buffer_size: 100,
+                flush_interval: Duration::from_millis(10),
+                snapshot_size: 2,
+            },
+        )
+        .await
+        .unwrap();
+        let session_context = IOxSessionContext::with_testing();
+        let runtime_env = session_context.inner().runtime_env();
+        register_iox_object_store(runtime_env, "influxdb3", Arc::clone(&object_store));
```
Comment (hiltontj) [inline influxdb3_write/src/write_buffer/mod.rs:818]: There is a `setup` helper below that does all of these steps, although, to use it here, looks like you would need to parameterize the different parts of the `WalConfig` in the function signature.

**Review by hiltontj — APPROVED** [review]
One discretionary comment - otherwise LGTM.

File: influxdb3_write/src/write_buffer/mod.rs (hunk 2 above)
Comment (pauldix) [reply influxdb3_write/src/write_buffer/mod.rs]: Parameterized in 1eed007c4088b2055a6336dfea484f992452d5ce

**Review by hiltontj — APPROVED** [review]

**Comment by pauldix** [comment]
Going to merge this in as @mgattozzi is out today. I can remove the `_projection` parameter in a follow up PR or do #25220
