### PR TITLE
fix(bolt): prevent concurrent access to telegraf plugin metrics cache

### LINKED ISSUE #20999: panic in bolt/metrics.go due to concurrent map iteration and map write
Every couple of days my influxdb dies with a panic (e.g. after 13452 or 236 or 6725) minutes.

Linux orfeo 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

ts=2021-03-18T09:19:17.915373Z lvl=info msg="Welcome to InfluxDB" log_id=0Sy9xmbl000 version=2.0.4 commit=4e7a59bb9a build_date=2021-02-08T17:47:02Z

Prometheus is at version 2.25.0

fatal error: concurrent map iteration and map write
goroutine 20561008 [running]:
runtime.throw(0x279ee19, 0x26)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc049e89bf0 sp=0xc049e89bc0 pc=0x438af2
runtime.mapiternext(0xc049e89e68)
        /usr/local/go/src/runtime/map.go:853 +0x554 fp=0xc049e89c70 sp=0xc049e89bf0 pc=0x412134
runtime.mapiterinit(0x237bde0, 0xc0635042a0, 0xc049e89e68)
        /usr/local/go/src/runtime/map.go:843 +0x1c5 fp=0xc049e89c90 sp=0xc049e89c70 pc=0x411ae5
github.com/influxdata/influxdb/v2/bolt.(*Client).Collect(0xc00186e000, 0xc065192240)
        /home/circleci/go/src/github.com/influxdata/influxdb/bolt/metrics.go:223 +0x835 fp=0xc049e89ed8 sp=0xc
049e89c90 pc=0x1008995
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/circleci/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:443 +0x1a2
 fp=0xc049e89fe0 sp=0xc049e89ed8 pc=0xb5b2a2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc049e89fe8 sp=0xc049e89fe0 pc=0x471821
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/circleci/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:454 +0x5ce

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #20999 

I'm not happy with the timing-based pieces of the test I added, but it's probably better than nothing?

### CODE REVIEW

File: bolt/metrics.go [hunk 1]
```diff
@@ -84,38 +85,92 @@ func (c *Client) Describe(ch chan<- *prometheus.Desc) {
...
 }
 
-type instaTicker struct {
-	tick   chan struct{}
-	timeCh <-chan time.Time
+type pluginMetricsCollector struct {
+	ticker     *time.Ticker
+	tickerDone chan struct{}
+	cache      map[string]float64
+	cacheMu    sync.RWMutex
```
Comment (lesam) [inline bolt/metrics.go:98]: It's fairly obvious from the name, but I would have written something like:

```
type pluginMetricsCollector struct {
 	ticker     *time.Ticker
 	tickerDone chan struct{}
 	
 	// cacheMu protects the cache
 	cacheMu    sync.RWMutex
 	cache      map[string]float64
 }
 ```

File: bolt/metrics.go [hunk 2]
```diff
@@ -84,38 +85,92 @@ func (c *Client) Describe(ch chan<- *prometheus.Desc) {
...
+			telegrafPluginsDesc,
+			prometheus.GaugeValue,
+			v,
+			k, // Adds a label for plugin type.name.
+		)
+	}
+}
+
+func (c *pluginMetricsCollector) Close() {
+	close(c.tickerDone)
```
Comment (lesam) [inline bolt/metrics.go:165]: Do you care if `refreshTelegrafStats` was started earlier and is still running even after you call Close?

File: bolt/metrics_test.go [hunk 3]
```diff
@@ -38,3 +47,85 @@ func TestInitialMetrics(t *testing.T) {
...
+	// Register some more plugins.
+	tconf = influxdb.TelegrafConfig{
+		Name:   "test",
+		Config: "[[inputs.mem]]\n[[outputs.influxdb_v2]]",
+		OrgID:  1,
+	}
+	require.NoError(t, tsvc.CreateTelegrafConfig(ctx, &tconf, 2))
+
+	// Let a few more background gathers run.
+	time.Sleep(250 * time.Millisecond)
```
Comment (lesam) [inline bolt/metrics_test.go:120]: These sleeps seem fine, we want to flush out race conditions.

File: bolt/metrics.go (hunk 2 above)
Comment (danxmoran) [reply bolt/metrics.go:165]: It probably doesn't matter since we're ignoring errors within `refreshTelegrafStats`, but I'll throw a `c.cacheMu.Lock()` at the front of this to be safe

File: bolt/metrics.go [hunk 4]
```diff
@@ -84,38 +85,98 @@ func (c *Client) Describe(ch chan<- *prometheus.Desc) {
...
+			v,
+			k, // Adds a label for plugin type.name.
+		)
+	}
+}
+
+func (c *pluginMetricsCollector) Close() {
+	// Wait for any already-running cache-refresh procedures to complete.
+	c.cacheMu.Lock()
+	defer c.cacheMu.Unlock()
```
Comment (lesam) [inline bolt/metrics.go:169]: this is actually insufficient - we could get the tick and start processing on https://github.com/influxdata/influxdb/pull/21042/files#diff-17f5e7b462f5c1258a2de08fcae83ff101227e80cb005d86222331ef263deeccR112 ,

then take the lock here and call `close`,

then take the lock in `refreshTelegrafStats`

Comment (lesam) [reply bolt/metrics.go:169]: If you want to enforce this, you can check `tickerDone` under the lock every other time we take it.

**Review by lesam — APPROVED** [review]
