### PR TITLE
Fix series not getting created

### LINKED ISSUE #8169: Index disappears after compaction
While running a largish stress test using `influx_stress` on https://github.com/influxdata/influxdb/commit/5d67c424bfb44add94698e3be94da3c11c94d20c series data disappears after a while.

A reboot of the server bring the data back. It's probably index/snapshot related.

`influx_stress` config:

```
[provision]
  [provision.basic]
    enabled = true
    address = "localhost:8086"
    database = "stress"
    reset_database = true

[write]
  [write.point_generator]
    [write.point_generator.basic]
      enabled = true
      point_count = 100
      series_count = 400000
      tick = "10s"
      jitter = true
      measurement = "cpu"
      start_date = "2006-Jan-02"
      [[write.point_generator.basic.tag]]
        key = "host"
        value = "server"
      [[write.point_generator.basic.tag]]
        key = "location"
        value = "us-west"
      [[write.point_generator.basic.field]]
        key = "value"
        value = "float64"


  [write.influx_client]
    [write.influx_client.basic]
      enabled = true
      addresses = ["localhost:8086"] # stress_test_server runs on port 1234
      database = "stress"
      precision = "n"
      batch_size = 10000
      batch_interval = "0s"
      concurrency = 100
      ssl = false
      format = "line_http" # line_udp, graphite_tcp, graphite_udp

[read]
  [read.query_generator]
    [read.query_generator.basic]
      template = "SELECT count(value) FROM cpu where host='server-%v'"
      query_count = 700

  [read.query_client]
    [read.query_client.basic]
      enabled = true
      addresses = ["localhost:8086"]
      database = "stress"
      query_interval = "100ms"
      concurrency = 10

```

### PR DESCRIPTION
**Pull request by jwilder**
`n` only gets updated when there are max tag values limits set.  The re-slicing slices off all series that need to get created causing them to not get created.

Fixes #8169

### CODE REVIEW

File: tsdb/index/inmem/inmem.go [hunk 1]
```diff
@@ -701,10 +701,13 @@ type ShardIndex struct {
...
 // CreateSeriesListIfNotExists creates a list of series if they doesn't exist in bulk.
 func (idx *ShardIndex) CreateSeriesListIfNotExists(keys, names [][]byte, tagsSlice []models.Tags) error {
-	// Ensure that no tags go over the maximum cardinality.
 	var reason string
-	var dropped, n int
+	var dropped int
+
+	// Ensure that no tags go over the maximum cardinality.
 	if maxValuesPerTag := idx.opt.Config.MaxValuesPerTag; maxValuesPerTag > 0 {
+		var dropped, n int
```
Comment (benbjohnson) [inline tsdb/index/inmem/inmem.go]: This `dropped` is shadowing the `dropped` above. It will never be non-zero for this `if`: https://github.com/influxdata/influxdb/blob/3b25cffda4a1e2b05a18ebb42a95cf18fa4b2412/tsdb/index/inmem/inmem.go#L748-L754

Comment (jwilder) [inline tsdb/index/inmem/inmem.go]: Fixed in 5515785
