### PR TITLE
fix panic in query execution

### LINKED ISSUE #7880: [1.2] Dividing an aggregate function with elapsed() throws panic
version tested: 1.2

Description: `sum(count::float) / elapsed(sum(count::float), 1m)` throws panic.

Repro case using actual sample dataset: `influx -import -path=sample.txt`

[sample.txt](https://github.com/influxdata/influxdb/files/729951/sample.txt)

```
use repro

SELECT sum(count::float) / elapsed(sum(count::float), 1m) FROM jvm_threads WHERE time > '2017-01-25T06:40:41.663090514Z' GROUP BY time(1m) fill(previous)
```

response is:

```
[panic:runtime error: invalid memory address or nil pointer dereference]
```

log excerpt:

```
25 16:16:13 ubuntu16 influxd[27798]: runtime/debug.Stack(0xc423ff9ba0, 0xc422182bb0, 0xa7)
25 16:16:13 ubuntu16 influxd[27798]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
25 16:16:13 ubuntu16 influxd[27798]: github.com/influxdata/influxdb/influxql.(*QueryExecutor).recover(0xc420154660, 0xc423ff9ba0, 0xc422a812c0)
25 16:16:13 ubuntu16 influxd[27798]:         /root/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:362 +0x96
25 16:16:13 ubuntu16 influxd[27798]: panic(0xa03980, 0xc420010070)
25 16:16:13 ubuntu16 influxd[27798]:         /usr/local/go/src/runtime/panic.go:458 +0x243
25 16:16:13 ubuntu16 influxd[27798]: github.com/influxdata/influxdb/influxql.(*floatExprIterator).Next(0xc421b0a200, 0xe2bce0, 0xc421b0a200, 0xc42655b7a0)
25 16:16:13 ubuntu16 influxd[27798]:         /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1290 +0x13a
25 16:16:13 ubuntu16 influxd[27798]: github.com/influxdata/influxdb/influxql.(*Emitter).readIterator(0xc4205ec300, 0xe2bce0, 0xc421b0a200, 0xc42655b8b8, 0xc422d6c0e0, 0xc422186440, 0xc42606c06
25 16:16:13 ubuntu16 influxd[27798]:         /root/go/src/github.com/influxdata/influxdb/influxql/emitter.go:195 +0xc2
25 16:16:13 ubuntu16 influxd[27798]: github.com/influxdata/influxdb/influxql.(*Emitter).loadBuf(0xc4205ec300, 0xc42655b8e8, 0x0, 0x0, 0x0, 0xc3, 0xc422d6c0e0, 0xb, 0x0)
25 16:16:13 ubuntu16 influxd[27798]:         /root/go/src/github.com/influxdata/influxdb/influxql/emitter.go:101 +0x778
25 16:16:13 ubuntu16 influxd[27798]: github.com/influxdata/influxdb/influxql.(*Emitter).Emit(0xc4205ec300, 0xbac548, 0xc4205ec300, 0x2, 0x1)
25 16:16:13 ubuntu16 influxd[27798]:         /root/go/src/github.com/influxdata/influxdb/influxql/emitter.go:53 +0x60
25 16:16:13 ubuntu16 influxd[27798]: github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc42016c070, 0xc421986e00, 0xc42655bc68, 0x0, 0x0)
25 16:16:13 ubuntu16 influxd[27798]:         /root/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:454 +0x3f0
25 16:16:13 ubuntu16 influxd[27798]: github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc42016c070, 0xe324a0, 0xc421986e00, 0x0, 0x8, 0xc422a813e0, 0xc422a812c0
25 16:16:13 ubuntu16 influxd[27798]:         /root/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:57 +0x2afc
25 16:16:13 ubuntu16 influxd[27798]: github.com/influxdata/influxdb/influxql.(*QueryExecutor).executeQuery(0xc420154660, 0xc423ff9ba0, 0xc42479731c, 0x5, 0x2710, 0x0, 0x0, 0x0, 0xc422a81200, 0
25 16:16:13 ubuntu16 influxd[27798]:         /root/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:312 +0x55d
25 16:16:13 ubuntu16 influxd[27798]: created by github.com/influxdata/influxdb/influxql.(*QueryExecutor).ExecuteQuery
25 16:16:13 ubuntu16 influxd[27798]:         /root/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:207 +0xb5
25 16:16:13 ubuntu16 influxd[27798]:  service=query
```

### PR DESCRIPTION
**Pull request by corylanou**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass

fixes #7880

### CODE REVIEW

File: cmd/influxd/run/server_test.go [hunk 1]
```diff
@@ -7356,3 +7356,38 @@ func TestServer_Query_Sample_Wildcard(t *testing.T) {
...
+	test := NewTest("db0", "rp0")
+	test.writes = Writes{
+		&Write{data: strings.Join(writes, "\n")},
+	}
+
+	test.addQueries([]*Query{
+		&Query{
+			name:    "dividing by elapsed count should not panic",
+			params:  url.Values{"db": []string{"db0"}},
+			command: `SELECT sum(count::float) / elapsed(sum(count::float), 1m) FROM jvm_threads WHERE time > '2017-01-25T06:40:41.663090514Z' GROUP BY time(1m) fill(previous)`,
```
Comment (jsternberg) [inline cmd/influxd/run/server_test.go]: Can you add an expected output for this?

File: influxql/iterator.gen.go [hunk 2]
```diff
@@ -1287,6 +1287,11 @@ func (itr *floatExprIterator) Next() (*FloatPoint, error) {
 			if itr.points == nil {
 				continue
 			}
+
+			if b == nil || b.Nil {
```
Comment (jsternberg) [inline influxql/iterator.gen.go]: Can you modify this so it's `} else if b == nil {`?

Also, if b is not nil so `b.Nil` is true, that's fine. We don't want to exclude that since that's a valid value. We only want to restrict when `b == nil`.

File: influxql/iterator.gen.go [hunk 3]
```diff
@@ -2297,6 +2304,7 @@ func (itr *floatBooleanExprIterator) Next() (*BooleanPoint, error) {
 			if itr.points == nil {
 				continue
 			}
+
```
Comment (jsternberg) [inline influxql/iterator.gen.go]: You need to include something for when the types are not the same otherwise you're leaving a hole (for boolean statements mostly).

File: cmd/influxd/run/server_test.go (hunk 1 above)
Comment (corylanou) [inline cmd/influxd/run/server_test.go]: The expected output is so large it becomes chunked and the test suite isn't set up for that.  I would have to put some work into the test suite to see that happen.

File: influxql/iterator.gen.go (hunk 3 above)
Comment (corylanou) [inline influxql/iterator.gen.go]: yeah, I have no idea what that would be....  I don't even know what this method even does.  Comments FTW :-).

I would need your help on this to figure it out.

File: cmd/influxd/run/server_test.go (hunk 1 above)
Comment (jsternberg) [inline cmd/influxd/run/server_test.go]: Is it possible to make a smaller test case for this that would cause the issue? I think this would happen in any situation where the last value is null. So if you did something like:

```
> INSERT cpu value=2 0
> SELECT sum(value) / elapsed(sum(value), 1m) FROM cpu WHERE time >= 0 AND time < '10m' GROUP BY time(1m)
```

You might need to insert more values for each minute except the last, but I think that should work.

**Comment by jwilder** [comment]
Appveyor failed for some reason.
