### PR TITLE
fix: remove nats for scraper processing

### LINKED ISSUE #23085: When a bucket for a scraper is deleted, it causes a memory leak
InfluxDB buffers unsuccessful scraper runs in memory. If the bucket to write the scraper runs to is deleted, the scraper never succeeds and data is buffered forever (or until the memory runs out).

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a scraper
2. Delete the target bucket
3. Watch the memory increase

__Expected behavior:__
Only a fixed amount of memory should be used for buffering scraper runs. It should be clear to users if a scraper is not working.

__Actual behavior:__
Unlimited memory is used to buffer scraper runs. It is not clear to users that a scraper is failing.

See https://influxcommunity.slack.com/archives/CH8RV8PK5/p1637252397427300?thread_ts=1637159075.389000&cid=CH8RV8PK5

### LINKED ISSUE #23106: Deleting a bucket does not delete the TSDB engine metadata for the bucket
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Configure a scraper
2. Delete the bucket for the scraper via the API
3. Observe the bucket 'come back' after a few seconds when the scraper runs

__Expected behavior:__
The bucket is deleted so the scraper should error. We should be deleting the metadata from the TSDB layer during bucket deletes.

__Actual behavior:__
The scraper writes at the TSDB layer, not the bucket layer. So while front-door API writes to the bucket fail, the scraper writes simply re-create the bucket on disk as the TSDB layer is not aware the bucket was deleted.

### PR DESCRIPTION
**Pull request by lesam**
Scrapers now use go channels instead of NATS and interprocess communication.

Closes  #23085
Closes  #23106

Describe your proposed changes here.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: cmd/influxd/launcher/cmd.go [hunk 1]
```diff
@@ -591,20 +586,6 @@ func (o *InfluxdOpts) BindCliOpts() []cli.Opt {
...
-			Flag:    "nats-port",
-			Desc:    fmt.Sprintf("Port that should be bound by the NATS streaming server. A value of %d will cause a random port to be selected.", nats.RandomPort),
-			Default: o.NatsPort,
-		},
-		{
-			DestP:   &o.NatsMaxPayloadBytes,
-			Flag:    "nats-max-payload-bytes",
-			Desc:    "The maximum number of bytes allowed in a NATS message payload.",
-			Default: o.NatsMaxPayloadBytes,
-		},
```
Comment (DStrand1) [inline cmd/influxd/launcher/cmd.go:606]: Do we want to do anything with these flags to allow for them to be in existing scripts and not cause problems?

**Review by DStrand1 — APPROVED** [review]
I don't know much about NATS, but the changes made look good to me. Nice to remove some dependencies, especially some big ones like Bolt. I had just one small discussion point
