### PR TITLE
Teach the CQ runner how to deal with a resample interval higher than the query interval

### LINKED ISSUE #5286: [0.10.0] Unexpected behavior for CQs with EVERY
Unexpectedly, when I just include `EVERY` in the `RESAMPLE` clause the CQ doesn't seem to run:
```
CREATE CONTINUOUS QUERY eight ON telegraf RESAMPLE EVERY 4m BEGIN SELECT count(value) INTO telegraf."default".eight FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' GROUP BY time(2m) END
```

As expected, when I just include `FOR` in the `RESAMPLE` clause the CQ runs every two minutes and has four queries per run:
```
CREATE CONTINUOUS QUERY seventh ON telegraf RESAMPLE FOR 8m BEGIN SELECT count(value) INTO telegraf."default".seventh FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' GROUP BY time(2m) END
```

When I add `EVERY 4m` to the CQ above, I expected it to run every four minutes and have four queries per run:
```
CREATE CONTINUOUS QUERY fifth ON telegraf RESAMPLE EVERY 4m FOR 8m BEGIN SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' GROUP BY time(2m) END
```

Logs:
```
[continuous_querier] 2016/01/06 09:44:00 executing continuous query fifth (2016-01-06 09:40:00 -0800 PST to 2016-01-06 09:42:00 -0800 PST)
[query] 2016/01/06 09:44:00 SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' AND time >= '2016-01-06T17:40:00Z' AND time < '2016-01-06T17:42:00Z' GROUP BY time(2m)
[continuous_querier] 2016/01/06 09:44:00 executing continuous query fifth (2016-01-06 09:38:00 -0800 PST to 2016-01-06 09:40:00 -0800 PST)
[query] 2016/01/06 09:44:00 SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' AND time >= '2016-01-06T17:38:00Z' AND time < '2016-01-06T17:40:00Z' GROUP BY time(2m)
[continuous_querier] 2016/01/06 09:44:00 executing continuous query fifth (2016-01-06 09:36:00 -0800 PST to 2016-01-06 09:38:00 -0800 PST)
[query] 2016/01/06 09:44:00 SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' AND time >= '2016-01-06T17:36:00Z' AND time < '2016-01-06T17:38:00Z' GROUP BY time(2m)

[continuous_querier] 2016/01/06 09:48:00 executing continuous query fifth (2016-01-06 09:44:00 -0800 PST to 2016-01-06 09:46:00 -0800 PST)
[query] 2016/01/06 09:48:00 SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' AND time >= '2016-01-06T17:44:00Z' AND time < '2016-01-06T17:46:00Z' GROUP BY time(2m)
[continuous_querier] 2016/01/06 09:48:00 executing continuous query fifth (2016-01-06 09:42:00 -0800 PST to 2016-01-06 09:44:00 -0800 PST)
[query] 2016/01/06 09:48:00 SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' AND time >= '2016-01-06T17:42:00Z' AND time < '2016-01-06T17:44:00Z' GROUP BY time(2m)
[continuous_querier] 2016/01/06 09:48:00 executing continuous query fifth (2016-01-06 09:40:00 -0800 PST to 2016-01-06 09:42:00 -0800 PST)
[query] 2016/01/06 09:48:00 SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' AND time >= '2016-01-06T17:40:00Z' AND time < '2016-01-06T17:42:00Z' GROUP BY time(2m)


[continuous_querier] 2016/01/06 09:52:00 executing continuous query fifth (2016-01-06 09:48:00 -0800 PST to 2016-01-06 09:50:00 -0800 PST)
[query] 2016/01/06 09:52:00 SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' AND time >= '2016-01-06T17:48:00Z' AND time < '2016-01-06T17:50:00Z' GROUP BY time(2m)
[continuous_querier] 2016/01/06 09:52:00 executing continuous query fifth (2016-01-06 09:46:00 -0800 PST to 2016-01-06 09:48:00 -0800 PST)
[query] 2016/01/06 09:52:00 SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' AND time >= '2016-01-06T17:46:00Z' AND time < '2016-01-06T17:48:00Z' GROUP BY time(2m)
[continuous_querier] 2016/01/06 09:52:00 executing continuous query fifth (2016-01-06 09:44:00 -0800 PST to 2016-01-06 09:46:00 -0800 PST)
[query] 2016/01/06 09:52:00 SELECT count(value) INTO telegraf."default".fifth FROM telegraf."default".cpu_usage_idle WHERE cpu = 'cpu-total' AND time >= '2016-01-06T17:44:00Z' AND time < '2016-01-06T17:46:00Z' GROUP BY time(2m)
```

The CQ runs every four minutes, but I only see three queries per run. Focusing on the first run, the CQ runs at `17:44:00` and executes three queries for the following time ranges:
```
time >= '2016-01-06T17:40:00Z' AND time < '2016-01-06T17:42:00Z'
time >= '2016-01-06T17:38:00Z' AND time < '2016-01-06T17:40:00Z'
time >= '2016-01-06T17:36:00Z' AND time < '2016-01-06T17:38:00Z'
```
I'd expect to see one more query with the time range `time >= '2016-01-06T17:42:00Z' AND time < '2016-01-06T17:44:00Z'`.

### PR DESCRIPTION
**Pull request by jsternberg**
Previously if you issued a CQ with a resample interval higher than the
query interval, such as the following:

    CREATE CONTINUOUS QUERY cq ON db
        RESAMPLE EVERY 4m
        BEGIN
            SELECT mean(value) INTO cpu_mean FROM cpu GROUP BY time(2m)
        END

This would result in strange behavior because the FOR value defaulted to
the GROUP BY interval and the minimum time passing before a CQ ran was
also the resample interval, so it wouldn't run the appropriate intervals
even if you set the resample duration to a higher value.

This tweaks the CQ runner to set the minimum interval before a bucket
becomes capable of running to the lower of the query interval or the
resample interval instead of always using the resample interval.

It also sets the default resample duration to be the higher value of the
query interval or the resample interval so the above query gets a
default of 4m instead of 2m and will execute 2 queries every 4 minutes.

If you manually set the resample duration to a lower value than the
resample interval, the old behavior will still happen and should be
considered an error.

Fixes #5286.

### CODE REVIEW

**Comment by jwilder** [comment]
LGTM :+1: but maybe @dgnorton or @corylanou could take look.  They might be more familiar with this code than I am.

**Comment by dgnorton** [comment]
@jsternberg should it error at parse time if it's higher than the `GROUP BY` time?

**Comment by jsternberg** [comment]
I think it's reasonable for a person to want to run a continuous query less often than the group by interval. It may be good though to add a check that makes sure a `FOR` section isn't lower than an `EVERY` section though. So when a person says "group my queries by 2 minute intervals and run every 4 minutes" they get exactly what they're expecting of 2 queries to run every 4 minutes.

**Comment by gunnaraasen** [comment]
@dgnorton I agree with @jsternberg that allowing the resample interval to be larger than the `GROUP BY` interval is a desirable feature. For instance, only running a set of 1m CQs every 5m.

Ensuring the `FOR` is always higher than the `EVERY` and `GROUP BY` duration would be a good error check.

**Comment by dgnorton** [comment]
@jsternberg @gunnaraasen okay, just wanted to make sure it was given some thought.

@jsternberg can you add the `FOR` check you and @gunnaraasen  mentioned?  Other than that I think it looks good.

**Comment by jsternberg** [comment]
Should we also check for a valid group by interval? The current behavior seems to be to ignore queries like that and don't run them, but I would argue that those continuous queries should have always been an error. On the other hand, it would be a breaking change since someone could have made those queries and they would just silently do nothing.

We do have a test though that checks if you can make a continuous query with no interval, so I'm not sure where we stand on that.

**Comment by gunnaraasen** [comment]
I think there's a use case in the future for CQs which "fan out" or transform data into new measurements/retention policies and would not need a `GROUP BY` statement. However, I'm fairly sure that functionality is not currently supported so there's likely no harm in adding an error there for now.

**Comment by jsternberg** [comment]
@dgnorton can I get a code review of the statement validation?

File: influxql/ast.go [hunk 1]
```diff
@@ -2019,6 +2019,23 @@ func (s *CreateContinuousQueryStatement) RequiredPrivileges() ExecutionPrivilege
...
+	if err != nil {
+		return err
+	}
+
+	if s.ResampleFor != 0 {
+		if s.ResampleEvery != 0 && s.ResampleEvery > interval {
+			interval = s.ResampleEvery
+		}
+		if interval > s.ResampleFor {
+			return fmt.Errorf("resample duration too low: must be a minimum of %s, got %s", FormatDuration(interval), FormatDuration(s.ResampleFor))
```
Comment (dgnorton) [inline influxql/ast.go]: Would it be more clear to the user if the error message explained the rule instead of values for the specific query?
```
FOR duration must be >= GROUP BY time duration
```

Comment (jsternberg) [inline influxql/ast.go]: Done.

**Comment by dgnorton** [comment]
+1
