### PR TITLE
fix(cmd/influx): accept `--input` flag in `restore` command

### LINKED ISSUE #21475: `influx restore` requires a single positional argument even when `--input` is specified
__Steps to reproduce:__

1. Create a backup using `influx backup`
2. Attempt to restore the backup using `influx restore --input <path-to-the-backup>`, as shown in our public docs

__Expected behavior:__
CLI attempts to restore the backup.

__Actual behavior:__
`Error: must specify path to backup directory`

---

The CLI is currently coded to require a single positional arg, for use as the input path. The `--input` option is effectively useless because of this.

To fix:
1. Don't require a positional arg when `--input` is given
2. Mark `--input` as deprecated / log a warning when it's used

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #21475

`--input` has been effectively useless up until now, but all of the examples in our public docs show using it instead of the positional arg.

I chose to deprecate `--input` instead of the arg because `influx backup` uses a positional arg to specify the path where backup data should be stored, and it felt intuitive to have symmetry between the two.

### CODE REVIEW

File: restore/restore.go [hunk 1]
```diff
@@ -74,6 +74,11 @@ func RunRestore(ctx context.Context, req Request, svcs Services, log *zap.Logger
 	if err := runner.loadManifests(req.Path); err != nil {
 		return err
 	}
+	// Bail out early if no manifests were found.
+	// TODO: Should this be an error?
```
Comment (wbaker85) [inline restore/restore.go:78]: Yeah I think something should be output. Just failing with no output if an invalid path is provided might make me think that everything happened successfully when it had in fact not. Just a simple message like "invalid path" or something like that would be good.

**Review by wbaker85 — APPROVED** [review]
Looks good!
