### PR TITLE
fix(query): avoid breaking query config validation when upgrading from older versions

### LINKED ISSUE #21319: `influxd config` generates invalid config files [backport 2.0.x]
Backport the fix for #21315 to the `2.0` branch

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #21319 

Backports #21321 and #21324

* Ensure query config written by influxd upgrade is valid.
* Revert to nonzero defaults for `query-concurrency` and `query-queue-size` to avoid validation failures for upgrading users.
* Don't fail validation when `query-concurrency` is 0 and `query-queue-size` is > 0.

### CODE REVIEW

File: cmd/influxd/launcher/cmd.go [hunk 1]
```diff
@@ -205,11 +205,11 @@ func NewOpts(viper *viper.Viper) *InfluxdOpts {
 
 		NoTasks: false,
 
-		ConcurrencyQuota:                0,
+		ConcurrencyQuota:                1024,
```
Comment (davidby-influx) [inline cmd/influxd/launcher/cmd.go:208]: Were you going to lower this because of the goproc limit?

**Review by davidby-influx — APPROVED** [review]
LGTM.  

One non-blocking question.

File: cmd/influxd/launcher/cmd.go (hunk 1 above)
Comment (danxmoran) [reply cmd/influxd/launcher/cmd.go:208]: I think you saw in the original PR, but: the limits are lowered in the test launcher. See `launcher_helpers.go`
