### PR TITLE
fix(cmd/influx): fix long startup when running `influx help` and other similar commands. 

### LINKED ISSUE #15441: Long startup time for influx CLI since introducing Flux 0.42
I noticed that it is taking about 2.5 seconds to run `influx help` on my workstation. 

I bisected to the commit that upgraded to Flux 0.42. Before that it takes around a second, which is still too long IMO.

I have not yet taken a CPU profile to understand where exactly time is being spent.
```
bash-3.2$ git log -1
commit 454003841aabeb74396d73541378bfa59c75b5db (HEAD)
Author: Nathaniel Cook <nvcook42@gmail.com>
Date:   Fri Aug 30 12:22:48 2019 -0600

    build(flux): upgrade to Flux v0.42.0

    Skips a test that requires special dependencies to pass.
bash-3.2$ GO111MODULE=on go build ./cmd/influx && time ./influx help
Influx Client

Usage:
  influx [flags]
  influx [command]
<snip>

real	0m2.355s
user	0m3.832s
sys	0m0.120s

bash-3.2$ git checkout 45400384^
Previous HEAD position was 454003841 build(flux): upgrade to Flux v0.42.0
HEAD is now at 333dc1d19 Merge pull request #14883 from influxdata/fix/flux-data-check

bash-3.2$ GO111MODULE=on go build ./cmd/influx && time ./influx help
Influx Client

Usage:
  influx [flags]
  influx [command]
<snip>

real	0m0.981s
user	0m2.099s
sys	0m0.086s
```

### PR DESCRIPTION
**Pull request by fchikwekwe**
Closes #15441

Describe your proposed changes here.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: cmd/influx/query.go [hunk 1]
```diff
@@ -4,9 +4,13 @@ import (
...
+	"github.com/influxdata/flux"
+
 	"github.com/influxdata/flux/repl"
+	_ "github.com/influxdata/flux/stdlib" // Import the stdlib
 	platform "github.com/influxdata/influxdb"
-	_ "github.com/influxdata/influxdb/query/builtin"
+
+	_ "github.com/influxdata/influxdb/query/stdlib" // Import the stdlib
 	"github.com/spf13/cobra"
 	"github.com/spf13/viper"
```
Comment (nathanielc) [inline cmd/influx/query.go]: Can you remove the extra blank lines here and below?

Comment (fchikwekwe) [reply cmd/influx/query.go]: yeah, no problem.

File: cmd/influx/repl.go [hunk 2]
```diff
@@ -41,6 +42,8 @@ func init() {
 }
 
 func replF(cmd *cobra.Command, args []string) error {
+	flux.FinalizeBuiltIns()
```
[the remark this answers is not in the document]
Comment (fchikwekwe) [reply cmd/influx/repl.go]: Yeah that is true. Changing it now.
