### PR TITLE
fix: task scheduler test uses a fixed time

### LINKED ISSUE #21883: Task Scheduler Test Failing on Intervals > 1hr Due to DST
On certain architectures (MacOS), the test `TestSchedule_Next/@every_fires_on_appropriate_boundaries` started to fail recently. This is due to differences in time being calculated based on local time rather than UTC. Linux does time comparisons based on UTC so the test was not failing in our Linux CI environment, but on Mac the time difference is apparently calculated from local time, which was causing a discrepency for the `@1 week` interval.

The test code initializes a mock schedule using `time.Now()` - a fix for this would be to use a fixed time which does not include a DST change in the 16 week time window that the tasks are triggered during the test.

### PR DESCRIPTION
**Pull request by wbaker85**
Closes #21883

Use a fixed time for the task scheduler tests which do not include a DST change to ensure that the test suite can be run on systems which do not determine time differences based on UTC.

### CODE REVIEW

File: task/backend/scheduler/scheduler_test.go [hunk 1]
```diff
@@ -94,7 +94,10 @@ func TestSchedule_Next(t *testing.T) {
 					}
 				}}
 				mockTime := clock.NewMock()
-				mockTime.Set(time.Now())
+				// need to run on a time window which does not include daylight savings
+				// time for testing on systems which do not default to UTC.
+				testTime, _ := time.Parse("2006-01-02", "2020-04-01")
```
Comment (danxmoran) [inline task/backend/scheduler/scheduler_test.go:99]: Could we make both of these values identical? My immediate reaction was to start trying to figure out which was the layout and which was the date

Comment (wbaker85) [reply task/backend/scheduler/scheduler_test.go]: Couldn't actually make them identical (2006-01-02 is actually too close the the time change and the test failed) - but I did refactor it to use a `time.RFC3339` as the format string, which should be more clear.

**Review by danxmoran — APPROVED** [review]
