### PR TITLE
Polish Threshold Styles

### LINKED ISSUE #11786: Styles for threshold configuration appear broken
screen shot 2019-02-08 at 3 17 54 pm

### PR DESCRIPTION
**Pull request by alexpaxton**
Closes #11786 

Improve clarity of feature by exposing `<=` (was previously obscured what operator was being use)

screen shot 2019-02-08 at 4 56 53 pm
screen shot 2019-02-08 at 4 57 31 pm

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [ ] http/swagger.yml updated (if modified Go structs or API)
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/shared/components/ColorDropdown.tsx [hunk 1]
```diff
@@ -7,28 +7,41 @@ import {Dropdown, ComponentStatus, DropdownMenuColors} from 'src/clockface'
...
   onChoose: (colors: ColorLabel) => void
 }
 
+interface DefaultProps {
+  disabled?: boolean
+  stretchToFit?: boolean
+  widthPixels?: number
+}
+
+type Props = PassedProps & DefaultProps
```
Comment (ebb-tide) [inline ui/src/shared/components/ColorDropdown.tsx]: ooh I really like this distinction actually

Comment (alexpaxton) [reply ui/src/shared/components/ColorDropdown.tsx]: Yarr Iris and Del gave me the idea
