### PR TITLE
fix(influx): validate host urls for influx config commands

### LINKED ISSUE #18706: cli: creating a config should validate that the url has a schema
I should not be allowed to create a config with a url that does not have a shema.

```
➜  influxdb git:(master) ./bin/darwin/influx config list
Active	Name		URL			Org
	localhost	http://localhost:9999	my-org
*	localhost_bad	localhost:9999		my-org
	default		http://localhost:9999	influxdata
➜  influxdb git:(master) ./bin/darwin/influx ping
Error: Get "localhost:9999/health": unsupported protocol scheme "localhost".
Error: Get "localhost:9999": unsupported protocol scheme "localhost".
See 'influx ping -h' for help
➜  influxdb git:(master)
```

### PR DESCRIPTION
**Pull request by jsteenb2**
Closes #18706 

note: ignore white space for this PR, makes this body of work pretty small

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass
- [ ] Documentation updated or issue created (provide link to issue/pr)

### CODE REVIEW

File: cmd/influx/config.go [hunk 1]
```diff
@@ -289,6 +288,27 @@ func (b *cmdConfigBuilder) cmdListRunEFn(*cobra.Command, []string) error {
...
+	cmd.MarkFlagRequired("token")
+
+	cmd.Flags().StringVarP(&b.url, "host-url", "u", "", "The host url (required)")
+	cmd.MarkFlagRequired("host-url")
+
+	// deprecated moving forward, not explicit enough based on feedback
+	// the short flags will still be respected but their long form is different.
+	cmd.Flags().StringVar(&b.name, "name", "", "The config name (required)")
+	cmd.Flags().MarkDeprecated("name", "use the --config-name flag")
+	cmd.Flags().StringVar(&b.url, "url", "", "The host url (required)")
```
Comment (jsteenb2) [inline cmd/influx/config.go:308]: @sanderson these are the flags that are being deprecated. They still work, but won't show up in the `-h` anymore

Comment (sanderson) [reply cmd/influx/config.go:308]: 👍
