### PR TITLE
fix(ui): add honeybadger error report to checks (#16443)

### LINKED ISSUE #16443: Add honeybadger notification to failed check create

### PR DESCRIPTION
**Pull request by zoesteinkamp**
Closes #16443 

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/alerting/actions/checks.ts [hunk 1]
```diff
@@ -213,9 +214,12 @@ export const saveCheckFromTimeMachine = () => async (
     } else {
       throw new Error(resp.data.message)
     }
-  } catch (e) {
-    console.error(e)
-    dispatch(notify(copy.createCheckFailed(e.message)))
```
Comment (ebb-tide) [inline ui/src/alerting/actions/checks.ts]: maybe keep the notification to user that create check did in fact fail?

Comment (zoesteinkamp) [reply ui/src/alerting/actions/checks.ts]: got it!
