### PR TITLE
fix(ui/timerangedropdown): refactored the daterangepicker implementation from modal to popover

### LINKED ISSUE #15420: Rebuild DateRangePicker using Clockface Popover
`DateRangePicker.tsx` located within `TimeRangeDropdown.tsx`

Looks like this one freely floats in the middle of the screen rather than being anchored to any particular element. `Popover` requires you to anchor the popover to an element, in this case it should be the `DropdownButton` within `TimeRangeDropdown`

Screen Shot 2019-10-15 at 9 39 14 AM

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #15420 

### Problem

The current Data Explorer DateRangePicker was set in a modal that would render to a fixed location on the screen (middle)

### Solution

Refactored the way the component was being rendered so that it was relative to the dropdown and within a popover

datetimepopover

### CODE REVIEW

File: ui/src/shared/components/TimeRangeDropdown.tsx [hunk 1]
```diff
@@ -4,7 +4,13 @@ import {get} from 'lodash'
...
 
 // Components
-import {Dropdown} from '@influxdata/clockface'
+import {
+  Dropdown,
+  Popover,
+  PopoverPosition,
+  PopoverInteraction,
+  PopoverType,
+} from '@influxdata/clockface'
```
Comment (zoesteinkamp) [inline ui/src/shared/components/TimeRangeDropdown.tsx]: Yay importing the popovers!

File: ui/src/shared/components/dateRangePicker/DateRangePicker.tsx [hunk 2]
```diff
@@ -13,7 +13,13 @@ interface Props {
...
   onSetTimeRange: (timeRange: TimeRange) => void
   onClose: () => void
-  position?: {top?: number; right?: number; bottom?: number; left?: number}
+  position?: {
+    top?: number
+    right?: number
+    bottom?: number
+    left?: number
+    position?: string
+  }
```
Comment (zoesteinkamp) [inline ui/src/shared/components/dateRangePicker/DateRangePicker.tsx]: Improving that line count i see ;)

#new linting for the win
