### PR TITLE
fix(http): Ensures users are created with an active status

### LINKED ISSUE #15274: GET http://localhost:9999/api/v2/me returns empty user status
In latest nightly InfluxDB 2.0 build is broken /api/v2/me endpoint.

```json
{
  "links": {
    "logs": "/api/v2/users/04863f56cb5d1000/logs",
    "self": "/api/v2/users/04863f56cb5d1000"
  },
  "id": "04863f56cb5d1000",
  "name": "my-user",
  "status": ""
}
```
Allowed values for status is enum "active" , "inactive".

### PR DESCRIPTION
**Pull request by dearyhud**
Closes #15274

Adds `active` as the default status for the user response.

### CODE REVIEW

File: http/user_service.go [hunk 1]
```diff
@@ -323,6 +323,10 @@ type userResponse struct {
 }
 
 func newUserResponse(u *influxdb.User) *userResponse {
+	if u.Status == "" {
```
Comment (kelwang) [inline http/user_service.go]: This should be removed. We shall not fake any response.
