### PR TITLE
fix(ui): wiring for labels

### LINKED ISSUE #10999: connect UI labels to the backend API
we need to connect the front end capability to the labels api and remove anything hardcoded

- [x] Check status on implementing global `/labels` endpoint. The mock api calls in `src/configuration/api` no longer accept an org and expect to use `/api/labels` instead of `/api/orgs/{orgID}/labels`. see progress at https://github.com/influxdata/influxdb/pull/11198
- [x] Remove/discuss label `resourceID`s from `cur_swagger.yml`. See https://github.com/influxdata/influxdb/pull/11198#issuecomment-455626434
- [ ] Add fetched resourceID to labels
- [x] Update labels generated client after `/labels` endpoint work is complete. Update cur_swagger descriptions with http/swagger for labels
- [x] Update `src/configuration/api` and `src/shared/apis/labels` to use generated client instead of mocks. Determine if these `getLabels` utils are using the same endpoint.

----
> - [ ] Nice to have: discuss updating dashboards/labels and similar endpoints to allow **adding** and **removing** multiple labels in one post or delete

### PR DESCRIPTION
**Pull request by OfTheDelmer**
Closes #10999 

_Briefly describe your proposed changes:_
 - Update `cur_swagger` to the labels response format
- Update client wrapper to make actual api calls and fix wiring errors

  - [ ] Rebased/mergeable
  - [ ] Tests pass

### CODE REVIEW

File: ui/src/dashboards/components/dashboard_index/TableRow.tsx [hunk 1]
```diff
@@ -114,8 +114,8 @@ export default class DashboardsIndexTableRow extends PureComponent<Props> {
       >
         {dashboard.labels.map(label => (
           <Label
-            key={`${label.resourceID}-${label.name}`}
-            id={label.resourceID}
+            key={`${label.id}-${label.name}`}
```
Comment (121watts) [inline ui/src/dashboards/components/dashboard_index/TableRow.tsx]: is the `name` necessary?  are the ids not guaranteed to be unique?
