### PR TITLE
fix: change failed query with missing db to 404

### LINKED ISSUE #25653: Cleanup: Update "database not found" to a 404 error, rather than a 500
This ticket is for a small cleanup on error messaging to more accurately convey the error that occurred. 

__Steps to reproduce:__

1. Start influxdb3
2. Run a query on a database that doesn't exist, with valid query syntax

__Expected behaviour:__
If a database is not found, I should receive a 404 error, specifying the database was not found, and that I should verify the name is correct and the database exists.

```
pete@macbookpro Development % influxdb3 query --dbname=sampleDB "SHOW TABLES"
Query command failed: server responded with error [400 Not Found Error]: query error: Database 'sampleDB' not found. 
Please verify the database name and ensure it exists before querying.
```

__Actual behaviour:__
When a query is run on a non-existent DB, a 500 Internal Server Error is returned. 
```
pete@macbookpro Development % influxdb3 query --dbname=sampleDB "SHOW TABLES"
Query command failed: server responded with error [500 Internal Server Error]: query error: database not found: sampleDB
```

__Additional info:__

* `influxdb3 query dbname=[NON-EXISTENT DB] "[SQL QUERY]"`
* Verified on both macOS/Darwin and Ubuntu 22.04

### PR DESCRIPTION
**Pull request by mgattozzi**
This changes the status code of a failed query that uses a db that does not exist. We now instead return a 404 rather than the default 500 code

Closes #25653

### CODE REVIEW

File: influxdb3_server/src/http.rs [hunk 1]
```diff
@@ -369,6 +369,18 @@ impl Error {
...
             }
+            Self::Query(query_executor::Error::DatabaseNotFound { .. }) => {
+                let err: ErrorMessage<()> = ErrorMessage {
+                    error: self.to_string(),
+                    data: None,
+                };
+                let serialized = serde_json::to_string(&err).unwrap();
+                let body = Body::from(serialized);
+                Response::builder()
+                    .status(StatusCode::NOT_FOUND)
```
Comment (praveen-influx) [inline influxdb3_server/src/http.rs:380]: Will it be easy enough to get a test added to assert the status?

Comment (mgattozzi) [reply influxdb3_server/src/http.rs:380]: Yeah should be easy enough! Surprised we don't already have one now that I think about it

**Review by praveen-influx — APPROVED** [review]
Looks good - if it's not too much hassle a test to assert the status will be good.

Not sure if we need to align the error messages returned to user. In some cases it's just string and in some cases it's a JSON string - probably in a separate ticket.

**Comment by mgattozzi** [comment]
@praveen-influx added the test so I'll merge it when it all passes
