### PR TITLE
fix: tsi index should compact old or too-large log files

### LINKED ISSUE #21942: TSL files over size limit are never compacted
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run a database with some value of `max-index-log-file-size`
2. Stop the database, change the limit to a value lower than some existing file, and restart
3. Watch as a new TSL file is created but the old one is never compacted.

__Expected behavior:__
Old TSL file should be compacted at startup since it is over the size limit

__Actual behavior:__
Old TSL file is never compacted

### PR DESCRIPTION
**Pull request by lesam**
Closes #21942

In addition to cleaning up old log files that are too large, ensure that a full TSI compaction is run on the same schedule as the TSM full compaction - so by default after the shard is cold for 4 hours, compact the TSL log files into the TSI index regardless of size.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: tsdb/index/tsi1/partition.go [hunk 1]
```diff
@@ -973,11 +1045,6 @@ func (p *Partition) compactToLevel(files []*IndexFile, level int, interrupt <-ch
 	default:
 	}
 
-	// Files have already been retained by caller.
-	// Ensure files are released only once.
-	var once sync.Once
-	defer once.Do(func() { IndexFiles(files).Release() })
```
Comment (lesam) [inline tsdb/index/tsi1/partition.go:979]: This is an unrelated change - we should ensure that even during cancellation we release the index files that were locked.

File: tsdb/index/tsi1/partition.go [hunk 2]
```diff
@@ -1082,27 +1157,17 @@ func (p *Partition) CheckLogFile() error {
...
-
 	// Open new log file and insert it into the first position.
 	if err := p.prependActiveLogFile(); err != nil {
 		return err
 	}
 
 	// Begin compacting in a background goroutine.
-	p.currentCompactionN++
 	go func() {
-		p.compactLogFile(logFile)
```
Comment (lesam) [inline tsdb/index/tsi1/partition.go:1100]: Log file compaction has been moved into the `Compact` method.

File: tsdb/index/tsi1/partition.go [hunk 3]
```diff
@@ -897,6 +900,46 @@ func (p *Partition) compactionsEnabled() bool {
 	return p.compactionsDisabled == 0
 }
 
+func (p *Partition) runPeriodicCompaction() {
+	// kick off an initial compaction at startup without the optimization check
+	p.Compact()
+
+	// check for compactions once an hour (usually not necessary but a nice safety check)
```
Comment (davidby-influx) [inline tsdb/index/tsi1/partition.go:907]: Doesn't this default to 4 hours, not one hour?

File: tsdb/index/tsi1/partition.go [hunk 4]
```diff
@@ -897,6 +900,46 @@ func (p *Partition) compactionsEnabled() bool {
...
+	defer p.mu.RUnlock()
+	if p.needsLogCompaction() {
+		return true
+	}
+	levelCount := make(map[int]int)
+	maxLevel := len(p.levels) - 2
+	// If we have 2 log files (level 0), or if we have 2 files at the same level, we should do a compaction.
+	for _, f := range p.fileSet.files {
+		level := f.Level()
+		levelCount[level] = levelCount[level] + 1
```
Comment (davidby-influx) [inline tsdb/index/tsi1/partition.go:935]: Is this intended to be anything other than `levelCount[level] += 1` ?

File: tsdb/index/tsi1/partition.go [hunk 5]
```diff
@@ -909,6 +952,30 @@ func (p *Partition) compact() {
...
+		if f.Level() == 0 {
+			logFile := f.(*LogFile) // It is an invariant that a file is level 0 iff it is a log file
+			if logFile == p.activeLogFile {
+				continue
+			}
+			if p.levelCompacting[0] {
+				break
+			}
+			// Mark the level as compacting.
+			p.levelCompacting[0] = true
```
Comment (davidby-influx) [inline tsdb/index/tsi1/partition.go:966]: Do we need to take a lock here?

**Review by davidby-influx — COMMENTED** [review]
I need to reread this when I am fresher, so just a few initial comments for now.

File: tsdb/index/tsi1/partition.go (hunk 5 above)
Comment (lesam) [reply tsdb/index/tsi1/partition.go:966]: We have already taken it:

```
// Compact requests a compaction of log files.
func (p *Partition) Compact() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.compact()
}
```

File: tsdb/index/tsi1/index.go [hunk 6]
```diff
@@ -89,6 +91,12 @@ var WithMaximumLogFileSize = func(size int64) IndexOption {
 	}
 }
 
+var WithMaximumLogFileAge = func(dur time.Duration) IndexOption {
```
[the remark this answers is not in the document]
Comment (lesam) [reply tsdb/index/tsi1/index.go:94]: Yes good catch! I should test `buildtsi`.

**Comment by lesam** [comment]
Thanks to @foobar for pointing out this issue over in https://github.com/influxdata/influxdb/pull/19002

File: tsdb/index/tsi1/partition.go (hunk 5 above)
Comment (davidby-influx) [reply tsdb/index/tsi1/partition.go:966]: I'd like a comment at the start of little 'c' `compact()` saying that this assumes the lock is taken.

File: tsdb/index/tsi1/partition.go [hunk 7]
```diff
@@ -909,6 +952,30 @@ func (p *Partition) compact() {
...
+			p.currentCompactionN++
+			go func() {
+				p.compactLogFile(logFile)
```
Comment (davidby-influx) [inline tsdb/index/tsi1/partition.go:969]: Maybe an error return from `compactLogFile` that aborts the subsequent compaction?

**Review by davidby-influx — COMMENTED** [review]
Ready for the next set of changes.

File: tsdb/index/tsi1/partition.go (hunk 7 above)
Comment (lesam) [reply tsdb/index/tsi1/partition.go:969]: We would unconditionally try to call compact after a log file compaction before, so I think this is ok.

File: tsdb/index/tsi1/partition.go (hunk 4 above)
Comment (lesam) [reply tsdb/index/tsi1/partition.go]: Made it `levelCount[level]++`

File: tsdb/index/tsi1/partition.go (hunk 3 above)
Comment (lesam) [reply tsdb/index/tsi1/partition.go:912]: Fixed to be hard-coded as hourly.

File: tsdb/index/tsi1/index.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (lesam) [reply tsdb/index/tsi1/index.go:94]: We actually don't need it as we use 4 hours as a default - but I realised another good change in buildtsi would be to fully compact the log files so that at least on startup the database is in a good state.

**Review by davidby-influx — APPROVED** [review]
All my concerns have been addressed.  Merge, ho!

**Review by benbjohnson — APPROVED** [review]
