### PR TITLE
fix(cmd): adds org svc dep to pkg

### LINKED ISSUE #15828: influx bucket create cannot use organization name
The `influx bucket create` command doesn't seem to have a `-o` flag for specifying the organization name. Here is what I did on my local box using the latest master at revision a64b976561c798f9aeeb771c4f48fb5d3141ad5f.

```
jsternberg:[~/g/s/g/i/influxdb] $ (master $=) influx bucket create -o influxdata -n NOAA                                              [7/7]
Error: unknown shorthand flag: 'o' in -o
Usage:
  influx bucket create [flags]

Flags:
  -h, --help                 Help for the create command
  -n, --name string          Name of bucket that will be created
      --org-id string        The ID of the organization that owns the bucket
  -r, --retention duration   Duration in nanoseconds data will live in bucket

Global Flags:
      --host string    HTTP address of Influx (default "http://localhost:9999")
      --local          Run commands locally against the filesystem
  -t, --token string   API token to be used throughout client calls

jsternberg:[~/g/s/g/i/influxdb] $ (master $=) influx org find
ID                      Name
97aa81cc0e247dc4        influxdata
jsternberg:[~/g/s/g/i/influxdb] $ (master $=) influx bucket create --org-id 97aa81cc0e247dc4 -n NOAA
ID                      Name    Retention       Org     OrganizationID
b76b31ef2f0341e0        NOAA    0s              <nil>   <nil>
```

Additionally, I found it weird that when I did create the bucket, the `Org` and `OrganizationID` fields were nil. It seems like these aren't getting copied in to the command's display. When I do `influx bucket find` these fields are still nil.

Most other commands support `-o org` as an option and it is a lot more convenient than having to find the organization id explicitly. It would also make writing tutorials easier because then you don't have to teach the person how to retrieve the organization id.

### PR DESCRIPTION
**Pull request by dearyhud**
Closes #15828
#16187 introduced a regression to the pkg cli. This PR ensures that the org SVC is added to the pkg cli in-line with the builder pattern.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass

### CODE REVIEW

File: cmd/influx/pkg.go [hunk 1]
```diff
@@ -117,31 +117,31 @@ func (b *cmdPkgBuilder) pkgApplyRunEFn() func(*cobra.Command, []string) error {
 		color.NoColor = !b.hasColor
 		var influxOrgID *influxdb.ID
 
+		svc, orgSVC, err := b.svcFn(flags.httpClientOpts(), pkger.WithApplyReqLimit(b.applyReqLimit))
+		if err != nil {
+			return err
+		}
+
 		if b.orgID != "" {
```
Comment (jsteenb2) [inline cmd/influx/pkg.go]: lets abstract thsi out into a helper function

File: cmd/influx/main.go [hunk 2]
```diff
@@ -242,3 +242,23 @@ func newLocalKVService() (*kv.Service, error) {
...
 }
+
+func getOrgID(orgSVC influxdb.OrganizationService, id string, name string) (influxdb.ID, error) {
+	if id != "" {
+		influxOrgID, err := influxdb.IDFromString(id)
+		if err != nil {
+			return 0, fmt.Errorf("invalid org ID provided: %s", err.Error())
+		}
+		return *influxOrgID, nil
+	} else if name != "" {
```
Comment (jsteenb2) [inline cmd/influx/main.go]: nit: you don't need the else here, you can just do

```go
if id != "" {
.... yada yada
}
if name != "" {
.. yada yada
}
return yada yada
```

this is the usual approach in most go libs I've seen/authored 🤔

File: cmd/influx/pkg.go [hunk 3]
```diff
@@ -107,47 +107,38 @@ func (b *cmdPkgBuilder) cmdPkgApply() *cobra.Command {
 	return cmd
 }
 
+func (b *cmdPkgBuilder) validOrgFlags() error {
+	if b.orgID == "" && b.org == "" {
```
Comment (jsteenb2) [inline cmd/influx/pkg.go]: nit: move this to the end of the list of methods (before funcs)

File: cmd/influx/pkg_test.go [hunk 4]
```diff
@@ -126,6 +131,24 @@ func Test_Pkg(t *testing.T) {
...
+					encoding: pkger.EncodingYAML,
+					filename: "pkg_0.yml",
+					flags: []flagArg{
+						{name: "name", val: "new name"},
+						{name: "description", val: "new desc"},
+						{name: "version", val: "new version"},
+						{name: "org", val: "influxdata"},
+					},
+				},
+				expectedMeta: pkger.Metadata{
```
Comment (jsteenb2) [inline cmd/influx/pkg_test.go]: we need a test for each cmd that updated with org stuff. You'll need to add this to export(export all is separate) func

File: cmd/influx/main.go (hunk 2 above)
Comment (dearyhud) [reply cmd/influx/main.go]: oh okay. the former communicates to me that either one should exist or the other. nbd though, i can update it.

File: cmd/influx/pkg_test.go (hunk 4 above)
Comment (dearyhud) [reply cmd/influx/pkg_test.go]: not 100% sure I follow ya

Comment (jsteenb2) [reply cmd/influx/pkg_test.go]: the export cmd and export all cmd were obth updated. but only 1 test was added. There should be an additional test for the export cmd. You added to the export all. BUt the other is missing

Comment (dearyhud) [reply cmd/influx/pkg_test.go]: yeah hm. does exporting resources by organization id exist?

Comment (jsteenb2) [reply cmd/influx/pkg_test.go]: the org id is needed for the exporting of resources, any resource, since the `orgID` is necessary for many of the resource lookups. The export all exports everything for an org, which you have covered in the test right now, so we're good there. The tests are only testing that the correct params are being passed/accessed really. Just tests our public API for the CI

Comment (dearyhud) [reply cmd/influx/pkg_test.go]: I understand, but where I'm getting at is the implementation of `influx pkg export` doesn't really accept an organization id as input. If that holds true, I'm going to remove the flag for now from the export.

Comment (jsteenb2) [reply cmd/influx/pkg_test.go]: ahhh yah, your'e right man, that got ripped out a while back 🤦‍♂
