### PR TITLE
Fix single stat and gauge value formatting

### LINKED ISSUE #11370: Entering 0 in the decimal places column sets unlimited decimals
it should just mean no decimal values are shown.

### PR DESCRIPTION
**Pull request by chnn**
- Extract value formatting in the the `SingleStat` and `Gauge` components to a shared utility function
- Rewrite `SingleStat` for readability
- Implement the "auto" mode for a `DecimalPlaces` setting. For now, this will format integers with no digits after the decimal place, and will format rationals with 2 digits after the decimal place.

Closes #11370

### CODE REVIEW

File: ui/src/shared/components/Gauge.tsx [hunk 1]
```diff
@@ -261,18 +267,18 @@ class Gauge extends Component<Props> {
...
     const {degree, lineCount, labelColor, labelFontSize} = GAUGE_SPECS
 
     const incrementValue = (maxValue - minValue) / lineCount
 
-    const gaugeValues = []
+    const labels = []
     for (let g = minValue; g < maxValue; g += incrementValue) {
-      const valueString = this.labelToString(g)
-      gaugeValues.push(valueString)
+      const valueString = formatStatValue(g, {decimalPlaces, prefix, suffix})
```
Comment (ischolten) [inline ui/src/shared/components/Gauge.tsx]: nice!
