### PR TITLE
fix: tell browser about cookie expiry

### LINKED ISSUE #17142: influxd --session-length has no effect
I'm trying to configure influxd 2 on a local network to not require logging in (at least not very often). The `--session-length` flag seems the obvious one to change, and I changed it to one year (in minutes), but it seems to have no effect and I'm prompted to log in frequently.

I'm running it in docker.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run influxd 2.0.0-beta with `--session-length=525600`
2. Log in to the web UI and view a dashboard
3. Wait 24 hours
4. Visit the same url again (in the same browser session)

__Expected behavior:__
I expect to see the dashboard and not be prompted to log in.

__Actual behavior:__
I get prompted to log in.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
`Linux 5.3.0-24-generic x86_64`
* InfluxDB version: Run `influxd version` and copy the output here
`InfluxDB 2.0.0-beta.5 (git: 2295247a5) build_date: 2020-03-09T01:32:06Z`
* Other relevant environment details: Container runtime, disk info, etc
`docker top`:
```
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                15978               15957               0                   Mar04               ?                   00:52:05            influxd --reporting-disabled --bolt-path=/influx/influxd.bolt --engine-path=/influx/engine --session-length=525600
```

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

From `docker inspect`:
```
...
        "Args": [
            "--reporting-disabled",
            "--bolt-path=/influx/influxd.bolt",
            "--engine-path=/influx/engine",
            "--session-length=525600"
        ],
...
        "Image": "sha256:cc6ce7f90cdd0a6f921ae6f127f09f110bdf250c3e1336bab0a363ed25977cfe",
...
        "Config": {
...
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive"
            ],
...
            "Cmd": [
                "--reporting-disabled",
                "--bolt-path=/influx/influxd.bolt",
                "--engine-path=/influx/engine",
                "--session-length=525600"
            ],
...
            "Image": "quay.io/influxdb/influxdb:2.0.0-beta",
...
        },
...
```

__Logs:__
Include snippet of errors in log.
```
ts=2020-03-09T01:22:47.341672Z lvl=info msg=Unauthorized log_id=0LMFedNW000 error="session has expired"
```

### PR DESCRIPTION
**Pull request by lesam**
Closes #17142

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: session/http_server.go [hunk 1]
```diff
@@ -165,9 +165,10 @@ const cookieSessionName = "influxdb-oss-session"
 
 func encodeCookieSession(w http.ResponseWriter, s *influxdb.Session) {
 	c := &http.Cookie{
-		Name:  cookieSessionName,
-		Value: s.Key,
-		Path:  "/api/",
+		Name:    cookieSessionName,
+		Value:   s.Key,
+		Path:    "/api/",
+		Expires: s.ExpiresAt,
```
Comment (jdstrand) [inline session/http_server.go:171]: This has the effect of making the cookie persistent (see https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#expire-and-max-age-attributes). Specifically:

"
_If a cookie presents the [Max-Age](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Directives) (that has preference over [Expires](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Directives)) or Expires attributes, it will be considered a persistent cookie and will be stored on disk by the web browser based until the expiration time._

_Typically, session management capabilities to track users after authentication make use of non-persistent cookies. This forces the session to disappear from the client if the current web browser instance is closed. Therefore, it is highly recommended to use non-persistent cookies for session management purposes, so that the session ID does not remain on the web client cache for long periods of time, from where an attacker can obtain it._
"

While OWASP's recommendation makes sense in general, our implementation stores the actual session server side so there is no sensitive information in the cookie (eg, just the name, session id and path) so I think setting `Expires` is ok if it helps to address a usability issue. There seems to be a slight preference in the community to use `max-age` instead of `Expires`, and indeed it makes conceptual sense to take `--session-length`, convert that to seconds (as per https://go.dev/src/net/http/cookie.go) and shove that into `MaxAge` in the `http.Cookie`. However, `session/service.go:CreateSession()` is already doing the math and giving you `ExpiresAt` for free. `Expires` works and it simplifies our implementation so using it seems fine.

**Review by jdstrand — APPROVED** [review]

File: session/http_server.go (hunk 1 above)
Comment (jdstrand) [reply session/http_server.go:171]: > [1] by definition, the session id is sensitive because it gives access to the authenticated login session. Storing it on disk means that a security issue in the browser could expose the contents of the cookie from the disk. The default session length of 1 hour means that cookie will only stick around until it is refreshed, so shorter values mitigate this risk. Of course, a different browser vulnerability could allow getting the cookie for memory or preventing the cookie from expiring, so non-persistent cookies aren't invulnerable to these issues. Also note that browsers have 'session restore' capabilities which will store open tabs/windows between restarts, further complicating 'non-persistent' cookies.

@lesam and I discussed this risk and I advocated adding some additional text to our documentation, which @lesam said he'd take to the documentation team.
