### PR TITLE
Fix partially written TSM files

### LINKED ISSUE #5889: [0.10.1-1] crash on startup without error possibly after disk full
Hello,

I have an 0.10.1-1 influxdb instanec that is failing to startup. I am almost certain that the host had a disk full situation sometime yesterday. This is what I see logged:

```
2016/03/02 10:02:21 InfluxDB starting, version 0.10.1, branch HEAD, commit df902a4b077bb270984303b8e4f8a320e3954b40, built 2016-02-18T20:44:27.807242
2016/03/02 10:02:21 Go version go1.4.3, GOMAXPROCS set to 16
2016/03/02 10:02:21 Using configuration at: /etc/influxdb/influxdb.conf
[meta] 2016/03/02 10:02:21 Starting meta service
[meta] 2016/03/02 10:02:21 Listening on HTTP: 127.0.0.1:8091
[metastore] 2016/03/02 10:02:21 Using data dir: /data/fusionio/fio01/apps/tpeng/influxdb/meta
[metastore] 2016/03/02 10:02:21 Node at localhost:8087 [Follower]
[metastore] 2016/03/02 10:02:22 Node at localhost:8087 [Leader]. peers=[localhost:8087]
[meta] 2016/03/02 10:02:27 127.0.0.1 - - [02/Mar/2016:10:02:27 -0500] GET /?index=0 HTTP/1.1 200 68129 - Go 1.1 package http c771bdeb-e087-11e5-8001-000000000000 40.044831ms
[store] 2016/03/02 10:02:27 Using data dir: /data/fusionio/fio01/apps/tpeng/influxdb/data
[tsm1wal] 2016/03/02 10:02:27 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/02 10:02:27 tsm1 WAL writing to /data/fusionio/fio01/apps/tpeng/influxdb/wal/_internal/monitor/4909
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4909/000000001-000000001.tsm (#0) opened in 82.923µs
[cacheloader] 2016/03/02 10:02:27 reading file /data/fusionio/fio01/apps/tpeng/influxdb/wal/_internal/monitor/4909/_00004.wal, size 0
[tsm1wal] 2016/03/02 10:02:27 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/02 10:02:27 tsm1 WAL writing to /data/fusionio/fio01/apps/tpeng/influxdb/wal/_internal/monitor/4921
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4921/000000001-000000001.tsm (#0) opened in 63.209µs
[cacheloader] 2016/03/02 10:02:27 reading file /data/fusionio/fio01/apps/tpeng/influxdb/wal/_internal/monitor/4921/_00005.wal, size 0
[tsm1wal] 2016/03/02 10:02:27 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/02 10:02:27 tsm1 WAL writing to /data/fusionio/fio01/apps/tpeng/influxdb/wal/_internal/monitor/4928
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000001-000000001.tsm (#0) opened in 34.36µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000002-000000001.tsm (#1) opened in 44.974µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000004-000000001.tsm (#3) opened in 11.674µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000003-000000001.tsm (#2) opened in 9.611µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000005-000000001.tsm (#4) opened in 12.349µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000007-000000001.tsm (#6) opened in 26.804µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000011-000000001.tsm (#10) opened in 10.482µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000016-000000001.tsm (#15) opened in 13.799µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000017-000000001.tsm (#16) opened in 9.799µs
...
...
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000013-000000001.tsm (#12) opened in 11.964µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000063-000000001.tsm (#62) opened in 10.446µs
run: open server: open tsdb store: failed to open shard 4928: open engine: error opening memory map for file /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000001-000000001.tsm: init: error reading magic number of file: EOF
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000091-000000001.tsm (#90) opened in 9.914µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000094-000000001.tsm (#93) opened in 11.045µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000040-000000001.tsm (#39) opened in 16.799µs
[filestore]2016/03/02 10:02:27 /data/fusionio/fio01/apps/tpeng/influxdb/data/_internal/monitor/4928/000000092-000000001.tsm (#91) opened in 18.218µs
```
and then it dies

### PR DESCRIPTION
**Pull request by jwilder**
- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

This fixes an issue where a TSM file would be partially written due to a `defer w.Close()` call swallowing an error that occurred during the `Close`.  In the case of the `TSMWriter`, `Close` flushes the underlying index buffer to disk.  If that failed, possibly due to out of disk space, the error would be hidden from the compactor and the compactor would install the file as if everything was fine.  On restart, the file could fail to load because the index may be truncated.

Fixes #5889

### CODE REVIEW

**Comment by jwilder** [comment]
@joelegasse

File: tsdb/engine/tsm1/compact.go [hunk 1]
```diff
@@ -553,45 +553,49 @@ func (c *Compactor) write(path string, iter KeyIterator) error {
 	if err != nil {
 		return err
 	}
-	defer w.Close()
```
Comment (joelegasse) [inline tsdb/engine/tsm1/compact.go]: Instead of replacing this with a large, anonymous function. What do you think about naming the return parameter and doing this:
```
defer func() { closeErr := w.Close(); if err == nil { err = closeErr } }()
```

The current code also doesn't close the file if an error occurred, potentially holding on to filesystem space until the program closes.

File: tsdb/engine/tsm1/file_store.go [hunk 2]
```diff
@@ -436,6 +436,16 @@ func (f *FileStore) Replace(oldFiles, newFiles []string) error {
...
+	fd, err := os.Open(f.dir)
+	if err != nil {
+		return err
+	}
+	defer fd.Close()
+
+	if err := fd.Sync(); err != nil {
+		return err
+	}
+
```
Comment (joelegasse) [inline tsdb/engine/tsm1/file_store.go]: This block looks like `syncDir` which is defined in `file_unix.go`, should that be used instead?

Comment (jwilder) [inline tsdb/engine/tsm1/file_store.go]: Good catch.  fixed.

File: tsdb/engine/tsm1/compact.go (hunk 1 above)
Comment (jwilder) [inline tsdb/engine/tsm1/compact.go]: Done.

**Comment by joelegasse** [comment]
:+1:  on green
