### PR TITLE
Ensure safe access to Shard engine

### LINKED ISSUE #6140: [0.12] Panic on shutdown
Got a random panic when I tried to shutdown my local instance:

```
monitor] 2016/03/28 16:56:33 shutting down monitor system
[monitor] 2016/03/28 16:56:33 terminating storage of statistics
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x2325c5]

goroutine 300686 [running]:
github.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc841b8cfc0, 0x1907a08, 0xc82dd29aa0, 0xbed000, 0x0, 0x0, 0xc84a6aa460, 0x1, 0x1, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/tsdb/shard.go:420 +0x115
github.com/influxdata/influxdb/tsdb.(*shardIteratorCreator).CreateIterator(0xc86fe646a0, 0x1907a08, 0xc82dd29aa0, 0xbed000, 0x0, 0x0, 0xc84a6aa460, 0x1, 0x1, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/tsdb/shard.go:886 +0x69
github.com/influxdata/influxdb/influxql.IteratorCreators.CreateIterator.func1(0xc8200c8a00, 0x12, 0x20, 0xc8b1630990, 0xc8b1630880, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/influxql/iterator.go:483 +0xdf
github.com/influxdata/influxdb/influxql.IteratorCreators.CreateIterator(0xc8200c8a00, 0x12, 0x20, 0x1907a08, 0xc82dd29aa0, 0xbed000, 0x0, 0x0, 0xc84a6aa460, 0x1, ...)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/influxql/iterator.go:481 +0xd8
github.com/influxdata/influxdb/influxql.(*IteratorCreators).CreateIterator(0xc8331b5f40, 0x1907a08, 0xc82dd29aa0, 0xbed000, 0x0, 0x0, 0xc84a6aa460, 0x1, 0x1, 0x0, ...)
	<autogenerated>:152 +0xeb
github.com/influxdata/influxdb/influxql.buildExprIterator.func1(0xc82dd29aa0, 0x1907e28, 0xc8331b5f40, 0xc8b1631240, 0x0, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/influxql/select.go:255 +0x196
github.com/influxdata/influxdb/influxql.buildExprIterator(0x1907a08, 0xc82dd29aa0, 0x1907e28, 0xc8331b5f40, 0x1907a08, 0xc82dd29aa0, 0xbed000, 0x0, 0x0, 0xc84a6aa460, ...)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/influxql/select.go:339 +0x13a0
github.com/influxdata/influxdb/influxql.buildFieldIterators.func1(0xc86fe64618, 0x1, 0x1, 0x1907e28, 0xc8331b5f40, 0xc8b16315d8, 0xc84a6aa840, 0x1, 0x1, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/influxql/select.go:154 +0x5b6
github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc86fe64618, 0x1, 0x1, 0x1907e28, 0xc8331b5f40, 0x0, 0x0, 0xbed000, 0x0, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/influxql/select.go:140 +0xf8
github.com/influxdata/influxdb/influxql.Select(0xc8861ce000, 0x1907e28, 0xc8331b5f40, 0xc8b1631c90, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/influxql/select.go:81 +0xba9
github.com/influxdata/influxdb/cluster.(*QueryExecutor).executeSelectStatement(0xc8200a4400, 0xc8861ce000, 0x2710, 0x0, 0xc82ec42480, 0xc82ec424e0, 0x0, 0x0)
```

### PR DESCRIPTION
**Pull request by e-dard**
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Fixes #6140.

This PR ensures that it's not possible to access a shard's underlying engine once it has been closed. It also synchronises access to the underlying engine to prevent potential data races on `Shard.engine`.

@benbjohnson @jwilder I'd appreciate your thoughts here since I'm not sure if this is going to be adding undue bottlenecks. The alternative would be to never `nil` `s.engine` and let the underlying `tsm1/Engine` return errors when it's accessed after it's been closed.

/cc @jsternberg

### CODE REVIEW

**Comment by jsternberg** [comment]
Looks good to me, but the PR title is a bit weird.

**Comment by e-dard** [comment]
@jsternberg heh, I got distracted with the merge conflict I'm unravelling :smile:

File: tsdb/shard.go [hunk 1]
```diff
@@ -255,9 +266,7 @@ func (s *Shard) WritePoints(points []models.Point) error {
 			}
 
 			// This was populated earlier, don't need to validate that it's there.
-			s.mu.RLock()
```
Comment (jwilder) [inline tsdb/shard.go]: Can you keep the locks here and explicitly release them for the `ErrEngineClose` check above?  These locks were intentionally placed here to reduce contention as seen under load.

File: tsdb/shard.go [hunk 2]
```diff
@@ -284,6 +293,11 @@ func (s *Shard) WritePoints(points []models.Point) error {
 
 // DeleteSeries deletes a list of series.
 func (s *Shard) DeleteSeries(seriesKeys []string) error {
+	s.mu.RLock()
```
Comment (jwilder) [inline tsdb/shard.go]: This may be the correct lock to take but L306 takes a write lock for some reason.  The code is basically doing the same thing so we should probably use the same lock for both.

Comment (e-dard) [inline tsdb/shard.go]: The difference is that `DeleteMeasurement` needs a write lock because it's writing to `s.measurementFields`, while `DeleteSeries` here is not mutating anything protected by `s.mu`, so the read lock is fine.

File: tsdb/shard.go [hunk 3]
```diff
@@ -472,6 +506,11 @@ func (s *Shard) SeriesKeys(opt influxql.IteratorOptions) (influxql.SeriesList, e
 		return []influxql.Series{{Aux: auxFields}}, nil
 	}
 
+	s.mu.RLock()
```
Comment (jwilder) [inline tsdb/shard.go]: You could probably do something like the following to reduce some of the locking/nil code that is duplicated.
```
func (s *Shard) IsClosed() bool {
  s.mu.RLock()
  defer s.mu.RUnlock()
  return s.engine == nil
}
```

and then use:

```
if s.IsClosed() {
  return nil, ErrEngineClosed
}
```

Comment (jsternberg) [inline tsdb/shard.go]: I think this is a good idea. In this case, we can also avoid using a defer. @joelegasse pointed out to me once that a defer has a performance penalty.

Here's the first article I could find about it so I'm not sure how accurate the article is: http://lk4d4.darth.io/posts/defer/

Comment (joelegasse) [inline tsdb/shard.go]: `defer` does do an allocation, and testing locally, is about ~4x slower than a direct `Lock()` then `Unlock()`. If you know exactly where the code is going to return, and aren't worried about cleaning up during a `panic()`, then doing this is better for code that will be called often:

```
func (s *Shard) IsClosed() bool {
  s.mu.RLock()
  closed := s.engine == nil
  s.mu.RUnlock()
  return closed
}
```

Comment (joelegasse) [inline tsdb/shard.go]: Although I should add that "~4x slower" is going from 23ns to 92ns per `Lock()`/`Unlock()` pair, so the extra time may not be noticeable compared to the larger operations, but reducing allocations is a good thing, right?

Comment (benbjohnson) [inline tsdb/shard.go]: I don't think you need "Is" in the function name. I think `Closed() bool` is cleaner. :bikeshed:

**Comment by benbjohnson** [comment]
lgtm

**Comment by e-dard** [comment]
@jwilder can you give it the once over again?

**Comment by jwilder** [comment]
Needs a rebase, but :+1:
