### PR TITLE
Fix and implement the controller and http service for flux v0.33.0

### LINKED ISSUE #14159: Update http code for Flux changes in 1.x
There were some changes to the http bits for Flux. On this branch `chore/update-flux-0.33.0` you will see that the code no longer compiles.

### PR DESCRIPTION
**Pull request by jsternberg**
Fixes #14159 and #14161.

### CODE REVIEW

File: services/httpd/handler.go [hunk 1]
```diff
@@ -1796,7 +1796,7 @@ func (h *Handler) recovery(inner http.Handler, name string) http.Handler {
 
 // Store describes the behaviour of the storage packages Store type.
 type Store interface {
-	Read(ctx context.Context, req *datatypes.ReadRequest) (reads.ResultSet, error)
+	ReadFilter(ctx context.Context, req *datatypes.ReadFilterRequest) (reads.ResultSet, error)
```
Comment (affo) [inline services/httpd/handler.go]: Is this a piece of another PR?

File: internal/flux_controller.go [hunk 2]
```diff
@@ -14,9 +15,12 @@ type FluxControllerMock struct {
...
 		QueryFn: func(ctx context.Context, compiler flux.Compiler) (query flux.Query, e error) {
-			// See https://github.com/influxdata/influxdb/issues/14161
-			//return NewFluxQueryMock(), nil
-			return nil, nil
+			p, err := compiler.Compile(ctx)
+			if err != nil {
+				return nil, err
+			}
+			alloc := &memory.Allocator{}
+			return p.Start(ctx, alloc)
```
Comment (affo) [inline internal/flux_controller.go]: Can't you adapt `FluxQueryMock` to implement `flux.Query` and return that instead?

File: services/httpd/handler_test.go [hunk 3]
```diff
@@ -1078,7 +1080,9 @@ func TestHandler_Flux_QueryJSON(t *testing.T) {
 			t.Fatalf("unexpected query -got/+exp\n%s", cmp.Diff(c.Query, exp))
 		}
 		called = true
-		return internal.NewFluxQueryMock(), nil
+
+		p := &mock.Program{}
+		return p.Start(ctx, nil)
```
Comment (affo) [inline services/httpd/handler_test.go]: You could  use `FluxQueryMock` if that implements `flux.Query`. Otherwise, I think you can just remove that.

File: services/httpd/handler.go (hunk 1 above)
Comment (jsternberg) [reply services/httpd/handler.go]: Yea. This was a change to the storage interface.

File: internal/flux_controller.go (hunk 2 above)
Comment (jsternberg) [reply internal/flux_controller.go]: I thought it was easier to just have the default use the compiler. The purpose of this is to make it possible to override the query function for the controller I believe.

File: services/httpd/handler_test.go (hunk 3 above)
Comment (jsternberg) [reply services/httpd/handler_test.go]: We added a mock package at some point to flux probably after the last time we updated this so I thought it was easier to just start using that since it would actually be maintained while the offshoot struct in the 1.x line of InfluxDB would likely get out of sync again.

File: cmd/store/query/query.go [hunk 4]
```diff
@@ -1,3 +1,5 @@
+//+build ignore
```
Comment (affo) [inline cmd/store/query/query.go]: Are you ignoring these just to make it build?

Do we have issues to fix commands?

Comment (jsternberg) [reply cmd/store/query/query.go]: We've apparently fixed it on InfluxDB 2.0 and it's an internal command that uses a now removed interface according to @stuartcarnie so he said it was fine if I just ignore the files for now. Since it's not part of the release, I figured it would be fine.
