### PR TITLE
fix(ui): updated default positioning for adding aggregate funcs when toggling from query builder

### LINKED ISSUE #16668: Data Explorer: Script Editor should default position to END of script
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open Data Explorer 
2. Begin a query using the query builder
3. Toggle to 'Script Editor' view [text editor sets focus on the top line]
4. Click on a function to add to the query
5. Function gets added as the TOP line of the query [after the from() statement]

__Expected behavior:__
Expect that the focus is set so that any additional functions would be added to the END of the script by default (unless I have manually selected a different insertion point in the text editor)

__Actual behavior:__
New items are inserted as first 'argument' (i'm probably using the wrong term)

__Environment info:__

Cloud, Acceptance and Production Version 2.0.0 (8ff62ab)

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #16668

### Problem

Currently toggling from the query builder to the script editor will default aggregate functions that are selected to the initial part of the query.

### Solution

Create a conditional check to update the range that we are adding to to be the end of the existing query. Also added logic to add a new line whenever an aggregate function is selected.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)

### CODE REVIEW

File: ui/src/timeMachine/utils/insertFunction.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export const formatFunctionForInsert = (
     return `\n${fluxFunction}`
   }
 
-  return `  |> ${fluxFunction}`
+  return `\n  |> ${fluxFunction}`
```
Comment (Asalem1) [inline ui/src/timeMachine/utils/insertFunction.ts]: ensures that all selected aggregate functions are inserted onto a new line
