### PR TITLE
fix(cmd/influxd): suggest running with -h on error instead of printing usage

### LINKED ISSUE #19922: Do not automatically print the help docs for influxd command
when there is an error calling the influxd command, we should not automatically print the help text. we should follow the same conventions as the `influx` command.

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #19922 

I'm not incredibly happy with this whack-a-mole approach, but it seemed like the most minimal approach. I'm going to open a separate issue for refactoring the CLI code here.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Feature flagged (if modified API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: cmd/influxd/main.go [hunk 1]
```diff
@@ -28,23 +29,25 @@ func main() {
 
 	influxdb.SetBuildInfo(version, commit, date)
 
-	rootCmd := launcher.NewInfluxdCommand(context.Background(),
-		// FIXME
-		//generate.Command,
```
Comment (danxmoran) [inline cmd/influxd/main.go:33]: Issue: #19429

File: cmd/influxd/main.go [hunk 2]
```diff
@@ -28,23 +29,25 @@ func main() {
...
-		//restore.Command,
```
Comment (danxmoran) [inline cmd/influxd/main.go:34]: (As far as I can tell) this was replaced by the backup/restore commands in the `influx` CLI, so it's fine to remove the FIXME without a tracking issue

File: cmd/influxd/inspect/export_index.go [hunk 3]
```diff
@@ -16,6 +16,7 @@ func NewExportIndexCommand() *cobra.Command {
 		Long: `
 This command will export all series in a TSI index to
 SQL format for easier inspection and debugging.`,
+		Args: cobra.NoArgs,
```
Comment (danxmoran) [inline cmd/influxd/inspect/export_index.go:19]: This is the magic needed to trigger errors on unknown / typoed subcommands

File: cmd/influxd/launcher/launcher.go [hunk 4]
```diff
@@ -178,7 +178,6 @@ var vaultConfig vault.Config
 
 func setLauncherCMDOpts(l *Launcher, cmd *cobra.Command) {
 	cli.BindOptions(cmd, launcherOpts(l))
-	cmd.AddCommand(inspect.NewCommand())
```
Comment (danxmoran) [inline cmd/influxd/launcher/launcher.go:181]: Before this, the code was registering both `influxd inspect` and `influxd run inspect` commands. That felt like a mistake, but this technically a breaking change.  I felt decently confident making the change because the public docs site only list `influxd inspect`, but I can revert if needed.

File: cmd/influxd/launcher/launcher.go [hunk 5]
```diff
@@ -101,7 +100,7 @@ const (
 	MaxInt = 1<<uint(strconv.IntSize-1) - 1
 )
 
-func NewInfluxdCommand(ctx context.Context, subCommands ...*cobra.Command) *cobra.Command {
```
Comment (danxmoran) [inline cmd/influxd/launcher/launcher.go:104]: The humble beginnings of my quest to simplify `launcher.go`...

File: cmd/influxd/launcher/launcher.go (hunk 4 above)
Comment (stuartcarnie) [reply cmd/influxd/launcher/launcher.go:181]: This is good with me; `run` shouldn't have any subcommands.

File: cmd/influxd/launcher/launcher.go (hunk 5 above)
Comment (stuartcarnie) [reply cmd/influxd/launcher/launcher.go:104]: And a noble quest it is!

**Review by stuartcarnie — APPROVED** [review]
These a nice UX improvements 👏
