### PR TITLE
fix(kit/cli): fix loading config from directories with '.' in the name

### LINKED ISSUE #20701: INFLUXD_CONFIG_PATH does not work if there is a `.` in the directory name [backport 2.0.x]
Backport the fix for #20696 to the `2.0` branch

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #20701

Backports #20702

### CODE REVIEW

File: kit/cli/viper_test.go [hunk 1]
```diff
@@ -306,6 +307,26 @@ func yamlConfigWriter(shortExt bool) configWriter {
 	}
 }
 
+func Test_RequiredFlag(t *testing.T) {
```
Comment (danxmoran) [inline kit/cli/viper_test.go:310]: This moved from below, must have had a strange backport before.

**Review by psteinbachs — APPROVED** [review]
Looks fine.
