### PR TITLE
fix(ui): value zero has no background color

### LINKED ISSUE #15803: Background color doesn't set when field value = 0
backgroundtext_0
<!--

### PR DESCRIPTION
**Pull request by zoesteinkamp**
Now fixed, falsy zero is no longer being bad

Closes #15803 

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/shared/constants/colorOperations.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export const generateThresholdsListHexs = ({
     hex: defaultColoring.textColor,
   }
 
-  if (!lastValue) {
+  if (lastValue != 0 && !lastValue) {
```
Comment (hoorayimhelping) [inline ui/src/shared/constants/colorOperations.ts]: first, prefer strict equality checking `!==` here:
```js
0 == '0' // true
0 === '0' // false
```
because '0' might pass this 😱 


the second bit is kind of pedantic, but stick with me.

when designing a boolean expression, i like to think of it like a funnel, where it starts wide and broad and gets narrow and specific. i want my widest and broadest expressions first, and my more specific ones last.

i think `!lastValue` is more broad than `lastValue !== 0`: `lastValue !== 0` includes truthy expressions, which is definitely not what we want in this. we want only the falsy expressions that are not 0 (so `''`, and `null` according to [the type hint here](https://github.com/influxdata/influxdb/blob/de4397874b3bdb425d05a4301121fd72f055ee09/ui/src/shared/constants/colorOperations.ts#L38)).

i also like to think about the flow of an `if / then` expression. if we factored

```ts
if (lastValue !== 0 && !lastValue) {
  return {...defaultColoring, textColor: baseColor.hex}
}
```
into separate expressions, it would look like this:

```ts
if (lastValue !== 0) {
  // lastValue can equal any string that isn't '' here
  if (!lastValue) {
    return {...defaultColoring, textColor: baseColor.hex}
  }
}
```

#### now imagine if we flipped the order:
```ts
if (!lastValue && lastValue !== 0) {
  return {...defaultColoring, textColor: baseColor.hex}
}
```
it would factor out to
```ts
if (!lastValue) {
  // last value can only equal null, '', or 0 here
  if (lastValue !== 0) {
    return {...defaultColoring, textColor: baseColor.hex}
  }
}
```
which i think is what we'd rather have here - last value is `falsy,` and it's not the number `0`. it's a subtle thing, but it communicates a lot about intent.

how does all of that strike you?

Comment (zoesteinkamp) [reply ui/src/shared/constants/colorOperations.ts]: This seems perfect! even better! Im going to go make the change :)
