### PR TITLE
fix(ui): improve relevant token detection when saving a query as a task

### LINKED ISSUE #14226: Evaluate DE query using AST
When getting a read bucket name for displaying tokens, instead of string manipulation try to use AST to evaluate the query.

### PR DESCRIPTION
**Pull request by chnn**
Closes #14226

See commits for details

### CODE REVIEW

File: ui/src/authorizations/utils/permissions.ts [hunk 1]
```diff
@@ -171,3 +157,24 @@ export enum BucketTab {
   AllBuckets = 'All Buckets',
   Scoped = 'Scoped',
 }
+
+/*
+  Given a list of authorizations, return only those that allow performing the
+  supplied `action` to the supplied `bucketName`.
```
Comment (chnn) [inline ui/src/authorizations/utils/permissions.ts]: This should read as "... to all of the supplied `bucketNames`".
