### PR TITLE
fix(build): update the download path for ui assets

### LINKED ISSUE #21174: Update `fetch-ui-assets.sh` Download Path for UI Assets on Release Branches
Currently on the `2.0` branch of OSS, the download path for UI assets is this: `https://github.com/influxdata/ui/releases/download/OSS-2.0/build.tar.gz`

Initially, in the `ui` repository, there was a branch created named `OSS-2.0` with a tag `OSS-2.0` to which the built UI assets were attached. Having the tag and the branch named the same thing makes it cumbersome to work with them. For example, to push to the `OSS-2.0` branch, you have to be specific enough for git to know that you aren't trying to push to the tag, for ex: `git push origin refs/heads/OSS-2.0:refs/heads/OSS-2.0` instead of a more concise form.

A new tag has been created in the `ui` repository `OSS-2.0` branch called `OSS-2.0-Assets`. The new download link for these assets is `https://github.com/influxdata/ui/releases/download/OSS-2.0-Assets/build.tar.gz`. The `fetch-ui-assets.sh` script needs to be updated to use this new link. Then the `OSS-2.0` tag can be deleted.

Note: The `master` branch of OSS has the corresponding `OSS-Master` tag created on in the `ui` repository. This isn't a problem since the `OSS-Master` tag is unique - the `master` branch in `ui` is just called `master`, so there is no ambiguity.

### PR DESCRIPTION
**Pull request by wbaker85**
Closes #21174

### CODE REVIEW

File: ui/fetch_ui_assets.sh [hunk 1]
```diff
@@ -12,6 +12,6 @@
 # respective releases in "influxdata/ui" (OSS-2.0, OSS-2.1, etc). Those releases
 # are updated only when a bug fix needs included for the UI of that OSS release.
 
-curl -L https://github.com/influxdata/ui/releases/download/OSS-2.0/build.tar.gz --output build.tar.gz
+curl -L https://github.com/influxdata/ui/releases/download/OSS-2.0-Assets/build.tar.gz --output build.tar.gz
```
Comment (danxmoran) [inline ui/fetch_ui_assets.sh:15]: If it isn't too late to suggest a different approach...

Why not mirror the strategy we use for the OSS releases, and tag this as the full `v<major>.<minor>.<patch>`? So we'd have a branch `OSS-2.0` and tags `OSS-v2.0.5`, `OSS-v2.0.6`... etc

Comment (danxmoran) [reply ui/fetch_ui_assets.sh:15]: Phrased another way: `OSS-2.0-Assets` looks to me like a "floating" tag that will move around within the UI repo. That's convenient, but it prevents our builds from being reproducible.

Comment (wbaker85) [reply ui/fetch_ui_assets.sh:15]: Definitely not too late for a different approach! And you're right about the `OSS-2.0-Assets` floating - it would need to get moved forward whenever something is backported into the `ui/OSS-2.0` branch, and that would make it difficult to know exactly what the UI was at the point of a certain OSS release.

With the `v<major>.<minor>.<patch>` strategy we will just need to update the download script a little more often - every patch release rather than every minor release. But probably worth it for being able to reproduce builds of OSS patch releases. I'll go ahead and make that update.

**Review by danxmoran — APPROVED** [review]
