### PR TITLE
fix: Improve the UI for the influx v1 auth commands

### LINKED ISSUE #19933: Improve UI for v1 auth create CLI command
## What

The `influx v1 auth create` command requires the following improvements:

* rename `--auth-token` argument to `--username` to be clear its purpose from a v1 perspective
* prompt for token password by default and ensure the password is set
* add `--no-password` to skip password prompt

## Why

The existing implementation of the `influx v1 auth create` command allows a user to create an auth token, but does not set a password until the user executes the `influx v1 auth set-password` command. Without a password, the token is unusable, returning an unauthorised error. It is unclear from the API that this is because the password is not set.

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #19933

This PR improves the `v1 auth` commands of the `influx` CLI tool, and includes some minor improvements to the `kit/cli` package. The enhancements and fixes to the user experience are as follows:

* Rename `--auth-token` to `--username` for the `v1 auth create` command to clarify its purpose in the context of v1 requests

* `v1 auth create` now requires a password when creating a new authorisation. It can be optionally disabled with the `--no-password` flag, however, the user much set a password using the `v1 auth set-password` command prior to using the token.

* Rename `v1 auth active` and `v1 auth inactive` commands to the actions `set-active` and `set-inactive` respectively to clarify their behaviour.
  
  For example, to set a token to active:
  
  ```
  influx v1 auth set-active (--id|--username)
  ```
  
  To set a token to inactive, preventing its use in subsequent requests:
  
  ```
  influx v1 auth set-inactive (--id|--username)
  ```
  
* Universally allow the `--id` or `--username` flags anywhere a single authentication token is
  required

* Use separate global variables to store the flag state of each v1 auth command

* factor out the behavior to find a single authentication token into
  a shared function, `v1FindOneAuthorization`

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: cmd/influx/v1_authorization.go [hunk 1]
```diff
@@ -31,155 +31,175 @@ func cmdV1Auth(f *globalFlags, opt genericCLIOpts) *cobra.Command {
...
+		}
 
-	var permissions []influxdb.Permission
-	for _, bp := range bucketPerms {
-		for _, p := range bp.perms {
-			var id influxdb.ID
-			if err := id.DecodeFromString(p); err != nil {
+		// verify an existing token with the same username doesn't already exist
+		filter := influxdb.AuthorizationFilter{
+			Token: &v1AuthCreateFlags.username,
```
Comment (danxmoran) [inline cmd/influx/v1_authorization.go:107]: I find it confusing that the `--username` flag gets mapped to the token name, instead of `user.Name`. Ex: in the demo video the command `v1 auth create --username bar` creates a token with: `Name / Token: bar` and `User Name: my-user`. It's not clear where that `my-user` came from, or how I could set it if I wanted to.

File: cmd/influx/v1_authorization.go [hunk 2]
```diff
@@ -479,9 +519,78 @@ func v1AuthorizationInactiveF(cmd *cobra.Command, args []string) error {
 	})
 }
 
+var (
+	errMultipleMarchingAuthorizations = errors.New("multiple authorizations found")
```
Comment (danxmoran) [inline cmd/influx/v1_authorization.go:523]:
```suggestion
	errMultipleMatchingAuthorizations = errors.New("multiple authorizations found")
```

File: cmd/influx/v1_authorization.go [hunk 3]
```diff
@@ -479,9 +519,78 @@ func v1AuthorizationInactiveF(cmd *cobra.Command, args []string) error {
...
+			Persistent: persistent,
+		},
+	}
+	opts.mustRegister(cmd)
+}
+
+func (f *v1AuthLookupFlags) validate() error {
+	switch {
+	case f.id.Valid() && f.username != "":
+		return errors.New("specify id or username")
```
Comment (danxmoran) [inline cmd/influx/v1_authorization.go:570]: Could we reword the error to make it more clear that it's an XOR? At first glance I wasn't sure why this was an error.

File: cmd/influx/v1_authorization.go (hunk 1 above)
Comment (stuartcarnie) [reply cmd/influx/v1_authorization.go:107]: @danxmoran I agree. However, this is an artefact of existing product deficiencies, product management requirements (upgrade 1.x without touching existing clients) and maintaining existing API compatibility with Cloud by not changing existing Users or Tokens.

1. Product management was forced to use tokens as the User object does not provide the appropriate features to restrict access to a subset of buckets, whereas Tokens do.

2. Tokens are always owned / associated with a real v2 `User` object. This is the `User Name` column and the `my-user` user you identified. By default, when you access an InfluxDB instance via the `influx` CLI tool, you are using a token owned by a v2 User (set via config or an environment variable), in this case `my-user`. So, when the operator create new tokens, they will be owned by their V2 User.

File: cmd/influx/v1_authorization.go (hunk 2 above)
Comment (stuartcarnie) [reply cmd/influx/v1_authorization.go:523]: Thanks! I am not used to typing on this laptop keyboard – one of the joys of being in quarantine in Australia right now 🤣

File: cmd/influx/v1_authorization.go (hunk 3 above)
Comment (stuartcarnie) [reply cmd/influx/v1_authorization.go:570]: How about 

> specify either id or username, not both

File: cmd/influx/v1_authorization.go (hunk 1 above)
Comment (danxmoran) [reply cmd/influx/v1_authorization.go:107]: Hmmm in that case, could we use something like `--token-name` as the option instead of `--username`? Or does `username` have a specific meaning when it comes to V1 that we shouldn't change?

File: cmd/influx/v1_authorization.go (hunk 3 above)
Comment (danxmoran) [reply cmd/influx/v1_authorization.go:570]: LGTM

File: cmd/influx/v1_authorization.go (hunk 1 above)
Comment (stuartcarnie) [reply cmd/influx/v1_authorization.go:107]: No, `--token-name` is unclear. `--username` is familiar to a v1 user, as this will match their users upgraded from a v1 database.

Comment (danxmoran) [reply cmd/influx/v1_authorization.go:107]: Fair enough 😄

Comment (stuartcarnie) [reply cmd/influx/v1_authorization.go:107]: To be clear, users upgraded from v1 are _not_ created as real V2 users, due to the deficiencies I described earlier. They will be created as these special tokens.

Comment (stuartcarnie) [reply cmd/influx/v1_authorization.go:107]: Our hands a tied somewhat, as we can't leverage the existing V2 Tokens. We chose to create these private tokens, with restricted use only to the 1.x compatible APIs (`/write` and `/query`).

1. We can't change them and break compatibility with Cloud APIs (for example to support bcrypt passwords, for a seamless upgrade from 1.x to 2.x)
2. It is time-consuming to propose a new token type, requiring a thorough review and verification they will be viable and useful in Cloud. Time constraints for OSS 2.0 GA prevented us from taking this approach.

**Review by danxmoran — APPROVED** [review]
:shipit: assuming CI passes
