### PR TITLE
fix(storage/reads): fix the storage tables to work correctly with multiple transformations

### LINKED ISSUE #12891: Flaky: Flux end to end tests
I got this red run on a PR: https://circleci.com/gh/influxdata/influxdb/36696

```
--- FAIL: TestFluxEndToEnd (23.09s)
    --- PASS: TestFluxEndToEnd/aggregate_empty_window.flux (0.42s)
    --- FAIL: TestFluxEndToEnd/aggregate_fill_window.flux (0.61s)
    --- FAIL: TestFluxEndToEnd/aggregate_window.flux (0.53s)
    --- FAIL: TestFluxEndToEnd/limit_offset.flux (0.58s)
    --- FAIL: TestFluxEndToEnd/lowestCurrent.flux (0.53s)
```

I've attached the build file.

[build_36696_step_108_container_0.txt](https://github.com/influxdata/influxdb/files/3007865/build_36696_step_108_container_0.txt)

### PR DESCRIPTION
**Pull request by jsternberg**
The storage table reader will now work correctly when there are multiple
outputs. The table interface now implements the new table and column
reader interfaces and works properly with `execute.CopyTable`. The
source uses `execute.CopyTable` to buffer the table in memory when there
are multiple output transformations.

Fixes #12891.

### CODE REVIEW

File: query/stdlib/influxdata/influxdb/source.go [hunk 1]
```diff
@@ -84,6 +74,30 @@ func (s *Source) processTables(ctx context.Context, tables TableIterator, waterm
 	return nil
 }
 
+func (s *Source) processTable(ctx context.Context, tbl flux.Table) error {
+	if len(s.ts) == 0 {
+		tbl.Done()
+		return nil
+	} else if len(s.ts) == 1 {
+		return s.ts[0].Process(s.id, tbl)
```
Comment (jlapacik) [inline query/stdlib/influxdata/influxdb/source.go]: I see. So if there are multiple downstream transformations, for each table we send copies downstream and then release our specific instance. But if there's only one downstream transformation, there's no need to copy the table, we just send it downstream and it is the job of that transformation to release it. Correct?

Comment (jsternberg) [reply query/stdlib/influxdata/influxdb/source.go]: Yes. That is correct.

File: storage/reads/table.gen.go.tmpl [hunk 2]
```diff
@@ -73,36 +72,37 @@ func (t *{{.name}}Table) Do(f func(flux.ColReader) error) error {
...
-		t.err = f(t)
-		for !t.isCancelled() && t.err == nil && t.advance() {
-			t.err = f(t)
+	for !t.isCancelled() && t.err == nil  {
+		cr := t.advance()
+		if cr == nil {
+			break
 		}
+		t.err = f(cr)
+		cr.Release()
```
Comment (jlapacik) [inline storage/reads/table.gen.go.tmpl]: Is it possible for Release to be called before another transformation Retains it?

Comment (jsternberg) [reply storage/reads/table.gen.go.tmpl]: I think the contract for `Do` says that as soon as the function ends it goes out of scope so it shouldn't be possible to have anything like the `consecutiveTransport` as that would break that contract (unless the transport retained it itself).

So I don't think this should cause a race condition unless the passed in function is breaking the contract.
