### PR TITLE
fix(cmd/influx): fix auth user name

### LINKED ISSUE #16808: User names are not displayed in auth list
When running `auth find` or `auth active` in the CLI, no user names are displayed:

Screen Shot 2020-02-10 at 4 22 33 PM

The column header exists, but the values are never provided to the TabWriter.

We should look up those user names and display them in the CLI.

### PR DESCRIPTION
**Pull request by kelwang**
Closes #16808 

display the user name

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: cmd/influx/authorization.go [hunk 1]
```diff
@@ -362,11 +367,16 @@ func authorizationFindF(cmd *cobra.Command, args []string) error {
 		for _, p := range a.Permissions {
 			permissions = append(permissions, p.String())
 		}
+		user, err := us.FindUserByID(context.Background(), a.UserID)
```
Comment (jsteenb2) [inline cmd/influx/authorization.go]: good find @jademcgough  👍

File: CHANGELOG.md [hunk 2]
```diff
@@ -5,6 +5,7 @@
 ### Bug Fixes
 1. [17039](https://github.com/influxdata/influxdb/pull/17039): Fixed issue where tasks are exported for notification rules
 1. [17042](https://github.com/influxdata/influxdb/pull/17039): Fixed issue where tasks are not exported when exporting by org id
+1. [17050](https://github.com/influxdata/influxdb/pull/17050): Fixed the CLI auth find, user name issue
```
Comment (jademcgough) [inline CHANGELOG.md]: This isn't very clear, maybe something like "Added missing user names to auth CLI commands"
