### PR TITLE
test: skip HoltWinters tests when GOARCH != amd64

### LINKED ISSUE #22410: Holt-Winters tests fail with floating-point differences on non-AMD64 architectures
`TestHoltWinters_AusTourists` and `TestSelect/HoltWinters_GroupBy_Agg` assert on AMD64-specific floating-point outputs. When the test runs on ARM64 (or other architectures), it fails because the underlying CPU optimizations aren't the same, so the results differ slightly.

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #22410

The logic used in our HoltWintersReducer produces different floating-point results depending on the CPU architecture. Tests that assert on specific outputs of the functions fail on non-amd64 architectures (see #18254 for an example).

### CODE REVIEW

File: influxql/query/select_test.go [hunk 1]
```diff
@@ -2881,6 +2884,10 @@ func TestSelect(t *testing.T) {
 		},
 	} {
 		t.Run(tt.name, func(t *testing.T) {
+			if tt.onlyArch != "" && runtime.GOARCH != tt.onlyArch {
```
Comment (codyshepherd) [inline influxql/query/select_test.go:2887]: What's the scenario where `tt.onlyArch` is the empty string? Should this `&&` be `||` instead?

Comment (danxmoran) [reply influxql/query/select_test.go:2887]: Empty string is the default (i.e. expected to work on every GOARCH). `&&` is the right operator, it's basically saying "if a single GOARCH was specified AND we're not running on that arch"

**Review by lesam — APPROVED** [review]
