### PR TITLE
[BUGFIX] client url path

### LINKED ISSUE #9154: Client - Allow path in address
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

__Steps to reproduce:__
https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/v2/client.go#L26
With a `Addr` like `https://example.org/influxdb/` like behind a proxy server or so

__Expected behavior:__ [What you expected to happen]
concat path with e.g. `ping`.

__Actual behavior:__ [What actually happened]
override path with e.g. `ping`.

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/v2/client.go#L123

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/v2/client.go#L370

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/v2/client.go#L476

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/influxdb.go#L191

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/influxdb.go#L267

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/influxdb.go#L345

https://github.com/influxdata/influxdb/blob/2ed0d2d1c918ea4624dfe45dad0e6c5fd288e56f/client/influxdb.go#L391

### PR DESCRIPTION
**Pull request by genofire**
fix #9154 

###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by genofire** [comment]
@e-dard @benbjohnson @hpbieker @jsternberg could somebody make any reaction - i am feeling like forgotten

**Comment by hpbieker** [comment]
Hi @genofire! Thank you for mentioning me alongside InfluxDB's great heros, but I am just a poor/happy user of InfluxDB :-)

File: client/influxdb.go [hunk 1]
```diff
@@ -186,9 +187,9 @@ func (c *Client) Query(q Query) (*Response, error) {
 // QueryContext sends a command to the server and returns the Response
 // It uses a context that can be cancelled by the command line client
 func (c *Client) QueryContext(ctx context.Context, q Query) (*Response, error) {
-	u := c.url
+	u, _ := url.Parse(c.url.String())
```
Comment (e-dard) [inline client/influxdb.go]: Please don't ignore any errors from `url.Parse`. Return them to the caller

**Comment by e-dard** [comment]
Hi @genofire, sorry your PR got overlooked. I've checked the CLA, but I can't find you listed anywhere. Are you sure you signed [this form here?](https://www.influxdata.com/community/cla/)

**Comment by genofire** [comment]
Better now? - i  did not know why your ci failed.

File: client/influxdb.go [hunk 2]
```diff
@@ -195,9 +196,13 @@ func (c *Client) Query(q Query) (*Response, error) {
 // QueryContext sends a command to the server and returns the Response
 // It uses a context that can be cancelled by the command line client
 func (c *Client) QueryContext(ctx context.Context, q Query) (*Response, error) {
-	u := c.url
+	// clone url struct
```
Comment (jsternberg) [inline client/influxdb.go]: I don't like this cloning the struct thing. The original line, `u := c.url`, already does a soft clone of the struct without the additional requirement to render a string and then reparse that string back into the struct. The only thing that doesn't get cloned properly is the `.User` variable on the struct, but that isn't being modified so a shallow clone should be fine.

It seems to me like it would be better to just modify line 200 in the original diff to:

```
u.Path += "/query"
```

And that's all that would be required to implement this feature. If the path is empty, the path should still be preceded by a slash anyway and it outputs the correct output. See this example: https://play.golang.org/p/veRZfeI9Grj

Comment (genofire) [reply client/influxdb.go]: soft clone did not work, it is a pointer:
https://play.golang.org/p/X9vztSPdo4P

Comment (genofire) [reply client/influxdb.go]: ???

Comment (jsternberg) [reply client/influxdb.go]: Sorry, I didn't see you had replied.

If you look at the struct definition, you will see this:

```go
type Client struct {
    url        url.URL
    unixSocket string
    username   string
    password   string
    httpClient *http.Client
    userAgent  string
    precision  string
}
```

If you notice, `url.URL` is not a pointer. So when you do this:

```
u := c.url
```

That creates a copy of the `url.URL` struct. We can then look at [url.URL](https://godoc.org/net/url#URL) in the documentation and we see that almost all of the attributes in there are values. There's one pointer, but we don't modify it so it doesn't matter. That means it is safe for us to modify without causing any kind of race condition.

So my original statement stands. It would be easier to modify the original code to just add the additional path component rather than to do a complex rendering of the url to a string and then reparsing it while checking for an error that would never happen.

Comment (genofire) [reply client/influxdb.go]: oh sry, u are right

Comment (genofire) [reply client/influxdb.go]: https://play.golang.org/p/8FHZDXpLnK_c

**Comment by jsternberg** [comment]
@e-dard can you take a look?

**Comment by jsternberg** [comment]
@genofire also,  have you signed the CLA? We need you to sign that before we can merge this.

**Comment by genofire** [comment]
screenshot_20180207-200457
