### PR TITLE
fix(storage): simple8b passes checkptr

### LINKED ISSUE #15509: simple8b: fails pointer alignment check
New in go tip is a checkptr flag: https://groups.google.com/forum/#!msg/golang-dev/SzwDoqoRVJA/IvtnBW5oDwAJ

If you use [golang.org/dl/gotip](https://godoc.org/golang.org/dl/gotip) or otherwise build from source, and run `GO111MODULE=on gotip test -gcflags=all=-d=checkptr ./tsdb/tsm1/` you will get a panic like this, indicating incorrect pointer alignment:

```
--- FAIL: TestIntegerArrayEncodeAll_Compare (0.00s)
panic: (runtime.ptrAlign) (0x1a275c0,0xc0001f8200) [recovered]
	panic: (runtime.ptrAlign) (0x1a275c0,0xc0001f8200)

goroutine 31 [running]:
testing.tRunner.func1(0xc0001f4700)
	/Users/mr/gotip/src/github.com/golang/go/src/testing/testing.go:874 +0x3a3
panic(0x1a275c0, 0xc0001f8200)
	/Users/mr/gotip/src/github.com/golang/go/src/runtime/panic.go:679 +0x1b2
github.com/influxdata/influxdb/pkg/encoding/simple8b.DecodeBytesBigEndian(0xc000166008, 0x3e7, 0x3e7, 0xc00016e589, 0x530, 0x577, 0xc00016e580, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdata/influxdb/pkg/encoding/simple8b/encoding.go:493 +0x7e
github.com/influxdata/influxdb/tsdb/tsm1.integerBatchDecodeAllSimple(0xc00016e580, 0x539, 0x580, 0x0, 0x0, 0x3e8, 0x539, 0x539, 0xc00012c008, 0xc00012c000, ...)
	/Users/mr/go/src/github.com/influxdata/influxdb/tsdb/tsm1/batch_integer.go:212 +0x204
github.com/influxdata/influxdb/tsdb/tsm1.IntegerArrayDecodeAll(0xc00016e580, 0x539, 0x580, 0x0, 0x0, 0x0, 0xc00016e580, 0x539, 0x580, 0x0, ...)
	/Users/mr/go/src/github.com/influxdata/influxdb/tsdb/tsm1/batch_integer.go:150 +0x95
github.com/influxdata/influxdb/tsdb/tsm1.testIntegerArrayEncodeAll_Compare(0xc0001f4700, 0xc00012c000, 0x3e8, 0x3e8, 0xd2b6601)
	/Users/mr/go/src/github.com/influxdata/influxdb/tsdb/tsm1/batch_integer_test.go:105 +0x508
github.com/influxdata/influxdb/tsdb/tsm1.TestIntegerArrayEncodeAll_Compare(0xc0001f4700)
	/Users/mr/go/src/github.com/influxdata/influxdb/tsdb/tsm1/batch_integer_test.go:61 +0x13a
testing.tRunner(0xc0001f4700, 0x1b29868)
	/Users/mr/gotip/src/github.com/golang/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/Users/mr/gotip/src/github.com/golang/go/src/testing/testing.go:960 +0x351
FAIL	github.com/influxdata/influxdb/tsdb/tsm1	0.113s
```

The failure is in this method: https://github.com/influxdata/influxdb/blob/aa34444df439a7649554f1e80eee032ca70c0f38/pkg/encoding/simple8b/encoding.go#L483-L498

and it appears to also be present in the 1.8 branch.

If you run all of our tests, there are other failed checks in go-cmp and bbolt, so we should plan on upgrading those dependencies once appropriate fixes land. There are also some failed checks in arrow, but I am not yet sure if those are a mistake on our end or a bug in arrow.

### PR DESCRIPTION
**Pull request by jacobmarble**
Using `unsafe.Pointer` to convert a slice to array pointer fails `checkptr`. This adds slice versions of array functions used by batch decoding.

Fixes #15509

### CODE REVIEW

**Comment by tmgordeeva** [comment]
I see, the bounds checking is getting us.

@e-dard could you link the branch you mentioned that has your own WIP on this?

**Comment by tmgordeeva** [comment]
The latest change skips `checkptr` on the batch decode functions and also pulls in Edd's encoding perf improvements.

File: pkg/encoding/simple8b/encoding.go [hunk 1]
```diff
@@ -520,8 +524,8 @@ func canPack(src []uint64, n, bits int) bool {
 
 	max := uint64((1 << uint64(bits)) - 1)
 
-	for i := 0; i < end; i++ {
-		if src[i] > max {
+	for _, s := range src[:n] {
```
Comment (jacobmarble) [inline pkg/encoding/simple8b/encoding.go]: Are `n` and `end` the same value?

Comment (stuartcarnie) [reply pkg/encoding/simple8b/encoding.go]: Agree, the logic is strange, with regard to `n` and `end`.

Lets walk through a pseudo-proof.

On entry to `canPack`, the first precondition is 

```
if n ≥ len(src) then immediately exit
```

therefore, the condition `n < len(src)` must be `true` in order to reach:

```go
end := len(src)
```

Next test, by substituting `end` for `len(src)`: 

```go
if n < len(src) {
    end = n
}
```

Given `n < len(src)` is always true, `end` will always equal `n`.

File: pkg/encoding/simple8b/encoding.go [hunk 2]
```diff
@@ -541,7 +545,8 @@ func pack120(src []uint64) uint64 {
 
 // pack60 packs 60 values from in using 1 bit each
 func pack60(src []uint64) uint64 {
-	return 2<<60 |
+	return src[59]<<59 | // eliminate multiple bounds checks
```
Comment (stuartcarnie) [inline pkg/encoding/simple8b/encoding.go]: I would recommend leaving the order and adding this line to eliminate the bounds check, which follows precedent established by the Go team in [`encoding/binary` package](https://github.com/golang/go/blob/ad7ce3911f4947b4cccb435b6374e3808f0062db/src/encoding/binary/binary.go#L53).

```
_ = src[59] // bounds check hint to compiler; see golang.org/issue/14808
```

File: pkg/encoding/simple8b/encoding.go (hunk 1 above)
Comment (e-dard) [reply pkg/encoding/simple8b/encoding.go]: looks like `end` can be removed.
