### PR TITLE
fix: enable write-only users to pass auth checks in the V1 API

### LINKED ISSUE #19944: Creating new DBRP mappings requires read-access to underlying bucket
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a new bucket using `influx setup`
2. Create a v1 auth token using `influx v1 auth create`, granting the user write (not read) permission on the bucket
3. Attempt to write data into your new bucket using the v1 auth token and v1 API

__Expected behavior:__
The write should succeed.

__Actual behavior:__
The write fails with a "read:orgs/xxx/buckets/yyy is unauthorized" error.

I stepped through the code in a debugger. The problem is that the logic in the DBRP service calls `FindBucketByID` before creating a new mapping, and the find-related methods check read-access.

Idea: tweak the find-related methods to check read OR write access.

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #19944 

Our V1 auth layer allows for write-only users, but our V1 write-path requires looking up buckets via DBRP mappings. That lookup currently performs multiple checks for bucket-read permission, causing failures.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Feature flagged (if modified API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by danxmoran** [comment]
I manually tested this along with a hacky fix for #19949. Am open to suggestions for automated tests, the change to `launcher` makes me worry.

File: cmd/influxd/launcher/launcher.go [hunk 1]
```diff
@@ -954,8 +954,8 @@ func (m *Launcher) run(ctx context.Context) (err error) {
 		}
 	}
 
-	dbrpSvc := dbrp.NewService(ctx, authorizer.NewBucketService(ts.BucketService), m.kvStore)
-	dbrpSvc = dbrp.NewAuthorizedService(dbrpSvc)
+	// N.B. the BucketService used by the DBRP service doesn't perform authentication.
```
Comment (danxmoran) [inline cmd/influxd/launcher/launcher.go:957]: Self-nitpick: authorization, not authentication

File: authorizer/authorize_find.go [hunk 2]
```diff
@@ -12,7 +12,12 @@ func AuthorizeFindDBRPs(ctx context.Context, rs []*influxdb.DBRPMappingV2) ([]*i
 	// https://github.com/golang/go/wiki/SliceTricks#filtering-without-allocating
 	rrs := rs[:0]
 	for _, r := range rs {
+		// N.B. we have to check both read and write permissions here to support the legacy write-path,
+		// which calls AuthorizeFindDBRPs when locating the bucket underlying a DBRP target.
 		_, _, err := AuthorizeRead(ctx, influxdb.BucketsResourceType, r.BucketID, r.OrganizationID)
+		if err != nil {
```
Comment (stuartcarnie) [inline authorizer/authorize_find.go:18]: nit: Update the function doc comment to change `read` to `access`:

```go
// AuthorizeFindDBRPs takes the given items and returns only the ones that the user is authorized to access.
```

**Review by stuartcarnie — DISMISSED** [review]
Looks great. One nit is a change to the doc comment of the function.

**Review by stuartcarnie — APPROVED** [review]
:shipit:
