### PR TITLE
Compress tombstone files

### LINKED ISSUE #8558: Dropping measurement used several GB disk space
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Version: e3918e0
OS: Linux

__Steps to reproduce:__

1. `drop measurement foo`

__Expected behavior:__ [What you expected to happen]
Reduce disk usage

__Actual behavior:__ [What actually happened]
Increased disk usage

__Additional info:__ [Include gist of relevant config, logs, etc.]
Before running `drop measurement`:
```
# df -h .
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/sys-influxdb   30G   16G   13G  57% /mnt/influxdb
```
After running `drop measurement`:
```
# df -h .
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/sys-influxdb   30G   23G  5.8G  80% /mnt/influxdb
```

In this specific case I was trying to remove unneeded data to address performance issues, not disk usage issues. But if I were low on disk space, and trying to remove data to get some back, this would be a big problem. I would not expect dropping a measurement to result in using more disk space. Especially an additional 43% of the original size. If I were low on disk space, dropping a measurement in attempt to get some space back could end up causing me to run out of space entirely.

### PR DESCRIPTION
**Pull request by jwilder**
This adds a v3 tombstone format that is a gzip compressed version of the v2
format.  It reduces the size of tombstone files substantially without
having to support a more feature rich file format for tombstones.  Prior versions can still be read, but new tombstone will use the v3 format.

Testing with 1M series and dropping all of them in my local env reduced disk usage for tombstone files from 397MB to 11MB.  Each file is about 98% smaller.

### Before
```
$ du -c -h *.tombstone
 99M	000000004-000000003.tombstone
 99M	000000008-000000003.tombstone
 99M	000000011-000000002.tombstone
 99M	000000012-000000001.tombstone
397M	total
```

### After
```
$ du -c -h *.tombstone
2.8M	000000004-000000003.tombstone
2.8M	000000008-000000003.tombstone
2.8M	000000011-000000002.tombstone
2.8M	000000012-000000001.tombstone
 11M	total
```

Fixes #8558 

###### Required for all non-trivial PRs
- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] CHANGELOG.md updated
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: tsdb/engine/tsm1/tombstone.go [hunk 1]
```diff
@@ -323,6 +338,70 @@ func (t *Tombstoner) readTombstoneV2(f *os.File, fn func(t Tombstone) error) err
...
+	b := make([]byte, 4096)
+	for {
+		if _, err = io.ReadFull(gr, b[:4]); err == io.EOF || err == io.ErrUnexpectedEOF {
+			return nil
+		} else if err != nil {
+			return err
+		}
+		n += 4
+
+		keyLen := int(binary.BigEndian.Uint32(b[:4]))
```
Comment (e-dard) [inline tsdb/engine/tsm1/tombstone.go]: Paranoid me... But.. On a 32-bit system isn't it going to be possible for the `keyLen` to be a value larger than `math.MaxInt32`, and therefore when we convert to an `int` (which will be an `int32` on a 32-bit system), we may overflow.

Probably unlikely, but it could be a bit safer to do: 

```go
keyLen := binary.BigEndian.Uint32(b[:4])
if keyLen > uint32(len(b)) {
...
}
```

Just a thought.

File: tsdb/engine/tsm1/tombstone.go [hunk 2]
```diff
@@ -323,6 +338,70 @@ func (t *Tombstoner) readTombstoneV2(f *os.File, fn func(t Tombstone) error) err
...
 
+// readTombstoneV3 reads the third version of tombstone files that are capable
+// of storing keys and the range of time for the key that points were deleted. This
+// format is a binary and compressed with gzip.
+func (t *Tombstoner) readTombstoneV3(f *os.File, fn func(t Tombstone) error) error {
+	// Skip header, already checked earlier
+	if _, err := f.Seek(headerSize, io.SeekStart); err != nil {
+		return err
+	}
+	n := int64(headerSize)
```
Comment (e-dard) [inline tsdb/engine/tsm1/tombstone.go]: Aside from keeping track of the bytes read, you don't seem to be doing anything with `n`? I can't find a read anywhere.

File: tsdb/engine/tsm1/tombstone.go [hunk 3]
```diff
@@ -181,30 +186,40 @@ func (t *Tombstoner) writeTombstone(tombstones []Tombstone) error {
 
 	bw := bufio.NewWriterSize(tmp, 1024*1024)
 
-	binary.BigEndian.PutUint32(b[:4], v2header)
+	binary.BigEndian.PutUint32(b[:4], v3header)
 	if _, err := bw.Write(b[:4]); err != nil {
 		return err
 	}
 
+	if err := bw.Flush(); err != nil {
```
Comment (jwilder) [inline tsdb/engine/tsm1/tombstone.go]: Yes.  It might not be needed though. I was getting some weird decompresssion results when testing and added this, but it was actually that I was not using `io.ReadFull`

File: tsdb/engine/tsm1/tombstone.go (hunk 2 above)
Comment (jwilder) [inline tsdb/engine/tsm1/tombstone.go]: That's copy/paste leftover from the v2 version.  I'll remove it since it use `io.EOF` now to check for termination.

File: tsdb/engine/tsm1/tombstone.go (hunk 1 above)
Comment (jwilder) [inline tsdb/engine/tsm1/tombstone.go]: The max key length is 65k so we shouldn't ever get near a value that can overflow.

**Comment by jwilder** [comment]
@e-dard All fixed.
