### PR TITLE
Fix subscriber service dropping writes under high write load

### LINKED ISSUE #7330: data loss during high ingest rate
### Bug report

__System info:__ 
influxdb 1.0
Linux & MacOS

__Steps to reproduce:__

1. Start second influxdb on port 8087
2. from `influx` shell: `create database test'`
3. from `influx` shell: `create subscription "sub0" on "test"."autogen" destinations all 'http://localhost:8087'`
4. `for ((i=0; i<30; i++)); do ( for ((n=0; n<300; n++)); do echo "insert test,foo=bar value=${i}i"; done | influx -database test ) & done; wait`
5. from `influx -database test` shell: `select sum(value) from test`
6. from `influx -database test -port 8087` shell: `select sum(value) from test` 

__Expected behavior:__
`130500`
`130500`

__Actual behavior:__
`130488`
`20188`

__Additional info:__
The first number is only sometimes off, and only by a small amount.
The second number (from the second influxdb) is always off, by a huge amount.

This is causing a problem for me as kapacitor is missing large amounts of data.

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

The subscriber write goroutine would drop points if the write load
was higher than it could process.  This could happen with a just
a few writers to the server.

Instead, process the channel with multiple writers to avoid dropping
writes so easily.  This also adds some config options to control how
large the channel buffer is as well as how many goroutines are started.

Fixes #7330

cc @nathanielc

### CODE REVIEW

File: services/subscriber/config.go [hunk 1]
```diff
@@ -8,7 +8,9 @@ import (
 )
 
 const (
-	DefaultHTTPTimeout = 30 * time.Second
+	DefaultHTTPTimeout      = 30 * time.Second
+	DefaultWriteConcurrenty = 40
```
Comment (nathanielc) [inline services/subscriber/config.go]: Should this be `DefaultWriteConcurrency`?

Comment (jwilder) [inline services/subscriber/config.go]: Yep

**Comment by jwilder** [comment]
@nathanielc Updated.
