### PR TITLE
fix(component/TemplateBrowserList): sort list of templates alphabetically

### LINKED ISSUE #14465: The list of templates should be sorted alphabetically
this list should be alphabetical:

image

### PR DESCRIPTION
**Pull request by desa**
Closes #14465

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/templates/components/createFromTemplateOverlay/TemplateBrowserList.tsx [hunk 1]
```diff
@@ -23,16 +23,18 @@ class TemplateBrowser extends PureComponent<Props> {
...
-            key={t.id}
-            template={t}
-            label={t.meta.name}
-            onClick={onSelectTemplate}
-            testID={`template--${t.meta.name}`}
-            selected={_.get(selectedTemplateSummary, 'id', '') === t.id}
-          />
-        ))}
+        {templates
+          .sort((a, b) => (b.meta.name < a.meta.name ? 1 : -1))
```
Comment (121watts) [inline ui/src/templates/components/createFromTemplateOverlay/TemplateBrowserList.tsx]: probably want a `string.toLocaleLowerCase` when evaluating these string.  also, we have a component which does this for you.  it's called `SortingHat`.  if you don't want to use that, might I suggest using lodash's `sortBy` or `orderBy`.  It just reads nicer.
