### PR TITLE
Optimize queries that compare a tag value to an empty string

### LINKED ISSUE #7243: Performance for queries with tag <> '' seems significantly degraded with 0.13 and 1.0.0-rc1
### Bug report

There's a significant speed difference between 0.12 and 0.13+ when using a query like this:

```
select sum(value) from visitors where ip <> ''
```

It takes 2.5s on 0.12:

```
time influx -database square_holes -execute "select sum(value) from visitors where ip <> ''"
name: visitors
--------------
time    sum
0       235673


real    0m2.506s
user    0m0.004s
sys     0m0.004s
```

But on 0.13 it takes 35s

```
 time influx -database square_holes -execute "select sum(value) from visitors where ip <> ''"
name: visitors
--------------
time    sum
0       235673


real    0m34.780s
user    0m0.003s
sys     0m0.003s

```

And on 1.0.0-rc1 it takes 47s.

```
time influx -database square_holes -execute "select sum(value) from visitors where ip <> ''"
name: visitors
--------------
time    sum
0       235673


real    0m46.913s
user    0m0.005s
sys     0m0.017s
```

All 3 cases make the processor go to the top, in the first case it stays there for 3 seconds while on the other two cases it stays on top for much longer.

In this dataset `ip` is a string representation of an IPv4 address, series looks like this:

```
show series
...
visitors,ip=254.247.144.250
visitors,ip=254.248.148.130
visitors,ip=254.248.166.225
visitors,ip=254.248.215.152
visitors,ip=254.248.218.103
...
```

Speed seems to improve when using `= '254.248.148.130'` (fastest!) and `<> '254.248.148.130'` (still decent) but not as good when using `<> ''`, in this dataset, there's no tag with the `''` value (there's however the possibility that this tag could be empty at some point).

The current dataset I am using to test has about 18k different values on this tag, if the database is larger, influxdb 0.13+ takes more time to compute a query like that, even tho when the same query takes a few seconds on 0.12. I could generate a larger dataset if this one doesn't produce a noticeable effect on your end.

Thanks.

__System info:__ Influxdb 0.13 and 1.0.0-rc1, Ubuntu Linux (3.13.0-24-generic)

__Steps to reproduce:__

1. Import this dataset [square_holes.tar.gz](https://github.com/influxdata/influxdb/files/444993/square_holes.tar.gz) with `influxd restore -database square_holes`, you can also generate a dataset with [this program](https://gist.github.com/xiam/c61c53f2e463c344824ce563ed39eec8). The database I attached has about 18k different values, which seems to be enough to demonstrate this behaviour.
2. Compare this command `time influx -database square_holes -execute "select sum(value) from visitors where ip <> ''"` on 0.12, 0.13 and 1.0.0-rc1. 

__Expected behavior:__ Query performance is better or equal on greater versions.

__Actual behavior:__ Query performance, for this particular case, was degraded.

__Additional info:__

* [block.txt](https://github.com/influxdata/influxdb/files/445058/block.txt)
* [goroutine.txt](https://github.com/influxdata/influxdb/files/445060/goroutine.txt)
* [heap.txt](https://github.com/influxdata/influxdb/files/445063/heap.txt)
* [vars.txt](https://github.com/influxdata/influxdb/files/445065/vars.txt)
* [iostat.txt](https://github.com/influxdata/influxdb/files/445066/iostat.txt)
* [shards.txt](https://github.com/influxdata/influxdb/files/445067/shards.txt)
* [stats.txt](https://github.com/influxdata/influxdb/files/445068/stats.txt)
* [diagnostics.txt](https://github.com/influxdata/influxdb/files/445069/diagnostics.txt)

### PR DESCRIPTION
**Pull request by jsternberg**
The behavior for querying tag values with an empty string was originally
fixed in #6283, but it also added a performance problem when the
cardinality of the tag was high. Since a call to `Union()` or `Reject()`
would happen for every series key and it would be called N times for N
cardinality, the comparisons against a blank string were unnecessarily
slow with large memory allocations.

This optimizes these queries so it doesn't use those methods anymore.
Those methods are still useful and used when combining AND and OR
clauses, but they aren't useful when finding the series ids for a single
clause. These methods were unnecessary anyway because the series ids for
the tags were unique anyway and didn't have to be merged as a set.

Fixes #7243.

### CODE REVIEW

File: tsdb/meta.go [hunk 1]
```diff
@@ -927,18 +927,68 @@ func (m *Measurement) idsForExpr(n *influxql.BinaryExpr) (SeriesIDs, influxql.Ex
...
+				// Make a new slice with only the remaining ids.
+				if sz > 0 {
+					ids = make([]uint64, 0, sz)
+					for _, id := range seriesIDs {
+						if id.evict {
+							continue
+						}
+						ids = append(ids, id.val)
+					}
 				}
```
Comment (benbjohnson) [inline tsdb/meta.go]: I think this all makes sense but can you refactor it to a function so it's more isolated and doesn't indent out so much. It makes it difficult to follow.

Comment (jsternberg) [inline tsdb/meta.go]: Done and also implemented it for regexes too.

File: tsdb/meta.go [hunk 2]
```diff
@@ -1608,6 +1622,84 @@ func (a SeriesIDs) Reject(other SeriesIDs) SeriesIDs {
...
+				seriesIDs[i].evict = true
+				a.sz--
+			}
+			// Skip over this series since it has been evicted and won't be
+			// encountered again.
+			i++
+		}
+		seriesIDs = seriesIDs[i:]
+	}
+}
```
Comment (benbjohnson) [inline tsdb/meta.go]: Does the method need to be exported? Same goes for `Evict()`.

Comment (jsternberg) [inline tsdb/meta.go]: No, but the type isn't exported so I thought the method wouldn't be exported either.

**Comment by jsternberg** [comment]
The 32bit/ubuntu:14.04 image seems to be missing from Docker Hub. It looks like images for 16.04 were pushed 15 hours ago (as I am writing this) and I don't see any tags for 14.04 anymore.

**Comment by benbjohnson** [comment]
:+1:

**Comment by beckettsean** [comment]
@jsternberg #7243 isn't listed on the CHANGELOG that I can see. Is this part of 1.0? Looks like from the merge.

**Comment by jsternberg** [comment]
@beckettsean did you check the changelog in the 1.0 branch? It hasn't hit master yet.

**Comment by jsternberg** [comment]
This should now be in master.

**Comment by beckettsean** [comment]
Thanks, @jsternberg, I didn't even think about that. My apologies!
