### PR TITLE
fix: handle https in systemd wrapper, and prevent it from looping forever

### LINKED ISSUE #21967: startup script influxd-systemd-start.sh stuck in while loop if http auth set
__Actual behavior:__

systemd service stuck in /usr/lib/influxdb/scripts/influxd-systemd-start.sh in while loop if http authentification is set
I belive that problem is introduced in commit c8de72ddbc5fdf20f821ca473f1fdf92820f9ac3

__Environment info:__

* System info: Linux 5.10.53-sunxi64 aarch64
* InfluxDB version: InfluxDB v1.8.7 (git: 1.8 v1.8.7)
* Other relevant environment details:
dpkg -l | grep influx
ii  influxdb                           1.8.7-1                                    arm64        Distributed time-series database.
cat /etc/issue
Ubuntu 18.04.5 LTS

### PR DESCRIPTION
**Pull request by codyshepherd**
Closes #21967 

Check for https-enabled in influxdb config. Exit if certificate path does not exist or if 10 attempts have been made to contact the endpoint after startup.

This PR also updates the package install test to include a test of https using a self-signed certificate.
****

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: scripts/influxd-systemd-start.sh [hunk 1]
```diff
@@ -1,17 +1,38 @@
...
 HOST=${BIND_ADDRESS%%:*}
 HOST=${HOST:-"localhost"}
 PORT=${BIND_ADDRESS##*:}
-
+  
 set +e
-result=$(curl -s -o /dev/null http://$HOST:$PORT/health -w %{http_code})
+max_attempts=10
+url="$PROTOCOL://$HOST:$PORT/health"
+result=$(curl -k -s -o /dev/null $url -w %{http_code})
```
Comment (docmerlin) [inline scripts/influxd-systemd-start.sh:27]: the space after the -w needs to be removed here.
The above line should read:
`result=$(curl -k -s -o /dev/null $url -w%{http_code})`

File: scripts/influxd-systemd-start.sh [hunk 2]
```diff
@@ -1,17 +1,38 @@
...
 while [ "$result" != "200" ]; do
   sleep 1
-  result=$(curl -s -o /dev/null http://$HOST:$PORT/health -w %{http_code})
+  result=$(curl -k -s -o /dev/null $url -w %{http_code})
```
Comment (docmerlin) [inline scripts/influxd-systemd-start.sh:30]: same as above.

**Review by docmerlin — CHANGES_REQUESTED** [review]

**Review by docmerlin — APPROVED** [review]

File: scripts/influxd-systemd-start.sh (hunk 1 above)
Comment (docmerlin) [reply scripts/influxd-systemd-start.sh:27]: sorry this was a result of a typo in my testing

**Review by psteinbachs — APPROVED** [review]
This looks good.
