### PR TITLE
fix(ui): DWP should default bucket name to selected bucket

### LINKED ISSUE #16011: Delete with predicate state persisted across data explorer and buckets page
dwp

Note how the selected bucket in the delete with predicate overlay is not the same as the bucket that I clicked on.

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #16011

### Problem

Selecting to delete with predicate from an active bucket was not updating the selected bucket once an initial bucket was set

### Solution

The solution to this problem was to separate some of the logic from where the initial bucket name was being received, and also making sure to reset the deleteWithPredicate reducer component to its default state when the overlay is closed.

Buckets:
buckets-dwp

Data Explorer:
de-dwp

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)

### CODE REVIEW

File: ui/src/shared/components/DeleteDataOverlay.tsx [hunk 1]
```diff
@@ -2,61 +2,70 @@
...
-  const handleDismiss = () =>
+  const handleDismiss = () => {
+    resetPredicateStateAction()
     router.push(`/orgs/${orgID}/load-data/buckets/${bucketID}`)
-  // separated find logic and name logic since directly routing the a delete-data
-  // endpoint was crashing the app because the bucket is undefined until the component mounts
+  }
   const bucket = buckets.find(bucket => bucket.id === bucketID)
-  const bucketName = bucket && bucket.name ? bucket.name : ''
-  const initialBucketName = selectedBucketName || bucketName
```
Comment (drdelambre) [inline ui/src/shared/components/DeleteDataOverlay.tsx]: how does not having a selected bucket fix the not having a selected bucket issue?

Comment (drdelambre) [reply ui/src/shared/components/DeleteDataOverlay.tsx]: ie: should we instead be making sure that the selected bucket is being correctly maintained throughout the application's lifecycle
