### PR TITLE
fix(ui): regression fix, notes are now deletable

### LINKED ISSUE #16170: There is no way to delete a note on a dashboard
we need to add the ability to delete a note.

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #16170

### Problem

No option was given for deleting note cells

### Solution

Added the existing delete cell functionality to the dropdown

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)

### CODE REVIEW

File: ui/src/shared/components/cells/CellContext.tsx [hunk 1]
```diff
@@ -69,6 +69,13 @@ const CellContext: FunctionComponent<Props> = ({
             onHide={onHide}
             testID="cell-context--note"
           />
+          <CellContextDangerItem
```
Comment (ebb-tide) [inline ui/src/shared/components/cells/CellContext.tsx]: ❤️

File: ui/src/clockface/components/inputs/multipleInput/MultipleRows.tsx [hunk 2]
```diff
@@ -20,10 +20,10 @@ interface RowsProps {
 const Rows: SFC<RowsProps> = ({tags, onDeleteTag, onChange}) => {
   return (
     <div className="input-tag-list">
-      {tags.map(item => {
+      {tags.map((item, index) => {
         return (
           <Row
-            index={tags.indexOf(item)}
+            index={index}
```
Comment (ebb-tide) [inline ui/src/clockface/components/inputs/multipleInput/MultipleRows.tsx]: what dis about?

File: CHANGELOG.md [hunk 3]
```diff
@@ -17,6 +17,7 @@
 1. [16105](https://github.com/influxdata/influxdb/pull/16105): Fix crash when loading queries built using Query Builder
 1. [16112](https://github.com/influxdata/influxdb/pull/16112): Create cell view properties on dashboard creation
 1. [16172](https://github.com/influxdata/influxdb/pull/16172): Fixed table ui threshold colorization issue where setting thresholds would not change table UI
+1. [16175](https://github.com/influxdata/influxdb/pull/16175): Added delete functionality to note cells so that they can be deleted
```
Comment (ebb-tide) [inline CHANGELOG.md]: Actually yes- looking at the code I don't think `type= markdown` cells were ever able to be deleted.

File: ui/src/clockface/components/inputs/multipleInput/MultipleRows.tsx (hunk 2 above)
Comment (Asalem1) [reply ui/src/clockface/components/inputs/multipleInput/MultipleRows.tsx]: Truthfully this was me working on:

https://github.com/influxdata/honeybadger-errors/issues/19

Since I believe that the issue is resolved and won't be pushing up the change, I figured it was small and straightforward enough update that simplified the component's logic. I can remove it from the PR if needed

File: CHANGELOG.md (hunk 3 above)
Comment (Asalem1) [reply CHANGELOG.md]: That is correct, not sure why they that functionality hadn't been integrated from the outset, but 🤷‍♂

File: ui/src/clockface/components/inputs/multipleInput/MultipleRows.tsx (hunk 2 above)
Comment (ebb-tide) [reply ui/src/clockface/components/inputs/multipleInput/MultipleRows.tsx]: hrmm.  it does seem like a reasonable change, but I also think we shouldn't fix it if we don't know its not broken? I'm not sure.

Comment (Asalem1) [reply ui/src/clockface/components/inputs/multipleInput/MultipleRows.tsx]: I hear ya, I'll go ahead and revert it
