### PR TITLE
fix(ui): ignore false change events in VariableForm

### LINKED ISSUE #15059: Save as Variable: Save the query when selection other variable types (map, csv)
as a user
when i decide to save my query as a variable and select other variable types
then i would like my query to be saved so that when i switch back to it, i don't lose it

variable

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #15059

If a user re-selects the same variable type when adding a variable, no action takes place

### CODE REVIEW

**Comment by drdelambre** [comment]
waiting on clarification of acceptance criteria before merging

**Comment by desa** [comment]
@drdelambre it's pretty common that people rebase and squash things into a single commit, but there's no hard requirements on that at the moment. Feel free to merge at your discretion.

**Comment by drdelambre** [comment]
i'm all about it! game plan is to use the big green "squash and merge" button and rewrite the commit log, unless otherwise instructed.

**Comment by desa** [comment]
works for me 👍

File: ui/src/types/arguments.ts [hunk 1]
```diff
@@ -1,21 +1,22 @@
-export interface MapArguments {
-  type: 'map'
-  values: KeyValueMap
+interface Argument<T> {
+  type: VariableArgumentType
+  values: T
```
Comment (121watts) [inline ui/src/types/arguments.ts]: Love this use of generics.

File: ui/src/variables/components/VariableArgumentsEditor.tsx [hunk 2]
```diff
@@ -21,20 +22,21 @@ interface Props {
...
-    switch (args.type) {
+    switch (variableType) {
       case 'query':
         return (
           <Form.Element label="Script">
             <Grid.Column>
               <div className="overlay-flux-editor">
                 <FluxEditor
-                  script={args.values.query}
+                  script={(args as QueryArguments).values.query}
```
Comment (121watts) [inline ui/src/variables/components/VariableArgumentsEditor.tsx]: Generally a smell when I have to cast a type using `as`

File: ui/src/variables/components/VariableForm.test.tsx [hunk 3]
```diff
@@ -0,0 +1,84 @@
+// Libraries
+import React from 'react'
+import {shallow} from 'enzyme'
```
Comment (121watts) [inline ui/src/variables/components/VariableForm.test.tsx]: Why not use `react-testing-library`?

File: ui/src/variables/components/VariableForm.test.tsx [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+
+// Components
+import VariableForm from 'src/variables/components/VariableForm'
+
+// Constants
+import {variables} from 'mocks/dummyData'
```
Comment (121watts) [inline ui/src/variables/components/VariableForm.test.tsx]: Let's decide on a convention on where to put dummy test data.

File: ui/src/variables/components/VariableForm.test.tsx [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+  describe('rendering', () => {
+    it('renders', () => {
+      const {wrapper} = setup()
+      expect(wrapper.exists()).toBe(true)
+      expect(wrapper).toMatchSnapshot()
+    })
+  })
+
+  describe('type selector', () => {
+    it('should not tell the the parrent if the type was not changed', () => {
```
Comment (121watts) [inline ui/src/variables/components/VariableForm.test.tsx]:
```suggestion
    it('should not tell the the parent if the type was not changed', () => {
```

File: ui/src/variables/components/VariableFormContext.test.tsx [hunk 6]
```diff
@@ -0,0 +1,45 @@
+// Libraries
+import React from 'react'
+import {shallow} from 'enzyme'
```
Comment (121watts) [inline ui/src/variables/components/VariableFormContext.test.tsx]: I thought you liked `react-testing-library`

File: ui/src/variables/components/VariableFormContext.tsx [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+  private handleHideOverlay() {
+    const {onHideOverlay, onEditorClose} = this.props
+
+    onEditorClose()
+    onHideOverlay()
+  }
+}
+
+const mstp = (state: AppState): StateProps => {
+  const variables = extractVariablesList(state),
```
Comment (121watts) [inline ui/src/variables/components/VariableFormContext.tsx]: Love all the selectors.

Silly nit but is the prefix `extract` adding value to these function names?

File: ui/src/variables/components/VariableArgumentsEditor.tsx (hunk 2 above)
Comment (drdelambre) [reply ui/src/variables/components/VariableArgumentsEditor.tsx]: felt the same way, seemed to come along with the use of the generics and the `vartype = type1 | type2 | type3` definitions. typescript seems to be only able to resolve in one direction. any tips on mitigating this kind of polymorphism?

File: ui/src/variables/components/VariableForm.test.tsx (hunk 3 above)
Comment (drdelambre) [reply ui/src/variables/components/VariableForm.test.tsx]: ....cause i forgot.
WILL DO!

File: ui/src/variables/components/VariableForm.test.tsx (hunk 4 above)
Comment (drdelambre) [reply ui/src/variables/components/VariableForm.test.tsx]: i need a rough overview of this tomorrow. running into weird conditions when trying to run the code in different environments.

File: ui/src/variables/components/VariableForm.test.tsx (hunk 5 above)
Comment (drdelambre) [reply ui/src/variables/components/VariableForm.test.tsx]: lol thanks for the catch

File: ui/src/variables/components/VariableFormContext.tsx (hunk 7 above)
Comment (drdelambre) [reply ui/src/variables/components/VariableFormContext.tsx]: not at all! i was trying to follow the convention, but extractions/segmentation/whatever is a function of their include path, so it's a bit redundant.

File: ui/src/variables/actions/index.ts [hunk 8]
```diff
@@ -31,14 +31,80 @@ import * as copy from 'src/shared/copy/notifications'
...
+
+interface SetConstant {
+  type: 'UPDATE_VARIABLE_EDITOR_CONSTANT'
+  payload: VariableArguments
+}
+
+export const updateConstant = (arg: VariableArguments): SetConstant => ({
+  type: 'UPDATE_VARIABLE_EDITOR_CONSTANT',
+  payload: arg,
+})
```
[the remark this answers is not in the document]
Comment (drdelambre) [reply ui/src/variables/actions/index.ts]: is there some more examples in the code so that i can wrap my head around this?

[the remark this answers is not in the document]
Comment (ebb-tide) [reply ui/src/variables/actions/index.ts]: ui/src/alerting/actions/checks.ts

[the remark this answers is not in the document]
Comment (drdelambre) [reply ui/src/variables/actions/index.ts]: updated the file to reflect the new pattern!
