### PR TITLE
Make sure parenthesized SELECT arguments are evaluated properly without panic

### LINKED ISSUE #5628: [0.10.0] Crashed the server with a bad derivative query
* centos 6.7 
* influxdb-0.10.0-1.x86_64

Ran the following query from Grafana - crashed the influxdb server

```
SELECT (derivative(value, 1m) / 60.000) FROM collectd."default".interface_rx 
WHERE type = 'if_octets' AND type_instance = 'eth0' AND time > now() - 30m AND 
time < now() - 1m GROUP BY host
```

Log output:

```
[query] 2016/02/11 10:22:15 SELECT (derivative(value, 1m) / 60.000) FROM collectd."default".interface_rx WHERE type = 'if_octets' AND type_instance = 'eth0' AND time > now() - 30m AND time < now() - 1m GROUP BY host
panic: interface conversion: interface is float64, not map[string]interface {}

goroutine 233276 [running]:
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc20b1afd40, 0xc20c796800, 0xad, 0x100, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/raw.go:524 +0x1173
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc20b1afd40)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/raw.go:446 +0xd6
github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc20baba7b0, 0xc2093420c0, 0xc20805ff20)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/raw.go:154 +0x17e5
created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/raw.go:59 +0x64

```

### LINKED ISSUE #5630: [0.11.0] (master) panic when surrounding the select statement arguments in brackets
A simple
```sql
SELECT (mean(value)/1) from cpu
```
or 
```sql
SELECT (derivative(value, 1m)) FROM cpu
```
 yields a panic:
```
[query] 2016/02/11 07:27:04 SELECT (mean(value) / 1.000) FROM stress."default".cpu
panic: invalid expression type: *influxql.ParenExpr

goroutine 105 [running]:
github.com/influxdata/influxdb/influxql.buildExprIterator(0x37ca820, 0xc825c817e0, 0x37cac08, 0xc826908740, 0x37ca820, 0xc825c817e0, 0xd24908, 0x0, 0x0, 0xc825c81c40, ...)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:362 +0x36dc
github.com/influxdata/influxdb/influxql.buildFieldIterators.func1(0xc825c0f9a8, 0x1, 0x1, 0x37cac08, 0xc826908740, 0xc821fe74e8, 0xc825c81c90, 0x1, 0x1, 0x0, ...)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:140 +0x548
github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc825c0f9a8, 0x1, 0x1, 0x37cac08, 0xc826908740, 0x0, 0x0, 0xd24908, 0x0, 0x0, ...)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:127 +0xf8
github.com/influxdata/influxdb/influxql.Select(0xc8222c2750, 0x37cac08, 0xc826908740, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:67 +0xb9c
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).PlanSelect(0xc820132500, 0xc8222c2750, 0x2710, 0x0, 0x0, 0x0, 0x0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:275 +0x724
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).planStatement(0xc820132500, 0x37caa58, 0xc8222c2750, 0xc8202e1e0e, 0x6, 0x2710, 0x0, 0x0, 0x0, 0x0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:524 +0x177
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).executeStatement(0xc820132500, 0x0, 0x37caa58, 0xc8222c2750, 0xc8202e1e0e, 0x6, 0xc820070120, 0x2710, 0xc8202e1ec0, 0x0, ...)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:648 +0x86
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).ExecuteQuery.func1(0xc820070120, 0xc8269084c0, 0xc8202e1e0e, 0x6, 0xc820132500, 0x2710, 0xc8202e1ec0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:172 +0x97f
created by github.com/influxdata/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:227 +0xa8
```

### PR DESCRIPTION
**Pull request by seiflotfy**
Fixes https://github.com/influxdata/influxdb/issues/5630
Fixes #5628

### CODE REVIEW

**Comment by corylanou** [comment]
+1 with changelog.  Thanks!

**Comment by jwilder** [comment]
@jsternberg Can you take a look?

**Comment by jsternberg** [comment]
Is this an issue with the new query engine? We call reduce before performing any processing on the underlying query. @seiflotfy can you rebase and try your test case without any other changes?

**Comment by seiflotfy** [comment]
This was an issue with the new engine. I wrote the test to make it crash. Then wrote the fix

**Comment by seiflotfy** [comment]
@jsternberg this is what i get running it without the line
```
	exit status 2
	FAIL	github.com/influxdata/influxdb/influxql	0.032s
	
	panic: invalid expression type: *influxql.ParenExpr [recovered]
		panic: invalid expression type: *influxql.ParenExpr
	
	goroutine 92 [running]:
	testing.tRunner.func1(0xc820272360)
		/usr/local/Cellar/go/1.5.3/libexec/src/testing/testing.go:450 +0x171
	github.com/influxdata/influxdb/influxql.buildExprIterator(0x7b89c0, 0xc8201381c0, 0x7b8cc8, 0xc82007cde0, 0x7b89c0, 0xc8201381c0, 0x595c58, 0x0, 0x0, 0xc820138280, ...)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:362 +0x36dc
	github.com/influxdata/influxdb/influxql.buildFieldIterators.func1(0xc82002fd48, 0x1, 0x1, 0x7b8cc8, 0xc82007cde0, 0xc820125968, 0xc8201386f0, 0x1, 0x1, 0x0, ...)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:140 +0x548
	github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc82002fd48, 0x1, 0x1, 0x7b8cc8, 0xc82007cde0, 0x0, 0x0, 0x595c58, 0x0, 0x0, ...)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:127 +0xf8
	github.com/influxdata/influxdb/influxql.Select(0xc82012a5b0, 0x7b8cc8, 0xc82007cde0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:67 +0xb9c
	github.com/influxdata/influxdb/influxql_test.TestSelect_ParenExpr(0xc820272360)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select_test.go:1440 +0x109
	testing.tRunner(0xc820272360, 0x571250)
		/usr/local/Cellar/go/1.5.3/libexec/src/testing/testing.go:456 +0x98
	created by testing.RunTests
		/usr/local/Cellar/go/1.5.3/libexec/src/testing/testing.go:561 +0x86d
```

**Comment by seiflotfy** [comment]
@jsternberg this is what I get running it without the line
```
	exit status 2
	FAIL	github.com/influxdata/influxdb/influxql	0.032s
	
	panic: invalid expression type: *influxql.ParenExpr [recovered]
		panic: invalid expression type: *influxql.ParenExpr
	
	goroutine 92 [running]:
	testing.tRunner.func1(0xc820272360)
		/usr/local/Cellar/go/1.5.3/libexec/src/testing/testing.go:450 +0x171
	github.com/influxdata/influxdb/influxql.buildExprIterator(0x7b89c0, 0xc8201381c0, 0x7b8cc8, 0xc82007cde0, 0x7b89c0, 0xc8201381c0, 0x595c58, 0x0, 0x0, 0xc820138280, ...)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:362 +0x36dc
	github.com/influxdata/influxdb/influxql.buildFieldIterators.func1(0xc82002fd48, 0x1, 0x1, 0x7b8cc8, 0xc82007cde0, 0xc820125968, 0xc8201386f0, 0x1, 0x1, 0x0, ...)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:140 +0x548
	github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc82002fd48, 0x1, 0x1, 0x7b8cc8, 0xc82007cde0, 0x0, 0x0, 0x595c58, 0x0, 0x0, ...)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:127 +0xf8
	github.com/influxdata/influxdb/influxql.Select(0xc82012a5b0, 0x7b8cc8, 0xc82007cde0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:67 +0xb9c
	github.com/influxdata/influxdb/influxql_test.TestSelect_ParenExpr(0xc820272360)
		/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select_test.go:1440 +0x109
	testing.tRunner(0xc820272360, 0x571250)
		/usr/local/Cellar/go/1.5.3/libexec/src/testing/testing.go:456 +0x98
	created by testing.RunTests
		/usr/local/Cellar/go/1.5.3/libexec/src/testing/testing.go:561 +0x86d
```

**Comment by jsternberg** [comment]
Ah, so the reason is because I used `Reduce()` in the aux iterator, but forgot to use it in `buildExprIterator`. Can you use `Reduce()` instead inside of `buildFieldIterators` before the expression gets sent to `buildExprIterator`? The reason is because the binary expression evaluator relies on it to reduce things like this: `SELECT max(value) + 2 + 2` to `SELECT  max(value) + 4`.

That way you shouldn't have to handle a `ParenExpr` inside of `buildExprIterator`, although it may be good to include both so that expressions like this get evaluated correctly: `SELECT max(value) + (2 + min(value))`.

**Comment by seiflotfy** [comment]
On it

**Comment by seiflotfy** [comment]
@jsternberg all done :+1:

File: influxql/select.go [hunk 1]
```diff
@@ -132,6 +132,9 @@ func buildFieldIterators(fields Fields, ic IteratorCreator, opt IteratorOptions)
 			// Build iterators for calls first and save the iterator.
 			// We do this so we can keep the ordering provided by the user, but
 			// still build the Call's iterator first.
+
+			f.Expr = Reduce(f.Expr, nil)
```
Comment (jsternberg) [inline influxql/select.go]: Can you assign the reduced expression to a temporary variable? I would prefer not to modify the array that is coming into this function to avoid unintended side effects at the call site. You can do the reduction here after checking for a variable reference and then do it one more time below when the auxiliary iterators are being created.

**Comment by jsternberg** [comment]
One comment and then the rest looks good.

File: influxql/select.go [hunk 2]
```diff
@@ -132,12 +132,15 @@ func buildFieldIterators(fields Fields, ic IteratorCreator, opt IteratorOptions)
 			// Build iterators for calls first and save the iterator.
 			// We do this so we can keep the ordering provided by the user, but
 			// still build the Call's iterator first.
-			if ContainsVarRef(f.Expr) {
+
+			expr := Reduce(f.Expr, nil)
```
Comment (jsternberg) [inline influxql/select.go]: This should be after the `ContainsVarRef` call to avoid any unnecessary reductions in the case of an aux field. You also need to add this reduction when building the aux iterators.

**Comment by seiflotfy** [comment]
@jsternberg n-th time is the charm (I will replace the n once its merged :+1: )

**Comment by jsternberg** [comment]
:+1:
