### PR TITLE
fix(ui): show checked on multidropdown

### LINKED ISSUE #11538: Multiselect dropdown checkboxes not appearing checked
screen shot 2019-01-24 at 11 01 57 am

### PR DESCRIPTION
**Pull request by OfTheDelmer**
Closes #11538 

_Briefly describe your proposed changes:_
Show style for selected items in multi select dropdown

  - [x] Rebased/mergeable
  - [x] Tests pass
 - [x] Update CHANGELOG

kapture 2019-02-06 at 11 30 55

### CODE REVIEW

File: ui/src/dataExplorer/components/DashboardsDropdown.tsx [hunk 1]
```diff
@@ -58,7 +58,9 @@ class DashboardsDropdown extends PureComponent<Props> {
   }
 
   private get dividerItem(): JSX.Element {
-    return <MultiSelectDropdown.Divider key={0} />
```
Comment (OfTheDelmer) [inline ui/src/dataExplorer/components/DashboardsDropdown.tsx]: the default for a new dashboard has `id` of `0` and `key` of `0` so this was causing a key collision
