### PR TITLE
fix(task/ui): display server error message

### LINKED ISSUE #12689: Update error handling in Tasks Create UI
the error message is always blank for creating a task. let's fill it in with the error returned from tasks.

image

### PR DESCRIPTION
**Pull request by 121watts**
Closes #12689

#### Notes
I really like [this](https://github.com/influxdata/influxdb/pull/12704/files#diff-26d13671c2309446101c125ea3499756R7) pattern.  Whoever wrote this, kudos.  Now to only implement it everywhere...

### CODE REVIEW

File: ui/src/tasks/actions/v2/index.ts [hunk 1]
```diff
@@ -473,8 +467,8 @@ export const runTask = (taskID: string) => async dispatch => {
   try {
     await client.tasks.startRunByTaskID(taskID)
     dispatch(notify(taskRunSuccess()))
-  } catch (e) {
-    console.error(e)
+  } catch (error) {
+    console.error(error)
```
Comment (ischolten) [inline ui/src/tasks/actions/v2/index.ts]: do we not need to notify on this error?

File: ui/src/tasks/actions/v2/index.ts [hunk 2]
```diff
@@ -484,8 +478,8 @@ export const getLogs = (taskID: string, runID: string) => async (
   try {
     const logs = await client.tasks.getLogEventsByRunID(taskID, runID)
     dispatch(setLogs(logs))
-  } catch (e) {
-    console.error(e)
+  } catch (error) {
+    console.error(error)
```
Comment (ischolten) [inline ui/src/tasks/actions/v2/index.ts]: same for this one?
