### PR TITLE
fix(upgrade): ensure query config written by `influxd upgrade` is valid

### LINKED ISSUE #21315: `influxd config` generates invalid config files
1: Client:
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.2-0ubuntu1~20.10.1
 Built:             Tue Mar 23 23:21:32 2021
 OS/Arch:           linux/amd64

2: migration from Influxdb 1.8 to 2.0 works without issue

3: start docker-compose with Influxdb version 2.05.

docker starts but crashes at the end.

With previous version, it was working. I cannot revert to previous versions as previous tags don't exist in th github

Traces :  

2021-04-28T09:44:52.486291000Z 2021-04-28T09:44:52.484797214Z	info	booting influxd server in the background	{"system": "docker"}

2021-04-28T09:44:54.491720000Z 2021-04-28T09:44:54.490864600Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:44:56.530532000Z 2021-04-28T09:44:56.529661141Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:44:58.574439000Z 2021-04-28T09:44:58.573581995Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:00.611272000Z 2021-04-28T09:45:00.610462985Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:02.643694000Z 2021-04-28T09:45:02.642926910Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:04.674626000Z 2021-04-28T09:45:04.673950932Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:06.708452000Z 2021-04-28T09:45:06.707758675Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:08.744978000Z 2021-04-28T09:45:08.744181216Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:10.780972000Z 2021-04-28T09:45:10.780291546Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:11.105450000Z ts=2021-04-28T09:45:11.105038Z lvl=info msg="Welcome to InfluxDB" log_id=0TmyjWl0000 version=2.0.5 commit=741389781e build_date=2021-04-27T17:57:07Z

2021-04-28T09:45:11.115838000Z ts=2021-04-28T09:45:11.115366Z lvl=info msg="Resources opened" log_id=0TmyjWl0000 service=bolt path=/var/lib/influxdb2/influxd.bolt

2021-04-28T09:45:11.118845000Z ts=2021-04-28T09:45:11.117971Z lvl=info msg="Bringing up metadata migrations" log_id=0TmyjWl0000 service=migrations migration_count=15

2021-04-28T09:45:11.293618000Z ts=2021-04-28T09:45:11.292942Z lvl=info msg="Using data dir" log_id=0TmyjWl0000 service=storage-engine service=store path=/var/lib/influxdb2/engine/data

2021-04-28T09:45:11.294331000Z ts=2021-04-28T09:45:11.293225Z lvl=info msg="Compaction settings" log_id=0TmyjWl0000 service=storage-engine service=store max_concurrent_compactions=2 throughput_bytes_per_second=50331648 throughput_bytes_per_second_burst=50331648

2021-04-28T09:45:11.294845000Z ts=2021-04-28T09:45:11.293265Z lvl=info msg="Open store (start)" log_id=0TmyjWl0000 service=storage-engine service=store op_name=tsdb_open op_event=start

2021-04-28T09:45:11.295780000Z ts=2021-04-28T09:45:11.293470Z lvl=info msg="Open store (end)" log_id=0TmyjWl0000 service=storage-engine service=store op_name=tsdb_open op_event=end op_elapsed=0.154ms

2021-04-28T09:45:11.296378000Z ts=2021-04-28T09:45:11.293597Z lvl=info msg="Starting retention policy enforcement service" log_id=0TmyjWl0000 service=retention check_interval=30m

2021-04-28T09:45:11.297003000Z ts=2021-04-28T09:45:11.293659Z lvl=info msg="Starting precreation service" log_id=0TmyjWl0000 service=shard-precreation check_interval=10m advance_period=30m

2021-04-28T09:45:11.297724000Z ts=2021-04-28T09:45:11.293786Z lvl=error msg="Failed to create query controller" log_id=0TmyjWl0000 error="invalid controller config: QueueSize must be positive when ConcurrencyQuota is limited"

2021-04-28T09:45:11.298211000Z Error: invalid controller config: QueueSize must be positive when ConcurrencyQuota is limited

2021-04-28T09:45:11.298790000Z See 'influxd -h' for help

2021-04-28T09:45:12.816054000Z 2021-04-28T09:45:12.814751323Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:14.850971000Z 2021-04-28T09:45:14.850219098Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:16.890075000Z 2021-04-28T09:45:16.888846989Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:18.932790000Z 2021-04-28T09:45:18.931792214Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:20.971827000Z 2021-04-28T09:45:20.970406268Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:23.013285000Z 2021-04-28T09:45:23.012397221Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:25.052645000Z 2021-04-28T09:45:25.051484741Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:27.095480000Z 2021-04-28T09:45:27.094203460Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:29.132464000Z 2021-04-28T09:45:29.131309608Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:31.175144000Z 2021-04-28T09:45:31.173861892Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:33.214224000Z 2021-04-28T09:45:33.212745990Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:35.254611000Z 2021-04-28T09:45:35.252773873Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:37.291473000Z 2021-04-28T09:45:37.290389015Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:39.329964000Z 2021-04-28T09:45:39.328627715Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:41.372527000Z 2021-04-28T09:45:41.370999753Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:43.413176000Z 2021-04-28T09:45:43.412085351Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:45.456273000Z 2021-04-28T09:45:45.454921675Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:47.495101000Z 2021-04-28T09:45:47.494000937Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:49.535571000Z 2021-04-28T09:45:49.534357728Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:51.575446000Z 2021-04-28T09:45:51.574366564Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:53.619755000Z 2021-04-28T09:45:53.618536926Z	info	pinging influxd...	{"system": "docker"}

2021-04-28T09:45:53.655118000Z 2021-04-28T09:45:53.654349598Z	error	failed to detect influxd startup	{"system": "docker", "ping_attempts": "30"}

2021-04-28T09:45:53.659258000Z 2021-04-28T09:45:53.657646478Z	warn	cleaning bolt and engine files to prevent conflicts on retry	{"system": "docker", "bolt_path": "/var/lib/influxdb2/influxd.bolt", "engine_path": "/var/lib/influxdb2/engine"}

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #21315 

1. Stop rewriting `0` to `10` when upgrading `query-concurrency` config, now that 0 is a valid value
2. If writing a value > 0 for `query-concurrency`, ensure we also write a > 0 value for `query-queue-size`

I had to refactor a bunch of things to make our upgrade-real-DB regression test actually test loading upgraded config. I confirmed that the 1st commit fails with the error seen in #21315, and the 2nd commit gets things to pass again.

### CODE REVIEW

File: cmd/influxd/upgrade/config.go [hunk 1]
```diff
@@ -168,36 +142,70 @@ func (cu *configUpgrader) save(config map[string]interface{}, path string) error
...
+		return
+	}
+	var concurrency int64
+	switch c := concurrencyVal.(type) {
+	case int:
+		concurrency = int64(c)
+	case int32:
+		concurrency = int64(c)
+	case int64:
+		concurrency = c
```
Comment (danxmoran) [inline cmd/influxd/upgrade/config.go:180]: All these cases are paranoia on my part; I'm not sure when the config-loader would pick each type of int.

File: cmd/influxd/upgrade/config.go [hunk 2]
```diff
@@ -168,36 +142,70 @@ func (cu *configUpgrader) save(config map[string]interface{}, path string) error
...
+		concurrency = 0
+	}
+	if concurrency == 0 {
+		// The upgrade process doesn't generate a value for query-queue-size, so if
+		// query-concurrency is 0 / unset then it's safe to leave query-queue-size unset.
+		return
+	}
+
+	// When query-concurrency is > 0, query-queue-size must also be > 0.
+	v2Config["query-queue-size"] = concurrency
```
Comment (danxmoran) [inline cmd/influxd/upgrade/config.go:191]: There's a risk here that:
* Somebody will pick a huge value for query-concurrency
* We write the same value into query-queue-size
* At startup, the server uses the huge value for query-queue-size as the size of a new `chan`, consuming a lot of memory all at once

I'm assuming the risk is low now that we support 0 for unlimited, so most people who would be writing huge concurrency values can now write 0 instead.

**Review by davidby-influx — APPROVED** [review]
LGTM to me. I hate the type switch, but can't think of any way to improve it....
