### PR TITLE
Compaction fixes

### LINKED ISSUE #6406: After intense write load: "error compacting TSM files: ... exceeds max index entries"
### Bug report

__System info:__ 

OSX, InfluxDB from master @ 93745d96939f0af828921eb550a74bd52befda6d, default configuration, started with an empty ~/.influxdb folder.

__Steps to reproduce:__

Flood the system with writes in 20k batches, single series with single point, real-time nanosecond precision.

__Expected behavior:__ 

TSM compaction succeeds.

__Actual behavior:__

Queries seem to complete successfully, but seeing repeated messages about TSM compaction failing:

> [tsm1] 2016/04/16 18:22:01 beginning full compaction of group 3, 4 TSM files
> [tsm1] 2016/04/16 18:22:01 compacting full group (3) /Users/mr/.influxdb/data/b3k2m1mjvqqw_0/default/4/000000272-000000005.tsm (#0)
> [tsm1] 2016/04/16 18:22:01 compacting full group (3) /Users/mr/.influxdb/data/b3k2m1mjvqqw_0/default/4/000000288-000000004.tsm (#1)
> [tsm1] 2016/04/16 18:22:01 compacting full group (3) /Users/mr/.influxdb/data/b3k2m1mjvqqw_0/default/4/000000304-000000004.tsm (#2)
> [tsm1] 2016/04/16 18:22:01 compacting full group (3) /Users/mr/.influxdb/data/b3k2m1mjvqqw_0/default/4/000000320-000000004.tsm (#3)
> [tsm1] 2016/04/16 18:22:07 error compacting TSM files: key 'ctr,expid=b3k2m1mjvqqw#!~#n' exceeds max index entries: 136940 > 65535
> [tsm1] 2016/04/16 18:22:07 error compacting TSM files: key 'ctr,expid=b3k2m1mjvqqw#!~#n' exceeds max index entries: 138240 > 65535
> [tsm1] 2016/04/16 18:22:07 error compacting TSM files: key 'ctr,expid=b3k2m1mjvqqw#!~#n' exceeds max index entries: 137240 > 65535
> [tsm1] 2016/04/16 18:22:07 error compacting TSM files: key 'ctr,expid=b3k2m1mjvqqw#!~#n' exceeds max index entries: 138620 > 65535
> [tsm1] 2016/04/16 18:22:07 error compacting TSM files: key 'ctr,expid=b3k2m1mjvqqw#!~#n' exceeds max index entries: 193000 > 65535
> [tsm1] 2016/04/16 18:22:08 error compacting TSM files: key 'ctr,expid=b3k2m1mjvqqw#!~#n' exceeds max index entries: 223200 > 65535

__Additional info:__

44MB TSM file sent out-of-band since it exceeds the 25MB upload limit.

/cc @jwilder

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

This PR re-introduces the fix for #6556 that was reverted in #6637.  The original fix could drop points during compactions as well as cause an `interface conversion` panic (#6652) in some cases.   What happened was that merged values from one series could get mixed with the values for the next series.  If the series were different types, a panic could occur.  If it was the last block to be merged, the values would be lost.  Both of these issues should be fixed now as well as the original issue of overwriting a point in a large series triggering memory spikes.

This also fixes #6406 that can occur if enough points are written into a single series to cause the TSM index to exceed the max index entries allotment. It will now handle that error and rollover to a new file.

### CODE REVIEW

**Comment by jwilder** [comment]
@aderumier @daviesalex @easyrasta if you have a dataset that can easily reproduce #6652, would you be able to test this PR on it?

**Comment by jwilder** [comment]
@e-dard @benbjohnson

**Comment by daviesalex** [comment]
This did not work. The startup was very fast, but much of our data (most really) only exists from midnight on the 16th (not all , though). See example data:

image

FWIW, during the startup, most of the time (by a long way) is spent in sync/atomic.AddUint32:

```
Samples: 4M of event 'cycles', Event count (approx.): 430757131359
  28.53%  influxd                       [.] sync/atomic.AddUint32
  11.64%  influxd                       [.] strings.Index
   5.80%  influxd                       [.] scanblock
   4.72%  [kernel]                      [k] _raw_spin_lock
   4.60%  influxd                       [.] runtime.MSpan_Sweep
   2.33%  influxd                       [.] github.com/influxdata/influxdb/tsdb.(*DatabaseIndex).Series
   1.82%  influxd                       [.] runtime.memmove
   1.76%  influxd                       [.] runtime.aeshashbody
   1.54%  influxd                       [.] runtime.memeqbody
   1.52%  [kernel]                      [k] down_read_trylock
   1.39%  influxd                       [.] runtime.mallocgc
   1.34%  influxd                       [.] runtime.mapaccess1_faststr
   1.22%  influxd                       [.] runtime.deferreturn
   1.18%  influxd                       [.] runtime.newdefer
   1.14%  influxd                       [.] runtime.writebarrierptr
   1.10%  influxd                       [.] runtime.cas64
   1.02%  influxd                       [.] runtime.xchg
   0.95%  influxd                       [.] runtime.readvarint
   0.89%  influxd                       [.] github.com/influxdata/influxdb/tsdb/engine/tsm1.(*FileStore).WalkKeys
   0.82%  [kernel]                      [k] page_fault
   0.80%  influxd                       [.] github.com/influxdata/influxdb/tsdb/engine/tsm1.(*indirectIndex).KeyAt
   0.78%  [kernel]                      [k] up_read
   0.76%  influxd                       [.] runtime.findfunc
   0.74%  influxd                       [.] runtime.gentraceback
   0.73%  influxd                       [.] runtime.releasem
   0.69%  influxd                       [.] getfull
   0.66%  influxd                       [.] runtime.freedefer
   0.55%  influxd                       [.] runtime.acquirem
   0.53%  influxd                       [.] runtime.atomicload64
   0.53%  influxd                       [.] runtime.memclr
```

If this computation can be done in a more parallel way, there are consistently large numbers of cores available:

image

**Comment by daviesalex** [comment]
Log showing the start with this PR (branch unknown in log, but it was built from branch jw-compact-fix - 0b2554) that works but is missing most data, and then a start with the 0.13 stable release at https://gist.github.com/daviesalex/f9e70754fb2c0ac85454b6db341b34a4 which works and has the data.

File: tsdb/engine/tsm1/compact.go [hunk 1]
```diff
@@ -573,7 +573,16 @@ func (c *Compactor) write(path string, iter KeyIterator) (err error) {
...
 
 		// Write the key and value
-		if err := w.WriteBlock(key, minTime, maxTime, block); err != nil {
+		err = w.WriteBlock(key, minTime, maxTime, block)
+		if err == ErrMaxBlocksExceeded {
+			if err := w.WriteIndex(); err != nil {
+				return err
+			}
+
+			return ErrMaxBlocksExceeded
```
Comment (e-dard) [inline tsdb/engine/tsm1/compact.go]: This seems redundant since there is an `err != nil` check below.

**Comment by e-dard** [comment]
Just a nit, but LGTM 👍

File: tsdb/engine/tsm1/compact.go (hunk 1 above)
Comment (benbjohnson) [inline tsdb/engine/tsm1/compact.go]: I don't mind the redundant return but I think specifying `ErrMaxBlocksExceeded` twice is redundant. You can just do a `return err` instead.

Comment (benbjohnson) [inline tsdb/engine/tsm1/compact.go]: Also, stylistically I prefer grouping the entire thing together so the `err` is confined to a specific block:

```go
if err := w.WriteBlock(key, minTime, maxTime, block); err == ErrMaxBlocksExceeded {
	if err := w.WriteIndex(); err != nil {
		return err
	}
	return ErrMaxBlocksExceeded
} else if err != nil {
	return err
}
```

**Comment by aderumier** [comment]
@jwilder It's starting fine with this PR. (still around 10min of startup time)

File: tsdb/engine/tsm1/compact.go [hunk 2]
```diff
@@ -747,81 +801,120 @@ func (k *tsmKeyIterator) Next() bool {
...
+					return nil
+				}
+
+				// Remove values we already read
+				v = Values(v).Exclude(k.blocks[i].readMin, k.blocks[i].readMax)
+
+				// Filter out only the values for overlapping block
+				v = Values(v).Include(first.minTime, first.maxTime)
+				if len(v) > 0 {
+					// Recoder that we read a subset of the block
```
Comment (benbjohnson) [inline tsdb/engine/tsm1/compact.go]: Is this meant to say, "Record"?

File: tsdb/engine/tsm1/compact_test.go [hunk 3]
```diff
@@ -562,64 +562,94 @@ func TestCompactor_CompactFull_TombstonedMultipleRanges(t *testing.T) {
...
 
-// Tests that a single TSM file can be read and iterated over
-func TestTSMKeyIterator_Single(t *testing.T) {
+// Ensures that a compaction will properly rollover to a new file when the
+// max keys per blocks is exceeded
+func TestCompactor_CompactFull_MaxKeys(t *testing.T) {
+	// This test creates a lot of data and causes timeout failures for these envs
+	if testing.Short() || os.Getenv("CIRCLECI") != "" || os.Getenv("APPVEYOR") != "" || os.Getenv("GORACE") != "" {
+		t.Skip("Skipping max keys compaction test")
+	}
```
Comment (benbjohnson) [inline tsdb/engine/tsm1/compact_test.go]: CircleCI and Appveyor both set the `CI` environment variable.

https://circleci.com/docs/environment-variables/
https://www.appveyor.com/docs/environment-variables

**Comment by benbjohnson** [comment]
Minor nits but lgtm 👍

**Comment by jwilder** [comment]
@daviesalex With the same dataset/host, does 0.13 load all the data?  I'm not sure why you would be missing data using this branch as it does not have any changes related to startup.

**Comment by jwilder** [comment]
Also, were there any errors in the logs?

**Comment by daviesalex** [comment]
@jwilder yes. 0.13 loads all the data. This branch does not (nor does the nightly).

The full log (a start under this version, which fails to load all the data, and 0.13, which does) is in the gist above - https://gist.github.com/daviesalex/f9e70754fb2c0ac85454b6db341b34a4

File: tsdb/engine/tsm1/compact.go (hunk 1 above)
Comment (e-dard) [inline tsdb/engine/tsm1/compact.go]: `s/return ErrMaxBlocksExceeded/return err` though 😉

**Comment by jwilder** [comment]
@daviesalex If the current nightly has missing data, then it's not caused by this PR.  Any chance you could `git bisect`  0.13 and master to see if you can find the commit that is introduced the issue?   I suspect 0dbd4893daff91ed29f23de57dcd4b8520b78064 might have introduced the bug.  

Would you be able to test that commit and just before it?

**Comment by jwilder** [comment]
I was able to reproduce the missing data on startup.  It is due to https://github.com/influxdata/influxdb/commit/0dbd4893daff91ed29f23de57dcd4b8520b78064#diff-82e4e65bd72f00208a49c4797d466ecdR383.

**Comment by jwilder** [comment]
@daviesalex I pushed a fix for the data not reloading on this branch.  Let me know if that resolves it for you.

**Comment by daviesalex** [comment]
@jwilder good news. Confirmed that data is there. 

```
[run] 2016/05/18 13:12:08 InfluxDB starting, version unknown, branch unknown, commit unknown
[run] 2016/05/18 13:28:48 Listening for signals

Startup down from about 55 minutes to about 15. I tested on two machines and saw the same just over 3x speedup.

Great success! Thank you

+1 from us.
