### PR TITLE
fix(ui): duplicate logout buttons

### LINKED ISSUE #13550: There can only be one logout button
Screen Shot 2019-04-22 at 9 59 00 AM

### PR DESCRIPTION
**Pull request by 121watts**
Closes #13550

### CODE REVIEW

File: ui/src/me/components/LogoutButton.tsx [hunk 1]
```diff
@@ -15,11 +15,11 @@ const LogoutButton: SFC = () => (
         <Button text="Logout" size={ComponentSize.ExtraSmall} />
       </Link>
     </CloudExclude>
-    <CloudInclude>
+    <CloudOnly>
```
Comment (OfTheDelmer) [inline ui/src/me/components/LogoutButton.tsx]: :sparkles: :rocket: :moon: ✨
