### PR TITLE
fix: bugs

### LINKED ISSUE #16054: [UI - Dashboards] Export Dashboard > Copy to Clipboard has unreadable on success message
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a dashboard
2. In the dashboards page click export - the export popup loads
3. Click Copy to Clipboard

__Expected behavior:__
That an on success message with human readable content will notify me that the contents have been copied. 

e.g. 
```
Dashboard 'My Dashboard' has been copied to clipboard.
```

__Actual behavior:__
The success message does appear, but it contains the start of the JSON document from the preview area, which is not easily human readable. 

e.g. 

```
Dashboard '{
 "meta": {
  "version": "1",...' has been copied to clipboard.
```
Can't the name be parsed from the JSON `meta.name` and used in the notification instead? 

__Screencast__
DashboardsExportCopy2Clipboard

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.4.0-169-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly builds: 
```
ts=2019-11-27T08:44:01.001953Z lvl=info msg="Welcome to InfluxDB" log_id=0JN0LtQG000 version=nightly commit=e0098f05b build_date=2019-11-27T07:23:31Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 78__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 
```
--e2e-testing=true
```

### LINKED ISSUE #16806: Have query builder tab reflect the state I'm in, not the state I would be if I pressed the "eye"
Have query builder tab :eye: reflect the state I'm in, not the state I would be if I pressed the :eye:

### Have
image

### Want
When the series is hidden show the 🚫 👁.   When the series is visible show the 👁 .

### PR DESCRIPTION
**Pull request by drdelambre**
idk what happened.. they all kind of just kept getting fixed in one branch

Closes #16806
Closes influxdata/idpe#6052
Closes influxdata/idpe#6059
Closes influxdata/idpe#6075
Closes #16054

### CODE REVIEW

File: ui/src/dashboards/components/DashboardExportOverlay.tsx [hunk 1]
```diff
@@ -43,11 +48,20 @@ class DashboardExportOverlay extends PureComponent<Props> {
...
+
+      return dashboardCopyFailed()
+    }
+
     return (
       <ExportOverlay
         resourceName="Dashboard"
         resource={dashboardTemplate}
         onDismissOverlay={this.onDismiss}
+        onCopyText={notes}
```
Comment (drdelambre) [inline ui/src/dashboards/components/DashboardExportOverlay.tsx]: used this to stay in line with #16933
