### PR TITLE
fix: systemd unit should block on startup until http endpoint is ready

### LINKED ISSUE #6068: systemd service should "wait" until influxdb has finished starting up
Currently, using a configuration management tool, whenever the InfluxDB configuration file gets modified, InfluxDB gets restarted. The `systemctl restart` seems to complete immediately, but InfluxDB doesn't seem to be fully restarted - because some subsequent commands that check if an InfluxDB user exists and creates it if it doesn't, fails with a "Connection refused" message. If I run the configuration manager again right afterwards (<5 sec delay), it works just fine.

I know systemd has a concept of notifications to help solve this problem: https://www.freedesktop.org/software/systemd/man/systemd-notify.html

Alternatively, the script that launches the daemon shouldn't exit until the forked process is done starting up InfluxDB.

I'm not sure if this is an issue in other init systems, I've only tested in Debian 8.

### PR DESCRIPTION
**Pull request by codyshepherd**
Closes #6068 

Backport from c8de72ddbc5fdf20f821ca473f1fdf92820f9ac3.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: scripts/influxd-systemd-start.sh [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+/usr/bin/influxd -config /etc/influxdb/influxdb.conf $INFLUXD_OPTS &
+echo $! > /var/lib/influxdb/influxd.pid
+
+BIND_ADDRESS=$(influxd print-config --key-name http-bind-address)
+HOST=${BIND_ADDRESS%%:*}
+HOST=${HOST:-"localhost"}
+PORT=${BIND_ADDRESS##*:}
+
+set +e
+result=$(curl -s -o /dev/null http://$HOST:$PORT/ready -w %{http_code})
```
Comment (lesam) [inline scripts/influxd-systemd-start.sh:12]: nitpick: this might have been cleaner:

```
result=
while [ "$result" != "200" ]; do
   result=$(curl -s -o /dev/null http://$HOST:$PORT/ready -w %{http_code})
   sleep 1
 done
```

**Review by lesam — APPROVED** [review]
lgtm
