### PR TITLE
fix(copy): minor copy updates

### LINKED ISSUE #14938: Extra line in ? new notifcation rule info box
see screenshot

image

### LINKED ISSUE #14948: Change default name on Create Endpoint
the default name should be "Name this Endpoint"

### LINKED ISSUE #14956: Change "Configure a Data Collector" to "Load Data"
On the homepage page. It should link to the same place.

image

### PR DESCRIPTION
**Pull request by russorat**
Closes #14956
Closes #14938
Closes #14948

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/me/components/GettingStarted.tsx [hunk 1]
```diff
@@ -23,8 +23,7 @@ class GettingStarted extends PureComponent<WithRouterProps> {
             <GradientBorder />
             <CollectorGraphic />
             <h3 className="getting-started--title">
-              Configure a<br />
-              Data Collector
+              Load your data
```
Comment (alexpaxton) [inline ui/src/me/components/GettingStarted.tsx]: Super nitpicky, but all the cards in the getting started page have text on 2 lines, so I am wondering if there's a way to make them all 1 line or to make this 2 lines for consistency
