### PR TITLE
fix: show queries built in advanced mode when switching tabs

### LINKED ISSUE #16169: QueryBuilder: valid queries with invalid BuilderConfigs cause wonky tab behavior
when you have an editor, with multiple tabs for queries, deleting a tab that you are not currently viewing deletes all the queries.

Kapture 2019-12-09 at 9 57 26

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Closes #16169

If a query isn't a valid QueryBuilder query, but it still has text (in other words, it was built using the script editor, or by the system), use the text, rather than blanking the text out.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: ui/src/telegrafs/reducers/index.ts [hunk 1]
```diff
@@ -74,4 +74,4 @@ export const telegrafsReducer = (
         return
       }
     }
-  })
\ No newline at end of file
+  })
```
Comment (hoorayimhelping) [inline ui/src/telegrafs/reducers/index.ts]: `prettier:fix`
