### PR TITLE
Fix tag parsing

### LINKED ISSUE #5380: [0.9.6.1] backslash followed by escaped comma in tag results in wrong value or key
This is a parsing bug concerning how tags are parsed. The end result is that the wrong tag value is inserted into Influx.

Example:

```
> insert cpu,regions=east\\,west value=1.0
> show series
name: cp\\
----------
_key
cp\\,u


name: cpu
---------
_key			regions
cpu,regions=east\\,west	east\\

> select * from cpu where regions = 'east\\,west'
> select * from cpu where regions = 'east\\\\'
name: cpu
---------
time			regions	value
1453055570973182043	east\\	1
```

So Influx says that the value for the `regions` tag key is `east\\`, but it should be `east\\,west`.

I think I have a fix for this one, similar to some other fixes I made previously.

### PR DESCRIPTION
**Pull request by e-dard**
This PR fixes #5380  and #5381.

I've added a new type to the test package, which allows for more robust testing by validating that the tags you specify in your expected case are what you get from the processed point. Prior to this the bugs were being introduced to the expected tags values because one had to use `point.Tags()` to retrieve them.

Heads up: anywhere that skips a buffer by two places when the current byte is `\`  (as in `if buf[i] == '\\' { i +=2 }`) is possibly hiding a bug. I'd be happy to look in more detail at the Points/tags/fields stuff in a couple of weeks when I come on board @jwilder.

### CODE REVIEW

**Comment by jwilder** [comment]
@jsternberg Can you take a look as well?

@e-dard Looks good.  Can you update the changelog as well?

**Comment by e-dard** [comment]
@jwilder updated

File: models/points.go [hunk 1]
```diff
@@ -876,8 +876,10 @@ func scanLine(buf []byte, i int) (int, []byte) {
 }
 
 // scanTo returns the end position in buf and the next consecutive block
-// of bytes, starting from i and ending with stop byte.  If there are leading
-// spaces or escaped chars, they are skipped.
+// of bytes, starting from i and ending with stop byte, where stop byte
+// has not been escaped.
+//
+//  If there are leading spaces, they are skipped.
```
Comment (jsternberg) [inline models/points.go]: Can you remove the extra space at the beginning of this docstring?

**Comment by e-dard** [comment]
@jsternberg :+1:

**Comment by jsternberg** [comment]
If you can just squash the commits, this looks good to me :+1:

**Comment by e-dard** [comment]
Done

**Comment by jsternberg** [comment]
:+1: and merging since @jwilder gave his +1 too.

**Comment by toddboom** [comment]
@e-dard nice fixes! let me know if you find yourself bored over the next two weeks. ;)
