### PR TITLE
Fix meta.Client CreateDatabaseWithRetentionPolicy RPC command

### LINKED ISSUE #5696: re-CREATE DATABASE with default duration deletes old data!
Hi,

when a database and associated measurements already exist and you run "CREATE DATABASE IF NOT EXISTS x WITH DURATION..." **the data is gone**. Example:

```
> use dkn
Using database dkn

> select count(value) from processed_by_client
name: processed_by_client
-------------------------
time	count
0	213

> CREATE DATABASE IF NOT EXISTS dkn WITH DURATION 90d REPLICATION 1

> select count(value) from processed_by_client
> show measurements
>
```

If i skip "WITH DURATION..." everything behaves as expected. From my perspective "IF NOT EXISTS" should never ever delete data! Looks like a pretty bad bug to me.

Cheers :beers: 
Daniel

### PR DESCRIPTION
**Pull request by jsternberg**
Previously, meta.Client would drop the default retention policy when
trying to create a database with a retention policy. The RPC has now
been modified to include the desired retention policy in the
CreateDatabase command and have it use that retention policy information
instead of the default configuration when provided.

This also lowers the number of RPC calls for
CreateDatabaseWithRetentionPolicy to only a single RPC call instead of
two.

Protections have also been included so creating a retention policy with
different parameters will return an error similar to if you tried to
modify the retention policy separately.

Fixes #5696.

### CODE REVIEW

File: services/meta/client.go [hunk 1]
```diff
@@ -343,24 +343,24 @@ func (c *Client) CreateDatabaseWithRetentionPolicy(name string, rpi *RetentionPo
...
-	}
-
-	if err := c.DropRetentionPolicy(name, rpi.Name); err != nil {
-		return nil, err
+	if db, _ := c.Database(name); db != nil {
+		// Check if the retention policy already exists. If it does and matches
+		// the desired retention policy, exit with no error.
+		if rp := db.RetentionPolicy(rpi.Name); rp != nil {
+			if rp.ReplicaN != rpi.ReplicaN || rp.Duration != rpi.Duration {
+				return nil, ErrRetentionPolicyExists
```
Comment (jwilder) [inline services/meta/client.go]: Could we return a slightly different error here?  When I hit this via the cli I get:
```
> create database if not exists test with duration 10h replication 1
> create database if not exists test with duration 15h replication 1
ERR: retention policy already exists
```

which is a little confusing because the retention policy does already exist, but it's different than what I'm trying to create.  Maybe the error text just needs to be updated.

**Comment by jwilder** [comment]
One question.  Otherwise :+1:  on green.

File: services/meta/client.go (hunk 1 above)
Comment (jsternberg) [inline services/meta/client.go]: We would have to likely add a new error. That error is thrown if you try to use `CREATE RETENTION POLICY` which makes sense as the text. What do you propose making this error into?

Comment (jwilder) [inline services/meta/client.go]: Maybe `ErrRetentionPolicyConflict` with text `retention policy conflicts with an existing policy`?

Comment (jsternberg) [inline services/meta/client.go]: I like it. I'll add it.
