### PR TITLE
Fix aggregate returns when data is missing from some shards

### LINKED ISSUE #6495: DISTINCT does not operate on string fields
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

InfluxDB 0.12.2 on Ubuntu 14.04, fresh install

__Steps to reproduce:__

1. insert string fields
2. query string field with `DISTINCT`

__Expected behavior:__ [What you expected to happen]

Return from `DISTINCT(<string>)` would be the number of distinct strings.

__Actual behavior:__ [What actually happened]

Return was null.

__Additional info:__ [Include gist of relevant config, logs, etc.]

```
> show field keys from a
name: a
-------
fieldKey
string
value

> select * from a
name: a
-------
time			string	value
1461695896546713026	12	12
1461856121749763139	11	11
1461856127357529714	10	10
1461856128790092843	10	10
1461856129686020379	10	10
1461856131452838575	11	11
1461856136245585327	13	13

> select distinct(value) from a
name: a
-------
time	distinct
0	12
0	11
0	10
0	13

> select distinct(string) from a
> select count(string) from a
name: a
-------
time	count
0	7

> format json
> select distinct(string) from a
{"results":[{}]}
```

### PR DESCRIPTION
**Pull request by jsternberg**
If a shard is empty for a specific field and the field type is something
other than a float, a nil iterator would get returned from one of the
empty shards and cause the combined iterators to be cast to the float
type and all other iterator types to be discarded (or for integers, to
be cast).

This is rare since most aggregates don't accept strings or booleans, but
for queries like:

    SELECT distinct(string) FROM mydata

It would result in nothing getting returned if one of the shards didn't
have a value for `string`.

This change modifies the query engine to return nil for the shards
instead of a fake iterator and then to only use the fake iterator if the
final aggregate iterator is nil (meaning that no iterators could be
constructed for the field from any shard).

Fixes #6495.

### CODE REVIEW

**Comment by e-dard** [comment]
LGTM 👍

**Comment by jsternberg** [comment]
@benbjohnson can you review too? I'm not sure I like the coding style used in this, but I haven't thought of another way to do this.

File: influxql/iterator.go [hunk 1]
```diff
@@ -535,26 +535,31 @@ func (a IteratorCreators) CreateIterator(opt IteratorOptions) (Iterator, error)
 	// Merge into a single iterator.
 	if opt.MergeSorted() {
 		itr := NewSortedMergeIterator(itrs, opt)
-		if opt.InterruptCh != nil {
-			itr = NewInterruptIterator(itr, opt.InterruptCh)
+		if itr != nil {
+			if opt.InterruptCh != nil {
+				itr = NewInterruptIterator(itr, opt.InterruptCh)
+			}
 		}
```
Comment (benbjohnson) [inline influxql/iterator.go]: This can be combined into a single `if itr != nil && opt.InterruptCh != nil`

**Comment by benbjohnson** [comment]
:+1:
