### PR TITLE
Ensure shards and engine are safely closed

### LINKED ISSUE #5244: panic: close of closed channel
I have a Windows Service reading data from some sensors every second, aggregating this data every ten minutes and inserting it on InfluxDB.

[InfluxDB_crash_20151230.txt](https://github.com/influxdb/influxdb/files/74734/InfluxDB_crash_20151230.txt)

It's a single node instance of InfluxDB v.0.9.6.1 (tsm1) compiled with Go v.1.4.3 running on a machine with Windows Server 2012 R2 and 32GB of RAM.

### PR DESCRIPTION
**Pull request by e-dard**
Hopefully fixes #5244.

I have a small query over `Engine.Close`. There are four receivers of the `done` channel. Three of them directly receive on the `done` channel and also are part of the engine's waitgroup, but one—the compactor—receives from a copy of the channel and is not in the waitgroup.

nilling the `e.done` channel after the waitgroup is done is safe for the first three, and since the compactor is using a copy of the channel, it's never going to attempt to receive from a nilled channel, so that's fine too. Just seemed a bit strange to me that the channel gets copied over to the compactor in the first place.

### CODE REVIEW

File: tsdb/engine/tsm1/engine.go [hunk 1]
```diff
@@ -150,6 +154,7 @@ func (e *Engine) Close() error {
 	// Lock now and close everything else down.
 	e.mu.Lock()
 	defer e.mu.Unlock()
+	e.done = nil // Ensures that the channel will not be closed again.
```
Comment (jwilder) [inline tsdb/engine/tsm1/engine.go]: Setting the channel to `nil` causes problems with code using default case in the selector such as:

https://github.com/influxdata/influxdb/blob/master/tsdb/engine/tsm1/engine.go#L454-L458

When it's `nil`, if falls through to the `default` clause.

File: tsdb/engine/tsm1/engine.go [hunk 2]
```diff
@@ -141,8 +141,12 @@ func (e *Engine) Open() error {
 	return nil
 }
 
-// Close closes the engine.
+// Close closes the engine. Subsequent calls to Close are a nop.
 func (e *Engine) Close() error {
+	if e.done == nil {
```
Comment (jwilder) [inline tsdb/engine/tsm1/engine.go]: This should be checked under read lock.

File: tsdb/engine/tsm1/engine.go (hunk 1 above)
Comment (e-dard) [inline tsdb/engine/tsm1/engine.go]: These should be the cases I discussed above. They won't be in their `select` loops if `w.wg` is done, since the `wg` can't be done until anything receiving on `done` has returned.

Maybe I should change the approach to something clearer?

**Comment by jwilder** [comment]
:+1:
