### PR TITLE
fix(influxql): make meta queries respect query timeout

### LINKED ISSUE #20738: Make meta queries respect QueryTimeout values [forward-port 2.x]
Forward-port #20736 to the master branch.

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #20738

Forward-ports #20736. It wasn't a clean cherry-pick, but I think the interesting code in `tsdb/store.go` and `tsdb/store_test.go` is an exact match.

### CODE REVIEW

File: cmd/influxd/launcher/engine.go [hunk 1]
```diff
@@ -31,7 +31,7 @@ type Engine interface {
 	influxdb.BackupService
 	influxdb.RestoreService
 
-	SeriesCardinality(orgID, bucketID platform.ID) int64
+	SeriesCardinality(ctx context.Context, bucketID platform.ID) int64
```
Comment (davidby-influx) [inline cmd/influxd/launcher/engine.go:34]: The orgID is not a placeholder for some future usage?

**Review by davidby-influx — APPROVED** [review]
This looks like a good cherry-pick, given the merging necessary.
