### PR TITLE
fix(templates): update org name to ID for fetching templates

### LINKED ISSUE #13246: fix flaky Create Dashboard from Template e2e test
When getting the list of Templates for a Dashboard, the server comes back with a 400 error:

Screen Shot 2019-04-08 at 2 54 42 PM

From the Network tab:
`{"code":"invalid","message":"Invalid orgID"}`

### PR DESCRIPTION
**Pull request by AlirieGray**
Closes #13246

This PR fixes the Import Dashboard from Template Overlay by updating `orgName` to `orgID` when fetching templates from the server.

  - [x] Rebased/mergeable
  - [x] Tests pass

### CODE REVIEW

File: ui/src/dashboards/components/DashboardImportFromTemplateOverlay.tsx [hunk 1]
```diff
@@ -75,7 +78,7 @@ class DashboardImportFromTemplateOverlay extends PureComponent<
           />
           <Overlay.Body>
             <div className="import-template-overlay">
-              <OrgTemplateFetcher orgName={this.orgName}>
+              <OrgTemplateFetcher orgID={orgID}>
```
Comment (ischolten) [inline ui/src/dashboards/components/DashboardImportFromTemplateOverlay.tsx]: I think there's a get resources component that fetches templates and loads them into redux. maybe that would be better to sue for consistency
