### PR TITLE
fix(pkger): don't swallow errors when failing to get organization

### LINKED ISSUE #16387: pkgr: auth errors aren't shown to the user
if your token is invalid, there is no error shown to the user.

image

### PR DESCRIPTION
**Pull request by jademcgough**
Closes #16387

### CODE REVIEW

File: cmd/influx/pkg.go [hunk 1]
```diff
@@ -129,7 +129,7 @@ func (b *cmdPkgBuilder) pkgApplyRunEFn() func(*cobra.Command, []string) error {
 
 		influxOrgID, err := b.org.getID(orgSVC)
 		if err != nil {
-			return nil
+			return err
```
Comment (jsteenb2) [inline cmd/influx/pkg.go]: 🤦‍♂ how did I miss this in PR review 😳  lol, nice find @jademcgough 👍
