### PR TITLE
fix(http): convert write error

### LINKED ISSUE #11206: Writing invalid line protocol gives an EOF error
If you try to write a bad point like this:

```
jsternberg:[~/g/s/g/i/influxdb] $ (master *$=) influx write -o influxdata -b scraper3 'cpu,a=a,a=b value=3'
Error: EOF
Usage:
  influx write line protocol or @/path/to/points.txt [flags]

Flags:
  -b, --bucket string      The name of destination bucket
      --bucket-id string   The ID of destination bucket
  -h, --help               Help for the write command
  -o, --org string         The name of the organization that owns the bucket
      --org-id string      The ID of the organization that owns the bucket
  -p, --precision string   Precision of the timestamps of the lines (default "ns")

Global Flags:
      --host string    HTTP address of Influx (default "http://localhost:9999")
      --local          Run commands locally against the filesystem
  -t, --token string   API token to be used throughout client calls

EOF
```

The error should be more instructive and the EOF error seems inappropriate.

### PR DESCRIPTION
**Pull request by zhulongcheng**
Closes #11206

_Briefly describe your proposed changes:_

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] http/swagger.yml updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: http/write_handler.go [hunk 1]
```diff
@@ -160,19 +160,31 @@ func (h *WriteHandler) handleWrite(w http.ResponseWriter, r *http.Request) {
 	points, err := models.ParsePointsWithPrecision(data, time.Now(), req.Precision)
 	if err != nil {
 		logger.Info("Error parsing points", zap.Error(err))
-		EncodeError(ctx, err, w)
+		EncodeError(ctx, &platform.Error{
+			Code: platform.EInvalid,
+			Op:   "http/handleWrite",
```
Comment (goller) [inline http/write_handler.go]: Would you add 

```go
Msg: fmt.Printf("unable to parse points: %v", err),
```

File: http/write_handler.go [hunk 2]
```diff
@@ -160,19 +160,31 @@ func (h *WriteHandler) handleWrite(w http.ResponseWriter, r *http.Request) {
...
 		return
 	}
 
 	exploded, err := tsdb.ExplodePoints(org.ID, bucket.ID, points)
 	if err != nil {
 		logger.Info("Error exploding points", zap.Error(err))
-		EncodeError(ctx, err, w)
+		EncodeError(ctx, &platform.Error{
+			Code: platform.EInvalid,
+			Op:   "http/handleWrite",
```
Comment (goller) [inline http/write_handler.go]: This one should be an internal server error rather than EInvalid

```go
Msg: fmt.Printf("unable to convert points to internal structures: %v", err),
```

File: http/write_handler.go [hunk 3]
```diff
@@ -160,19 +160,31 @@ func (h *WriteHandler) handleWrite(w http.ResponseWriter, r *http.Request) {
...
+			Err:  err,
+		}, w)
 		return
 	}
 
 	if err := h.PointsWriter.WritePoints(exploded); err != nil {
-		EncodeError(ctx, errors.BadRequestError(err.Error()), w)
+		EncodeError(ctx, &platform.Error{
```
Comment (goller) [inline http/write_handler.go]: Msg here should be

```go
Msg: fmt.Printf("unable to write points to database: %v", err),
```

**Comment by goller** [comment]
@zhulongcheng great thanks!
