### PR TITLE
Convert duration to string without dot and zeros

### LINKED ISSUE #8813: [Bug Report] SHOW RETENTION POLICIES returns invalid formated duration
### Bug report

__System info:__ 

* Ubuntu 16.04.3 LTS
* influxdb 1.3.5

__Steps to reproduce:__

```
> ALTER RETENTION POLICY test1 ON test DURATION 336h14ms

> SHOW RETENTION POLICIES ON test

name    duration     shardGroupDuration replicaN default
----    --------     ------------------ -------- -------
test1   336h0m0.014s 24h0m0s            1        true

> ALTER RETENTION POLICY test1 ON test DURATION 336h0m0.014s
ERR: error parsing query: invalid duration at line 1, char 47
```

__Expected behavior:__ The duration returned by SHOW RETENTION POLICIES should be a valid formated duration, which can be used in a ALTER RETENTION POLICY query

__Actual behavior:__ The duration returned by SHOW RETENTION POLICIES is not in all cases a valid formated duration

### PR DESCRIPTION
**Pull request by liketic**
Closes #8813 . 
Format `Duration` to `[w][d][h][m][s][ms][u][ns]`. Another resolution is `parser.FormatDuration`.

### CODE REVIEW

**Comment by liketic** [comment]
@e-dard Can you help to review this? Thanks!

File: coordinator/statement_executor.go [hunk 1]
```diff
@@ -1166,3 +1172,57 @@ func joinUint64(a []uint64) string {
 	}
 	return buf.String()
 }
+
+// fmtDuration formats a duration to a string without dot(.) and unnecessary '0's.
+func fmtDuration(td time.Duration) string {
```
Comment (jsternberg) [inline coordinator/statement_executor.go]: Can you use `influxql.FormatDuration` instead? Thanks.

Comment (liketic) [reply coordinator/statement_executor.go]: sure. Please review again.
