### PR TITLE
Don't catch SIGQUIT; safer close of Quit channel

### LINKED ISSUE #6474: Can't get rid of a stalled connection or long run query in CLI without `kill -9`
InfluxDB shell 0.12.0, on Arch Linux x86_64.

I connect to an InfluxDB server, and
* either run a query that takes too long to finish
* or forget to disconnect it before I put my computer into sleep, or my network connection just goes bad

I have a non-responsible influx shell now, <kbd>Ctrl-C</kbd> or <kbd>Ctrl-\\</kbd> doesn't work. The only way to get out is `kill -9`.

I expect <kbd>Ctrl-C</kbd> to abort the current operation and return me a new prompt. I also expect <kbd>Ctrl-\\</kbd> to forcefully exit the influx shell so I can connect again, without searching for its pid and killing it elsewhere.

### PR DESCRIPTION
**Pull request by e-dard**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

A `SIGQUIT` signal should indicate to a running process that it should exit immediately, and also dump its core. This is the default behaviour for a Go program, unless the program catches the signal using `signal.Notify`. 

We were catching this signal in `influx` and then attempting to exit gracefully, which is the incorrect behaviour, especially if `influx` is stuck somewhere, or in a long running query.

Also, we were catching other signals that didn't make sense, e.g., `SIGHUP`—usually used to indicate a live configuration change, `os.Kill`—we're not even allowed to catch this.

This PR reduces the signals we catch down to `syscall.SIGINT` and `syscall.SIGTERM`. It also ensure that the `Quit` channel is closed properly.

Helps to fix #6474

### CODE REVIEW

**Comment by sczk** [comment]
Nice catch! For what it's worth, this looks good to me, although you have more authority than I do! :)

File: cmd/influx/cli/cli.go [hunk 1]
```diff
@@ -182,7 +182,13 @@ func (c *CommandLine) Run() error {
 	for {
 		select {
 		case <-c.osSignals:
-			close(c.Quit)
+			// Attempt to gracefully exit
```
Comment (jsternberg) [inline cmd/influx/cli/cli.go]: This isn't needed since this section is single threaded. The close should always succeed. If the channel is already closed, then the `Quit` channel will always be the one chosen by `select`.

Comment (e-dard) [inline cmd/influx/cli/cli.go]: @jsternberg I'm not sure that's technically the case. If two signals are received in quick succession the scheduler could decide to chose the `case <-c.osSignals` case twice in succession. 

I don't think there is anything that guarantees a closed-channel-receive will always be chosen if there are competing cases available to select over is there? I could be wrong though.

Comment (jsternberg) [inline cmd/influx/cli/cli.go]: I thought there was since I had done this previously, but this example seems to indicate there isn't.

```
package main

import "fmt"

func main() {
	for i := 0; i < 1000; i++ {
		ch := make(chan bool, 1)
		ch <- true
		closing := make(chan struct{})
		close(closing)
		select {
		case <-closing:
		case <-ch:
			fmt.Println("bad value", i)
			return
		}
	}
}
```

It prints `bad value` fairly quickly. So never mind.

It may just be more clear to duplicate the code from the `c.Quit` case rather than do some semi-convoluted for loop with a select statement. Whichever change is fine though.

Comment (e-dard) [inline cmd/influx/cli/cli.go]: Doh. I can completely remove the need for these selects

**Comment by pires** [comment]
The rationale behind the PR LGTM.

**Comment by jwilder** [comment]
👍
