### PR TITLE
fix(upgrade): delete references to 'security script' in upgrade command

### LINKED ISSUE #19921: remove security script from help
this is no longer relevant: https://github.com/influxdata/influxdb/blob/master/cmd/influxd/upgrade/upgrade.go#L125

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #19921 

"Security script" is unused / irrelevant since #19854 

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Feature flagged (if modified API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: cmd/influxd/upgrade/security.go [hunk 1]
```diff
@@ -104,20 +104,20 @@ func upgradeUsers(ctx context.Context, v1 *influxDBv1, v2 *influxDBv2, targetOpt
 	return nil
 }
 
-// securityScriptHelper is a helper used by `generate-security-script` command.
-type securityScriptHelper struct {
+// securityUpgradeHelper is a helper used by `upgrade` command.
+type securityUpgradeHelper struct {
```
Comment (danxmoran) [inline cmd/influxd/upgrade/security.go:108]: The logic in this struct's methods still seemed to be useful, so I just renamed it to avoid future confusion

**Review by docmerlin — APPROVED** [review]
LGTM

**Comment by ayang64** [comment]
LGTM
