### PR TITLE
fix(tls): Update TLS strict cipher suite to actually work 

### LINKED ISSUE #20762: tls-strict-ciphers causes https service failure
__Steps to reproduce:__
1. Set configuration (I did via yml config file) of "tls-strict-ciphers" to true along with other required tls options (cert/key)
2. Run influxdb container

__Expected behavior:__
InfluxDB should start successfully and be available via https using only the strict cipher suite. (ref: https://docs.influxdata.com/influxdb/v2.0/reference/config-options/#tls-strict-ciphers)

__Actual behavior:__
https service fails to launch with log error noted below.
Without tls-strict-ciphers set to true, system starts successfully.

__Environment info:__
* System info: Podman on Fedora 33 Server x86_64
* InfluxDB version: InfluxDB 2.0.4 (git: 4e7a59bb9a) build_date: 2021-02-08T17:47:02Z (quay.io/influxdb/influxdb:v2.0.4)
* Other relevant environment details: All other configuration options standard.

__Config:__
```yml
tls-cert: /root/.influxdbv2/ssl/domain/fullchain.pem
tls-key: /root/.influxdbv2/ssl/domain/privkey.pem
tls-min-version: "1.2"
tls-strict-ciphers: true
```

__Logs:__
`lvl=error msg="Failed https service" log_id=0SMyA_Dl000 error="http2: TLSConfig.CipherSuites is missing an HTTP/2-required AES_128_GCM_SHA256 cipher (need at least one of TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 or TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256)."`

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #20762

The cipher suite we had hard-coded was invalid, and would cause the `influxd` process to hang on startup. The user who reported the problem referenced a Mozilla page that showed the proper suite to use, so I swapped to using it. I also fixed the code so a failure to serve HTTP/HTTPS will cause `influxd` to exit instead of hang.

I've added a regression suite to check that enabling TLS works at all. Hopefully that'll catch problems like this in the future...

### CODE REVIEW

File: cmd/influxd/launcher/launcher.go [hunk 1]
```diff
@@ -616,10 +619,6 @@ func (m *Launcher) run(ctx context.Context, opts *InfluxdOpts) (err error) {
 		log.Info("Stopping")
 	}(m.log)
 
-	m.httpServer = &nethttp.Server{
```
Comment (danxmoran) [inline cmd/influxd/launcher/launcher.go:619]: Took the opportunity to factor some code out of the _huge_ `run` method here.

File: cmd/influxd/launcher/launcher.go [hunk 2]
```diff
@@ -897,125 +896,148 @@ func (m *Launcher) run(ctx context.Context, opts *InfluxdOpts) (err error) {
...
+			tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
+			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
 		}
 	}
 
-	if addr, ok := ln.Addr().(*net.TCPAddr); ok {
-		m.httpPort = addr.Port
+	m.httpServer.TLSConfig = &tls.Config{
+		CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
+		PreferServerCipherSuites: true,
```
Comment (Codecasaurus) [inline cmd/influxd/launcher/launcher.go:1026]: If we are using strict ciphers, PreferServerCipherSuites should be false.

File: cmd/influxd/launcher/launcher.go [hunk 3]
```diff
@@ -897,125 +892,148 @@ func (m *Launcher) run(ctx context.Context, opts *InfluxdOpts) (err error) {
...
+	case "1.2":
+		tlsMinVersion = tls.VersionTLS12
+	case "1.3":
+		if useStrictCiphers {
+			log.Warn("TLS version 1.3 does not support configuring strict ciphers")
+			useStrictCiphers = false
 		}
+		tlsMinVersion = tls.VersionTLS13
+	default:
+		return fmt.Errorf("unsupported TLS version: %s", opts.HttpTLSMinVersion)
```
Comment (lesam) [inline cmd/influxd/launcher/launcher.go:1003]: 👍

File: cmd/influxd/launcher/launcher.go [hunk 4]
```diff
@@ -897,125 +892,148 @@ func (m *Launcher) run(ctx context.Context, opts *InfluxdOpts) (err error) {
...
+	if _, err = tls.LoadX509KeyPair(opts.HttpTLSCert, opts.HttpTLSKey); err != nil {
+		log.Error("Failed to load x509 key pair", zap.String("cert-path", opts.HttpTLSCert), zap.String("key-path", opts.HttpTLSKey))
+		return err
+	}
 
-		// TLS 1.3 does not support configuring the Cipher suites
-		if tlsMinVersion != tls.VersionTLS13 && opts.HttpTLSStrictCiphers {
-			cipherConfig = strictCiphers
+	var tlsMinVersion uint16
+	var useStrictCiphers = opts.HttpTLSStrictCiphers
```
Comment (lesam) [inline cmd/influxd/launcher/launcher.go:986]: Does this / should this default true for 1.2?

File: cmd/influxd/launcher/launcher.go [hunk 5]
```diff
@@ -897,125 +892,148 @@ func (m *Launcher) run(ctx context.Context, opts *InfluxdOpts) (err error) {
...
+	if !opts.ReportingDisabled {
+		m.runReporter(ctx)
+	}
+	if err := m.runHTTP(opts, httpHandler); err != nil {
+		return err
+	}
+
+	return nil
+}
+
```
Comment (lesam) [inline cmd/influxd/launcher/launcher.go:938]: 👍 for function break

**Review by lesam — COMMENTED** [review]
Couple questions - see comments

File: cmd/influxd/launcher/launcher.go (hunk 4 above)
Comment (danxmoran) [reply cmd/influxd/launcher/launcher.go:986]: It currently defaults to `false` for all versions (maybe because setting it to `true` made everything break). I'm wary of changing the default at this point since I don't know what impact to expect on existing users, but if somebody from product / somebody with more TLS knowledge gave the :+1: then I'd be ok with it. Would want to remove the `Warn` log in the 1.3 case to avoid noise.

**Comment by danxmoran** [comment]
Self review: it looks like the description of the strict-cipher flag hard-codes the accepted cipher list. Will need to update that.

**Review by lesam — APPROVED** [review]
