### PR TITLE
fix: filling views and cells when we grab dashboards

### LINKED ISSUE #17787: Adding a new Query to a new dashboard cell fails
__Steps to reproduce:__
1. go to explore
1. reload the page **this is critical**
1. create a new query
1. save the query to a dashboard and create a new cell
1. failure, undefined variables

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #17787

when fetching a list of dashboards, we weren't filling the cells / views that also come back from the result of this api call.

### CODE REVIEW

File: ui/src/dashboards/utils/cellGetters.ts [hunk 1]
```diff
@@ -50,9 +50,9 @@ export const getNewDashboardCell = (
     status: RemoteDataState.Done,
   }
 
-  const cells = dashboard.cells.map(
-    cellID => state.resources.cells.byID[cellID]
-  )
+  const cells = dashboard.cells
+    .map(cellID => state.resources.cells.byID[cellID])
+    .filter(c => !!c)
```
Comment (drdelambre) [inline ui/src/dashboards/utils/cellGetters.ts:55]: this is just to guard from the issue above causing the page to error

File: ui/src/dashboards/actions/thunks.ts [hunk 2]
```diff
@@ -229,6 +233,34 @@ export const getDashboards = () => async (
     )
 
     dispatch(setDashboards(RemoteDataState.Done, dashboards))
+
+    if (!dashboards.result.length) {
+      return
+    }
+
+    Object.values(dashboards.entities.dashboards)
```
Comment (drdelambre) [inline ui/src/dashboards/actions/thunks.ts:241]: this is the source of the issue; not backfilling views and cells

File: ui/src/dashboards/actions/thunks.ts [hunk 3]
```diff
@@ -229,6 +233,34 @@ export const getDashboards = () => async (
     )
 
     dispatch(setDashboards(RemoteDataState.Done, dashboards))
+
+    if (!dashboards.result.length) {
```
Comment (hoorayimhelping) [inline ui/src/dashboards/actions/thunks.ts:237]: is `result` guaranteed to be exist and to be a array-like? we often have undefined errors because of assumptions that variables exist, just want to confirm this is kosher.

File: ui/src/dashboards/actions/thunks.ts [hunk 4]
```diff
@@ -229,6 +233,34 @@ export const getDashboards = () => async (
...
+        )
+
+        const normCells = normalize<Dashboard, DashboardEntities, string[]>(
+          e.cells,
+          arrayOfCells
+        )
+
+        dispatch(setViews(RemoteDataState.Done, normViews))
+        dispatch(setCells(e.id, RemoteDataState.Done, normCells))
+      })
```
Comment (hoorayimhelping) [inline ui/src/dashboards/actions/thunks.ts:263]: i really dislike single letter variable names - they make it very hard to find patterns and to track down loose ends in global searches and require a little extra brainpower to process while reading. writing out a variable name costs us very little.

```suggestion
      .map(dashboard => {
        return {
          id: dashboard.id,
          cells: dashboard.cells.map(cell => dashboards.entities.cells[cell]),
        }
      })
      .forEach(entity => {
        const viewsData = viewsFromCells(entity.cells, entity.id)

        const normViews = normalize<View, ViewEntities, string[]>(
          viewsData,
          arrayOfViews
        )

        const normCells = normalize<Dashboard, DashboardEntities, string[]>(
          entity.cells,
          arrayOfCells
        )

        dispatch(setViews(RemoteDataState.Done, normViews))
        dispatch(setCells(entity.id, RemoteDataState.Done, normCells))
      })
```

File: ui/src/dashboards/utils/cellGetters.ts (hunk 1 above)
Comment (hoorayimhelping) [inline ui/src/dashboards/utils/cellGetters.ts:55]:
```suggestion
    .filter(cell => !!cell)
```

File: ui/src/dashboards/actions/thunks.ts (hunk 3 above)
Comment (drdelambre) [reply ui/src/dashboards/actions/thunks.ts:237]: totally is by the normalize function above
