### PR TITLE
fix(ui): remove returnTo on logout

### LINKED ISSUE #11302: remove returnTo on logout
A user that clicks logout should not be logged out with a returnTo query param for the page they were previously on.

### PR DESCRIPTION
**Pull request by OfTheDelmer**
Closes #11302

_Briefly describe your proposed changes:_
Removes returnTo query param on logout

  - [ ] Rebased/mergeable
  - [ ] Tests pass

### CODE REVIEW

File: ui/src/me/components/LogoutButton.tsx [hunk 1]
```diff
@@ -1,15 +1,14 @@
...
 import {Link} from 'react-router'
-import {withRouter, WithRouterProps} from 'react-router'
 
 // Components
 import {Button, ComponentSize} from 'src/clockface'
 
-const LogoutButton: SFC<WithRouterProps> = props => (
-  <Link to={`/logout?returnTo=${props.location.pathname}`}>
+const LogoutButton: SFC = () => (
+  <Link to={`/logout`}>
```
Comment (chnn) [inline ui/src/me/components/LogoutButton.tsx]:
```suggestion
  <Link to="/logout">
```
