### PR TITLE
fix(ui): arrows in table

### LINKED ISSUE #15888: Arrows in table UI don't do anything
View data in Table View and arrows appear on column headers. When clicked, they don't change until you click out of the table. And none of the data in the table rearranges no matter if the arrow is up/down. 

Why Important: Confusing to users because if they see the arrows they would expect interacting with them to change the data

In screenshot, "Points Against" column is sorted with `desc:false` in Flux query

tableview_arrows

### PR DESCRIPTION
**Pull request by zoesteinkamp**
The fix for getting sorting to work

Closes #15888 

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/shared/components/tables/TableGraph.tsx [hunk 1]
```diff
@@ -71,7 +71,9 @@ class TableGraph extends PureComponent<Props, State> {
       sortOptions.field = fieldName
       sortOptions.direction = DEFAULT_SORT_DIRECTION
     }
-    this.setState({sortOptions})
+
+    const newSortOptions = {...sortOptions}
+    this.setState({sortOptions: newSortOptions})
```
Comment (TCL735) [inline ui/src/shared/components/tables/TableGraph.tsx]: Why not use the setState updater function here and put everything into the callback, which will update immediately? For reference see: https://reactjs.org/docs/react-component.html#setstate Something like this, which may need to be cleaned up with prettier:

    public handleSetSort = (fieldName: string) => {
      this.setState(({sortOptions}) => {
        const newSortOptions = {...sortOptions}
        if (fieldName === sortOptions.field) {
          newSortOptions.direction =
            sortOptions.direction === ASCENDING ? DESCENDING : ASCENDING
        } else {
          newSortOptions.field = fieldName
          newSortOptions.direction = DEFAULT_SORT_DIRECTION
        }
        return {newSortOptions}
      })
    }

Comment (drdelambre) [reply ui/src/shared/components/tables/TableGraph.tsx]: I'm not following. I'm cheating by having offline context, but this change is to fix a condition in which data within sortOptions had changed, but the reference was never updated for `sortOptions` so react didn't know about it. Cool reference though! Maybe i'm still wrapping my head around it.

Comment (TCL735) [reply ui/src/shared/components/tables/TableGraph.tsx]: setState takes an object or a function. Using a function makes the component update immediately, instead of possibly waiting (when using an object) due to React batching the state updates.

When a user updates the sort options, they expect to see something update immediately, which seems like a good thing to guarantee with the setState updater function.

Comment (drdelambre) [reply ui/src/shared/components/tables/TableGraph.tsx]: 👍 thanks for helping me learn

Comment (zoesteinkamp) [reply ui/src/shared/components/tables/TableGraph.tsx]: I tried to do this in the code, and it was complaining about sort options not being assignable, so for now ill just keep what we have :)

Comment (TCL735) [reply ui/src/shared/components/tables/TableGraph.tsx]: i edited my snippet. I left off the correct key in the updated state
