### PR TITLE
fix: forbid reading OSS buckets for a token with only write permissions

### LINKED ISSUE #23110: write-only token able to access /query v1 endpoint
__Steps to reproduce:__
1. Create API token with limited scope, e.g. only "write" on specific bucket
2. Submitting a "SELECT" query to the /query endpoint with this token

This is the actual request:
`curl --location --request GET 'http://influxdb:8086/query?q=select * from cpu where time >= now()-5h&db=metrics' \
--header 'Authorization: Token abc<redacted>=='`

__Expected behavior:__
403 Forbidden as the scope of the token does not grant read

__Actual behavior:__
Able to see returned series

__Environment info:__

* System info: Docker
* InfluxDB version:  InfluxDB OSS 2.1.1
* Other relevant environment details: Default docker image

Influx auth list shows the correct permissions, e.g.
[write:orgs/b8dfd15dbd8d4123/buckets/2121beaa0940a123]

### PR DESCRIPTION
**Pull request by lesam**
We previously enabled write tokens to also find DBRP buckets, in order to allow
the legacy /write (not /api/v2/write) endpoint to read the DBRP mappings and
find the real bucket id to write to.

This had the unintended consequency of allowing tokens with only write permissions
to read data in buckets via the legacy /query (not /api/v2/query) endpoint with
InfluxQL.

This change fixes the behaviour to allow writing to /write with a write-only
token, while forbidding reading from /query.

Closes #23110

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: cmd/influxd/launcher/query_test.go [hunk 1]
```diff
@@ -75,43 +80,93 @@ mem,server=b value=45.2`))
...
+	}))
+
+	tests := []struct {
+		name         string
+		permissions  string
+		expectStatus int
+		expectBody   string
+	}{
+		{
+			name:         "only auth permission",
```
Comment (lesam) [inline cmd/influxd/launcher/query_test.go:136]: now with tests!

File: cmd/influxd/launcher/query_test.go [hunk 2]
```diff
@@ -3,8 +3,13 @@ package launcher_test
 import (
 	"bytes"
 	"context"
+	"encoding/json"
 	"errors"
 	"fmt"
+	context2 "github.com/influxdata/influxdb/v2/context"
+	"github.com/influxdata/influxdb/v2/mock"
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
```
Comment (lesam) [inline cmd/influxd/launcher/query_test.go:12]: @bnpfeife looks like the lint checks are not properly catching import grouping - we use `gci` for this in 1.x

**Review by DStrand1 — APPROVED** [review]
LGTM! I asked @jdstrand to review this as well since he is also familiar with the issue

**Review by jdstrand — APPROVED** [review]
This looks great. The code looks good and I verified the tests pass (thanks for the added tests!).

Blackbox testing revealed:
- tested with: all access, unscoped buckets read/write, unscoped buckets read, unscoped buckets write, scoped buckets read/write, scoped buckets read, scoped buckets write                                                         
  - the read/write and read tokens can query, but write only cannot (good)
  - the read/write and write tokens can write, but read only cannot (good) 
- read-only tokens trying to write yields: `{"code":"forbidden","message":"insufficient permissions for write"}`
- write-only tokens trying to read yields: `{"results":[{"statement_id":0,"error":"database not found: testbucket"}]}`
- also tested with token without buckets access:
  - read yields `{"results":[{"statement_id":0,"error":"database not found: testbucket"}]}`
  - write yields `{"results":[{"statement_id":0,"error":"database not found: testbucket"}]}`

IMO, it is a bit weird that we're returning 200 with a 'not found' message in the event that we're using a write token, but this PR is being consistent with existing behavior for write-only (the same as writing with non-buckets token; though, curiously we have different results when trying to write with a read-only token vs trying to write with a non-buckets token).

That said, I don't think this is a blocker for landing this PR as is since it is consistent with existing behavior. Perhaps at some point someone could look to clean this up in a follow-up, but it certainly isn't urgent.

Thanks again!

**Comment by lesam** [comment]
@jdstrand thanks a lot for the additional black box tests!
