### PR TITLE
Print error message for unknown errors in client

### LINKED ISSUE #9277: Improve cryptic error "ERR: %!s(<nil>)" in CLI
### Bug report

__System info:__ InfluxDB version 1.4.2, Ubuntu 16.04 VPS, 512M, query-timeout set to 30s

__Steps to reproduce:__

1. Create a measurement with 10M+ points (can't tell how many due to this bug itself) and a schema including 4 tags, 6 floats, and 2 strings.
2. Run this query from the CLI: `SELECT COUNT(*)`

Two other clients insert <300 points of data every 10 seconds each.

__Expected behavior:__
The counts, or, at worst, `ERR: query-timeout limit exceeded`

__Actual behavior:__
Cryptic error message `ERR: %!s(<nil>)` about 33 seconds after issuing the query

image

__Additional info:__ [Include gist of relevant config, logs, etc.]

```
Jan 04 02:45:01 localhost influxd[12407]: [httpd] 127.0.0.1 - - [03/Jan/2018:02:45:01 -0500] "GET /ping HTTP/1.1" 204 0 "-" "InfluxDBShell/1.4.2" 2bd6f313-f123-11e7-800b-000000000000 47
Jan 04 02:45:02 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:45:02 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 2c3d923c-f123-11e7-800c-000000000000 23566
Jan 04 02:45:03 localhost influxd[12407]: [I] 2018-01-04T07:45:03Z SELECT count(*) FROM quotes.autogen.ticks service=query
Jan 04 02:45:11 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:45:11 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 31af05ed-f123-11e7-800e-000000000000 1758
Jan 04 02:45:13 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:45:13 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 328fe63d-f123-11e7-800f-000000000000 607995
Jan 04 02:45:14 localhost influxd[12407]: [W] 2018-01-04T07:45:14Z Detected slow query: SELECT count(*) FROM ticks (qid: 2, database: quotes, threshold: 10s) service=query
Jan 04 02:45:22 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:45:21 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 37ace1b5-f123-11e7-8010-000000000000 506263
Jan 04 02:45:24 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:45:24 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 392cdb73-f123-11e7-8011-000000000000 843667
Jan 04 02:45:32 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:45:31 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 3da138a5-f123-11e7-8012-000000000000 410364
Jan 04 02:45:37 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:45:36 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 402a4432-f123-11e7-8013-000000000000 1149072
Jan 04 02:45:42 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:45:41 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 43b17806-f123-11e7-8014-000000000000 29193
Jan 04 02:45:52 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:45:52 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 49c167bd-f123-11e7-8015-000000000000 235658
Jan 04 02:46:02 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:46:02 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 4faadc80-f123-11e7-8016-000000000000 643906
Jan 04 02:46:06 localhost influxd[12407]: [httpd] 127.0.0.1 - - [03/Jan/2018:02:44:57 -0500] "POST /query?chunked=true&db=quotes&q=SELECT+COUNT%28%2A%29+FROM+ticks HTTP/1.1" 200 85 "-" "InfluxDBShell/1.4.2" 2905eaf4-f123-11e7-8009-000000000000 69662629
Jan 04 02:46:09 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:46:08 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 5365d963-f123-11e7-8017-000000000000 677371
Jan 04 02:46:13 localhost influxd[12407]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:46:12 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 55cede68-f123-11e7-8018-000000000000 701186
Jan 04 02:46:19 localhost systemd[1]: influxdb.service: Main process exited, code=killed, status=9/KILL
Jan 04 02:46:19 localhost systemd[1]: influxdb.service: Unit entered failed state.
Jan 04 02:46:19 localhost systemd[1]: influxdb.service: Failed with result 'signal'.
Jan 04 02:46:20 localhost systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.
Jan 04 02:46:20 localhost systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Jan 04 02:46:20 localhost systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
Jan 04 02:46:20 localhost influxd[12431]:  8888888           .d888 888                   8888888b.  888888b.
Jan 04 02:46:20 localhost influxd[12431]:    888            d88P"  888                   888  "Y88b 888  "88b
Jan 04 02:46:20 localhost influxd[12431]:    888            888    888                   888    888 888  .88P
Jan 04 02:46:20 localhost influxd[12431]:    888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
Jan 04 02:46:20 localhost influxd[12431]:    888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
Jan 04 02:46:20 localhost influxd[12431]:    888   888  888 888    888 888  888   X88K   888    888 888    888
Jan 04 02:46:20 localhost influxd[12431]:    888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
Jan 04 02:46:20 localhost influxd[12431]:  8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z InfluxDB starting, version 1.4.2, branch 1.4, commit 6d2685d1738277a1c2672fc58df7994627769be6
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Go version go1.9.2, GOMAXPROCS set to 1
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Using configuration at: /etc/influxdb/influxdb.conf
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Using data dir: /var/lib/influxdb/data service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/quotes/autogen/8/000000100-000000002.tsm (#0) opened in 1.396433ms engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/8/_00114.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/quotes/autogen/8 opened in 4.694462ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/11/000000004-000000003.tsm (#0) opened in 635.303µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/11/_00026.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/11 opened in 4.334793ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/12/000000004-000000003.tsm (#0) opened in 810.656µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/12/_00026.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/12 opened in 3.610136ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/13/000000004-000000003.tsm (#0) opened in 591.305µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/13/_00026.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/13 opened in 3.127527ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/14/000000004-000000003.tsm (#0) opened in 793.464µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/14/_00026.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/14 opened in 3.559473ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/15/000000004-000000003.tsm (#0) opened in 1.082796ms engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/15/_00027.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/15 opened in 5.48054ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/17/000000004-000000003.tsm (#0) opened in 873.542µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/17/_00027.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/17 opened in 3.55556ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/18/000000005-000000003.tsm (#0) opened in 926.858µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/18/_00026.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/18 opened in 3.771103ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/19/000000001-000000001.tsm (#0) opened in 655.146µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00006.wal, size 2174703 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00007.wal, size 334913 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00008.wal, size 126211 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00009.wal, size 167485 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00010.wal, size 125893 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00011.wal, size 321265 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00012.wal, size 559435 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00013.wal, size 195658 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00014.wal, size 154042 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/_internal/monitor/19/_00015.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/_internal/monitor/19 opened in 546.103901ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/quotes/autogen/16/000000181-000000001.tsm (#2) opened in 723.685µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/quotes/autogen/16/000000129-000000006.tsm (#0) opened in 1.418786ms engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/quotes/autogen/16/000000179-000000005.tsm (#1) opened in 611.533µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/16/_00183.wal, size 16839 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/16/_00184.wal, size 251387 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/16/_00185.wal, size 102644 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/16/_00186.wal, size 504691 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/16/_00187.wal, size 876085 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/16/_00188.wal, size 392201 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/16/_00189.wal, size 157276 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/16/_00190.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/quotes/autogen/16 opened in 111.272817ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/quotes/autogen/2/000000015-000000002.tsm (#0) opened in 950.539µs engine=tsm1 service=filestore
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z reading file /var/lib/influxdb/wal/quotes/autogen/2/_00038.wal, size 0 engine=tsm1 service=cacheloader
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z /var/lib/influxdb/data/quotes/autogen/2 opened in 2.242247ms service=store
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z opened service service=subscriber
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Starting monitor system service=monitor
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z 'build' registered for diagnostics monitoring service=monitor
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z 'runtime' registered for diagnostics monitoring service=monitor
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z 'network' registered for diagnostics monitoring service=monitor
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z 'system' registered for diagnostics monitoring service=monitor
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Starting precreation service with check interval of 10m0s, advance period of 30m0s service=shard-precreation
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Starting snapshot service service=snapshot
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Starting continuous query service service=continuous_querier
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Starting HTTP service service=httpd
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Authentication enabled:false service=httpd
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Listening on HTTP:127.0.0.1:16131 service=httpd
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Starting retention policy enforcement service with check interval of 30m0s service=retention
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Listening for signals
Jan 04 02:46:20 localhost influxd[12431]: [I] 2018-01-04T07:46:20Z Storing statistics in database '_internal' retention policy 'monitor', at interval 10s service=monitor
Jan 04 02:46:21 localhost influxd[12431]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:46:21 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 5b858532-f123-11e7-8001-000000000000 312
Jan 04 02:46:28 localhost influxd[12431]: [httpd] 127.0.0.1 - node [03/Jan/2018:02:46:28 -0500] "POST /write?db=quotes&p=%5BREDACTED%5D&precision=ms&rp=&u=node HTTP/1.1" 204 0 "-" "-" 5f4e3286-f123-11e7-8002-000000000000 43832
```

### PR DESCRIPTION
**Pull request by mschoenlaub**
This fixes #9277 on client side.

### CODE REVIEW

File: cmd/influx/cli/cli.go [hunk 1]
```diff
@@ -798,6 +798,8 @@ func (c *CommandLine) ExecuteQuery(query string) error {
 			err = ctx.Err()
 			if err == context.Canceled {
 				err = errors.New("aborted by user")
+			} else {
+				err = errors.New("unknown error")
```
Comment (jsternberg) [inline cmd/influx/cli/cli.go]: Should this instead by "no data received"? It seems like it describes what the usual cause is (server crashed and returned no data) while not necessarily declaring that it was the exact cause because we don't really know if that's what happened.

Comment (mschoenlaub) [reply cmd/influx/cli/cli.go]: I thought of printing something like "No data: Probably server crashed", because this is the usual case. "No data received" seems to be too ambigous to me, though.
