### PR TITLE
fix(ui): add ordering to org resources

### LINKED ISSUE #11891: All list views should be alphabetical by name
noticed this on the buckets page. let's update the component to default to sort by name

image

### PR DESCRIPTION
**Pull request by OfTheDelmer**
Closes #11891

_Briefly describe your proposed changes:_
Adds ordering to labels and org resources

  - [x] Rebased/mergeable
  - [ ] Tests pass
  - [ ] http/swagger.yml updated (if modified Go structs or API)
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/organizations/containers/OrganizationView.tsx [hunk 1]
```diff
@@ -196,6 +204,7 @@ class OrganizationView extends PureComponent<Props> {
                 <GetOrgResources<Variable[]>
                   organization={org}
                   fetcher={getVariables}
+                  orderBy={{keys: ['name']}}
```
Comment (ebb-tide) [inline ui/src/organizations/containers/OrganizationView.tsx]: should orderBy be an optional prop with default= `{keys:['name]}`

Comment (OfTheDelmer) [reply ui/src/organizations/containers/OrganizationView.tsx]: @ebb-tide I was wondering that after most places it was used benefited from a simple name ordering. It should just ignore ordering if the collection doesn't have that key. Hmm would it be worth typing the orderedBy.keys property names of the collection item?
