### PR TITLE
fix retention policy creation inconsistencies

### LINKED ISSUE #7448: Retention Policy Inconsistencies
There are inconsistencies in how retention policies are created and
altered in our system.  I will attempt to outline the current behavior and then
we can come to a consensus on the desired behavior.
## Create retention policy without default and with default

If you have a retention policy that is not the default, and then create it
again, with the same specifications, but add `DEFAULT` when creating it, it
will actually make that the default RP, even though it was already created.

``` sql
> CREATE DATABASE metrics
> SHOW RETENTION POLICIES ON metrics
name    duration        shardGroupDuration      replicaN        default
----    --------        ------------------      --------        -------
autogen 0s              168h0m0s                1               true

> CREATE RETENTION POLICY daily ON metrics DURATION 1d REPLICATION 1
> SHOW RETENTION POLICIES ON metrics
name    duration        shardGroupDuration      replicaN        default
----    --------        ------------------      --------        -------
autogen 0s              168h0m0s                1               true
daily   24h0m0s         1h0m0s                  1               false

> CREATE RETENTION POLICY daily ON metrics DURATION 1D REPLICATION 1 DEFAULT
> show retention policies on metrics
name    duration        shardGroupDuration      replicaN        default
----    --------        ------------------      --------        -------
autogen 0s              168h0m0s                1               false
daily   24h0m0s         1h0m0s                  1               true
```

Since the replication policy is already created, creating it again with a
different specification (in this case `DEFAULT`) should error out with
`retention policy conflicts with an existing policy`.

This is a bug currently, but fixing it will result in a `breaking change`.  I'm
not sure what our stance is on `breaking changes` when it fixes a bug that was
undesired behavior.
## Clarifying when `DEFAULT` retention policies should be created.

When using the `CREATE DATABASE` statement and including retention policy
information, that retention policy should get created, and become the default.
No other retention policy (not even `autogen` if it's enabled, should be
created).

Example when specifying retention policy.

```
> CREATE DATABASE "foo" with NAME "thing"
> SHOW RETENTION POLICIES ON foo
name    duration        shardGroupDuration      replicaN        default
----    --------        ------------------      --------        -------
thing   0s              168h0m0s                1               true
```

Example when not specifying retention policy.

```
> CREATE DATABASE "foo"
> SHOW RETENTION POLICIES ON foo
name    duration        shardGroupDuration      replicaN        default
----    --------        ------------------      --------        -------
autogen 0s              168h0m0s                1               true
```

This is the current behavior.  I am just confirming that this is still correct.

### PR DESCRIPTION
**Pull request by corylanou**
This PR fixes inconsistent retention policy logic found in both `CreateDatabaseWithRetentionPolicy`, `CreateRetentionPolicy`, and `AlterRetentionPolicy`.

I have also removed the `meta.SetDefaultRetentionPolicy` call as it should of never existed to begin with.  All defaults should be set with the actual statement calls so they are atomic.
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] Add additional test coverage
- [x] CHANGELOG.md updated
###### Required only if applicable

_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [x] [InfluxQL Spec](https://github.com/influxdata/influxdb/blob/master/influxql/README.md) updated
- [x] Provide example syntax

fixes #7448

### CODE REVIEW

File: coordinator/meta_client.go [hunk 1]
```diff
@@ -12,7 +12,7 @@ type MetaClient interface {
 	CreateContinuousQuery(database, name, query string) error
 	CreateDatabase(name string) (*meta.DatabaseInfo, error)
 	CreateDatabaseWithRetentionPolicy(name string, spec *meta.RetentionPolicySpec) (*meta.DatabaseInfo, error)
-	CreateRetentionPolicy(database string, spec *meta.RetentionPolicySpec) (*meta.RetentionPolicyInfo, error)
+	CreateRetentionPolicy(database string, spec *meta.RetentionPolicySpec, makeDefault bool) (*meta.RetentionPolicyInfo, error)
```
Comment (corylanou) [inline coordinator/meta_client.go]: Not sure if I'm a fan of the word `makeDefault`.  I'm open to suggestions.  `setDefault`?

File: services/meta/data.go [hunk 2]
```diff
@@ -163,11 +163,21 @@ func (data *Data) CreateRetentionPolicy(database string, rpi *RetentionPolicyInf
 		if rp.ReplicaN != rpi.ReplicaN || rp.Duration != rpi.Duration || rp.ShardGroupDuration != rpi.ShardGroupDuration {
 			return ErrRetentionPolicyExists
 		}
+		// if they want to make it default, and it's not the default, it's not an identical command so it's an error
+		if makeDefault && di.DefaultRetentionPolicy != rpi.Name {
```
Comment (e-dard) [inline services/meta/data.go]: This may not make any sense, but what if they provide the same RP details as an existing default one, but they don't provide `DEFAULT`? Should that be allowed, or is that an error?

Comment (corylanou) [inline services/meta/data.go]: With my fix it is now an error.  While we don't know why they would do this (although we can assume it was a mistake), we can't alter an RP via a create if it exists.  You can only alter WITH an alter.  The point of this code is so that if the create is issued with identical specifications, it's idempotent.  The intent is to allow them to run the same scripts over and over for create database or retention policy without it erring out when the specifications are identical.  If they change their script, then they will have to manually fix any changes to have it run in an idempotent manner again.

**Comment by beckettsean** [comment]
@corylanou so now repeated CREATEs with the exact same syntax return a 204? But if there's any difference, they return a 40x?

**Comment by corylanou** [comment]
I would have to check what the server does as far as a status code.  But certainly it will no longer work if there is any difference.

**Comment by beckettsean** [comment]
Please let us know what the actual expected response is, so that we can appropriately document, thanks!
