### PR TITLE
fix(core): dont fail on time boundary analysis

### LINKED ISSUE #26163: Can't filter by a transformed time column
```
influxdb3 query \
  --database sports\
  "SELECT \
fanduel_pending, \
date_trunc('day', tz(time, 'America/Detroit')) as time \
FROM sportsbook_wallet \
WHERE date_trunc('day', tz(time, 'America/Detroit')) >= cast('2025-03-12T04:00:00Z' as timestamp)"
```

This query fails with error:

```
Query command failed: server responded with error [500 Internal Server Error]: query error: error while planning query: External error: unable to analyze provided filters for a boundary on the time column
```

This query works as expected:
```
influxdb3 query \
  --database sports\
  "SELECT \
fanduel_pending, \
date_trunc('day', tz(time, 'America/Detroit')) as time \
FROM sportsbook_wallet \
WHERE time >= cast('2025-03-12T04:00:00Z' as timestamp)"
```

Anytime a transformation is applied to the time column, you are not able to filter your query by it. 

I am on influxdb3 beta using - 
quay.io/influxdb/influxdb3-core:latest@sha256:506d47004afa9bec39aec2a401af74d171f8ba39bc66e5d9a29f1a9661a3e5d0

### PR DESCRIPTION
**Pull request by hiltontj**
Closes #26163 

See also: https://github.com/influxdata/influxdb_pro/issues/1350

### CODE REVIEW

File: influxdb3_write/src/lib.rs [hunk 1]
```diff
@@ -427,12 +427,20 @@ impl<'a> ChunkFilter<'a> {
             // Determine time bounds, if provided:
             let boundaries = ExprBoundaries::try_new_unbounded(&arrow_schema)
                 .context("unable to create unbounded expr boundaries on incoming expression")?;
-            let mut analysis = analyze(
+            let Ok(mut analysis) = analyze(
```
Comment (alamb) [inline influxdb3_write/src/lib.rs:433]: I think it would help to provide some context about why errors are ignored. Perhaps something like
```suggestion
            // DataFusion does not support all possible expressions. If the expression can't be analyzed
            // skip the analysis rather than erroring the query
            // see https://github.com/influxdata/influxdb/issues/26163
            let Ok(mut analysis) = analyze(
```

File: influxdb3_write/src/lib.rs [hunk 2]
```diff
@@ -833,4 +864,46 @@ pub(crate) mod tests {
...
+        let expr = Expr::BinaryExpr(BinaryExpr {
+            left: Box::new(date_trunc_expr),
+            op: Operator::GtEq,
+            right: Box::new(cast(
+                lit("2025-03-12T04:00:00Z"),
+                DataType::Timestamp(TimeUnit::Nanosecond, None),
+            )),
+        });
+
+        // NB(tjh): since the time boundary analysis cannot analyze the above expression, the
```
Comment (alamb) [inline influxdb3_write/src/lib.rs:901]: I didn't realize that InfluxDB was using the `ExprBoundaries` code -- I think we could work on filling out the support upstream if it is important. Do you have any context of what types of expressions are important to support / how much of an issue it is if they are not supported?

Comment (hiltontj) [reply influxdb3_write/src/lib.rs:901]: The main objective of this was to reliably extract time boundaries. Those get used further down in the query execution path in monolith to filter parquet files that get served up to DataFusion, and other things that can be filtered by time.

I used `ExprBoundaries` to avoid hand-rolling filter/interval analysis.

From what I've seen in the reproducers on this PR is that `GROUP BY` on `time` causes issues, but also filtering with `date_trunc`, e.g., `WHERE time >= date_trunc('date')`. I don't know that we can do interval arithmetic on the former, but the latter seems like it would be doable.

**Comment by hiltontj** [comment]
Thanks @alamb - I rebased and applied your suggestion. Waiting for ✅ before merging.
