### PR TITLE
Return error if database is not found when calling (c *Client) Database

### LINKED ISSUE #5504: [0.10.0-nightly] create retention policy on unexistant DB crash InfluxDB
Since 0.10.0, when we create a create retention policy on a database that do not exists, instead of returning an error, InfluxDB crash:

```
2016/02/02 09:17:50 InfluxDB starting, version 0.10.0.n1454400035, branch master, commit fd85ae5b7fada9142aac66603200e6cc124f9aed, built 2016-02-02T08:01:46.972758
[...]
[query] 2016/02/02 09:18:28 CREATE RETENTION POLICY policy_name ON dbname DURATION 1d REPLICATION 1 DEFAULT
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x560abb]

goroutine 57 [running]:
github.com/influxdb/influxdb/services/meta.(*Client).RetentionPolicy(0xc2080ac780, 0xc20800bcf8, 0x6, 0xc20800bce0, 0xb, 0xc20803a260, 0x0, 0x0)
        /tmp/tmp.AhbDyY9LRi/src/github.com/influxdb/influxdb/services/meta/client.go:406 +0xeb
github.com/influxdb/influxdb/services/meta.(*Client).CreateRetentionPolicy(0xc2080ac780, 0xc20800bcf8, 0x6, 0xc20808de00, 0xc200000000, 0x0, 0x0)
        /tmp/tmp.AhbDyY9LRi/src/github.com/influxdb/influxdb/services/meta/client.go:379 +0x81
github.com/influxdb/influxdb/services/meta.(*StatementExecutor).executeCreateRetentionPolicyStatement(0xc208140170, 0xc2081068c0, 0xc2081068c0)
        /tmp/tmp.AhbDyY9LRi/src/github.com/influxdb/influxdb/services/meta/statement_executor.go:256 +0x105
github.com/influxdb/influxdb/services/meta.(*StatementExecutor).ExecuteStatement(0xc208140170, 0x7f8c598dca70, 0xc2081068c0, 0x50)
        /tmp/tmp.AhbDyY9LRi/src/github.com/influxdb/influxdb/services/meta/statement_executor.go:81 +0xb7b
github.com/influxdb/influxdb/services/meta.(*Client).ExecuteStatement(0xc2080ac780, 0x7f8c598dca70, 0xc2081068c0, 0x1)
        /tmp/tmp.AhbDyY9LRi/src/github.com/influxdb/influxdb/services/meta/client.go:889 +0x40
github.com/influxdb/influxdb/tsdb.func·024()
        /tmp/tmp.AhbDyY9LRi/src/github.com/influxdb/influxdb/tsdb/query_executor.go:204 +0x90d
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /tmp/tmp.AhbDyY9LRi/src/github.com/influxdb/influxdb/tsdb/query_executor.go:225 +0x242
```

This was not the case with 0.9.6.1

The query needed to crash the server seems to be any create retention on unexisting database with duration and replication settings e.g.: 
```
CREATE RETENTION POLICY policy_name ON dbname DURATION 1d REPLICATION 1
```

### PR DESCRIPTION
**Pull request by seiflotfy**
Instead of returning nil, nil in case of no DB being found return
errors.New("Database '%s' does not exist", name)
Fixes #5504

### CODE REVIEW

File: services/meta/client.go [hunk 1]
```diff
@@ -305,7 +305,7 @@ func (c *Client) Database(name string) (*DatabaseInfo, error) {
 		}
 	}
 
-	return nil, nil
+	return nil, fmt.Errorf("Database '%s' does not exist", name)
```
Comment (corylanou) [inline services/meta/client.go]: nit: all errors should be lower case so if they are wrapped in another error they read ok.

```
return nil, fmt.Errorf("database '%s' does not exist", name)
```

File: services/meta/client.go [hunk 2]
```diff
@@ -305,7 +305,7 @@ func (c *Client) Database(name string) (*DatabaseInfo, error) {
 		}
 	}
 
-	return nil, nil
+	return nil, fmt.Errorf("database '%s' does not exist", name)
```
Comment (corylanou) [inline services/meta/client.go]: I'm wondering if we should make this an exported error (like these: https://github.com/influxdata/influxdb/blob/master/services/meta/errors.go#L38) in case the caller ever needs to determine what type of error it got.  Detecting a `Not Found` style error is pretty common.

Although, fwiw, I always preferred the style of error checking like the [os](https://golang.org/pkg/os/#IsNotExist) package does for `IsExistError`.  However, that isn't a convention that we use in the current code base.  I like it mostly as it doesn't require us to expose errors as part of our API.

**Comment by dgnorton** [comment]
+1

**Comment by seiflotfy** [comment]
Please do not merge... Adding unit test

**Comment by dgnorton** [comment]
@seiflotfy  okay, will wait for unit test.  Can you also update `CHANGELOG.md`?  Thanks!

**Comment by corylanou** [comment]
+1 Thanks!
