### PR TITLE
fix(ui): add guard for hasKey check

### LINKED ISSUE #11993: Org page tabs spins indefinitely if no resources exist
If no variables exist page spins indefinitely. I would expect a page load completed status or no resources found page. 

kapture 2019-02-19 at 14 16 31

### PR DESCRIPTION
**Pull request by OfTheDelmer**
Fixes checking key in primitive or null types

Closes #11993 

_Briefly describe your proposed changes:_
Empty resources and primitive data types could cause the `in` operator to error and not load resources.

  - [ ] Rebased/mergeable
  - [ ] Tests pass
  - [ ] http/swagger.yml updated (if modified Go structs or API)
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/organizations/components/GetOrgResources.tsx [hunk 1]
```diff
@@ -97,6 +97,10 @@ export default class GetOrgResources<T> extends PureComponent<
     resources: T[],
     key: string | number | symbol
   ): key is keyof T {
-    return key in resources[0]
+    const resource = resources[0]
```
Comment (ebb-tide) [inline ui/src/organizations/components/GetOrgResources.tsx]: maybe also `resource = get(resources, '0', null)` ? just in case resources comes back undefined or not an array?

File: ui/src/organizations/components/GetOrgResources.tsx [hunk 2]
```diff
@@ -97,6 +97,10 @@ export default class GetOrgResources<T> extends PureComponent<
...
+    // gaurd against null and primitive types
+    const isObject = !!resource && typeof resource === 'object'
+
+    return isObject && key in resource
```
Comment (ebb-tide) [inline ui/src/organizations/components/GetOrgResources.tsx]: an alternative could be to use lodash [_.keys](https://lodash.com/docs/4.17.11#keys) function to get the array of keys and check that `keys.includes(key)`

Comment (OfTheDelmer) [reply ui/src/organizations/components/GetOrgResources.tsx]: Yeah I was going to add that but didn't like it's behavior with strings

```
_.keys("abc") // =>  ["0", "1", "3"]
```
