### PR TITLE
fix(variables): close create overlay when new variable created

### LINKED ISSUE #12332: Sort variables list by name

### LINKED ISSUE #12335: Creating a variable fails to close the overlay

### PR DESCRIPTION
**Pull request by AlirieGray**
Closes #12332
Closes #12335

This PR fixes a couple issues with the manage variables page: the create overlay now closes when the submit button is pressed, and the variables in the index are now sorted by name. Also, a notification is displayed to the user when a variable is successfully created.

  - [x] Rebased/mergeable
  - [x] Tests pass

### CODE REVIEW

File: ui/src/variables/actions/index.ts [hunk 1]
```diff
@@ -104,7 +105,9 @@ export const createVariable = (variable: Variable) => async (
   } catch (e) {
     console.log(e)
     dispatch(notify(createVariableFailed()))
+    return
   }
+  dispatch(notify(createVariableSuccess(variable.name)))
```
Comment (chnn) [inline ui/src/variables/actions/index.ts]: _nit_ It might be easier to read the control here if this was right after line 104 (in the "happy path" for the request)
