### PR TITLE
fix #6702: return correct required privileges

### LINKED ISSUE #6702: Database privileges do not work when selecting a non-default database in a SELECT
### Bug report

__System info:__ InfluxDB v0.13

__Steps to reproduce:__

1. Enable authentication.
2. Create admin user.
3. Use admin user to create two databases.
4. Insert data into both databases.
5. Create a normal user and grant that user permission to read one of the databases.
6. Run a select that uses `db=readable` in the query parameters for the database the user can read from and includes `hidden..cpu` in the `FROM` clause for the one that isn't.

You will be able to query the hidden database the user has no permission to read. There might be some difficulty with using `use` to select the readable database in the CLI because of #6397, but you can modify the database to allow calling `SHOW DATABASES` without any required privileges just so that one command works or use `curl` on the command line.

__Expected behavior:__ Either an authentication error or the `SELECT` statement should pretend the database doesn't exist. The latter is probably preferred for security reasons while the former is better for usability.

__Actual behavior:__ You can read from the database you have no permission to read or view.

### PR DESCRIPTION
**Pull request by dgnorton**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

Change SelectStatement to return required privileges for all Sources.

### CODE REVIEW

File: influxql/ast.go [hunk 1]
```diff
@@ -1296,14 +1296,25 @@ func (s *SelectStatement) String() string {
 }
 
 // RequiredPrivileges returns the privilege required to execute the SelectStatement.
-func (s *SelectStatement) RequiredPrivileges() ExecutionPrivileges {
-	ep := ExecutionPrivileges{{Admin: false, Name: "", Privilege: ReadPrivilege}}
+func (s *SelectStatement) RequiredPrivileges() (ExecutionPrivileges, error) {
+	ep := ExecutionPrivileges{}
+	for _, source := range s.Sources {
+		measurement, ok := source.(*Measurement)
```
Comment (jsternberg) [inline influxql/ast.go]: Most of the places we do this we just skip over anything that can't be seen as a measurement rather than returning an error.

Comment (dgnorton) [inline influxql/ast.go]: In this case, that would cause another security bug.

File: influxql/ast.go [hunk 2]
```diff
@@ -1296,14 +1296,25 @@ func (s *SelectStatement) String() string {
...
+		if !ok {
+			return nil, fmt.Errorf("invalid measurment: %s", source)
```
Comment (jsternberg) [inline influxql/ast.go]: Typo here: `measurement`

**Comment by jsternberg** [comment]
Seems fine otherwise. I want to revisit at some point the use of the `RequiredPrivileges()` method in general because I think that it's checking query authorization in the wrong place, but this should work for this issue and 1.0.

File: influxql/ast.go [hunk 3]
```diff
@@ -1296,14 +1296,25 @@ func (s *SelectStatement) String() string {
...
+		}
+
+		ep = append(ep, ExecutionPrivilege{
+			Name:      measurement.Database,
```
Comment (jsternberg) [inline influxql/ast.go]: Just making a note here, this seems like an error because measurements that haven't had their databases specified will not have been filled in yet, but it ends up not being an error because the query authorizer fills in a blank database field with the currently queried database.

A comment here regarding that little caveat might be helpful for someone else. I almost got tricked and thought this didn't work.

File: influxql/ast.go [hunk 4]
```diff
@@ -1296,14 +1296,27 @@ func (s *SelectStatement) String() string {
 }
 
 // RequiredPrivileges returns the privilege required to execute the SelectStatement.
-func (s *SelectStatement) RequiredPrivileges() ExecutionPrivileges {
-	ep := ExecutionPrivileges{{Admin: false, Name: "", Privilege: ReadPrivilege}}
+// NOTE: Statement must be normalized first (database name(s) in Sources and
```
Comment (jsternberg) [inline influxql/ast.go]: In the normal course of things, the statement will not be normalized yet. The comment should talk about how it's OK because the default database gets filled in correctly anyway.

Comment (dgnorton) [inline influxql/ast.go]: Not sure I understand. If this method is called before the database name as been populated, the result will not be correct.

Comment (jsternberg) [inline influxql/ast.go]: It's unintuitive, but the `QueryAuthorizer` code fills in the name using the default database if the name is an empty string. So since the default database gets filled in with the same value, they both end up getting the same database name when you don't specify one.

It's unintuitive which is why I thought it would be good to document it.

**Comment by jsternberg** [comment]
👍 on green.
