### PR TITLE
fix(models): grow tag index buffer if needed

### LINKED ISSUE #20136: line protocol point parser panics when the number of tags is 100
influxdb server panics when inserting a point with exactly 100 tags, like below:

```
m,t1=x,t2=x,t3=x,t4=x,t5=x,t6=x,t7=x,t8=x,t9=x,t10=x,t11=x,t12=x,t13=x,t14=x,t15=x,t16=x,t17=x,t18=x,t19=x,t20=x,t21=x,t22=x,t23=x,t24=x,t25=x,t26=x,t27=x,t28=x,t29=x,t30=x,t31=x,t32=x,t33=x,t34=x,t35=x,t36=x,t37=x,t38=x,t39=x,t40=x,t41=x,t42=x,t43=x,t44=x,t45=x,t46=x,t47=x,t48=x,t49=x,t50=x,t51=x,t52=x,t53=x,t54=x,t55=x,t56=x,t57=x,t58=x,t59=x,t60=x,t61=x,t62=x,t63=x,t64=x,t65=x,t66=x,t67=x,t68=x,t69=x,t70=x,t71=x,t72=x,t73=x,t74=x,t75=x,t76=x,t77=x,t78=x,t79=x,t80=x,t81=x,t82=x,t83=x,t84=x,t85=x,t86=x,t87=x,t88=x,t89=x,t90=x,t91=x,t92=x,t93=x,t94=x,t95=x,t96=x,t97=x,t98=x,t99=x,t100=x v=0
```

panics on 2.0.2 (or __any__ version)
```
runtime error: index out of range [100] with length 100" stacktrace="goroutine 921 [running]:
runtime/debug.Stack(0xc001960d80, 0xc00087ae02, 0x272dd42)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/influxdata/influxdb/v2/http.baseHandler.panic(0x39be520, 0x3970ea8, 0x39f2820, 0xc001abeb20, 0xc000058500, 0x259cc60, 0xc000f10a80)
    /go/src/github.com/influxdata/influxdb/http/router.go:96 +0x217
github.com/influxdata/httprouter.(*Router).recv(0xc00246c240, 0x39f2820, 0xc001abeb20, 0xc000058500)
    /go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:361 +0x79
panic(0x259cc60, 0xc000f10a80)
    /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/influxdata/influxdb/v2/models.scanTags(0xc000932600, 0x255, 0x600, 0x2,
0xc000e72400, 0x64, 0x64, 0x0, 0x2450380, 0xc0009c0980, ...)
    /go/src/github.com/influxdata/influxdb/models/points.go:681 +0x270
github.com/influxdata/influxdb/v2/models.scanKey(0xc000932600, 0x255, 0x600, 0x0, 0xc000e729a8, 0xb9f06c,
0xc000e72848, 0x40edb0, 0xc0025a25c0, 0x10)
    /go/src/github.com/influxdata/influxdb/models/points.go:530 +0xd0c
github.com/influxdata/influxdb/v2/models.parsePoint(0xc000932600, 0x255, 0x600, 0x36957298, 0xed74ae8dc, 0x0, 0xc0000560d7, 0x2, 0x49dba80, 0x43, ...)
    /go/src/github.com/influxdata/influxdb/models/points.go:407 +0x66
github.com/influxdata/influxdb/v2/models.ParsePointsWithPrecision(0xc000932600, 0x255, 0x600, 0x36957298, 0xed74ae8dc, 0x0, 0xc0000560d7, 0x2, 0x60459c8, 0x3a07c60, ...)
    /go/src/github.com/influxdata/influxdb/models/points.go:390 +0x30b
github.com/influxdata/influxdb/v2/http/points.(*Parser).parsePoints(0xc000e72cf0, 0x3a07c60, 0xc00106a930, 0x26d092a51efeca50, 0x62bf980b332649d4, 0x39e63e0, 0xc00087a380, 0x0, 0x0, 0x3a2f500)
    /go/src/github.com/influxdata/influxdb/http/points/points_parser.go:81 +0x1dd
github.com/influxdata/influxdb/v2/http/points.(*Parser).Parse(0xc000e72cf0, 0x3a07c60, 0xc00106a690, 0x26d092a51efeca50, 0x62bf980b332649d4, 0x39e63e0, 0xc00087a380, 0x0, 0x0, 0x0)
    /go/src/github.com/influxdata/influxdb/http/points/points_parser.go:50 +0x125
github.com/influxdata/influxdb/v2/http.(*WriteHandler).handleWrite(0xc002402e70, 0x39f2820, 0xc001abeb20, 0xc000058900)
    /go/src/github.com/influxdata/influxdb/http/write_handler.go:182 +0x54e
net/http.HandlerFunc.ServeHTTP(0xc0007912b0, 0x39f2820, 0xc001abeb20, 0xc000058900)
    /usr/local/go/src/net/http/server.go:2042 +0x44
...
```

this looks to be a day-one bug and can be easily reproduced with 1.x and 2.0

### PR DESCRIPTION
**Pull request by foobar**
Closes #20136

### CODE REVIEW

File: models/points.go [hunk 1]
```diff
@@ -678,6 +678,13 @@ func scanTags(buf []byte, i int, indices []int) (int, int, []int, error) {
 		case tagValueState:
 			state, i, err = scanTagsValue(buf, i)
 		case fieldsState:
+			// Grow our indices slice if needed
```
Comment (danxmoran) [inline models/points.go:681]: As a newbie to this part of the code, I wasn't sure what `if needed` actually meant. Could we make it more clear? Something like:
```suggestion
			// Grow our indices slice if we had exactly enough tags to fill it
```

File: models/points.go [hunk 2]
```diff
@@ -678,6 +678,13 @@ func scanTags(buf []byte, i int, indices []int) (int, int, []int, error) {
...
+			if commas >= len(indices) {
+				// this should be the last tag
```
Comment (danxmoran) [inline models/points.go:683]: Same here, I wasn't sure why this comment would be true. Suggested clarification:
```suggestion
				// The parser is in `fieldsState`, so there are no more tags. We only need 1 more entry in the slice to store the final entry.
```

**Review by danxmoran — COMMENTED** [review]
Thanks for the contribution @foobar, I've reproduced the bug locally, and your patch does seem to fix it! I left some suggestions for clarifying the code comments. Could you also:
1. Add a line to the CHANGELOG.md describing the fix? 
2. Add a regression test to [`models/points_test.go`](https://github.com/influxdata/influxdb/blob/master/models/points_test.go)?

File: models/points_test.go [hunk 3]
```diff
@@ -1255,6 +1255,17 @@ func TestParsePointWithDuplicateTags(t *testing.T) {
 	}
 }
 
+func TestParsePointWithVariousTags(t *testing.T) {
+	line := "m"
+	for i := 0; i < 1000; i++ {
```
Comment (danxmoran) [inline models/points_test.go:1260]: Nice test!

**Review by danxmoran — APPROVED** [review]
LGTM, thanks again for the contribution
