### PR TITLE
fix(influxdb): change resource to resource type

### LINKED ISSUE #11088: Allow top level permissions
Currently there is not a way to express who has write access to all orgs and all users.

### PR DESCRIPTION
**Pull request by desa**
Closes #11088

_Briefly describe your proposed changes:_
This PR changes `Resource` to `ResourceType` and creates a new structure called
```go
type Resource struct {
   Type ResourceType `json:"type"`
   OrgID *ID `json:"orgID,omitempty"`
   ID *ID `json:"id,omitempty"`
}
```

It allows us to express every permission possible in the system currently in a consistent framework.

  - [x] Rebased/mergeable
  - [ ] Tests pass
  - [x] http/swagger.yml updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: authz.go [hunk 1]
```diff
@@ -226,20 +282,32 @@ func NewPermissionAtID(id ID, a Action, r Resource, orgID ID) (*Permission, erro
...
-			ps = append(ps, Permission{Action: a, Resource: r, OrgID: orgID})
+			ps = append(ps, Permission{Action: a, Resource: Resource{Type: r, OrgID: &orgID}})
 		}
 	}
 
 	return ps
 }
 
-// MemberPermissions are the default permissions for those members.
+// MemberPermissions are the default permissions for those who own a resrouce
```
Comment (leodido) [inline authz.go]: Typo `resrouce`
