### PR TITLE
Fix checks bugs

### LINKED ISSUE #14559: Add xy view properties to check view properties type
In the first iteration, check views will be identical to XY views for visualization purposes. 

Add all xy view properties to check view on the back end.

### PR DESCRIPTION
**Pull request by ebb-tide**
Closes #14559

### CODE REVIEW

File: ui/src/dashboards/actions/index.ts [hunk 1]
```diff
@@ -362,6 +363,8 @@ export const getDashboardAsync = (dashboardID: string) => async (
 
     dispatch(setViews(RemoteDataState.Done, views))
 
+    dispatch(getChecks())
```
Comment (chnn) [inline ui/src/dashboards/actions/index.ts]: Is it OK for a dashboard to render before these are loaded? Or should this be inserted right after line 356?

File: ui/src/timeMachine/components/Vis.tsx [hunk 2]
```diff
@@ -103,6 +106,7 @@ const TimeMachineVis: SFC<Props> = ({
               files={files}
               loading={loading}
               properties={resolvedViewProperties}
+              check={check}
```
Comment (chnn) [inline ui/src/timeMachine/components/Vis.tsx]: I wonder if we would be better off connecting the `CheckPlot` to redux, rather than drilling the check from

```
Vis -> ViewSwitcher -> CheckPlot
```

and 
```
Cell -> View -> RefreshingView -> ViewSwitcher -> CheckPlot
```

I'm worried that all the intermediate stages will provide appealing places to introduce check-related logic in the future, even if that logic would be better off in redux or elsewhere.

File: ui/src/dashboards/selectors/index.ts [hunk 3]
```diff
@@ -14,13 +14,16 @@ export const getView = (state: AppState, id: string): View => {
 
 export const getCheckForView = (
   state: AppState,
-  {properties}: View
+  view: View
 ): Partial<Check> => {
-  if (properties.type === 'check') {
-    const checkList = state.checks.list
-    const check = checkList.find(c => c.id == properties.checkID)
+  if (view) {
```
Comment (chnn) [inline ui/src/dashboards/selectors/index.ts]: `_.get` could be helpful for avoiding the nested `if`s here:

```tsx
  const viewType: ViewType = get(view, 'properties.type')
  const checkID = get(view, 'properties.checkID')

  return viewType === 'check'
    ? state.checks.list.find(c => c.id === checkID)
    : null
```

File: ui/src/alerting/reducers/checks.ts [hunk 4]
```diff
@@ -70,13 +70,13 @@ export default (
         if (action.payload.type == 'deadman') {
           draftState.current.check = {
             ...DEFAULT_DEADMAN_CHECK,
-            ...omit(exCheck, 'thresholds'),
+            ...omit(exCheck, ['thresholds', 'type']),
```
Comment (chnn) [inline ui/src/alerting/reducers/checks.ts]: I wonder if a whitelist of still-valid-fields would be safer than using a blacklist here, given that a whitelist can be typechecked more effectively than a blacklist / `omit`.

File: ui/src/dashboards/selectors/index.ts (hunk 3 above)
Comment (ebb-tide) [reply ui/src/dashboards/selectors/index.ts]: thank you that's much prettier.

File: ui/src/alerting/reducers/checks.ts (hunk 4 above)
Comment (ebb-tide) [reply ui/src/alerting/reducers/checks.ts]: I feel like if checks change, we will forget to whitelist here, and we will overwrite fields we don't intend to.
