### PR TITLE
fix(ui): remove gradients from logo svg components

### LINKED ISSUE #16906: InfluxDB 2: Ruby logo for client library is not correctly displayed [Safari, macOS]
__Steps to reproduce:__

1. Login to InfluxDB 2.0 Cloud
1. Display page with Client libraries

__Expected behavior:__
Correctly display Ruby logo

__Actual behavior:__
Screenshot 2020-02-17 at 12 42 04

__Environment info:__

* macOS Catalina: Version 10.15.3 (19D76)
* Safari: Version 13.0.5 (15608.5.11)

cc @mavarius

### PR DESCRIPTION
**Pull request by alexpaxton**
Closes #16906 

- Using `<linearGradient>` within an inline SVG does not work in Safari so long as a `<base/>` tag is present in the DOM (which it is)
- Instead of removing the `<base />` tag we removed the gradients in favor of flat colors

Screen Shot 2020-03-11 at 1 51 59 PM
Here is the working svgs in Safari

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/clientLibraries/graphics/GoLogo.tsx [hunk 1]
```diff
@@ -9,6 +9,7 @@ const GoLogo: SFC = () => {
       height="100%"
       xmlns="http://www.w3.org/2000/svg"
       viewBox="0 0 300 300"
+      xmlSpace="preserve"
```
Comment (Asalem1) [inline ui/src/clientLibraries/graphics/GoLogo.tsx]: https://media.giphy.com/media/UiZpBJIwdJ34k/giphy.gif

File: ui/src/clientLibraries/graphics/JSLogo.tsx [hunk 2]
```diff
@@ -17,12 +17,12 @@ const JSLogo: SFC = () => {
...
            .js3{fill-rule:evenodd;clip-rule:evenodd;fill:#699F63;}
            .js4{clip-path:url(#XMLID_5_);}
-           .js5{fill:url(#SVGID_1_);}
-           .js6{fill:url(#SVGID_2_);}
-           .js7{fill:url(#SVGID_3_);}
-           .js8{fill:url(#SVGID_4_);}
-           .js9{fill:url(#SVGID_5_);}
-           .js10{fill:url(#SVGID_6_);}
+           .js5{fill:#699F63;}
+           .js6{fill:#699F63;}
```
Comment (Asalem1) [inline ui/src/clientLibraries/graphics/JSLogo.tsx]: Can we move these to a stylesheet?

File: ui/src/clientLibraries/graphics/JSLogo.tsx [hunk 3]
```diff
@@ -17,12 +17,12 @@ const JSLogo: SFC = () => {
...
+           .js7{fill:#699F63;}
+           .js8{fill:#699F63;}
+           .js9{fill:#699F63;}
+           .js10{fill:#699F63;}
         `}
       </style>
       <rect className="js0" width={300} height={300} />
```
Comment (Asalem1) [inline ui/src/clientLibraries/graphics/JSLogo.tsx]: Can we rename these classes to be a bit more descriptive?

File: ui/src/clientLibraries/graphics/JSLogo.tsx (hunk 2 above)
Comment (russorat) [reply ui/src/clientLibraries/graphics/JSLogo.tsx]: this matches the format of our other logo files.

File: ui/src/clientLibraries/graphics/JSLogo.tsx (hunk 3 above)
Comment (russorat) [reply ui/src/clientLibraries/graphics/JSLogo.tsx]: this matches the format of our other logo files.

File: ui/src/clientLibraries/graphics/JSLogo.tsx (hunk 2 above)
Comment (Asalem1) [reply ui/src/clientLibraries/graphics/JSLogo.tsx]: True, but we can also make things a little clearer if we wanted to. It's definitely not a deal breaker but something to keep in mind since we are doing it here:
