### PR TITLE
fix: services/httpd: parse correctly Accept header with extra test cases

### LINKED ISSUE #14296: The HTTP "Accept" header is interpreted in a non-standard way
InfluxDB does not seem to interpret the [Accept HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) according to the HTTP specification. It seems to return a MessagePack encoded response only when the header has the exact value `application/x-msgpack`. Adding a second accepted format to the header makes influxdb switch back to returning JSON.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Install influx
2. From a terminal, run 
```sh
curl -G 'http://localhost:8086/query' --data-urlencode 'q=SHOW databases' --header "Accept: application/x-msgpack, text/plain"
```

__Expected behavior:__
A MessagePack response is returned.

__Actual behavior:__
A JSON response is returned.

__Environment info:__

* InfluxDB version: InfluxDB vv1.7.6 (git: master 01c8dd416270f424ab0c40f9291e269ac6921964)

### PR DESCRIPTION
**Pull request by jsign**
Closes #14296

Until the standard lib decides to include a standard function to correctly parse Accept headers, we can rely on [goautoneg](https://github.com/golang/go/issues/19307#issuecomment-511133691) library which is a Github port used by Prometheus.

I also added sub-tests as Table Tests for multiples scenarios around this problem.

Adding a new dependency for this amount of code may hurt a bit, so maybe we could add the code directly too.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] Rebased/mergeable
- [x] Tests pass
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by jsign** [comment]
The failed test case seems to be a [reported flaky test](https://github.com/influxdata/influxdb/issues/11531)

**Comment by jsign** [comment]
@russorat , I rebased it to `1.8` to keep it clean. 
Is `1.8` OK for merging or do you prefer on `master`?

**Comment by jsign** [comment]
@jsternberg, pushed changes in the direction you mentioned.

File: services/httpd/response_writer.go [hunk 1]
```diff
@@ -25,19 +25,27 @@ type ResponseWriter interface {
...
-	case "application/x-msgpack":
-		w.Header().Add("Content-Type", "application/x-msgpack")
-		rw.formatter = &msgpackFormatter{}
-	case "application/json":
-		fallthrough
-	default:
-		w.Header().Add("Content-Type", "application/json")
-		rw.formatter = &jsonFormatter{Pretty: pretty}
+
+	acceptHeaders := parseAccept(r.Header.Get("Accept"))
```
Comment (jsternberg) [inline services/httpd/response_writer.go]: Can you change this to `r.Header` as the argument and change `parseAccept` to take a `[]string` value? I think it's possible for someone to do this:

```
Accept: application/csv
Accept: application/x-msgpack
```

File: services/httpd/accept.go [hunk 2]
```diff
@@ -0,0 +1,68 @@
+/* This file is a copy of github.com/markusthoemmes/goautoneg
```
Comment (jsternberg) [inline services/httpd/accept.go]: Can you copy the full license into this file? Something like:

```
// This file is an adaptation of https://github.com/markusthoemmes/goautoneg.
// The copyright and license header are reproduced below.
//
// (copy of the license)
//
// (link to the license)
```

File: services/httpd/response_writer.go [hunk 3]
```diff
@@ -25,19 +25,27 @@ type ResponseWriter interface {
...
+	for _, accept := range acceptHeaders {
+		switch accept.Type + "/" + accept.SubType {
```
Comment (jsternberg) [inline services/httpd/response_writer.go]: It seems to me this code handles wildcards incorrectly. If I am understanding the spec correctly, a `*` would match any one of these. Is this correct? If it is, I have some recommendations for how we can change the code. If it isn't, then we can skip past that.

File: services/httpd/response_writer_test.go [hunk 4]
```diff
@@ -19,63 +19,77 @@ import (
 )
 
 func TestResponseWriter_CSV(t *testing.T) {
-	header := make(http.Header)
-	header.Set("Accept", "text/csv")
-	r := &http.Request{
-		Header: header,
-		URL:    &url.URL{},
+	tableTest := []struct {
```
Comment (jsternberg) [inline services/httpd/response_writer_test.go]: I'd like some wildcard tests here.

File: services/httpd/response_writer.go (hunk 3 above)
Comment (jsign) [reply services/httpd/response_writer.go]: Uhm, I agree. Makes sense.

**Comment by jsign** [comment]
@jsternberg, I applied your suggestions, and also switched to performance mode since the code had many allocations that could be avoided. And considering this is a hot-path, deserved some extra attention.

Some points about the changes (apart from your comments):
- make `csvFormatter` stateless
- all known content types and formatters are defined as vars, so to a ton of allocations. This is the reason why I made `csvFormatter` stateless (since it wasn't).
- avoided string concats to save extra allocations (that's why `full` exist apart from splited parts)
- added `*` test case
- in case of `*/*` the switch isn't biased to a definite option. This is strictly correct (since any option complies to request), but maybe another default is wanted.
- as can be seen, adding future content types is much less verbose

**Comment by jsternberg** [comment]
Sorry I haven't had time to review this again. I will review by end of day tomorrow.

**Comment by dgnorton** [comment]
@jsternberg can you review this for the 1.8 release coming up?

**Comment by jsternberg** [comment]
I reverted the changes to the formatters and modified the creation of those formatters to a factory method. I think that the state is actually used by the code so a global instance doesn't work, but I also don't remember well enough to know for certain so I don't want those to change.

I am going to wait for the tests and run some myself and then merge this.
