### PR TITLE
fix(ui): don't exclude features if not in cloud

### LINKED ISSUE #15587: Orgs list is missing from UI Nav
wheres-the-orgs-list

### PR DESCRIPTION
**Pull request by ebb-tide**
Closes #15587

### CODE REVIEW

File: ui/src/shared/components/cloud/CloudExclude.tsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ export default class extends PureComponent {
   render() {
     const {children} = this.props
 
-    if (CLOUD) {
+    if (CLOUD !== true) {
```
Comment (Asalem1) [inline ui/src/shared/components/cloud/CloudExclude.tsx]: radical

File: ui/src/shared/components/cloud/CloudOnly.test.tsx [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+  it('CloudOnly does not render children', () => {
+    jest.mock('src/shared/constants', () => ({CLOUD: false}))
+    const CloudOnly = require('src/shared/components/cloud/CloudOnly.tsx')
+      .default
+    const wrapper = mount(<CloudOnly>{Childish}</CloudOnly>)
+
+    expect(wrapper.children().exists()).toBe(false)
+  })
+
+  it('CloudExclude renders chilren', () => {
```
Comment (drdelambre) [inline ui/src/shared/components/cloud/CloudOnly.test.tsx]: i prefer "chidlin"
