### PR TITLE
fix: add host id to parquet file paths

### LINKED ISSUE #25387: Parquet file paths should include the host prefix
I noticed that the parquet file paths under `dbs` don't include the host-id prefix and they should.

### PR DESCRIPTION
**Pull request by hiltontj**
Cleans up a legacy method for producing parquet file paths that was no longer used in release code (was only being used in tests) and makes the method that produces the parquet file path using a WAL sequence number and i64 timestamp the defaul `new` constructor for the `ParquetFilePath` type.

Tests that checked this function were modified accordingly.

Closes #25387

### CODE REVIEW

File: influxdb3_write/src/paths.rs [hunk 1]
```diff
@@ -52,39 +52,23 @@ impl AsRef<ObjPath> for CatalogFilePath {
 pub struct ParquetFilePath(ObjPath);
 
 impl ParquetFilePath {
+    /// Generate a parquet file path using the given arguments. This will convert the provided
+    /// `chunk_time` into a date time string with format `'YYYY-MM-DDTHH-MM'`
```
Comment (pauldix) [inline influxdb3_write/src/paths.rs:56]:
```suggestion
    /// `chunk_time` into a date time string with format `'YYYY-MM-DD/HH-MM'`
```

**Review by pauldix — APPROVED** [review]

**Review by praveen-influx — APPROVED** [review]
