### PR TITLE
fix: do not delete replication on remote config delete

### LINKED ISSUE #23491: Instance reporting replication stream error when no replications are present
Steps to reproduce:

- Remove a remote with an associated replication. By removing the remote, the replication/s will be removed as well.
- Write data to the the bucket that was configured to replicate

Should see error like:
```
error	Error in replication stream	{"log_id": "0bGeVxbl000", "service": "replications", "replication_id": "0959770f83eb0000", "error": "replication not found", "retries": 1}
```

### PR DESCRIPTION
**Pull request by DStrand1**
Closes #23491 

Fixes the above issue by no longer cascade deleting replication configs when the remote foreign key is deleted. Instead we return an error, requiring the user to delete the replication themselves first. This should "fix" the issue by not letting that situation happen. Additionally, this means that the user will not accidentally delete their replications by deleting a remote, and potentially losing data in the queue.

- [X] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

File: remotes/transport/http.go [hunk 1]
```diff
@@ -30,6 +31,11 @@ var (
 		Code: errors.EInvalid,
 		Msg:  "remote-connection ID is invalid",
 	}
+
+	errForeignKey = &errors.Error{
+		Code: errors.EInternal,
+		Msg:  "remote-connection cannot be deleted as a replication references it",
```
Comment (DStrand1) [inline remotes/transport/http.go:37]: This error response could probably be worded better, would appreciate feedback

File: remotes/transport/http.go [hunk 2]
```diff
@@ -198,7 +204,11 @@ func (h *RemoteConnectionHandler) handleDeleteRemote(w http.ResponseWriter, r *h
 	}
 
 	if err := h.remotesService.DeleteRemoteConnection(r.Context(), *id); err != nil {
-		h.api.Err(w, r, err)
+		if strings.Contains(strings.ToLower(err.Error()), "foreign key constraint failed") {
```
Comment (DStrand1) [inline remotes/transport/http.go:207]: I spent a good amount of time trying to find an exact error to check with `errors.Is()` in `sqlite3`, but could not find one that matched. I think this should be done better but I'm not sure the best way to go about it

File: remotes/transport/http.go (hunk 1 above)
Comment (jeffreyssmith2nd) [reply remotes/transport/http.go:37]: Sounds fine to me :+1:

**Review by jeffreyssmith2nd — APPROVED** [review]
LGTM but may want another review since we paired on the migrations

File: remotes/transport/http.go (hunk 2 above)
Comment (lesam) [reply remotes/transport/http.go:207]: Unless the API guarantees that the error types won't change, string matching is probably the better approach here. Worst case the string match fails and we get the 'new' underlying error.

File: sqlite/migrations/0006_migrate_replications_foreign_key.up.sql [hunk 3]
```diff
@@ -0,0 +1,34 @@
+PRAGMA foreign_keys=off;
```
[the remark this answers is not in the document]
Comment (DStrand1) [reply sqlite/migrations/0006_migrate_replications_foreign_key.up.sql:1]: I'm not sure that this is strictly necessary, though I was going off of [this reference](https://www.techonthenet.com/sqlite/foreign_keys/drop.php#:~:text=How%20to%20Drop%20a%20Foreign%20Key%20on%20a%20Table,data%20into%20the%20new%20table) for how to drop the foreign key in a migration, which included the pragma

[the remark this answers is not in the document]
Comment (lesam) [reply sqlite/migrations/0006_migrate_replications_foreign_key.up.sql:1]: I'd like a better explanation of why we would or wouldn't want this before this merges.

[the remark this answers is not in the document]
Comment (jeffreyssmith2nd) [reply sqlite/migrations/0006_migrate_replications_foreign_key.up.sql:1]: Hey @lesam, from the sqlite docs:
```
If foreign key constraints are enabled when it is prepared,
the DROP TABLE command performs an implicit DELETE to
remove all rows from the table before dropping it. The
implicit DELETE does not cause any SQL triggers to fire,
but may invoke foreign key actions or constraint violations.

...

The properties of the DROP TABLE and ALTER TABLE commands
described above only apply if foreign keys are enabled.
If the user considers them undesirable, then the
workaround is to use PRAGMA foreign_keys to disable
foreign key constraints before executing the DROP or
ALTER TABLE command.
```

If we didn't turn off the foreign keys, then the DROP of the old table would still trigger the cascading delete (the exact behavior we don't want). While having the pragma off allows us to potentially violate foreign key constraints, since we're doing a simple copy in a non-multi-connection environment, I believe it is safe.

https://www.sqlite.org/foreignkeys.html

File: sqlite/migrations/0006_migrate_replications_foreign_key.up.sql [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+
+-- Removes the "ON DELETE CASCADE" from the foreign key constraint
+ALTER TABLE replications RENAME TO _replications_old;
+
+CREATE TABLE replications
```
Comment (lesam) [inline sqlite/migrations/0006_migrate_replications_foreign_key.up.sql:6]: Are there any foreign keys pointing at the replications table that need to be updated with this dance? If no, I think this is good to go.

Comment (jeffreyssmith2nd) [reply sqlite/migrations/0006_migrate_replications_foreign_key.up.sql:6]: No, there are no foreign keys pointed towards replications

**Review by lesam — APPROVED** [review]
