### PR TITLE
fix(ui/var/dropdown): display map key names in dropdown

### LINKED ISSUE #13651: Map type variables do not display properly in a dashboard
when i create a map type variable:
image (16)

And then try to use it in a dashboard, it shows the value, but it should show the key.
image (15)

### PR DESCRIPTION
**Pull request by OfTheDelmer**
Closes #13651 

_Briefly describe your proposed changes:_
Map variables need to display their key name instead of their key values. This adds a selector to return an array of value entries from a selector. Using entries allows the variable dropdown to handle and render items without switching on types. However, displaying keys and values revealed an issue where variable two keys could have the same value. This can be resolved in a separate issue, https://github.com/influxdata/influxdb/issues/13658.

Screen Shot 2019-04-26 at 11 08 19 AM

Screen Shot 2019-04-26 at 11 08 55 AM

Screen Shot 2019-04-26 at 11 10 41 AM

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [ ] Rebased/mergeable
  - [ ] Tests pass
  - [ ] http/swagger.yml updated (if modified Go structs or API)
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx [hunk 1]
```diff
@@ -10,14 +10,14 @@ import {Dropdown, DropdownMenuColors} from 'src/clockface'
...
-import {getValuesForVariable} from 'src/variables/selectors'
+import {getVariableValuesForDropdown} from 'src/dashboards/selectors'
 
 // Types
 import {AppState} from 'src/types'
 
 interface StateProps {
-  values: string[]
-  selectedValue: string
+  values: [string, string][]
```
Comment (chnn) [inline ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx]: `Array<{name: string, value: string}>` might be easier to understand. Have you been writing elixir? This feels elixirish 😸

File: ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx [hunk 2]
```diff
@@ -37,47 +37,54 @@ type Props = StateProps & DispatchProps & OwnProps
...
           titleText="No Values"
           customClass="variable-dropdown--dropdown"
           menuColor={DropdownMenuColors.Amethyst}
         >
-          {dropdownValues.map(v => (
-            <Dropdown.Item key={v} id={v} value={v}>
-              {v}
+          {dropdownValues.map(([key]) => (
+            /*
+              Use key as value since they are unique otherwise
```
Comment (chnn) [inline ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx]: If I understand this, it is handling the case where there are multiple items in a map variable with the same key, right? Like:
```
foo,123
foo,456
```
In this case, shouldn't `foo` appear twice in the dropdown? Not sure.

File: ui/src/variables/selectors/index.tsx [hunk 3]
```diff
@@ -67,6 +67,33 @@ export const getValuesForVariable = (
...
+
+interface ArgumentMap {
+  map: {[key: string]: string}
+  list: string[]
+}
+
+export const getArgumentValuesForVariable = <T extends keyof ArgumentMap>(
+  state: AppState,
+  variableID: string
+): ArgumentMap[T] => {
```
Comment (chnn) [inline ui/src/variables/selectors/index.tsx]: This feels a bit too clever... took a while to understand how it could possibly be correct. What about returning `VariableArguments` instead and then using type assertions in the calling code? As far as I can tell, the generic return type is a roundabout way of doing a type assertion.

File: ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx (hunk 2 above)
Comment (chnn) [reply ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx]: Oh nevermind, I think I misunderstood. Disregard.

File: ui/src/variables/selectors/index.tsx (hunk 3 above)
Comment (OfTheDelmer) [reply ui/src/variables/selectors/index.tsx]: sgtm. I was a bit concerned about the cleverness
