### PR TITLE
fix(ui): displaying variable list default values

### LINKED ISSUE #16058: Display all available variables in UI
Screenshot 2019-11-27 12 28 31

Specifically `v.windowPeriod`, `v.timeRangeStart`, and `v.timeRangeStop` seem to be missing. Maybe there are even others?

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #16058

### Problem

Variable list was showing only created variables and not showing default variables

### Solution

Default variables are populated whenever the query runs, so the solution involved calculating the default variables whenever the variable list was rendered & whenever the variable tooltip was being toggled. Here's how it looks like in action:

defaultVariables

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)

### CODE REVIEW

**Comment by hoorayimhelping** [comment]
@Asalem1 is this ready for review or should i wait for you to fix the e2e tests?

**Comment by Asalem1** [comment]
@hoorayimhelping not quite yet unfortunately. I managed to update and add some tests, but I'm currently trying to add some individual tests for the utility functions I created and bumping into some uncaught existing issues that I'm looking to smooth over. I'll DM you when the PR is ready to go :D

File: ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.tsx [hunk 1]
```diff
@@ -105,7 +106,21 @@ const VariableTooltipContents: FunctionComponent<Props> = ({
 
 const mstp = (state: AppState, ownProps: OwnProps) => {
   const valuesStatus = getTimeMachineValuesStatus(state)
-  const values = getTimeMachineValues(state, ownProps.variableID)
+  const {variableID} = ownProps
+  let values: VariableValues
+  if (variableID.includes('timeRange') || variableID.includes('windowPeriod')) {
```
Comment (121watts) [inline ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.tsx]: This code is a perfect example of something that should live inside a selector and unit tested.  Shoot, it could even go inside the `getTimeMachineValues` selector.  Generally, anytime I'm doing a whole bunch of logic inside of `mstp` I like to ask myself "should this go into a selector?"

Comment (Asalem1) [reply ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.tsx]: Sounds good to me
