### PR TITLE
fix: reduce excessive CPU usage during compaction planning

### LINKED ISSUE #26431: High CPU usage after startup in 1.12.1rc0
1.12.1rc0 exhibits high CPU usage after startup. Based on logs, this appears to be due to frequent optimized compaction planning that is not used.

Compaction planner should avoid planning optimized compactions when they will not be used.

### PR DESCRIPTION
**Pull request by gwossum**
Reduce excessive CPU usage during compaction planning by:
- Avoid planning level 5 compactions unless no other compactions exist
- Add holdoff time in between allowed level 5 compaction plans
- Remove code to upgrade level 4 compaction to level 5 when greater than default points per block is found

Closes #26431

### CODE REVIEW

**Comment by gwossum** [comment]
Initial push is missing tests for `PT_SmartOptimize` and `PT_NoOptimize` planning types.

File: tsdb/engine/tsm1/engine.go [hunk 1]
```diff
@@ -2294,7 +2303,22 @@ type PlannedCompactionGroup struct {
 	PointsPerBlock int
 }
 
-func (e *Engine) PlanCompactions() (
+// PlanType modifies how PlanCompactions operates.
+type PlanType int
+
+const (
+	// PT_Standard indicates the classic planner that plans all levels all the the time.
```
Comment (davidby-influx) [inline tsdb/engine/tsm1/engine.go:2310]: `the the` typo

File: tsdb/engine/tsm1/engine.go [hunk 2]
```diff
@@ -2139,16 +2139,28 @@ func (e *Engine) IsGroupOptimized(group CompactionGroup) (optimized bool, file s
...
+// tickPeriod is the interval between successive compaction loops.
+const tickPeriod = time.Second
 
 func (e *Engine) compact(wg *sync.WaitGroup) {
 	t := time.NewTicker(tickPeriod)
 	defer t.Stop()
 
-	startTime := time.Now()
+	var optHoldoffStart time.Time
+	var optHoldoffDuration time.Duration
```
Comment (davidby-influx) [inline tsdb/engine/tsm1/engine.go:2156]: Can the constant be used directly, or is there some typecasting problem?

File: tsdb/engine/tsm1/compact_test.go [hunk 3]
```diff
@@ -4218,54 +4218,136 @@ func TestEnginePlanCompactions(t *testing.T) {
...
+	tests := []testEnginePlanCompactionsRunner{
 		{
-			blockCounts: []int{
-				tsdb.DefaultAggressiveMaxPointsPerBlock,
-				tsdb.DefaultMaxPointsPerBlock,
-				tsdb.DefaultMaxPointsPerBlock,
-				tsdb.DefaultMaxPointsPerBlock,
+			name:     "test case 1 with plantype of PT_Standard",
+			files:    testFileSets[0],
+			planType: tsm1.PT_Standard,
```
Comment (davidby-influx) [inline tsdb/engine/tsm1/compact_test.go:4242]: Instead of having the plantype in the test case, use nested loops. The outer loop goes through all plantypes, the inner loop goes through all test cases.

Comment (devanbenz) [reply tsdb/engine/tsm1/compact_test.go:4242]: Sounds good

Comment (davidby-influx) [reply tsdb/engine/tsm1/compact_test.go:4242]: Like the tests here (though it is test cases in outer loop, indices in inner loop)

https://github.com/influxdata/influxdb/blob/eab8a8a6e83c3142d11a464df13a99b9b6bdfea5/tsdb/engine/tsm1/engine_test.go#L2362C1-L2386C2

File: tsdb/engine/tsm1/compact_test.go [hunk 4]
```diff
@@ -4201,58 +4201,178 @@ func TestEnginePlanCompactions(t *testing.T) {
...
 		level4Groups []tsm1.PlannedCompactionGroup
 		level5Groups []tsm1.PlannedCompactionGroup
-	}{
+	}
+
+	type testEnginePlanCompactionsRunner struct {
+		name  string
+		files []tsm1.FileStat
+		// Each result is for the different plantypes
+		testBlockCountsAndResults []testBlockCountsAndResults
```
Comment (devanbenz) [inline tsdb/engine/tsm1/compact_test.go:4259]: WIP I'm thinking about changing this to have either a slice of compaction groups only :thinking:

File: tsdb/engine/tsm1/compact_test.go [hunk 5]
```diff
@@ -4180,78 +4032,272 @@ func TestIsGroupOptimized(t *testing.T) {
...
 				tsdb.DefaultMaxPointsPerBlock,
 			},
-			level5Groups: []tsm1.PlannedCompactionGroup{
-				{
-					tsm1.CompactionGroup{"01-05.tsm", "02-05.tsm", "03-05.tsm", "04-04.tsm"},
-					tsdb.DefaultAggressiveMaxPointsPerBlock,
-				},
+			testShardTime: -1,
+			getResultByPlanType: func(planType tsm1.PlanType) testLevelResults {
+				switch planType {
```
Comment (davidby-influx) [inline tsdb/engine/tsm1/compact_test.go:4083]: In this case, and not necessarily for all cases, are the results the same?

File: tsdb/engine/tsm1/compact_test.go [hunk 6]
```diff
@@ -4180,78 +4032,272 @@ func TestIsGroupOptimized(t *testing.T) {
...
+				case tsm1.PT_Standard:
+					return testLevelResults{
+						level4Groups: []tsm1.PlannedCompactionGroup{
+							{
+								tsm1.CompactionGroup{"01-05.tsm", "02-05.tsm", "03-05.tsm", "04-04.tsm"},
+								tsdb.DefaultMaxPointsPerBlock,
+							},
+						},
+					}
+				case tsm1.PT_SmartOptimize:
```
Comment (davidby-influx) [inline tsdb/engine/tsm1/compact_test.go:4093]: For ease of reading, I would make the case 

`case tsm1.PT_SmartOptimize, tsm1.PT_NoOptimize:`

if you have two identical results.  Later changes which differentiate the cases can be made by dividing the case branches as necessary.

File: tsdb/engine/tsm1/compact_test.go [hunk 7]
```diff
@@ -4180,78 +4032,272 @@ func TestIsGroupOptimized(t *testing.T) {
...
+				tsdb.DefaultMaxPointsPerBlock,
+				tsdb.DefaultMaxPointsPerBlock,
+				100,
+				10,
+				5,
+			},
+			testShardTime: -1,
+			getResultByPlanType: func(planType tsm1.PlanType) testLevelResults {
+				switch planType {
+				case tsm1.PT_Standard:
```
Comment (davidby-influx) [inline tsdb/engine/tsm1/compact_test.go:4174]: Same comment as above; combine cases where possible. This highlights that the two options behave the same (when they do).

Also, I think there should be cases here where we see different results for  standard and smart optimize.

Comment (davidby-influx) [reply tsdb/engine/tsm1/compact_test.go:4174]: Finally, would a `map` be better than case statements?  Just a thought, to have fully table-driven code.
```
var results map[tsm1.PlanType]testLeveltResults = {tsm1.PT_Standard: testlevelReesults{.....
```

I'm not sure which I prefer, so use case or map whichever seems best to you.

Comment (devanbenz) [reply tsdb/engine/tsm1/compact_test.go:4174]: I think that using a map could seem nice. I'm wondering if theres a good way to make multiple keys have the same value :thinking: 

```go
			results: map[tsm1.PlanType]testLevelResults{
				tsm1.PT_SmartOptimize: {
					level4Groups: []tsm1.PlannedCompactionGroup{
						{
							tsm1.CompactionGroup{"01-05.tsm", "02-05.tsm", "03-05.tsm", "04-04.tsm"},
							tsdb.DefaultMaxPointsPerBlock,
						},
					},
				},
				tsm1.PT_NoOptimize: {
					level4Groups: []tsm1.PlannedCompactionGroup{
						{
							tsm1.CompactionGroup{"01-05.tsm", "02-05.tsm", "03-05.tsm", "04-04.tsm"},
							tsdb.DefaultMaxPointsPerBlock,
						},
					},
				},
				tsm1.PT_Standard: {
					level4Groups: []tsm1.PlannedCompactionGroup{
						{
							tsm1.CompactionGroup{"01-05.tsm", "02-05.tsm", "03-05.tsm", "04-04.tsm"},
							tsdb.DefaultMaxPointsPerBlock,
						},
					},
				},
			},
```

Comment (davidby-influx) [reply tsdb/engine/tsm1/compact_test.go:4174]: Define the common result in a variable, then put that in the map.

Comment (davidby-influx) [reply tsdb/engine/tsm1/compact_test.go:4174]:
```
type Element struct {
    Name  string
    Value int
}

var repeatedElement = Element{Name: "Element1", Value: 10}

elements := map[string]Element{
    "key1": repeatedElement,
    "key2": {Name: "Element2", Value: 20},
    "key3": repeatedElement, // Reuse the variable
}
```

Comment (devanbenz) [reply tsdb/engine/tsm1/compact_test.go]: Hmmm I kinda like doing it with the switch + function better. 

```go
			getResultByPlanType: func(planType tsm1.PlanType) testLevelResults {
				common := testLevelResults{
					level5Groups: []tsm1.PlannedCompactionGroup{
						{
							tsm1.CompactionGroup{"01-05.tsm1", "01-06.tsm1", "01-07.tsm1", "01-08.tsm1", "02-05.tsm1", "02-06.tsm1", "02-07.tsm1", "02-08.tsm1", "03-04.tsm1", "03-05.tsm1"},
							tsdb.DefaultMaxPointsPerBlock,
						},
					},
				}

				switch planType {
				case tsm1.PT_Standard:
					return common
				case tsm1.PT_SmartOptimize:
					return common
				case tsm1.PT_NoOptimize:
					return testLevelResults{}
				}
				return testLevelResults{}
			},
```

I'm able to just throw the common var in the function body. I quite like this.

File: tsdb/engine/tsm1/compact_test.go [hunk 8]
```diff
@@ -3779,477 +2699,1362 @@ func TestDefaultPlanner_Plan_CompactsMiddleSteps(t *testing.T) {
...
+				}
 
-	tsm, pLen = cp.PlanLevel(2)
-	if exp, got := 1, len(tsm); got != exp {
-		t.Fatalf("tsm file length mismatch: got %v, exp %v", got, exp)
-	} else if pLen != int64(len(tsm)) {
-		t.Fatalf("tsm file plan length mismatch: got %v, exp %v", pLen, exp)
-	}
-	cp.Release(tsm)
+				switch planType {
```
Comment (davidby-influx) [inline tsdb/engine/tsm1/compact_test.go:3300]: Unify first two choices in a single `case`.

```
case tsm1.PT_Standard, tsm1.PT_SmartOptimize:
    return common
```

File: tsdb/engine/tsm1/compact_test.go [hunk 9]
```diff
@@ -3779,477 +2699,1362 @@ func TestDefaultPlanner_Plan_CompactsMiddleSteps(t *testing.T) {
...
+								"03-04.tsm1",
+								"03-05.tsm1",
+								"03-06.tsm1"},
+							tsdb.DefaultMaxPointsPerBlock,
+						},
+					},
+				}
+
+				switch planType {
+				case tsm1.PT_Standard:
```
Comment (davidby-influx) [inline tsdb/engine/tsm1/compact_test.go:3528]: combine first two cases for clarity.

**Review by davidby-influx — CHANGES_REQUESTED** [review]
@devanbenz - do we have tests that differentiate between PT_Standard and PT_SmartOptimize?

File: tsdb/engine/tsm1/reader.go [hunk 10]
```diff
@@ -560,6 +571,62 @@ func (t *TSMReader) TombstoneRange(key []byte) []TimeRange {
...
+// firstBlockCount should not be called with t.mu held.
+func (t *TSMReader) firstBlockCount() (int, error) {
+	cache := func() blockCountCache {
+		t.mu.RLock()
+		defer t.mu.RUnlock()
+		return t.firstBlockCountCache
+	}()
+
+	if !cache.valid {
+		count, err := t.BlockCount(1)
```
Comment (gwossum) [inline tsdb/engine/tsm1/reader.go:611]: @davidby-influx @devanbenz Currently `firstBlockCount` can not hold a lock on `t.mu` because the code would deadlock when it called `t.BlockCount`. I'm pretty sure that it is completely safe to call `t.BlockCount` without a lock on `t.mu`, but please verify.

**Comment by devanbenz** [comment]
> @devanbenz - My question is what is the difference between the two promotions to Level 5: [This one](https://github.com/influxdata/influxdb/blob/b2ad57d09e94a51e2627e0cbefc87e2441728981/tsdb/engine/tsm1/engine.go#L2380C1-L2399C4) and [this one](https://github.com/influxdata/influxdb/blob/b2ad57d09e94a51e2627e0cbefc87e2441728981/tsdb/engine/tsm1/engine.go#L2430C3-L2447C5)
> 
> What does Plan Optimize pick up that the earlier planners did not?

The code [here](https://github.com/influxdata/influxdb/blob/b2ad57d09e94a51e2627e0cbefc87e2441728981/tsdb/engine/tsm1/engine.go#L2430C3-L2447C5) does not do a level5 promotion it just takes an already existing level5 and increases the points per block count.

File: tsdb/engine/tsm1/compact_test.go [hunk 11]
```diff
@@ -4219,16 +4202,151 @@ func TestEnginePlanCompactions(t *testing.T) {
...
 		},
+		{
+			name: "Mock another planned level inside scheduler",
+			files: []tsm1.ExtFileStat{
+				{
+					FileStat: tsm1.FileStat{
+						Path: "01-05.tsm",
+						Size: 256 * 1024 * 1024,
+					},
+					FirstBlockCount: tsdb.DefaultAggressiveMaxPointsPerBlock,
```
Comment (davidby-influx) [inline tsdb/engine/tsm1/compact_test.go:4221]: Do we have a test where the file with the aggressive block count is not the first, but somewhere in the middle of file list?

Comment (davidby-influx) [reply tsdb/engine/tsm1/compact_test.go:4221]: We should have the aggressive block count file first, last, and in the middle, in three different file groups or tests (Whichever is more convenient).

File: tsdb/engine/tsm1/engine_test.go [hunk 12]
```diff
@@ -2701,6 +2702,8 @@ func NewEngine(index string) (*Engine, error) {
 	// store level.
 	seriesIDs := tsdb.NewSeriesIDSet()
 	opt.SeriesIDSets = seriesIDSets([]*tsdb.SeriesIDSet{seriesIDs})
+	// For testing purposes lets set a compaction limiter to 20
+	opt.CompactionLimiter = limiter.NewFixed(20)
```
Comment (devanbenz) [inline tsdb/engine/tsm1/engine_test.go:2706]: Had to add a compaction limiter in order to actually test SmartOptimize plan type

**Review by davidby-influx — CHANGES_REQUESTED** [review]
A few changes.  Some comments may have become outdated.

**Review by devanbenz — APPROVED** [review]
lgtm
