### PR TITLE
fix: Add Logger to constructor function to ensure log field is initialized

### LINKED ISSUE #19876: v2.0-rc.3 When trying to create a Bucket : runtime error: invalid memory address or nil pointer dereference
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Start a Debian 10 fresh new node
2. Install latest InfluxDB OSS release: v2.0-rc.3, according to the get started page on the official doc
3. Start InfluxDB using `influxd --http-bind-address=:9913 --reporting-disabled` _(note that bug happens even with a simple `influxd` command)_
4. Create a new bucket using `POST /api/v2/buckets` (or actually using the Influx UI, same result) with following parameters: 
```
{ "name": "bucket",
"orgID": "${orgId}", 
"retentionRules":[{"everySeconds":302400,"type":"expire"}]}
```
Bucket is created successfully.

5. However, repeating the exact same request, trying to create a new bucket using the same bucket name results in a `500 Internal server error` on the client side. On the server side we get a `panic: runtime error: invalid memory address or nil pointer dereference`. Full logs available bottom of the post.

__Expected behavior:__

Trying to create a bucket with existing name shouldn't return a fatal error but just a simple "bucket already exists" error (behavior I have on previous versions).

__Actual behavior:__

As mentioned previously, just trying to create a bucket with an already existing name results in a 500 error. 
InfluxDB logs available at the bottom of the post. 

__Environment info:__

* System info: 
```
uname -srm
Linux 4.19.0-12-amd64 x86_64
```

* InfluxDB version: 
`InfluxDB 2.0.0-rc.3 (git: f46a3bd91e) build_date: 2020-10-29T22:17:55Z`

__Config:__
I didn't touch configuration.

__Logs:__

 ```
panic: runtime error: invalid memory address or nil pointer dereference
 -> go.uber.org/zap.(*Logger).check
 ->   /go/pkg/mod/go.uber.org/zap@v1.14.1/logger.go:263

    go.uber.org/zap.(*Logger).Error
      /go/pkg/mod/go.uber.org/zap@v1.14.1/logger.go:202
    github.com/influxdata/influxdb/v2/storage.(*BucketService).CreateBucket.func1
      /go/src/github.com/influxdata/influxdb/storage/bucket_service.go:49
    github.com/influxdata/influxdb/v2/storage.(*BucketService).CreateBucket
      /go/src/github.com/influxdata/influxdb/storage/bucket_service.go:55
    github.com/influxdata/influxdb/v2/tenant.(*AuthedBucketService).CreateBucket
      /go/src/github.com/influxdata/influxdb/tenant/middleware_bucket_auth.go:95
    github.com/influxdata/influxdb/v2/tenant.(*BucketHandler).handlePostBucket
      /go/src/github.com/influxdata/influxdb/tenant/http_server_bucket.go:273
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi.(*Mux).routeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi.(*Mux).ServeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:70
    github.com/go-chi/chi.(*Mux).Mount.func1
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi.(*Mux).routeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.RealIP.func1
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/middleware/realip.go:34
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.RequestID.func1
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/middleware/request_id.go:76
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.Recoverer.func1
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/middleware/recoverer.go:37
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi.(*Mux).ServeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:70
    github.com/go-chi/chi.(*Mux).Mount.func1
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi.(*Mux).routeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1
      /go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:34
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.StripSlashes.func1
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/middleware/strip.go:25
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1
      /go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:72
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/influxdata/influxdb/v2/http.panicMW.func1.1
      /go/src/github.com/influxdata/influxdb/http/router.go:126
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi.(*Mux).ServeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:70
    github.com/influxdata/influxdb/v2/kit/feature.(*Handler).ServeHTTP
      /go/src/github.com/influxdata/influxdb/kit/feature/middleware.go:43
    github.com/influxdata/influxdb/v2/http.(*AuthenticationHandler).ServeHTTP
      /go/src/github.com/influxdata/influxdb/http/authentication_middleware.go:125
    github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1
      /go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:34
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1
      /go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:72
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/influxdata/influxdb/v2/http.(*PlatformHandler).ServeHTTP
      /go/src/github.com/influxdata/influxdb/http/platform_handler.go:78
    github.com/go-chi/chi.(*Mux).Mount.func1
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/influxdata/influxdb/v2/kit/transport/http.Metrics.func1.1
      /go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:57
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/influxdata/influxdb/v2/kit/transport/http.Trace.func1.1
      /go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:97
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi.(*ChainHandler).ServeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/chain.go:31
    github.com/go-chi/chi.(*Mux).routeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi.(*Mux).ServeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:86
    github.com/influxdata/influxdb/v2/http.(*Handler).ServeHTTP
      /go/src/github.com/influxdata/influxdb/http/handler.go:143
    net/http.serverHandler.ServeHTTP
      /usr/local/go/src/net/http/server.go:2843
    net/http.(*conn).serve
      /usr/local/go/src/net/http/server.go:1925
    created by net/http.(*Server).Serve
      /usr/local/go/src/net/http/server.go:2969
```

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #19876 

Ensure the `log` field is initialized at construction of the `BucketService` to avoid panics.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass

### CODE REVIEW

File: task/backend/analytical_storage_test.go [hunk 1]
```diff
@@ -64,7 +64,7 @@ func TestAnalyticalStore(t *testing.T) {
 				svcStack = backend.NewAnalyticalRunStorage(logger, svc, ts.BucketService, svc, rr, ab.QueryService())
 			)
 
-			ts.BucketService = storage.NewBucketService(ts.BucketService, ab.storageEngine)
+			ts.BucketService = storage.NewBucketService(nil, ts.BucketService, ab.storageEngine)
```
Comment (danxmoran) [inline task/backend/analytical_storage_test.go:67]: Any concerns that this `nil` might blow up on us later?

**Review by danxmoran — APPROVED** [review]
One question but LGTM!

File: task/backend/analytical_storage_test.go (hunk 1 above)
Comment (stuartcarnie) [reply task/backend/analytical_storage_test.go]: Absolutely – pushed a fix and thanks for finding it. My IDE hid that reference from me :)
